### ISSUE TITLE
FirebaseCrashlytics log() method takes only a message without priority and tag

### ISSUE THREAD

**Issue by lionel-dangelo** [firebase/firebase-android-sdk#1202] opened 2020-02-05 15:04 UTC
Why the only way to log something is FirebaseCrashlytics.getInstance().log(message) without tag and priority ? If we look the implementation, we see that this method calls the CrashlyticsCore method 
`   public void log(String msg) {
        this.doLog(3, "FirebaseCrashlytics", msg);
    }`

and this method sets always a the Debug priority (3) and the tag "FirebaseCrashlytics" which is not really readable in the firebase crash console.
Is this a bug ?

Thank you

**Comment by aguatno** [comment] 2020-02-05 15:57
Hi @lionel-dangelo thanks for filling this issue. Crashlytic.log() has a similar method with same name, but different argument wherein you can set the tag and priority, see image below for reference.

![Screenshot from 2020-02-05 23-46-34](https://user-images.githubusercontent.com/56451054/73857404-da592100-4871-11ea-9818-4e8a4aa3773d.png)

**Comment by lionel-dangelo** [comment] 2020-02-05 16:05
Thank you for your answer, but I try to use the new implementation of FirebaseCrashlytics (without Fabric)
https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=android 
So I don't have the "Crashlytics" class anymore and the new class "FirebaseCrashlytics" exposes only log(String msg)
Maybe is there an other way with the new implementation ?

**Comment by aguatno** [comment] 2020-02-05 16:57
Thanks for the clarification. It seems there should be another log() method with priority and tag as parameter, see [here](https://github.com/firebase/firebase-android-sdk/blob/b89694a5dd04fe923080ac2e1cc5f876b06c583d/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsCore.java#L371).

The Firebase Crashlytics SDK for Android is still a beta release so there are still a few issues that need to be addressed. I'll be tagging this issue as bug for now.

**Comment by lionel-dangelo** [comment] 2020-02-05 17:00
Thank you :)

**Comment by aguatno** [comment] 2020-02-05 17:06
For now, you try to log a message with tag using this syntax:

>  FirebaseCrashlytics.getInstance().log("E/TAG: my message");

You can read more [here](https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android#firebase-crashlytics-sdk_2).

**Comment by lionel-dangelo** [comment] 2020-02-05 17:17
Yes it works, but like I said in my first message it's just not ideal because FirebaseCrashlytics.getInstance().log() calls the method log(msg) of CrashlyticsCore 
`public void log(String msg) { this.doLog(3, "FirebaseCrashlytics", msg); }`
so alls my messages are prefixed by D/FirebaseCrashlytics
Example : 
`D/FirebaseCrashlytics I/SharedPrefsServiceImpl.kt:4)#<init>: SharedPrefsService initialization
D/FirebaseCrashlytics I/StorageServiceImpl.kt:2)#<init>: StorageService initialization
D/FirebaseCrashlytics I/ApiContextServiceImpl.kt:1)#l: Init authentication from prefs`

I'm going to use the library like that but  I'll wait for an improvement.
Thank you

**Comment by aguatno** [comment] 2020-02-05 17:50
Issue is being tracked internally using bug#148943501. I'll keep you posted.

**Comment by aguatno** [comment] 2020-02-10 16:58
Hi @lionel-dangelo I got feedback from our engineering team. It is intended behavior that priority and tag has been taken out in the Firebase Crashlytics SDK. We do log a priority and tag internally, but it's always "D/FirebaseCrashlytics,". 

We would like to ask your feedback on what you think of either of these changes to the log method:
1) Stop logging the superfluous "D/FirebaseCrashlytics"
2) Allow users to configure that for display in their dashboard, without actually passing it through to logcat.

Thanks.

**Comment by lionel-dangelo** [comment] 2020-02-13 19:07
Thank you for your answer.
Actually, not be able to pass a parameter for the priority is not a problem, because I can customize the message with my own prefix (E/ , W/ , I/).

So yes, I just think a good behavior could be stopping to log the superfluous "D/FirebaseCrashlytics"

For the moment, I have this on the firebase console (with the last implementation)

<img width="948" alt="Capture d’écran 2020-02-13 à 19 58 52" src="https://user-images.githubusercontent.com/51699446/74468633-6c2ce380-4e9b-11ea-804a-873f28337ee8.png">

And if I download the .log file from firebase :

<img width="895" alt="Capture d’écran 2020-02-13 à 20 06 05" src="https://user-images.githubusercontent.com/51699446/74469117-4e13b300-4e9c-11ea-833c-2ac659a1bba5.png">

**Comment by aguatno** [comment] 2020-02-19 16:24
Hi @lionel-dangelo We have implemented removing the uperfluous log and it will be released in beta02. Here's the pull request https://github.com/firebase/firebase-android-sdk/pull/1247.

Thanks so much for the feedback.

**Comment by aguatno** [comment] 2020-02-19 16:29
I am closing this issue for now. I'd recommend checking out our [releae notes](https://firebase.google.com/support/release-notes/android) to see when a PR makes it into an official release. Any new features/breaking changes/bug fixes should be detailed there :)

**Closed by aguatno** 2020-02-19 16:29 UTC
Labels: api: crashlytics, type: feature request
