### ISSUE TITLE
Make ComponentDiscovery bullet-proof with Dynamic Feature Module

### ISSUE THREAD

**Issue by etiennecadicidean** [firebase/firebase-android-sdk#1192] opened 2020-02-04 15:43 UTC
## What feature would you like to see?
Currently, the way firebase components are initialized thanks to ContentProvider makes developers cry when they want to use some firebase libs inside dedicated dynamic feature modules that should be able to launch immediately after request for install.

The only workaround is to kill the default FirebaseApp & then recreate it. Now imagine you have several firebase components running in the base apk. Deleting the default app at runtime while they may be running doesn't sound professionnal.

At the same time, it looks like AS is doing things wrong when building a default apk containing both the base apk & the feature module. It looks like the Firebase Registrars of the base module get replaced by the ones of the feature module (even when trying to add some tools:node="merge")

The only way for developers to test their work is then to use bundletool to generate an universal apk and push it to the device (which takes longer than an incremental build).

In few words, the way Firebase hacks the ContentProvider to get initialized breaks everything when mixed with Dynamic Feature Modules.

## How would you use it?
 1) Man would love having a way of initializing or ask the FirebaseApp to fetch newly installed firebase components.  Something like FirebaseApp::refreshInstalledApis()

 2) Make the AndroidManifest.xml merging right with AS so that developer can embed feature modules containing firebase libs without having them erasing firebase registrars of the base apk.

Steps to make sure it works : 
Use some libs like DynamicLinks or FirebaseVision inside a base apk and the other one in a dedicated feature module; then make sure calls of DynamicLinks.getInstance() & FirebaseVision.getInstance() are working in every case (when embedding both modules, or after module install).

**Comment by aguatno** [comment] 2020-02-20 14:49
Thanks for reporting this, @etiennecadicidean. I can't give any timelines for this request to be processed, so I'll leave this open for now.

**Comment by ashwinraghav** [comment] 2020-05-29 23:46
Duplicate of #1169

**Closed by ashwinraghav** 2020-05-29 23:46 UTC
Labels: type: feature request
