### ISSUE TITLE
notification_open event called 4 times, but notification_receive event called one

### ISSUE THREAD

**Issue by soohyeon13** [firebase/firebase-android-sdk#5325] opened 2023-09-13 09:30 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Giraffe | 2022.3.1 
  * Firebase Component: Firebase Cloud Messaging
  * Component version: 23.2.1

### [REQUIRED] Step 3: Describe the problem

<img width="283" alt="스크린샷 2023-09-13 오후 6 07 08" src="https://github.com/firebase/firebase-android-sdk/assets/48516385/30c0fa12-e131-4a7b-8071-56a86843ca67">

When the app is in the background and the app is entered through an FCM message, the `notification_receive` event is called 1 time in `DebugView`, but the `notification_open` event is called **4 times**. I checked with the debug point, but seenIntents continues to be initialized, so the condition in the `if statement` does not seem to be applied.

*Our app is not set up for BigQuery. 
```kt
// about
FirebaseMessaging.getInstance().setDeliveryMetricsExportToBigQuery(true)
```

#### Steps to reproduce:
1. The app is in the background 
2. Enable Firebase Analytics debug, and open the DebugView
3. Send FCM message to device
4. We can see the `notification_receive` event in the DebugView
5. Enter the app by clicking on the notification
6. See the `notification_open` event **4 times** show in the DebugView

#### Relevant Code:
`logNotificationOpen` in the `onActivityCreated` function of `FcmLifecycleCallbacks` is called 4 times.
```java
// TODO(b/258424124): Migrate to go/firebase-android-executors
  @SuppressLint("ThreadPoolCreation")
  @Override
  public void onActivityCreated(Activity createdActivity, Bundle instanceState) {
    Intent startingIntent = createdActivity.getIntent();
    if (startingIntent == null || !seenIntents.add(startingIntent)) {
      // already seen (and logged) this, no need to go any further.
      return;
    }

    if (VERSION.SDK_INT <= VERSION_CODES.N_MR1) {
      // On Android 7.1 and lower Bundle unparceling is not thread safe. Wait to log notification
      // open after Activity.onCreate() has completed to try to avoid race conditions with other
      // code that may be trying to access the Intent extras Bundle in onCreate() on a different
      // thread.
      new Handler(Looper.getMainLooper()).post(() -> logNotificationOpen(startingIntent));
    } else {
      logNotificationOpen(startingIntent);
    }
  }
```

**Comment by argzdev** [comment] 2023-09-15 15:16
Thanks for reaching out, @soohyeon13. I'm testing this using our [quickstart](https://github.com/firebase/quickstart-android)  but I'm unable to reproduce this behavior. Is this behavior consistently reproducible on your side?
![Uploading Screenshot 2023-09-15 at 11.14.59 PM.png…]()


Regarding this code snippet:
```
FirebaseMessaging.getInstance().setDeliveryMetricsExportToBigQuery(true)
```
I'm not sure if I understand, do you mean to say including this line of code will cause the issue? I've added this in my `onCreate` but I don't see experience the same behavior. Am I missing anything?

Also could you try testing it on a different device to see if this issue is reproducible?

**Comment by soohyeon13** [comment] 2023-09-19 01:25
@argzdev , thank you for checking.

`FirebaseMessaging.getInstance().setDeliveryMetricsExportToBigQuery(true)`
https://firebase.google.com/docs/projects/bigquery-export?hl=en
As stated in the firebase document, BigQuery was not used.

And I haven't tested it on other devices.
and I just added the firebase library. 

Is there anything else I should check?

**Comment by argzdev** [comment] 2023-09-19 13:33
That's odd, I'm not sure what's the reason causing the `notification_open` 4x. Could you share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so I have can take look into it?

**Comment by soohyeon13** [comment] 2023-09-22 00:46
1. When the app runs, execute FirebaseMessaging.getInstance() 1 time.
2. However, if an error occurs during the process, there is a retry strategy.
3. The firebase-messaging-ktx library is using version 23.2.1.
   -  There are also other firebase libraries
4. Also, there is only an intent filter of com.google.firebase.MESSAGING_EVENT.

Is this the information you want?

Thank you.

**Comment by argzdev** [comment] 2023-09-22 12:06
Hi @soohyeon13, I understand the information you've provided however I'm still unable to reproduce the issue with the given  steps. Could you upload a [minimal sample project](https://stackoverflow.com/help/minimal-reproducible-example) of the issue in GitHub and share it with me so I can take a look into it? Please do remove any Personal Identifiable Information (PII), thanks!

**Comment by soohyeon13** [comment] 2023-09-25 10:07
@argzdev 
I found one case.
Currently, our app uses `Firebase multiple projects`, so we ran `FirebaseApp.initializeApp` in each project. So it was **inited 4 times**, and I think this part was the problem. (I removed the 2 init codes, but the notification_open event came twice.)

- I have two questions.
1.  Is this a bug?
2. Is there any other way in this Firebase multiple projects case?

- Tried case
1. Except for one project, it was added. `FirebaseApp.setDataCollectionDefaultEnabled(false)`
2. Added the following code. `FirebaseAnalytics.getInstance().setAnalyticsCollectionEnabled(true)`

**Comment by argzdev** [comment] 2023-10-02 14:19
Hi @soohyeon13, thanks for the extra details. It makes sense why you would receive notification alert multiple times due to multiple project setup. Right now, this is not supported and may result to unexpected behavior. This is marked as a [feature request](https://github.com/firebase/firebase-android-sdk/issues/2285). 

That said, for better tracking please continue your report on that thread, and we'll mark this one as a duplicate. If possible, could you share your use case? We'd like to know and understand why our developers would have multiple project setups.

Please do leave a thumbs up emoji on the [other thread](https://github.com/firebase/firebase-android-sdk/issues/2285), so that we may prioritize accordingly.

**Closed by argzdev** 2023-10-02 14:19 UTC
Labels: needs-attention
