### ISSUE TITLE
Firebase remoteConfig return no value

### ISSUE THREAD

**Issue by KevynBct** [firebase/firebase-android-sdk#2186] opened 2020-11-19 15:57 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:  4.1.1
  * Firebase Component:  firebase-config/firebase-config-ktx
  * Component version: 20.0.1

Hello everyone,

Since I've updated the component `firebase-config` from 20.0.0 to 20.0.1, I can't get values from `Firebase.remoteConfig`.

Nothing has changed in my code since previous version :

First I fetch and active in my `MainActivity`

    val configSettings = remoteConfigSettings {
        minimumFetchIntervalInSeconds = 3600
    }

    Firebase.remoteConfig.setConfigSettingsAsync(configSettings)

    Firebase.remoteConfig.fetchAndActivate().addOnCompleteListener(this) { task ->

        if (task.isComplete) {
            // Some code here
        }

    }

And then in a fragment I get values :

    with (Firebase.remoteConfig) {

        val a = getValue("key1").asString()
        val b = getValue("key2").asString()

    }

**Comment by T1mmyK0** [comment] 2020-11-23 01:33
I have the same issue.
When updating the app to the new RemoteConfig version, no values are received anymore and the default values apply.
Reinstalling fixes the issue, but I cannot ask all my users to reinstall the app or clear data.

**Comment by AgiMaulana** [comment] 2020-11-25 05:04
I've encountered the same issue. The value has been synced in previous remote config SDK version when it updated with the version of 20.0.1 the data was lost. Although can be resolved simply by staling the remote config this is not the convenient way I think.

**Comment by AgiMaulana** [comment] 2020-11-25 05:31
This is reproducible, try to build with the version 19.2.0 everything is okay, then rebuild with the version 20.0.1 remote config return no value for the given key

**Comment by T1mmyK0** [comment] 2020-11-25 12:16
@AgiMaulana Same here. And when downgrading to 20.0.0 it works fine again. I have downgraded RemoteConfig in my production apk again.

**Comment by danasilver** [comment] 2020-11-30 23:19
Looking into this. I'm unable to reproduce it in a new Kotlin app with `firebase-config-ktx:20.0.1` and `firebase-analytics-ktx:18.0.0` as dependencies. @vic-flair do you mind taking a look, too?

**Comment by bocops** [comment] 2020-12-01 09:15
@danasilver I'm seeing the same as others have reported, with a `firebase-config:20.0.x` dependency and a `firebase-analytics:18.0.0` dependency (transitively via `firebase-core`):

1. Fresh install (via Android Studio, "Debug app") of app with a `20.0.0` dependency.
2. Run app, correct remote config values are shown
3. Stop app
4. Update dependency to '20.0.1' and install.
5. Run app, correct remote config values are **not** shown

If, between steps 3 and 4, I "clear data" for this app on the device, everything works correctly.

If, instead of clearing data, I set the device to airplane mode before steps 4/5, correct values are still **not** shown. Because of this, I believe the problematic part is not actually the fetching but the activating of a remote config that is already cached on the device.

**Comment by bocops** [comment] 2020-12-01 09:41
Could the issue be `ConfigStorageClient.read()` (permalink below)?

It seems that, if a config was written to disk **without** personalization (version <20.0.1), then trying to read it **with** personalization (version =20.0.1) should lead to `JSONObject.getJSONObject(key)` being called with a key that doesn't exist and thus throwing a JSONException, which in turn makes the method return null.

https://github.com/firebase/firebase-android-sdk/blob/0fa174c6f55ece8f13b87c1765522f87db3510f6/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigStorageClient.java#L105

**Comment by danasilver** [comment] 2020-12-01 18:44
@bocops Thanks for the help investigating. I'm able to reproduce the issue now with those steps. It does seem like the issue is reading the cached config. Working on a fix for this.

**Comment by maulikhirani** [comment] 2020-12-02 11:14
This issue is really scary.
Can we expect a fixed version ASAP?

Now that Firebase is recommending BoM (Bills of Materials) for adding dependencies, I don't want to specify an older version explicitly just for Remote Config.

**Comment by AgiMaulana** [comment] 2020-12-03 03:38
For everyone who has shipped the remote config 20.0.1 within your production app and already implemented [propagating realtime update](https://firebase.google.com/docs/remote-config/propagate-updates-realtime#android_1), you can to try [propagate realtime update](https://firebase.google.com/docs/remote-config/propagate-updates-realtime#android_1) to stale the local config so the app can rewrite local config with a new one using the new writing scheme.

I've fix the issue on production app using that workaround

**Comment by jd565** [comment] 2020-12-03 12:42
We have had the same issue and fixed by noticing when the app has been updated and calling `FirebaseRemoteConfig.getInstance().reset()`, which has fixed the issue for us.

**Comment by danasilver** [comment] 2020-12-03 19:07
Remote Config SDK version 20.0.2 is live now with a fix. A new version of the Firebase BOM (26.1.1) has been released, too, including this version.

Thanks all for your help reporting and investigating the issue!

**Closed by danasilver** 2020-12-03 19:07 UTC
Labels: api: remoteconfig

**Comment by XinyueZ** [comment] 2020-12-09 15:35
Was this bug affecting the Flutter version?

**Comment by danasilver** [comment] 2020-12-09 18:47
@XinyueZ I don't think this affected Flutter since it looks like the Flutter SDK is [using Firebase Android BOM 25.12.0](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_core/firebase_core/android/gradle.properties) and this issue was in [version 26.1.0 of the BOM](https://firebase.google.com/support/release-notes/android#bom_v26-1-0). It's fixed in version 26.1.1.
