### ISSUE TITLE
Adding FireBase Android BOM in Application BOM

### ISSUE THREAD

**Issue by RishabhJain1603** [firebase/firebase-android-sdk#3401] opened 2022-02-04 10:49 UTC
**Environment**
Android Studio version: Android Studio 4.2.1 
Component version:
firebase-bom version: 28.4.2

**Problem:**
`>Could not parse POM
Required version must not be null`
**Scenario:**
I have project internal BoM repo which serves as single source of truth for all the Internal library and third party library.
I have added FireBase Android BOM as dependency constraint inside internal project Bom repo. This repo is building fine.

**My current project structure is:**
FeatureA,FeatureB, FeatureC, FeatureD **<--(extends from)** Feature Base Component.
Inside Feature Base Component i added my project internal Bom and added firebase Bom as well but without giving version of it since it's dependency constrain coming from internal project BOM.
This repo compile and builds fine but when i try to use feature base component in any of the feature (featureA, featureB or featureC), they all failed to compile because of "Could not parse POM" error.

**Comment by argzdev** [comment] 2022-02-04 11:56
Hi @RishabhJain1603, thanks for the report. Any chance you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) of this issue? Thanks!

**Comment by argzdev** [comment] 2022-02-11 09:12
Since there is no update, I'll be closing this now. We can reopen this once you provide us with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) of your issue. Thanks!

**Closed by argzdev** 2022-02-11 09:12 UTC
Labels: needs-info, no-recent-activity, api: bom
