### ISSUE TITLE
Please fix failing tests (last passing commit was from 11 Oct 2022)

### ISSUE THREAD

**Issue by tellypresence** [firebase/firebase-android-sdk#4513] opened 2023-01-04 02:57 UTC
### [REQUIRED] Step 2: Describe your environment

 N/A: this ticket is purely about this github repo

### [REQUIRED] Step 3: Describe the problem
Every commit since 11 Oct 2022 has failed tests, makes it difficult to have confidence using more recent revisions

![firebase_red_x_problem_Screenshot 2023-01-03 185323](https://user-images.githubusercontent.com/26958898/210476042-be05c8e6-6dd5-413a-88ce-b56927a97edc.png)

**Comment by argzdev** [comment] 2023-01-04 10:29
Hi @tellypresence, thanks for reporting. I'll let our engineers know and see what we can do here.

**Comment by rlazo** [comment] 2023-01-04 16:07
Hi @tellypresence thanks for your report. We have two types of checks, ones that verify code is working as intended, which are mandatory and block PRs from being merged until passed, and others that provide extra functionality like coverage and repo sync. Mandatory checks are passing so you shouldn't worry about code integrity. On the other hand, reviewing the past commits based on your report, I can see that CodeCoverage is failing consistently since that date, which is a reason we don't have green checks in commits. We'll look into it. Thanks!

I'll close this issue once we have green commits again.

**Comment by tellypresence** [comment] 2023-01-13 20:13
@rlazo Thank you, that's a good explanation

**Comment by rlazo** [comment] 2023-02-17 21:17
Hi @tellypresence I'm glad to let you know we have made several improvements and fix outstanding bugs in our CI and the latest commits are back in green.

![Screenshot 2023-02-17 at 4 15 44 PM](https://user-images.githubusercontent.com/368578/219794801-7d05e7b7-c347-47c3-8542-9f49b37285f4.png)

Thanks!

**Closed by rlazo** 2023-02-17 21:17 UTC
Labels: test-flakiness
