### ISSUE TITLE
Memory leak due to firebase-auth

### ISSUE THREAD

**Issue by dvdhfnr** [firebase/firebase-android-sdk#3236] opened 2021-12-13 13:14 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.1
  * Firebase Component: Auth (Database, Firestore, Storage, Functions, etc)
  * Component version: 29.0.2

### [REQUIRED] Step 3: Describe the problem

Adding `com.google.firebase:firebase-auth` to an Android project leads to a memory leak of a (totally unrelated) dialog fragment:
<img width="1678" alt="memory-leak" src="https://user-images.githubusercontent.com/46796940/145818427-275ceac5-e2de-4eb8-a18a-4763a4ba6873.png">

This memory leak does not appear when not using 'firebase-auth'.

#### Steps to reproduce:

Please see the following repository with a minimal example to reproduce the memory leak: https://github.com/dvdhfnr/firebase-auth-memory-leak

By default, firebase-auth is not used. Pressing the button, which opens a dialogFragment, multiple times does not create any memory leak; checked via memory heap dump in the Android studio profiler.

When uncommenting Line 44 in app/build.gradle ([implementation 'com.google.firebase:firebase-auth'](https://github.com/dvdhfnr/firebase-auth-memory-leak/blob/b1b5e782dec951cf84041a6124c3b008758db630/app/build.gradle#L44)) and repeating the above experiment (i.e. pressing the Button multiple times), we observe above memory leak. Neither the activity nor the dialog fragment implement any firebase code, only adding `implementation 'com.google.firebase:firebase-auth'` to the gradle.build seems to cause this issue.

#### Relevant Code:

- https://github.com/dvdhfnr/firebase-auth-memory-leak
- [implementation 'com.google.firebase:firebase-auth'](https://github.com/dvdhfnr/firebase-auth-memory-leak/blob/b1b5e782dec951cf84041a6124c3b008758db630/app/build.gradle#L44)

**Comment by argzdev** [comment] 2021-12-13 13:53
Hi @dvdhfnr, thanks for the detailed report with the MCVE. I tried using the minimal repro you've provided, however I was unable to encounter the issue. The steps I tried were:

1. Open app, show dialog, create heap dump, no leaks found.
2. Open app, click create heap dump, show dialog while heap dump is being created, no leaks found.

Am I missing anything? Also may I ask how often does this occur? Is it consistent on every run?

**Comment by dvdhfnr** [comment] 2021-12-13 14:10
Hi @argzdev!

Thanks for looking into this.

By default, the project does not include `firebase-auth`; to show that there is no memory leak.
Hence, please uncomment https://github.com/dvdhfnr/firebase-auth-memory-leak/blob/b1b5e782dec951cf84041a6124c3b008758db630/app/build.gradle#L44 first, and then repeat the experiment. Moreover, the memory leak does not appear always. Would be great if you could try to click the button multiple times, and check the heap afterwards.

With `firebase-auth` I am consistently able to reproduce the leak, without I never saw this leak - even when pressing the button > 100 times.

**Comment by argzdev** [comment] 2021-12-13 14:31
Thanks @dvdhfnr, I was able to repro the issue. I'll notify an engineer and see what we can do here.

**Comment by dvdhfnr** [comment] 2021-12-20 10:30
Hi,

Is there any update on this issue?
Might it be related to #2387?

**Comment by argzdev** [comment] 2021-12-20 17:49
Hi @dvdhfnr, thanks for pointing that out. I've actually thought about it and was able to confirm with the engineer that these two issues are the same. Just to note, our engineers have been and still working on a fix for this issue. With that said, I'll mark this one as duplicate and close this for better tracking. You may comment on #2387 instead. Thanks!

**Comment by argzdev** [comment] 2021-12-20 17:49
Duplicate of #2387

**Closed** 2021-12-20 17:49 UTC
Labels: api: auth
