### ISSUE TITLE
ml-vision: text recognition model not downloaded on android 11

### ISSUE THREAD

**Issue by hardysim** [firebase/firebase-android-sdk#1275] opened 2020-02-25 09:42 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: `3.6`
  * Firebase Component: `com.google.firebase:firebase-ml-vision`
  * Component version: `24.0.1`

### [REQUIRED] Step 3: Describe the problem

This is basically https://github.com/firebase/quickstart-android/issues/784 but it started to happen for me after flashing Android 11 DP1 to my Pixel 3. It used to work on all other versions before.

Now, I get an exception when running `FirebaseVision.getInstance().onDeviceTextRecognizer.processImage()` (the same happens with `visionBarcodeDetector`):

> Text detection failed.com.google.firebase.ml.common.FirebaseMLException: Waiting for the text
recognition model to be downloaded. Please wait.

I've told it to auto-download the models in my manifest as well:

```xml
<meta-data
    android:name="com.google.firebase.ml.vision.DEPENDENCIES"
    android:value="barcode,ocr" />
```

#### Steps to reproduce

You can use https://github.com/firebase/mlkit-material-android and try to scan a barcode. There will be "the same" error:

> com.google.firebase.ml.common.FirebaseMLException: Waiting for the barcode detection model to be downloaded. Please wait.

**Comment by Warpzit** [comment] 2020-02-28 10:13
This is a serious issue. If we at least could ask how far in the download process it is that would be a great help in order to give some kind of useful feedback to our users.

**Comment by coderau776** [comment] 2020-03-19 13:39
It does run on real android, only Emulator is generating this issue :(

**Comment by hardysim** [comment] 2020-03-19 14:39
This is not true for me. I have this issue on a physical Pixel 3.

**Comment by coderau776** [comment] 2020-03-19 14:47
That's weird I tried it on physical MI A1 and it actually worked.
I think you should have google play services installed for ML Kit to support on your device....

**Comment by hardysim** [comment] 2020-03-19 14:57
Since this is an unaltered system image for the developer preview, play-services are already installed.

I cannot test DP2 today because the whole camera seems broken. I'm reporting back once it's working again, if the download-issue still exists.

**Comment by coderau776** [comment] 2020-03-19 15:23
Okay maybe new preview can solve your issue..
Still I think play-services can be the problem because some issues just like this were solved
after realizing the compatibility problem of ML-KIT.

**Comment by cs-googler** [comment] 2020-03-19 16:36
> Since this is an unaltered system image for the developer preview, play-services are already installed.
> 
> I cannot test DP2 today because the whole camera seems broken. I'm reporting back once it's working again, if the download-issue still exists.

Hi, there is an on-going effort to investigate the download failure currently. The module download is only supported by the recent several gmscore version. One issue we identified is that if a device's got updated from an unsupported version to a supported version of GMSCore, a reboot is needed for those module to be downloaded.  The fix is on its way. Could you share some bugreports with us by sending them to songchenxi@google.com for us to check the exactly issue happened to you?

**Comment by hardysim** [comment] 2020-03-20 07:19
I'm getting the following logs using DP2 (it repeats over and over):

```

D/TextNativeHandle: Cannot load feature, fall back to load dynamite module.
W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.ocr not found.
I/DynamiteModule: Considering local module com.google.android.gms.vision.ocr:0 and remote module com.google.android.gms.vision.ocr:0
E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
```

**Comment by cs-googler** [comment] 2020-03-25 16:17
> I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite.ocr:0 and remote module com.google.android.gms.vision.dynamite.ocr:0

Hi, it looks like that your GMSCore version might be too old. Could you provide the version of it? Also, a bugreport will be super helpful for us to look into this issue for you.

**Comment by hardysim** [comment] 2020-03-26 08:10
Do you mean this?

`implementation "com.google.android.play:core-ktx:1.6.5"`

**Comment by huangzh3** [comment] 2020-03-27 08:57
I have the same problem

**Comment by cs-googler** [comment] 2020-03-27 16:27
> Do you mean this?
> 
> `implementation "com.google.android.play:core-ktx:1.6.5"`
No, if you go to Settings -> Apps&Notifications ->Google Play Services -> Advanced -> App details you will see a version number(eg: 20.12.02)

**Comment by cs-googler** [comment] 2020-03-27 16:28
> I have the same problem
Does reboot help? If not, could you provide your GMSCore version? 
Go Settings -> Apps&Notifications ->Google Play Services -> Advanced -> App details, you will see a version number(eg: 20.12.02).

**Comment by hardysim** [comment] 2020-03-28 10:49
So my play-services version is 20.06.15 (140408-294478903)

**Comment by hardysim** [comment] 2020-04-03 09:40
I just found the following hint on https://firebase.google.com/docs/ml-kit/android/read-barcodes

> Version 24.0.0 of firebase-ml-vision introduces a new barcode scanning model, which comes with significant improvements in both latency and accuracy over the older model. In addition, with the latest API, you now can access the raw bytes for non UTF-8 encoded barcode data.
> 
> Be sure to add the new firebase-ml-vision-barcode-model module to your project dependencies to use the new model.

So we need to add ` implementation 'com.google.firebase:firebase-ml-vision-barcode-model:16.0.1'`.

But this only affects barcodes, not text.

**Comment by cs-googler** [comment] 2020-04-03 16:35
> I just found the following hint on https://firebase.google.com/docs/ml-kit/android/read-barcodes
> 
> > Version 24.0.0 of firebase-ml-vision introduces a new barcode scanning model, which comes with significant improvements in both latency and accuracy over the older model. In addition, with the latest API, you now can access the raw bytes for non UTF-8 encoded barcode data.
> > Be sure to add the new firebase-ml-vision-barcode-model module to your project dependencies to use the new model.
> 
> So we need to add ` implementation 'com.google.firebase:firebase-ml-vision-barcode-model:16.0.1'`.
> 
> But this only affects barcodes, not text.

Yes, this is only for barcode. We have identified a bug which required a reboot after google play service gets updated. The fix is to be released in a new google play service. For now, can you reboot to try again? Also, it would help a lot if you can send a bugreport to songchenxi@google.com

**Comment by hardysim** [comment] 2020-04-06 06:16
I've rebooted (after updating to developer preview 2.1) and now OCR is working :-)

**Comment by NamDoTri** [comment] 2020-04-06 11:25
I have the same issue when following this [article](https://firebase.google.com/docs/ml-kit/android/recognize-text#recognize-text-in-images) to use Firebase ML Vision for text recognition from images.

My environment: Android Studio 3.6.2
com.google.firebase:firebase-ml-vision 24.0.1
When using a Pixel 3 emulator with Android 10, Google Play services  20.19.04, it logs the same message saying "waiting for the text recognition model to be downloaded". 

Rebooting after updating Google Play services doesn't help. Could you give me some suggestions please?

**Comment by cs-googler** [comment] 2020-04-08 16:05
> I've rebooted (after updating to developer preview 2.1) and now OCR is working 👍

Awesome!

**Comment by hardysim** [comment] 2020-05-13 08:35
It started crashing again after updating to DP 4 `RPP4.200409.015` with Play Services `20.12.14 (140408-302211955)`. A reboot does not help.

**Comment by cs-googler** [comment] 2020-05-13 16:17
> It started crashing again after updating to DP 4 `RPP4.200409.015` with Play Services `20.12.14 (140408-302211955)`. A reboot does not help.

Thanks for reporting! 

Note that DP4 (RPP4.200409.015) is currently “for developers only​ and not intended for daily or consumer use.” The problem might be caused by the OS.

We will test internally and post update here. 

Thanks again!

**Comment by cs-googler** [comment] 2020-05-14 17:37
> It started crashing again after updating to DP 4 `RPP4.200409.015` with Play Services `20.12.14 (140408-302211955)`. A reboot does not help.

Hi this might be an OS issue which we can repro in the an older version of android R preview but not in the latest internal dev build. Please check again when the new preview is available.

**Comment by hardysim** [comment] 2020-07-10 12:46
It seems to be working out of the box with Beta 2.

**Comment by DSinge** [comment] 2020-11-09 21:39
Device: Pixel 2
Never had a developer preview installed

Opening the app after the crash did not cause the issue to happen again.

We've also been getting reports of this is issue from our users.

```
2020-11-09 15:54:30.646 W: Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
2020-11-09 15:54:30.647 I: onOpened: HDR+ client opened.
2020-11-09 15:54:30.651 D: enableHdrPlusModeLocked: HDR+ mode enabled
2020-11-09 15:54:30.651 D: getFwVersion: Easel getFwVersion: 20181102.5108589.002.000 code:0
2020-11-09 15:54:30.652 D: NetReassign [no changes]
2020-11-09 15:54:30.653 W: EASEL (54:30.653 P33 T41): doWorkLocked: Not enough inputs (0 but need 3).
2020-11-09 15:54:30.653 W: Unknown dynamite feature vision.dynamite.barcode
2020-11-09 15:54:30.659 I: Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
2020-11-09 15:54:30.664 W: Ignoring optional dynamite feature vision.barcode
2020-11-09 15:54:30.668 W: Local module descriptor class for com.google.android.gms.vision.barcode not found.
2020-11-09 15:54:30.668 I: Considering local module com.google.android.gms.vision.barcode:0 and remote module com.google.android.gms.vision.barcode:0
2020-11-09 15:54:30.668 E: Error loading optional module com.google.android.gms.vision.barcode: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
2020-11-09 15:54:30.669 W: Native handle not yet available. Reverting to no-op handle.
2020-11-09 15:54:30.672 W: notifyFrameMetadata: Frame metadata is not valid.
2020-11-09 15:54:30.685 I: Requesting optional module download of face.
2020-11-09 15:54:30.686 I: Requesting optional module download of barcode.
2020-11-09 15:54:30.690 W: Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
2020-11-09 15:54:30.700 I: Requesting optional module download of ocr.
2020-11-09 15:54:30.700 I: Checking for download completion for 5112813 -- face,barcode,ocr
2020-11-09 15:54:30.704 I: Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
2020-11-09 15:54:30.711 W: Local module descriptor class for com.google.android.gms.vision.barcode not found.
2020-11-09 15:54:30.711 I: Considering local module com.google.android.gms.vision.barcode:0 and remote module com.google.android.gms.vision.barcode:0
2020-11-09 15:54:30.711 E: Error loading optional module com.google.android.gms.vision.barcode: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
2020-11-09 15:54:30.723 I: [53] +vision.barcode:-1
2020-11-09 15:54:30.729 D: {Camera@aee36ab[id=0]} Use case ImageAnalysis:androidx.camera.core.ImageAnalysis-75eec2a6-08d6-460e-91e5-5e33eb7a245f INACTIVE
2020-11-09 15:54:30.731 D: Active and attached use case: [androidx.camera.core.Preview-fcd3fcae-2ca1-40a1-977a-a23b7c1d3f9b165466446] for camera: 0
2020-11-09 15:54:30.732 D: Attempting to submit CaptureRequest after setting
2020-11-09 15:54:30.733 D: Issuing request for session.
2020-11-09 15:54:30.738 W: notifyFrameMetadata: Frame metadata is not valid.
2020-11-09 15:54:30.738 I: Starting update, reason: 4 urgentFeatures: vision.barcode:-1
2020-11-09 15:54:30.755 W: Attempted to request and unrequest the same feature: brella. Ignoring unrequest.
2020-11-09 15:54:30.803 W: notifyFrameMetadata: Frame metadata is not valid.
2020-11-09 15:54:30.818 D: @ 5105.593: AP has been up: last 4804361018, now 5105592914 usec
2020-11-09 15:54:30.818 D: @ 5105.593: Sending to ASH storage: 0 651 0
2020-11-09 15:54:30.824 I: [167] amhf.j(26): Module info request for [# bbds@1282eed4] modules from package com.google.android.gms v=203915037 hasAccount:true authEnabled:false

2020-11-09 15:54:31.105 E: FATAL EXCEPTION: main
    Process: co.twenty.stop.spread.dev.debug, PID: 17756
    com.google.mlkit.common.MlKitException: Waiting for the barcode scanning model to be downloaded. Please wait.
        at com.google.mlkit.vision.barcode.internal.zzf.zzb(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.1.2:104)
        at com.google.mlkit.vision.barcode.internal.zzf.run(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.1.2:143)
        at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@16.1.0:23)
        at com.google.mlkit.vision.common.internal.zzc.call(Unknown Source:4)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@17.0.0:29)
        at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.0.0:3)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@17.0.0:24)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zza(com.google.mlkit:common@@17.0.0:30)
        at com.google.mlkit.common.sdkinternal.zzh.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by argzdev** [comment] 2023-05-22 12:05
Just bumping the thread, looking at the conversation it seems that this issue has been resolved. I'll close this issue for now. If anyone can verify that the issue still exists, please feel free to ask this to be reopened. Thanks!

**Closed by argzdev** 2023-05-22 12:05 UTC
Labels: api: mlkit
