### ISSUE TITLE
Offline document added & modified, comes with all null fields except modified when fetched from cache until app restart

### ISSUE THREAD

**Issue by xsheru** [firebase/firebase-android-sdk#3535] opened 2022-03-15 09:52 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Bumblebee
  * Firebase Component: Firestore
  * Component version: 24.0.1

### [REQUIRED] Step 3: Describe the problem

While device is completely offline I have added one document (person)
{
    name: Name 2,
    phone: 2222222222,
    amount: 0
}

While device is still offline I modified it using increment on amount field + 100,

Now after modifying I am showing list of people where i am fetching list of people, i get the following documents from snapshot
[{
    name: Name 1,
    phone: 1111111111
    amount: 0
},
{
    amount: 100
}]

The document returned as name & phone null should have been the one I just added. No matter how many times I fetched the people result is same.

This happens until I restart the app. Once I restart the app and even the device is still offline people list comes the way it is expected.

#### Steps to reproduce:

1. Keep android device offline.
2. Add a document to a collection while offline
3. Modified some number field using Firestore Increment Feature and add any number.
4. After adding fetch the same collection while offline using 'Source.CACHE'.
5. List should return with one document where all key values are null except the incremented key value.
6. Now stay in offline and restart the app.
7. Fetch the same collection.
8. List should return all documents as expected.

**Comment by dconeybe** [comment] 2022-03-15 14:32
@xsheru Thank you for reporting this. I will try to reproduce.

In the meantime, could you enable debug logging, reproduce, and provide the logcat output? To enable debug logging, call `FirebaseFirestore.setLoggingEnabled(true)`.

**Comment by dconeybe** [comment] 2022-03-15 18:51
@xsheru We have found the root cause of this incorrect behavior and it is indeed a bug in Firestore. It was actually very recently reported in https://github.com/firebase/firebase-android-sdk/issues/3528 so I'm going to close this issue as a duplicate of it. Please follow the duplicate issue for updates, but tl;dr your only workaround for now is to downgrade `com.google.firebase:firebase-bom` to 29.0.3.

**Closed by dconeybe** 2022-03-15 18:51 UTC
Labels: api: firestore
