### ISSUE TITLE
Significant Increase in ANRs After Updating to SDK 34 - Firebase Ads Libraries

### ISSUE THREAD

**Issue by axitasavani** [firebase/firebase-android-sdk#6223] opened 2024-09-02 09:56 UTC
### Step 1: Describe your environment

  * Android device: Samsung, Oppo, Vivo, Techno, Google, Motorola
  * Android OS version: 11,12,13,14
  * Google Play Services version: 'com.google.gms:google-services:4.4.2'
  * Firebase/Play Services SDK version: 

- firebase-crashlytics:18.6.3'
- firebase-analytics:21.6.2'
- firebase-ads:23.0.0'
- firebase-messaging:23.4.1'
- firebase-config:21.6.3'

  
#### Steps to reproduce:
 We have observed a substantial rise in ANRs (Application Not Responding) incidents after updating our Android SDK to version 34. The issue appears to be linked to Google Ads libraries, as the ANRs are predominantly coming from them. 

_Our project is configured with the following settings:_

- classpath 'com.android.tools.build:gradle:7.3.1' , distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip
- Target SDK version: 34
- Minimum SDK version: 21

This issue is critical and has negatively impacted the user experience. We seek urgent assistance in identifying and resolving the root cause of these ANRs.
  
![SS_1](https://github.com/user-attachments/assets/d8d9e57b-09bd-45f4-9137-bb8d9e8774fc)
![SS_2](https://github.com/user-attachments/assets/ba7c4139-25ac-4987-ab7b-c1c5f068a948)
![SS_3](https://github.com/user-attachments/assets/cccf5e40-1857-4a01-9669-d1957b1f42d3)

**Comment by thatfiredev** [comment] 2024-09-02 17:17
This issue was originally opened in the firebase/quickstart-android repository, but the error seems to be related to the SDK, so I've transferred it to the firebase/firebase-android-sdk repo.

**Comment by thatfiredev** [comment] 2024-09-02 17:19
@axitasavani Sorry that you ran into this.
Just to double check: are you calling `MobileAds.initialize()` in a separate thread, as suggested in the [docs](https://developers.google.com/admob/android/quick-start#initialize_the_mobile_ads_sdk)?

**Comment by axitasavani** [comment] 2024-09-05 05:27
Hi, @thatfiredev
Currently, I'm not calling this method in a separate Thread. 
But, after you suggested I checked with MobileAds.initialize() in a separate thread but it's getting more ANR in my app.
Also, Firebase TestLab rejects the app due to too much ANR & then Crashes.

**SS**: Attached Screenshot of Firebase TestLab 
**Device**: Samsung Galaxy S24, API Level 34 
![Screenshot 2024-09-05 105315](https://github.com/user-attachments/assets/afdc6b0c-ac11-476b-ae48-f6efb53665df)

- Note: I have not checked with [Optimizing initialization and ad loading](https://developers.google.com/admob/android/optimize-initialization) Because it is in Beta.

**Comment by lehcar09** [comment] 2024-09-05 21:19
Hi @axitasavani, I tried reproducing the issue, however, I did not encounter the ANR issue. I wonder if the issue is related to the behavioral changes in Android 14 documented [here](https://developer.android.com/about/versions/14/behavior-changes-14).

Could you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue?

**Comment by axitasavani** [comment] 2024-09-06 07:02
@lehcar09 Let me share the Init code of Admob which I used : 
- This function is called from the Application Class > onCreate() method 

```
private void initMobileSDK(Context context) {
        Log.i(TAG, "initMobileSDK:  --> ");

        MobileAds.initialize(context, new OnInitializationCompleteListener() {
            public void onInitializationComplete(@NotNull InitializationStatus initializationStatus) {
                Log.i(ObAdMobConfigManager.TAG, "onInitializationComplete: MobileAds initialize successfully.");
            }
        });
        this.getAdRequestInstance(); // here I create AdRequest.Builder 
    }
```

**Screenshot of ANR :** 

![ss_4_obadmob](https://github.com/user-attachments/assets/8444d651-9071-4b4b-ad85-514f4bd31ea6)
![ss_5_obadmob](https://github.com/user-attachments/assets/f7e1f2af-7626-475b-a453-f605ffeb7e30)


**ANR logs :** 

` main (runnable):tid=1 systid=24187 
#00 pc 0x4a7c34 libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool) + 140)
#01 pc 0x5b70bc libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const + 396)
#02 pc 0x5d465c libart.so (art::DumpCheckpoint::Run(art::Thread*) + 924)
#03 pc 0x5b8028 libart.so (art::Thread::RunCheckpointFunction() + 176)
#04 pc 0x1d5c24 libart.so (art::ClassLinker::LoadClass(art::Thread*, art::DexFile const&, art::dex::ClassDef const&, art::Handle<art::mirror::Class>) + 1372)
#05 pc 0x1d2544 libart.so (art::ClassLinker::DefineClass(art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::DexFile const&, art::dex::ClassDef const&) + 932)
#06 pc 0x1f7d48 libart.so (void* art::VisitClassLoaderDexFiles<void art::VisitClassLoaderDexFiles<art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30>(art::ScopedObjectAccessAlreadyRunnable&, art::Handle<art::mirror::ClassLoader>, art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30)::'lambda'(art::DexFile const*, void**), void*>(art::ScopedObjectAccessAlreadyRunnable&, art::Handle<art::mirror::ClassLoader>, art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30, void*) + 752)
#07 pc 0x1d1820 libart.so (art::ClassLinker::FindClassInBaseDexClassLoader(art::ScopedObjectAccessAlreadyRunnable&, art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::ObjPtr<art::mirror::Class>*) + 648)
#08 pc 0x1d3004 libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>) + 1060)
#09 pc 0x1bf310 libart.so (art::ClassLinker::DoResolveType(art::dex::TypeIndex, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>) + 184)
#10 pc 0x1bf8d0 libart.so (art::ObjPtr<art::mirror::Class> art::ClassLinker::DoResolveType<art::ObjPtr<art::mirror::Class> >(art::dex::TypeIndex, art::ObjPtr<art::mirror::Class>) + 232)
#11 pc 0x1d5e50 libart.so (art::ClassLinker::LoadSuperAndInterfaces(art::Handle<art::mirror::Class>, art::DexFile const&) + 240)
#12 pc 0x1d2598 libart.so (art::ClassLinker::DefineClass(art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::DexFile const&, art::dex::ClassDef const&) + 1016)
#13 pc 0x1f7d48 libart.so (void* art::VisitClassLoaderDexFiles<void art::VisitClassLoaderDexFiles<art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30>(art::ScopedObjectAccessAlreadyRunnable&, art::Handle<art::mirror::ClassLoader>, art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30)::'lambda'(art::DexFile const*, void**), void*>(art::ScopedObjectAccessAlreadyRunnable&, art::Handle<art::mirror::ClassLoader>, art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30, void*) + 752)
#14 pc 0x1d1820 libart.so (art::ClassLinker::FindClassInBaseDexClassLoader(art::ScopedObjectAccessAlreadyRunnable&, art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::ObjPtr<art::mirror::Class>*) + 648)
#15 pc 0x4d0c88 libart.so (art::VMClassLoader_findLoadedClass(_JNIEnv*, _jclass*, _jobject*, _jstring*) + 672)
       at java.lang.VMClassLoader.findLoadedClass(Native method)
       at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.google.android.gms.dynamic.RemoteCreator.getRemoteCreatorInstance(com.google.android.gms:play-services-basement@@18.1.0:5)
       at com.google.android.gms.ads.internal.client.zzeq.zza(com.google.android.gms:play-services-ads-lite@@22.0.0:2)
       at com.google.android.gms.ads.internal.client.zzaq.zzc(com.google.android.gms:play-services-ads-lite@@22.0.0:12)
       at com.google.android.gms.ads.internal.client.zzax.zzf(com.google.android.gms:play-services-ads-lite@@22.0.0:1)
       at com.google.android.gms.ads.internal.client.zzax.zzd(com.google.android.gms:play-services-ads-lite@@22.0.0:11)
       at com.google.android.gms.ads.internal.client.zzej.zzz(com.google.android.gms:play-services-ads-lite@@22.0.0:3)
       at com.google.android.gms.ads.internal.client.zzej.zzm(com.google.android.gms:play-services-ads-lite@@22.0.0:8)
       at com.google.android.gms.ads.MobileAds.initialize(com.google.android.gms:play-services-ads-lite@@22.0.0:3)
       at com.********..config.ObAdMobConfigManager.initMobileSDK(ObAdMobConfigManager.java:147)
       at com.********.ConfigManager.initObAdMobConfigManager(ObAdMobConfigManager.java:126)
       at com********..BusinessCardApplication.initObAdMob(BusinessCardApplication.java:291)
       at com********..BusinessCardApplication.initAllObHomeLibs(BusinessCardApplication.java:232)
       at com.********.BusinessCardApplication.onActivityCreated(BusinessCardApplication.java:317)
       at android.app.Application.dispatchActivityCreated(Application.java:390)
       at android.app.Activity.dispatchActivityCreated(Activity.java:1397)
       at android.app.Activity.onCreate(Activity.java:1670)
       at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:88)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:363)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
       at com********.EditorActivity.onCreate(EditorActivity.java:39)
       at android.app.Activity.performCreate(Activity.java:8119)
       at android.app.Activity.performCreate(Activity.java:8103)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3713)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8192)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)`

> I can't reproduce this ANR in real devices but user continue facing this on app startup.
NOTE: With "background thread" code also this ANR is comes. ([Optimizing initialization and ad loading](https://developers.google.com/admob/android/optimize-initialization))

**Comment by lehcar09** [comment] 2024-09-11 17:20
Thank you for the additional details @axitasavani . Looking at your logs, it looks like  that the ANR you’re experiencing is caused by the behavioral changes in Android 14. 

Our engineers are already working on this along with other improvements for API level 34 (android 14). Pardon me, but we don't have a definite timeline yet. However, it should be rolled out across all Firebase Android SDKs soon. We hope for your understanding.

To streamline the updates, you can follow on the issue [#6147](https://github.com/firebase/firebase-android-sdk/issues/6147). With that, I'll be closing this issue now. Thanks.

**Closed by lehcar09** 2024-09-11 17:20 UTC
Labels: api: ads, needs-attention
