### ISSUE TITLE
Updates about this issues with version 17.0.0. com.google.android.gms:play-services-safetynet

### ISSUE THREAD

**Issue by hathemi** [firebase/firebase-android-sdk#4666] opened 2023-02-13 08:15 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem

Votre dernière release de production (17 (0.0.17)) comporte des problèmes de SDK

> 
> com.google.android.gms:play-services-safetynet:17.0.0
> Le développeur du SDK a joint une note à cette version. Infos transmises par le développeur du SDK :
> 
> The SafetyNet Attestation API is being discontinued and replaced by the new Play Integrity API. Begin migration as soon as possible to avoid user disruption. The Play Integrity API includes all the integrity signals that SafetyNet Attestation offers and more, like Google Play licensing and better error messaging. Learn more and start migrating at https://developer.android.com/training/safetynet/deprecation-timeline

is there a way to ignore this issue and publish app to play store until firebase team find a solution? 
any information would be appreciated! 
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment] 2023-02-13 09:54
Hi @hathemi, thanks for reporting. You can still proceed with your app deployment and disregard the warning since the deadline for the migration is still on June 2023. Our engineers are currently working on this (#3890). That said, I'll try and ask for some updates and see if we can get some feedbacks.

I'll close this issue for now since this is a duplicate of #3890. Please do leave a thumbs up on the original author's post so we can track and prioritize the issue base on severity and demand. Thanks!

**Closed by argzdev** 2023-02-13 09:54 UTC
Labels: api: auth
