### ISSUE TITLE
Allow overriding the host for firebase auth request

### ISSUE THREAD

**Issue by anta-semenov** [firebase/firebase-android-sdk#1742] opened 2020-07-01 11:39 UTC
## What feature would you like to see?

Please allow overriding the host for auth requests to enable developers using their own reverse proxy in places where securetoken.googleapis.com or www.gooleapis.com are blocked.
This is related to ios sdk issue https://github.com/firebase/firebase-ios-sdk/issues/4987

but at least on ios it's possible to make a fork of the repo and do these changes by ourselves. With android sdk it seems it's not possible to make fork of firebase auth library.

## How would you use it?

I would set this proxy to point my app to my reverse proxy to be able to use firebase auth in places where official google hosts are blocked

**Comment by ashwinraghav** [comment] 2020-07-01 17:44
Thanks for the feature request.
Overriding the host is not really an option for the Android since Google play services has policies that prevent us from communicating to arbitrary backends. We do have some work in progress to decouple auth from play services, at which point this may be possible. At this point, we would also be open sourcing the Auth SDK. That would help you too.
For now, closing is as a duplicate of https://github.com/firebase/firebase-android-sdk/issues/125. Pls upvote there :)

**Closed by ashwinraghav** 2020-07-01 17:44 UTC
Labels: needs-triage
