### ISSUE TITLE
AppIndexing stickers no longer works with newest Gboard (10.3.05) 

### ISSUE THREAD

**Issue by Drakota** [firebase/firebase-android-sdk#2537] opened 2021-03-23 17:48 UTC
### Step 1: Describe your environment

  * Android device: Poco X3
  * Android OS version: 11
  * Google Play Services version: 21.06.13
  * Firebase/Play Services SDK version: 26.5.0
  * Firebase App Indexing SDK version: 19.2.0
  * Gboard version: 10.3.05
  
### Step 2: Describe the problem:
Firebase sticker indexing no longer seems to work on the newest Gboard version (10.3.05), the sticker pack is no longer displayed. To reproduce the problem, we can clone the [Firebase AppIndexing quickstart project](https://github.com/firebase/quickstart-android/tree/master/app-indexing) and follow the procedures below.

#### Steps to reproduce:

  1. Install or update Gboard to the latest version
  2. Launch the AppIndexing project on a emulator or device
  3. Open the keyboard and go to the stickers section and notice the absence of new sticker packs
  
#### Observed Results:
If I go to Settings -> Google -> Firebase App Indexing (at the bottom in the developer section) and tap on the application, I can see that all the stickers have been correctly indexed and shows no errors.
  
#### Expected Results:
I expect to see the stickers in the keyboard like it was before this version of Gboard

#### Likely issues:
I think this is another case of undocumented deprecation of a feature of Gboard and most likely doesn't have a fix

**Comment by aguatno** [comment] 2021-03-24 11:04
Hi @Drakota thanks for reporting. I was able to reproduce the issue. Let me check with team if there's any workarounds.

**Comment by aguatno** [comment] 2021-03-24 16:09
Per checking, we can’t guarantee that App Indexing will still work as expected since it will be eventually removed from the Firebase product set. Currently, we do not recommend using App Indexing for most Firebase apps and no longer support this feature.

I'll be closing this for now. Feel free to comment back so that this ticket can be reopened.

**Closed by aguatno** 2021-03-24 16:09 UTC
Labels: api: appindexing
