### ISSUE TITLE
Firebase Real time database issues

### ISSUE THREAD

**Issue by keval1040** [firebase/firebase-android-sdk#1936] opened 2020-09-03 17:37 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component:
implementation 'com.google.firebase:firebase-core:17.5.0'
    implementation 'com.google.firebase:firebase-auth:19.3.2'
    implementation 'com.google.firebase:firebase-messaging:20.2.4'
    implementation 'com.google.firebase:firebase-database:19.4.0'
    implementation 'com.google.firebase:firebase-config:19.2.0'
    implementation 'com.google.firebase:firebase-analytics:17.5.0'

  * Component version: Not know

### [REQUIRED] Step 3: Describe the problem
I used real time database for chat working fine in few day but now in some device not working properly not read and write functionality is working please provide some solution so my Live application working smoothly
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by schmidt-sebastian** [comment] 2020-09-18 20:50
Likely a dupe of https://github.com/firebase/firebase-android-sdk/issues/1937

**Closed by schmidt-sebastian** 2020-09-18 20:50 UTC
Labels: api: database
