### ISSUE TITLE
FirebaseInAppMessagingDisplay makes failing the Glide dependency 

### ISSUE THREAD

**Issue by jesphinpt** [firebase/firebase-android-sdk#5018] opened 2023-05-19 13:30 UTC
I am trying to add the FirebaseInAppMessagingDisplay sdk to my app. After adding and compiling the app, I am getting runtime error with my [glide](https://mvnrepository.com/artifact/com.github.bumptech.glide/glide) SDK.

Not sure why it makes failing the Glide after adding the FirebaseInAppMessagingDisplay.

FirebaseInAppMessagingDisplay: [20.3.2](https://mvnrepository.com/artifact/com.google.firebase/firebase-inappmessaging-display?repo=google)

**Comment by argzdev** [comment] 2023-05-19 14:07
Hey @jesphinpt, thanks for reaching out. Firebase InAppMessaging uses Glide inside as one of it's dependency, which I think is why you're getting an issue. Can you share with us your stacktrace for us to investigate this further? Also if you have any code snippet or minimal reproducible example to share let us know. It'll help speed up our investigation. Thanks!

**Comment by jesphinpt** [comment] 2023-05-19 15:11
```
error: cannot find symbol
import com.bumptech.glide.BitmapRequestBuilder;
                         ^
  symbol:   class BitmapRequestBuilder
  location: package com.bumptech.glide

error: cannot find symbol
import com.bumptech.glide.DrawableRequestBuilder;

error: cannot find symbol
import com.bumptech.glide.GenericRequestBuilder;
                         ^
  symbol:   class GenericRequestBuilder
  location: package com.bumptech.glide
```

**Comment by argzdev** [comment] 2023-05-19 16:35
`com.google.firebase:firebase-inappmessaging-display:20.3.2` is using a more latter version of Glide `4.11.0` which is causing a conflict with your import version of Glide `3.7.0`. You'll need to change your code and use the more updated version of Glide to avoid this error.

**Comment by jesphinpt** [comment] 2023-05-22 10:08
I have tried to exclude glide package from the firebasemessagedisplay.



```
 java.lang.NoSuchMethodError: No virtual method addDefaultRequestListener(Lcom/bumptech/glide/request/RequestListener;)Lcom/bumptech/glide/RequestManager; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/~~wvjoT1KqRj8-TCvf8A118g==/com-8U4lXO__Vnk1SDLc7_xkhA==/base.apk)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule.providesGlideRequestManager(GlideModule.java:32)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.providesGlideRequestManager(GlideModule_ProvidesGlideRequestManagerFactory.java:43)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:32)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:11)
        at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:21)
        at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:8)
        at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:61)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:16)
        at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.google.firebase.inappmessaging.display.internal.injection.components.DaggerAppComponent.providesFirebaseInAppMessagingUI(DaggerAppComponent.java:80)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.buildFirebaseInAppMessagingUI(FirebaseInAppMessagingDisplayRegistrar.java:75)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.$r8$lambda$mFT7XCE3YJXhnGdhKohfXnpd5DM(Unknown Source:0)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
        at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
        at com.google.firebase.tracing.ComponentMonitor.$r8$lambda$nUgWIWAyyZxi6mRt6KSZMmA5LxE(Unknown Source:0)
        at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:140)
        at com.google.firebase.components.ComponentRuntime.$r8$lambda$4FqOW9eOQsvFYo-HpMfxCOnPQr0(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:66)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
```

**Comment by jesphinpt** [comment] 2023-05-22 10:10
From which version firebsseinappmessagingdisplay supports glide version 4?

**Comment by argzdev** [comment] 2023-05-22 13:02
Yes, excluding this will definitely cause an error since InAppMessaging is using Glide to display images. The earliest version of `com.google.firebase:firebase-inappmessaging-display` which supported Glide was in version `20.1.0`, however the first version of Glide added in this version is already version `4.11.0`. You'll have to update your code to use the latest version of Glide. I don't see any alternative solution for this.

Given that the issue is now due to code update, I don't see anything else we can do on the SDK side. That said, I'll close this issue now. Feel free to ask this to be reopened if you think this is a mistake or there's any clarification needed on the SDK side. Thanks!

**Closed by argzdev** 2023-05-22 13:02 UTC
Labels: api: inappmessaging, needs-info
