### ISSUE TITLE
Attempt to invoke virtual method 'com.google.firebase.inappmessaging.model.MessageType com.google.firebase.inappmessaging.model.InAppMessage.getMessageType()' on a null object reference

### ISSUE THREAD

**Issue by zhaiyunbin** [firebase/firebase-android-sdk#3596] opened 2022-03-29 01:30 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.2
  * Firebase Component: inappMessaging
  * Component version: 20.1.2

#### Steps to reproduce:
firebase crash

#### Relevant Code:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.inappmessaging.model.MessageType com.google.firebase.inappmessaging.model.InAppMessage.getMessageType()' on a null object reference
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.extractActions(FirebaseInAppMessagingDisplay.java:438)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.inflateBinding(FirebaseInAppMessagingDisplay.java:309)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$000(FirebaseInAppMessagingDisplay.java:79)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$1.run(FirebaseInAppMessagingDisplay.java:287)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8192)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

**Comment by argzdev** [comment] 2022-03-29 11:44
Hi @zhaiyunbin, thanks for reporting. Could you provide steps how to reproduce this issue? If you could also provide a minimal repro of the issue, that'll greatly help us in our investigation. Thanks!

**Comment by zhaiyunbin** [comment] 2022-03-30 01:12
> Hi @zhaiyunbin, thanks for reporting. Could you provide steps how to reproduce this issue? If you could also provide a minimal repro of the issue, that'll greatly help us in our investigation. Thanks!

  I just add firebase related dependencies ,The in-appmessage message was sent in the firebase console and then the error was found in carsh.

> `   //firebase 
    implementation platform('com.google.firebase:firebase-bom:29.2.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-perf'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-inappmessaging-display'`

**Comment by argzdev** [comment] 2022-03-30 09:28
Hi @zhaiyunbin, I'm unable to reproduce this issue. Could you answer some details below:
1. Could you reproduce this issue? If yes, could you provide a minimal repro?
2. Is this issue persistent? In what Android version are you able to reproduce this issue?
3. Looking in the code, it seems that the error `InAppMessage.getMessageType()` is related to the InAppMessage layout. What option did you select in the Firebase InAppMessage Console?
<img width="457" alt="Screen Shot 2022-03-30 at 5 24 26 PM" src="https://user-images.githubusercontent.com/93124282/160799400-8b575586-8de5-4358-8bdd-c9b2b47ea141.png">


Thanks!

**Comment by zhaiyunbin** [comment] 2022-03-30 11:53
> * Could you reproduce this issue? If yes, could you provide a minimal repro?
> * Is this issue persistent? In what Android version are you able to reproduce this issue?
> * Looking in the code, it seems that the error `InAppMessage.getMessageType()` is related to the InAppMessage layout. What option did you select in the Firebase InAppMessage Console?

 This message has been deleted，I don't have any more information either...Just remember that the type is Top banner

**Comment by argzdev** [comment] 2022-03-30 17:25
Hi @zhaiyunbin, unfortunately I'm unable to reproduce the issue even with a top banner. Given that the issue is difficult to reproduce, I'm unable to investigate this further. If you could provide more details, it'll greatly help us out. However, I'll close this for now, since there's no way of moving forward. Feel free to reopen once you have more details. Thanks!

**Closed by argzdev** 2022-03-30 17:25 UTC
Labels: api: inappmessaging, needs-attention
