### ISSUE TITLE
Instantiation of JsonResponse failed! class com.google.android.gms.internal.firebase-auth-api.x1

### ISSUE THREAD

**Issue by aliyildiz1980** [firebase/firebase-android-sdk#4900] opened 2023-04-16 18:44 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Flamingo | 2022.2.1 (Build #AI-222.4459.24.2221.9862592, built on March 31, 2023)
  * Firebase Component: Auth (Firebase-Bom)
  * Component version: Firebase Bom 31.5.0
  * Gradle version: 8.0.0
  * OS: macOS Ventura 13.3.1 (M1 chip)

### [REQUIRED] Step 3: Describe the problem

I upgraded Android Studio to the latest version yesterday. AGP project update warning has appeared and gradle has been upgraded to latest version. After this upgrade, the exception below is thrown in release AAB (minifyEnabled is true) when signInWithEmailAndPassword function is called. When "-keep class com.google.android.gms.internal.** { *; }" line is added to proguard config file, the error disappears. I think this line should be added to firebase sdk configuration.

W  f5.m: An internal error has occurred. [ Instantiation of JsonResponse failed! class com.google.android.gms.internal.firebase-auth-api.x1 ]
W  	at com.google.android.gms.internal.firebase-auth-api.g.a(SourceFile:167)
W  	at com.google.android.gms.internal.firebase-auth-api.b0.a(SourceFile:221)
W  	at com.google.android.gms.internal.firebase-auth-api.c0.j(Unknown Source:8)
W  	at com.google.android.gms.internal.firebase-auth-api.z.e(SourceFile:197)
W  	at com.google.android.gms.internal.firebase-auth-api.e.b(SourceFile:3)
W  	at com.google.android.gms.internal.firebase-auth-api.gt.f(SourceFile:7)
W  	at com.google.android.gms.internal.firebase-auth-api.k0.c(SourceFile:104)
W  	at com.google.android.gms.internal.firebase-auth-api.k0.b(SourceFile:67)
W  	at com.google.android.gms.internal.firebase-auth-api.s.i(SourceFile:21)
W  	at com.google.android.gms.internal.firebase-auth-api.iu.c(SourceFile:22)
W  	at com.google.android.gms.internal.firebase-auth-api.f.r(SourceFile:26)
W  	at com.google.android.gms.internal.firebase-auth-api.bv.a(Unknown Source:18)
W  	at com.google.android.gms.internal.firebase-auth-api.d0.run(Unknown Source:8)
W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W  	at java.lang.Thread.run(Thread.java:1012)

**Comment by argzdev** [comment] 2023-04-17 18:46
Thanks for reporting, @aliyildiz1980. I was able to reproduce the same behavior. I'll notify our engineers about this.

**Comment by argzdev** [comment] 2023-04-19 09:27
It seems that this issue already exists in #2124. Let's keep that issue open and close this one for better tracking. Feel free to add extra details in #2124 if needed. That said, I'll mark this issue as duplicate. Thanks!

Internal tracking bug: 172259754

**Closed by argzdev** 2023-04-19 09:27 UTC
Labels: type: bug, api: auth

**Comment by aliyildiz1980** [comment] 2023-04-19 11:40
Yes, the exception seems the same but the conditions are different. Therefore, solving #2124 may not solve this one.

**Comment by argzdev** [comment] 2023-04-19 11:45
I have a hunch that it might be the same underlying issue, from what my investigation enabling `minifyEnabled` to `true` automatically enables R8. Although rest assured, we'll be testing out both scenarios after figuring out a fix.

**Comment by aliyildiz1980** [comment] 2023-04-19 11:56
minifyEnabled was enabled years ago in my project. I have never changed it afterwards. I mean it was not the trigger of this bug. I remarked that info as a clue to developer team. This error started after upgrading to new gradle version and new firebase bom version. In any case, of course, the source of the bug may be the same.

**Comment by argzdev** [comment] 2023-04-19 12:09
Gotcha, that makes sense. Thanks for that detail, @aliyildiz1980. I'll add that to the internal tracking bug.

**Comment by varun7952** [comment] 2023-04-22 17:54
@argzdev I am using AS Giraffe Preview with gradle 8.0 and minifyenabled= true since long but now when i tried to signed in firebase with custom token (While creating release bundle aab). To be noted it will not create any issue with the debug version when generating apk. I am attaching a exception. If i miss anything please let me know.

![error](https://user-images.githubusercontent.com/12626827/233799399-a96df9af-7333-4a4f-9ea9-5f0f2aba2043.png)

**Comment by dmatheyvives10** [comment] 2023-04-24 03:26
Make sure you have these lines:

-keep public class com.google.firebase.** {*;}
-keep class com.google.android.gms.internal.** {*;}
-keepclasseswithmembers class com.google.firebase.FirebaseException

> @argzdevEstoy usando AS Giraffe Preview con gradle 8.0 y minifyenabled= true desde hace mucho tiempo, pero ahora cuando traté de iniciar sesión en firebase con un token personalizado (mientras creaba el paquete de lanzamiento aab). Cabe señalar que no creará ningún problema con la versión de depuración al generar apk. Adjunto una excepción. Si me pierdo algo por favor hágamelo saber.
> 
> ![error](https://user-images.githubusercontent.com/12626827/233799399-a96df9af-7333-4a4f-9ea9-5f0f2aba2043.png)

**Comment by varun7952** [comment] 2023-04-24 11:50
@dmatheyvives10 I already have `-keep class com.google.android.gms.internal.** { *; }` and it worked but this is the hack not the solution for the problem. I hope firebase fix this in their upcoming release till then i will work with the hack.

**Comment by aliyildiz1980** [comment] 2023-04-26 10:38
> @dmatheyvives10 I already have `-keep class com.google.android.gms.internal.** { *; }` and it worked but this is the hack not the solution for the problem. I hope firebase fix this in their upcoming release till then i will work with the hack.

Totally agree
