### ISSUE TITLE
[Dynamic links] Dynamic Link works differently for each mobile phone.

### ISSUE THREAD

**Issue by coffeii** [firebase/firebase-android-sdk#5228] opened 2023-08-07 08:14 UTC
## Environment

- Android Studio version:
- Android Studio Chipmunk | 2021.2.1
- Build #AI-212.5712.43.2112.8609683, built on May 19, 2022
- Firebase Component: Dynamic Links
- Component version:  19.1.0

## The problem

- Updated Android targetSdkVersion to 33 (Android 13, Tiramisu) and dynamic links stopped working on some devices.

```
            <!-- Firebase Dynamiclink scheme -->
            <intent-filter android:label="@string/app_name">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="@string/firebase_dynamiclink_host"    // <-- "example.page.link"
                    android:scheme="https" />
                <data
                    android:host="@string/firebase_dynamiclink_host"
                    android:scheme="http" />
            </intent-filter>
```

- It works on Galaxy 23, Galxy S23 Ultra.
- It does not work on Galaxy S20, Galaxy Fold 3, Galaxy Flip 3..
- Not working devices... are all updated from Android 12 to Android 13.
- I think.. [Web intent resolution(android12)](https://developer.android.com/about/versions/12/behavior-changes-all?hl=ko#web-intent-resolution) some kind works differently on UPDATED DEVICE, but im not sure

- I click on dynamic link (in other app) and I get this error in Android Studio logcat when not working:

```
Activity not found to handle Intent action [CONTEXT service_id=77 ]
android.content.ActivityNotFoundException: Unable to find explicit activity class
When I downgrade targetSdkVersion to 32 it works again (but then other Android 13 features like notification permission are not working).
```

## Steps to reproduce:

- Update Android targetSdkVersion to 33
- Get two devices. one from Android OS 13 UPDATE from 12, and other one is just... Android OS 13.

Additional info:

[Unable to open app from Dynamic Link in android 13 devices](https://github.com/firebase/firebase-unity-sdk/issues/725)
[Reading Dynamic link is not working on Android app](https://github.com/firebase/firebase-android-sdk/issues/4198)
those two link helped... but i want to know WHY IT WORKED on some devices...

**Comment by argzdev** [comment] 2023-08-07 17:38
Hi @coffeii, thanks for reaching out. The Dynamic Link version `19.1.0` was released in Feb. 2020, I don't expect this to have full support, since Android 13 was released sometime around 2022. That said, please update to the latest version `21.1.0` and see if it makes any difference. Thanks!

**Comment by coffeii** [comment] 2023-08-08 00:26
Hi @argzdev 
thanks for your response.

i tried version 21.1.0, but there is no defference... 
Still some devices works, Some doesnt... 

if i change code to 
```
            <!-- Firebase Dynamiclink scheme -->
            <intent-filter android:label="@string/app_name">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="@string/firebase_dynamiclink_host"    // <-- "example.page.link"
                    android:scheme="https" />
                <data
                    android:host="@string/firebase_dynamiclink_host"
                    android:scheme="http" />

                <data
                    android:host="www.example.co.kr"
                    android:scheme="https" />
                <data
                    android:host="www.example.co.kr"
                    android:scheme="http" />

            </intent-filter>
```
it works and problem solved. 

but i want to know why "example.page.link" <- this works... on some devices...
thanks

**Comment by argzdev** [comment] 2023-08-08 16:33
HI @coffeii, thanks for the extra details. As for your question, I'm not really sure why it wouldn't work for some devices. It should work the same for all devices. I'm thinking if there's a problem with the whitelisting or app setup, but since you've mentioned that this is working on some devices. Could you answer a few questions below:
1. You mentioned that to reproduce this issue, the device needs to be OS 12 then updated to OS 13? Is this consistently reproducible in this scenario? 
2. And for the other Android 13 devices, does FDL also not work for them? Is this also consistently reproducible?
3. Is this also the case for emulators?

**Comment by coffeii** [comment] 2023-08-09 05:34
Hi @argzdev 
For your questions:

1. Our team has several devices. And which updated from OS 12 to 13, this issue always happened.....
2. Other Android 13 devices, not updated from 12, work. --->  for this, i saw weird things in logcat.
```
manifest.xml
      <activity
            android:name="ActivityB".            <---- this is i expected for FDL
            android:exported="true"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:noHistory="true">

            <!-- Firebase Dynamiclink scheme -->
            <intent-filter android:label="@string/app_name">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="@string/firebase_dynamiclink_host"    // <-- "example.page.link"
                    android:scheme="https" />
                <data
                    android:host="@string/firebase_dynamiclink_host"
                    android:scheme="http" />
            </intent-filter>
      </activity>

      <activity
            android:name="ActivityA" >      <----- this is main activity that if i run app
      </activity>

```
if DFL comes, ActivityA starts for those not updated..... this those not make sense,,, 
something about whitelisting has a problem...or.... i dont know.....

3. On emulator, issue works like updated device... FDL not working...

i really thank you.
After i saw logcat, i think FDL doesnot make problem.... but something on Android OS 13 has a bug...

**Comment by argzdev** [comment] 2023-08-09 19:45
Hi @coffeii, I see. I noticed something though, I think you might be lacking the `android:autoVerify="true"` in your intent-filters, which is why it's not redirecting properly. Could you try adding that and see if it works? It would look something like this:
```
<intent-filter 
    android:label="@string/app_name" 
    android:autoVerify="true">
```

**Comment by coffeii** [comment] 2023-08-11 08:20
Hi @argzdev ,

i ve tried your code, and it does no chage things.....
i thought `android:autoVerify="true"` is working after whitelisting, so... i tried, but doesn't fit with my problem...

Really thanks for your help. 
i think FDL is not problem.... so maybe this issue needs to be closed
thanks!

**Closed** 2023-08-11 08:20 UTC
Labels: api: dynamiclinks, needs-attention

**Comment by argzdev** [comment] 2023-08-11 09:16
Sure, but that's unfortunate, I'm not sure why it's not working. Feel free to come back here if you need anymore help in the future. Thanks too!
