### ISSUE TITLE
Unable to complete Apple SSO flow using `startActivityForSignInWithProvider`

### ISSUE THREAD

**Issue by Lyaisan** [firebase/firebase-android-sdk#4302] opened 2022-11-10 15:09 UTC
**Environment**
1. com.google.firebase:firebase-auth:21.0.7
2. Pixel 3 XL(Android 9), SM Galaxy S10 Lite(Android 12), Moto G4+(Android 7), Moto G 60 (Android 11)

**The problem**

Application uses Android SDK method ([startActivityForSignInWithProvider](https://developers.google.com/android/reference/com/google/firebase/auth/FirebaseAuth#startActivityForSignInWithProvider(android.app.Activity,%20com.google.firebase.auth.FederatedAuthProvider))) to authorise in the app via Apple SSO. When users start authentication flow, web browser is being opened, users enter their credentials, 2FA code (if needed) in a browser, then they are being returned to the app and get the `com.google.firebase.auth.FirebaseAuthWebException: The web operation was canceled by the user` exception.

**Steps to reproduce:**
- Start login flow using `startActivityForSignInWithProvider`
- Enter credentials in the opened browser
- Observe an error (the user will be returned to the app with an exception)

**Notes:**
- The issue does not reproduce on 100% devices
- The issue reproduces on some devices for one apple id and does not reproduce on the same device for another apple id
- The issue reproduces on one device and does not reproduce on another device for the same apple id

**Comment by argzdev** [comment] 2022-11-17 10:21
Hi @Lyaisan, thanks for reporting. For the devices & apple id that this issue is reproducible, is it consistently reproducible with the given scenario? I'm wondering if this has something to do with what browser is being used on those devices?

**Comment by Lyaisan** [comment] 2022-11-19 14:30
Hi @argzdev, thanks for reaching me! It is reproducible on the devices where the Google Chrome is the only browser, and the intent is being opened in the Chrome.
Note: If users click on overflow menu from this browser and tap on Continue with chrome, then the issue will not reproduce.
<img width="302" alt="Screenshot 2022-11-19 at 12 45 18" src="https://user-images.githubusercontent.com/10651911/202845374-7ab4662b-561e-428a-98e6-42bdd6e1edb4.png"> | <img width="318" alt="Screenshot 2022-11-19 at 12 56 43" src="https://user-images.githubusercontent.com/10651911/202855602-137d4ad2-bdb9-4ef7-ba0c-6fa9dbc31240.png">

**Comment by prameshj** [comment] 2022-11-21 19:47
Thanks for the additional info, @Lyaisan ! Are you able to share a screen recording of when the issue happens?

> It is reproducible on the devices where the Google Chrome is the only browser, and the intent is being opened in the Chrome.

Do you see the issue when sign is opened on a custom chrome tab(replacing the app screen), or in a separate browser window? The SDK will open the signin activity in a custom chrome tab whenever possible. We made a fix for this issue in 21.0.7 version, which I see you are already using - https://firebase.google.com/support/release-notes/android#auth_v21-0-7.

A screen recording would be very useful here. Thanks!

**Comment by argzdev** [comment] 2022-11-22 12:17
While we wait for the video recording, I'll add a `needs-info` tag for now. Don't worry if the issue closes due to stale, we can always reopen once we have further details.

**Comment by Lyaisan** [comment] 2022-11-22 18:29
Hi @prameshj @argzdev, here is a screen recording of when the issue happens
https://user-images.githubusercontent.com/10651911/203392710-2b12a5ba-ebdc-463e-a3df-012e365d3c68.mp4

**Comment by prameshj** [comment] 2022-11-22 19:11
> Hi @prameshj @argzdev, here is a screen recording of when the issue happens https://user-images.githubusercontent.com/10651911/203392710-2b12a5ba-ebdc-463e-a3df-012e365d3c68.mp4

Thanks for sharing, I had misunderstood this issue. I thought you see the "com.google.firebase.auth.FirebaseAuthWebException: The web operation was canceled by the user" when opening a different app to lookup 2FA credentials. Here it seems to be happening as part of the redirect flow. Not sure of the rootcause here.

2 followup questions:

1) Is this a regression? Was this working on older SDK versions?
2) Does login with other providers work, like "Continue with Google" button, in the video?

**Comment by Lyaisan** [comment] 2022-11-22 21:13
@prameshj, here are the answers:
1. Probably yes, because the first time an issue was filed in October
2. Initially we observed an issue with Google SSO (that is also was reproducible only on some of the devices), then the Apple SSO issue was found as well

**Comment by prameshj** [comment] 2022-11-24 01:37
Thanks! I tried the Apple sign in flow using "startActivityForSignInWithProvider" and it worked fine for me with a custom chrome tab. I tried on API version 28 (Android 9), Pixel on emulator.

Are the affected devices using the app built with Auth SDK version - 21.0.7 or above? Are you able to reproduce this in an emulator environment?

**Comment by Lyaisan** [comment] 2022-11-24 13:46
@prameshj Yes, the app is built with Auth SDK version 21.0.7. I was not able to reproduce this issue myself but it always reproduces on some of the test devices of our QA team. I will ask a team to try to reproduce it on the emulator as well.

Some notes are below:
- The issue does not reproduce on 100% devices
- The issue reproduces on some devices for one apple id and does not reproduce on the same device for another apple id
- The issue reproduces on one device and does not reproduce on another device for the same apple id
- The issue is reproducing when sign is opened on a custom chrome tab and is not reproducing in a chrome browser
- The issue is reproducing when there is no account that is connected with Apple ID and user tries to Login or Sign up with Apple ID for the first time after app installation

Thank you!

**Comment by prameshj** [comment] 2022-11-28 18:16
Thanks for the additional info, it does seem tricky to reproduce. Are you able to see this issue in older SDK versions as well, say 21.0.6?

**Comment by Lyaisan** [comment] 2022-12-05 07:09
@prameshj we have tested the issue on the build with an older SDK version 21.0.6 - the issue does not reproduce. Thank you!

**Comment by prameshj** [comment] 2022-12-05 19:54
Thanks! I think the fix made for https://github.com/firebase/firebase-android-sdk/issues/2741 might be causing an issue, but it is unclear since we are not able to repro.  Are you able to open a firebase support case to provide more info? 

I will leave this issue open for other folks to +1 in case they are seeing it.

**Comment by Lyaisan** [comment] 2022-12-07 14:20
Sure, thanks! Could you give more details about firebase support case and how to open it, please?

**Closed as completed** 2023-01-18 13:42 UTC
Labels: api: auth
