### ISSUE TITLE
AUTHENTICATION_FAILED when trying to get token

### ISSUE THREAD

**Issue by emrisb** [firebase/firebase-android-sdk#3243] opened 2021-12-15 11:12 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 3
  * Firebase Component: Firebase Messaging
  * Component version: Firebase bom version 26.5.0

### [REQUIRED] Step 3: Describe the problem
We are trying to get firebase token, but we got authentication failed error in some devices
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
I do not know how it happens but i think you can try to get token with this code FirebaseMessaging.getInstance().getToken()

java.io.IOException: AUTHENTICATION_FAILED
	at com.google.firebase.iid.GmsRpc$$Lambda$0.e(GmsRpc.java:2007)
	at com.google.android.gms.tasks.zze.run(zze.java:5)
	at com.google.firebase.iid.FirebaseIidExecutors$$Lambda$0.execute(FirebaseIidExecutors.java:0)
	at com.google.android.gms.tasks.zzc.b(zzc.java:6)
	at com.google.android.gms.tasks.zzq.c(zzq.java:19)
	at com.google.android.gms.tasks.zzu.d(zzu.java:104)
	at com.google.android.gms.tasks.zze.run(zze.java:15)
	at com.google.android.gms.cloudmessaging.zzz.execute(zzz.java:0)
	at com.google.android.gms.tasks.zzc.b(zzc.java:6)
	at com.google.android.gms.tasks.zzq.c(zzq.java:19)
	at com.google.android.gms.tasks.zzu.d(zzu.java:104)
	at com.google.android.gms.tasks.TaskCompletionSource.b(TaskCompletionSource.java:8)
	at com.google.android.gms.cloudmessaging.zzq.b(zzq.java:9)
	at com.google.android.gms.cloudmessaging.zzs.b(zzs.java:7)
	at com.google.android.gms.cloudmessaging.zzf.a(zzf.java:45)
	at com.google.android.gms.cloudmessaging.zzi.handleMessage(zzi.java:2)
#### Relevant Code:
```
FirebaseMessaging.getInstance().getToken()
```

**Comment by argzdev** [comment] 2021-12-15 12:01
Hi @emrisb, thanks for reporting. This seems to be a duplicate of #3040. Could you try updating to the latest version of the SDK 29.0.2, at the same time try the solution provided in #3040? Thanks.

**Closed** 2021-12-29 02:01 UTC
Labels: api: messaging, needs-info, no-recent-activity
