### ISSUE TITLE
FCM Messaging isn't listening after inactivity

### ISSUE THREAD

**Issue by PatilShreyas** [firebase/firebase-android-sdk#932] opened 2019-10-20 17:42 UTC
### Step 1: Are you in the right place?
Yes

### Step 2: Describe your environment

  * Android Studio version: 3.5.1
  * Firebase Component: Cloud Messaging
  * Component version: 20.0.0
  * Device Used for Testing: Xiaomi Redmi Note 4

### Step 3: Describe the problem
I have implemented FCM in my app. I sents data payload from REST API. After opening the app, it receives notifications. But 3-5 minutes after closing if we send data payload, below log appears and I can't display notification of app on the system tray. After this, If I open app then all previous notifications are shown on the tray. How can I solve this issue? I can't display real-time notifications.

#### Steps to reproduce:
After installation of app, just open and close it. It'll receive notifications first. After 3-5 minutes it'll not receive notifications and will show below log.

#### Logcat:
1. This following result is occuring in Logcat.
```
2019-10-20 22:54:04.950 1657-3157/? W/ActivityManager:
Background start not allowed: service Intent { act=com.google.firebase.MESSAGING_EVENT 
pkg=com.spdroid.schedulefcm.example cmp=com.spdroid.schedulefcm.example/.fcm.MyFirebaseMessagingService (has extras) 
} to com.spdroid.schedulefcm.example/.fcm.MyFirebaseMessagingService from pid=13176 uid=10476 pkg=com.spdroid.schedulefcm.example
```

2. This log appears rarely. 
```
E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.
```
#### FCM Request:
```json
{ 
	"to": "/topics/discount-offers", 
	"data" : {
		"title" : "Diwali 🎉 Sale Begins NewOneThisTime!",
		"message" : "Grab 90% Discount 😍 on Mobile Phones"
	},
	"priority": "high"
}
```

#### Relevant Code:
In `sendNotification()`, I have implemented Notification Showing function.
```kt
override fun onMessageReceived(remoteMessage: RemoteMessage) {

        // Check if message contains a data payload.
        remoteMessage.data.isNotEmpty().let {
            Log.d(TAG, "Message data payload: ${remoteMessage.data}")

            // Get Message details
            val title = remoteMessage.data["title"]
            val message = remoteMessage.data["message"]

            sendNotification(title, message)
        }
}
```

**Comment by aguatno** [comment] 2019-11-08 16:55
Hi @PatilShreyas sorry for the late response.  I can't seem to replicate the issue using [Firebase QuickStart](https://github.com/firebase/quickstart-android). 

Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) that I can run locally? You may also try the [FCM Quickstart](https://github.com/firebase/quickstart-android) to see if the issue is reproducible. Thanks

**Comment by PatilShreyas** [comment] 2019-11-08 16:58
Thanks for response.
Actually, I came to know that this is problem in Chinese ROMs devices like
Oppo, Vivo, Xiaomi, etc.

I'm using Xiaomi Redmi Note 4. After enabling background access in security
this problem not occurs.

>

**Comment by aguatno** [comment] 2019-11-08 17:15
Thanks @PatilShreyas. One possibility is that these devices are stopping the applications aggressively in the background. Some manufactures do this to save battery. Are you able to provide specific model numbers where this is happening?

**Comment by PatilShreyas** [comment] 2019-11-10 14:35
Yeah. I'm using Xiaomi Redmi Note 4 with Android 7.0 Nougat (API Level 24).

**Comment by aguatno** [comment] 2019-11-11 15:11
Hi @PatilShreyas qq, could you confirm how you close the app? Is it by swiping away in the app switcher?

**Comment by PatilShreyas** [comment] 2019-11-11 15:16
Yes. I swiped app from tasks.

**Comment by aguatno** [comment] 2019-11-11 19:15
Thanks @PatilShreyas. This is a known issue that is caused by a battery optimization implemented by some OEMs. When an app is swiped away in the app switcher, the application is treated as if it were Force stopped, which is not the default Android behavoir. The unfortunate side effect of this is that it can cause the FCM service for your app to stop running.

We are working to improve this behavior from our end but the actual fix has to come from OEM side.

One way to check if your app is affected by any OEM's battery management feature, is as below:

1) Attach the OEM device to adb

2) Run your app on the device

3) Swipe the app away from recent screen on the device

4) Run command: adb shell dumpsys package MY-PACKAGE | grep stopped

If it shows stopped=true, it's safe to assume that the OEM has such a mechanism and that your app is affected by the same.

I strongly recommend contacting the support team of (OEM name - search for their support portal and add a link if possible) to help get it resolved from their end.

You can read more about this issue and a possible way of solving it in this [blog post](https://medium.freecodecamp.org/why-your-push-notifications-never-see-the-light-of-day-3fa297520793)

**Comment by PatilShreyas** [comment] 2019-11-12 02:31
Thank you for your support!

>

**Comment by aguatno** [comment] 2019-11-12 12:18
I’ll be closing this issue now @PatilShreyas. If you want to continue the discussion just leave a comment here and we are happy to re-open this.

**Closed by aguatno** 2019-11-12 12:18 UTC
Labels: api: messaging
