### ISSUE TITLE
Crash on TransportManager Firebase Perf

### ISSUE THREAD

**Issue by stevenfredian** [firebase/firebase-android-sdk#3084] opened 2021-10-28 05:31 UTC
* Android Studio version: _____
  * Firebase Component: Performance
  * Component version: 19.0.11

**Describe the problem**
We are getting following crash on Crashlytics for good number of users with Android OS 8.1.0 only, since we upgrade bom version 26.0.0 to 26.2.0.

Could you please help us, since its happening on multiple users.

<img width="1104" alt="Screen Shot 2021-10-28 at 09 46 57" src="https://user-images.githubusercontent.com/15241939/139179779-c67d3829-52bb-4969-b64f-c689267a7e12.png">

<img width="330" alt="Screen Shot 2021-10-28 at 10 10 51" src="https://user-images.githubusercontent.com/15241939/139179787-28254785-1586-46ae-9ea8-12d03345761a.png">

We already tried several ways, but we could'nt reproduce it.

**Comment by stevenfredian** [comment] 2021-10-30 02:23
Thanks for the feedback, @argzdev . 
Unfortunately we cannot replicate the issue

**Comment by stevenfredian** [comment] 2021-10-30 02:23
Thank you, @argzdev .

**Comment by stevenfredian** [comment] 2021-10-30 02:31
Thank you, @argzdev .

We are using version 30.

We've already try, but we couldn't reproduce it on our codebase, eventhough with 8.1.0 os devices.
But we will try to reproduce with MCVE one.
I'll let you know as soon as possible.

**Comment by stevenfredian** [comment] 2021-11-04 08:49
Hi @argzdev , unfortunately we cannot reproduce it with emulator and our existing device.

**Comment by argzdev** [comment] 2021-11-09 19:10
Hello @stevenfredian, thanks for trying to reproduce the issue. Just to confirm, did your users still encounter this type of issue after using the latest sdk?

**Comment by stevenfredian** [comment] 2021-11-16 02:55
Hi @argzdev , i check on latest bom version (29.0.0), still using Firebase Performance 20.0.3 which has no changes on related function.
So i guess users will still encounter this issue as well.

**Comment by stevenfredian** [comment] 2021-12-14 07:11
Hi @argzdev , could you please elaborate the current status?

**Comment by visumickey** [comment] 2021-12-14 07:38
@stevenfredian Looks like the changes made by @argzdev is not submitted due to CI restrictions. I've made a similar change and will push this in quick to rollout the fix.

**Comment by argzdev** [comment] 2021-12-16 13:21
Hi @stevenfredian, the fix has been merged and will be included in the next release. I can't provide any specific timeline to when this feature will be available, but you may keep an eye out on our [release notes](https://firebase.google.com/support/release-notes/android) or open a new ticket once you still encounter the issue.

In the meantime, I'll be closing this issue for now, thanks!

**Closed by argzdev** 2021-12-16 13:21 UTC
Labels: api: performance
