### ISSUE TITLE
In-App Messaging is not displayed on the intended Activity

### ISSUE THREAD

**Issue by tatsuhama** [firebase/firebase-android-sdk#1324] opened 2020-03-07 15:58 UTC
### [READ] Step 1: Are you in the right place?
👀 

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.1
  * Firebase Component: In-App Messaging
  * Component version: `firebase-inappmessaging-display:19.0.3`, `firebase-messaging:20.1.1` 

### [REQUIRED] Step 3: Describe the problem

My Application has 2 Activities.
One is `LaunchActivity` (it has `android.intent.category.LAUNCHER` intent-filter),other is `MainActivity`.
I expect a In-App Messaging is appear on `MainActivity`, but not.

I use `FirebaseInAppMessaging.getInstance().setMessagesSuppressed(...)` but, message is disappear soon.
see : https://github.com/firebase/firebase-android-sdk/issues/1299

#### Steps to reproduce:

see below code.

#### Relevant Code:

```LaunchActivity.kt
class LaunchActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_launch)
        FirebaseInAppMessaging.getInstance().setMessagesSuppressed(true)
        openMainActivity()
    }

    private fun openMainActivity() {
        val intent = Intent(this, MainActivity::class.java)
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK)
        startActivity(intent)
    }

    override fun onResume() {
        super.onResume()
        fun createText(text: String): Text =
            Text.builder().setText(text).setHexColor("#000000").build()

        val campaignMetadata = CampaignMetadata("test_campaign", "name", true)
        val title = createText("messageTitle")
        val body = createText("bodyText")
        val message: ModalMessage = ModalMessage.builder()
            .setBackgroundHexColor("#ffffff")
            .setTitle(title)
            .setBody(body)
            .build(campaignMetadata, null)

        FirebaseInAppMessagingDisplay.getInstance().testMessage(this, message, null)
    }
}
```

```MainActivity.kt
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        FirebaseInAppMessaging.getInstance().setMessagesSuppressed(false)
    }
}
```

I found that, when `LaunchActivity` is destroyed, In-App message is disappear.
So, I use [this workaroud](https://github.com/firebase/firebase-android-sdk/issues/1299#issuecomment-594990704), but I don't think it's a good way.
Please fix the problem that the message disappears when the Activity which is not the foreground is destroyed.

**Comment by ashwinraghav** [comment] 2020-05-28 05:47
Duplicate of #1410 
Fixed in version 19.0.7 of  firebase-inappmessaging-display

**Closed by ashwinraghav** 2020-05-28 05:47 UTC
Labels: needs-triage

**Comment by vinayare29** [comment] 2020-06-21 13:25
@ashwinraghav I am facing the same problem
my version 19.0.7 of firebase-inappmessaging-display

**Comment by vinayare29** [comment] 2020-06-21 14:05
@ashwinraghav I am facing the same problem
my version 19.0.7 of firebase-inappmessaging-display
please me to fix this problem
