### ISSUE TITLE
Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver bom:31.0.2

### ISSUE THREAD

**Issue by tuclicks** [firebase/firebase-android-sdk#4266] opened 2022-10-31 08:18 UTC
## Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver in iid and messaing

I am receiving the below error when trying to build the app
``` txt
Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules jetified-firebase-iid-20.0.1-runtime (com.google.firebase:firebase-iid:20.0.1) and jetified-firebase-messaging-23.1.0-runtime (com.google.firebase:firebase-messaging:23.1.0)
```

* Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1Build #AI-213.7172.25.2113.9123335, built on September 30, 2022 Runtime version: 11.0.13+0-b1751.21-8125866 x86_64
* Firebase Component: gradle↓
* Component version: bom:31.0.2

## Cause
This is because there is a uniquely extended FirebaseInstanceIdReceiver in the messaging package.
Is there any way to resolve this issue?

![sss](https://user-images.githubusercontent.com/1716083/198962783-022d1cdc-7924-446e-9c48-0d16ebcf8d75.png)

gradle
```gradle
 //firebase
    implementation platform('com.google.firebase:firebase-bom:31.0.2')
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.firebase:firebase-storage-ktx'
    implementation 'com.google.firebase:firebase-firestore-ktx'
    implementation 'com.google.firebase:firebase-functions-ktx'
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-inappmessaging-ktx'
    implementation 'com.google.firebase:firebase-inappmessaging-display-ktx'
    implementation 'com.google.firebase:firebase-config-ktx'
```

gradle.properties
```
android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536m
```

**Comment by argzdev** [comment] 2022-10-31 09:08
This seems to be a duplicate of #4206. Can you check if the provided workaround works?

That said, I'll close this issue now. Thanks.

**Closed by argzdev** 2022-10-31 09:08 UTC
Labels: api: messaging
