### ISSUE TITLE
When would these use of "Depricated API" warnings will go away?

### ISSUE THREAD

**Issue by prakash-indorkar** [firebase/firebase-android-sdk#2256] opened 2020-12-15 09:01 UTC
![firebase](https://user-images.githubusercontent.com/60499738/102193220-d3635c00-3ee1-11eb-8885-e0ef131cab98.PNG)

### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by prakash-indorkar** [comment] 2020-12-19 12:41
Any comment on this issue please?

**Comment by aguatno** [comment] 2021-03-23 16:43
Hi @prakash-indorkar thanks for reporting. This seems to be a duplicate issue of [flutterfire-3876](https://github.com/FirebaseExtended/flutterfire/issues/3876) and many developers are having similar warnings.You may keep an eye on that thread for updates or file a new issue [here](https://github.com/FirebaseExtended/flutterfire/issues) if needed, so the Flutter team could give you more insights and guidance on resolving this issue.

If you're able to reproduce the issue using our native Firebase SDK (Web, Android, or iOS), please let me know so that I can continue to investigate the issue.

**Closed by aguatno** 2021-03-23 16:43 UTC
Labels: api: core
