### ISSUE TITLE
ClassCircularityError: Class gcq.oor.ced extends itself

### ISSUE THREAD

**Issue by zaiyubuzai** [firebase/firebase-android-sdk#5577] opened 2023-11-28 03:55 UTC
Step 2: Describe your environment

  * Android Studio version: Android Studio Giraffe | 2022.3.1
  * Firebase Component: firebase-crashlytics-gradle:2.9.9'

Step 3: Describe the problem

I have got this new crash reported 13 in Crashlytics for one user.
The device is a Pixel 7 Pro running Android 14. I could not find any mentions about it online and therefore decided to open this new issue.
```
Fatal Exception: java.lang.ClassCircularityError: Class gcq.oor.ced extends itself (declaration of 'gcq.oor.ced' appears in /data/app/~~xymbGmp7WqgyY6-DQLlxww==/com.xxxxxxx.xxxx-6x_cd5s39QMnZERJfORWKg==/base.apk!classes9.dex)
       at java.lang.VMClassLoader.findLoadedClass(VMClassLoader.java)
       at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
       at androidx.core.app.CoreComponentFactory.instantiateActivity()
       at android.app.Instrumentation.newActivity(Instrumentation.java:1378)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by argzdev** [comment] 2023-11-28 09:46
Hey @zaiyubuzai, thanks for reaching out. Looking through your stack trace, it doesn't show any mentions of Firebase, this issue might not be related to the Crashlytics SDK. That said, you should be able to trace or debug this issue if you're able to figure out what this class `gcq.oor.ced` is. However, I'm not sure if the class name is obfuscated due to minification.

I'll close this thread for now. We can reopen this once we verify that the issue is due to our Firebase SDK. Thanks!

**Closed by argzdev** 2023-11-28 09:46 UTC
Labels: api: crashlytics
