### ISSUE TITLE
IllegalStateException FirebaseRemoteConfig.getInstance

### ISSUE THREAD

**Issue by WIPKarthik** [firebase/firebase-android-sdk#1857] opened 2020-08-06 05:06 UTC
We have integrated Firebase Remote Config feature in our Application. It works fine in most of the device but we get the below Exception in some of the Devices.

Below is the Stacktrace.

java.lang.RuntimeException:
at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6715)
at android.app.ActivityThread.access$1300 (ActivityThread.java:226)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1898)
at android.os.Handler.dispatchMessage (Handler.java:107)
at android.os.Looper.loop (Looper.java:214)
at android.app.ActivityThread.main (ActivityThread.java:7615)
at java.lang.reflect.Method.invoke (Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)
Caused by: java.lang.IllegalStateException:
at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java:184)
at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance (FirebaseRemoteConfig.java:79)
at org.mopria.printplugin.Analytics.setupRemoteConfig (Analytics.java:1054)
at org.mopria.printplugin.Analytics. (Analytics.java:1046)
at org.mopria.printplugin.Analytics.getInstance (Analytics.java:1025)
at org.mopria.printplugin.Analytics.getInstance (Analytics.java:1019)
at org.mopria.printplugin.MopriaApplication.updatePrefs (MopriaApplication.java:195)
at org.mopria.printplugin.MopriaApplication.onCreate (MopriaApplication.java:115)
at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1190)
at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6710)
at android.app.ActivityThread.access$1300 (ActivityThread.java:226)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1898)
at android.os.Handler.dispatchMessage (Handler.java:107)
at android.os.Looper.loop (Looper.java:214)
at android.app.ActivityThread.main (ActivityThread.java:7615)
at java.lang.reflect.Method.invoke (Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)

As mentioned above the crash appears only in some of the Device.

**Comment by WIPKarthik** [comment] 2020-08-06 05:16
This issue look similar to #1766 . As per the issue #1766 it happens on Firebase Crashlytics.

**Comment by WIPKarthik** [comment] 2020-08-06 05:27
Additional info is that the issue happens in **Android OS version 6, 9 and 10.** Also the App does not support Direct Boot mode.

**Comment by ashwinraghav** [comment] 2020-08-07 17:01
Thanks for spotting the similar issues. Let's continue triaging there. Closing as duplicate of #1766

**Closed by ashwinraghav** 2020-08-07 17:01 UTC
Labels: needs-triage
