### ISSUE TITLE
AssetManager.java

### ISSUE THREAD

**Issue by 3HJack** [firebase/firebase-android-sdk#3605] opened 2022-03-31 08:10 UTC
* Android Studio version: 2021.1.1 Patch 2
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _firebase-bom: 29.0.3
  * implementation 'com.google.firebase:firebase-analytics'
  * implementation 'com.google.firebase:firebase-auth'
  * implementation 'com.google.firebase:firebase-auth-ktx'
  * implementation 'com.google.firebase:firebase-messaging'
  * implementation 'com.google.firebase:firebase-dynamic-links'
  * implementation 'com.google.firebase:firebase-perf'
  * implementation 'com.google.firebase:firebase-crashlytics-ndk'

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
Fatal Exception: java.util.concurrent.TimeoutException: android.content.res.AssetManager$AssetInputStream.finalize() timed out after 10 seconds
       at android.content.res.AssetManager$AssetInputStream.close(AssetManager.java:622)
       at android.content.res.AssetManager$AssetInputStream.finalize(AssetManager.java:655)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:217)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
       at java.lang.Thread.run(Thread.java:818)

```

![image](https://user-images.githubusercontent.com/17744189/161008061-c92f4bad-c72e-44f0-ba70-c9af9fb11305.png)

![image](https://user-images.githubusercontent.com/17744189/161017374-13f9a8a2-a997-4494-98d7-18a970d58931.png)

**Comment by argzdev** [comment] 2022-03-31 10:11
Hi @3HJack, thanks for reporting with code snippets. Just want to clarify, is the issue you're experiencing on Firebase Crashlytics? Any chance you could provide details how to reproduce this issue? Or if you have any [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), it'll greatly help us in our investigation.

**Comment by 3HJack** [comment] 2022-03-31 10:54
Yes,It's experiencing on Firebase Crashlytics.I can't reproduce it.But I fix it by downgrade firebase to 29.0.1.

**Comment by argzdev** [comment] 2022-04-01 16:07
Hi @3HJack, thanks for the extra details. Due to the nature of the issue being device specific, it is difficult to reproduce and investigate since we don't have the said device brand. Let's keep this issue open in case our engineers might have an idea how to fix this.

**Comment by chenggoi** [comment] 2022-04-02 05:43
@argzdev I found this method to check if flutter exists. So can you provide a switcher to ignore this checking if this bug is hard to reproduce and fix? Because we don't use flutter, so it should always return `false` for `assetPathExists(FLUTTER_ASSETS_PATH)`

**Comment by 3HJack** [comment] 2022-04-08 03:46
> @argzdev I found this method to check if flutter exists. So can you provide a switcher to ignore this checking if this bug is hard to reproduce and fix? Because we don't use flutter, so it should always return `false` for `assetPathExists(FLUTTER_ASSETS_PATH)`

@argzdev I think this suggestion can solve the problem.

**Comment by argzdev** [comment] 2022-04-08 09:27
Hi @chenggoi & @3HJack, thanks for the suggestions. Upon investigation, it looks like the `assetPathExists` is the switch to check if the development platform is Flutter or not. 

A quick fix for this is to add a `catch(TimeoutException e)`, I'll consult with an engineer to see if this solution is feasible.

**Comment by 3HJack** [comment] 2022-04-08 09:34
@argzdev The crash is not happening in the assetPathExists function, so I don't think it can be fixed.

**Comment by argzdev** [comment] 2022-04-08 18:06
Hi @3HJack, we were able to come up with a fix using `.open()` instead. Since `.list()` have performance issues, I think `.open()` would be a better option to choose when checking if a specific file exists, at the same time if any issue occurs, the correct exception (IOException) will definitely get caught. That being said, the fix for this has been merged, so I'll be closing this now.

**Closed by argzdev** 2022-04-08 18:06 UTC
Labels: api: crashlytics
