### ISSUE TITLE
Crash on Firebase database: hardAssert failed: Expected connection state disconnected, but was GettingToken

### ISSUE THREAD

**Issue by angelolloqui** [firebase/firebase-android-sdk#3126] opened 2021-11-11 08:51 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: AS Fox 2020.3.1
  * Firebase Component:  Database
  * Component version: BOM version 28.4.2 (database 20.0.2)

### [REQUIRED] Step 3: Describe the problem

After updating the firebase dependencies to the BOM 28.4.2, we are getting a tremendous increase of crashes happening in our Android app. It seems to be affecting around 0.4% of our sessions, which is several hundreds in our app. 

#### Steps to reproduce:

There is no clear reproduction steps, since this is happening randomly, but seems related to a connectivity issue badly handled in the PersistenConnectionImpl. Many of the users got the crash just after opening a new session of the app, but some during normal navigation.

Stack trace of the crash:
```
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.2). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
```
Caused by java.lang.AssertionError: hardAssert failed: Expected connection state disconnected, but was GettingToken
       at com.google.firebase.database.connection.ConnectionUtils.hardAssert(ConnectionUtils.java:67)
       at com.google.firebase.database.connection.PersistentConnectionImpl.lambda$tryScheduleReconnect$2$PersistentConnectionImpl(PersistentConnectionImpl.java:771)
       at com.google.firebase.database.connection.PersistentConnectionImpl$$ExternalSyntheticLambda1.onSuccess(:11)
       at com.google.android.gms.tasks.zzn.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

#### Relevant Code:

```
buildscript {
...
    ext.kotlin_version = '1.4.31'
    ext.support_library_version = '1.1.+'
    ext.google_play_services_version = '17.0.+'
    ext.build_tools_version = '30.0.3'
    ext.firebase_bom_version = '28.4.2' 
    ext.compile_sdk_version = 30
    ext.min_sdk_version = 21
...
```

```
 // Firebase
    implementation platform("com.google.firebase:firebase-bom:$firebase_bom_version")
    implementation 'com.google.firebase:firebase-database-ktx'
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.firebase:firebase-storage-ktx'
    implementation "com.google.firebase:firebase-crashlytics-ktx"
    implementation 'com.google.firebase:firebase-config-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-iid'
    implementation "com.google.firebase:firebase-messaging-ktx"
```
```
    compileSdkVersion compile_sdk_version
    buildToolsVersion build_tools_version
    defaultConfig {
        minSdkVersion min_sdk_version
        targetSdkVersion compile_sdk_version
        multiDexEnabled true     
    }
```
There is no other code involved I can think is related, but let me know if you want some extra context info like other dependencies or so.

**Comment by argzdev** [comment] 2021-11-11 09:51
Duplicate of #3074

**Closed by argzdev** 2021-11-11 09:51 UTC
Labels: api: database

**Comment by argzdev** [comment] 2021-11-11 09:52
Hi @angelolloqui, thanks for reporting. Since, this is similar to the #3074. I'll mark this one as a duplicate, thanks!

**Comment by argzdev** [comment] 2021-11-11 10:02
Could provide us any similarity that you've noticed from the crashes? Like same device type, version level, or anything that stands out. That'll help us with our investigation, thanks!

**Comment by angelolloqui** [comment] 2021-11-12 11:28
I halted the rollout due to the crashes but I will enable it back to a subset of our users so I can check if I find a pattern in it.
