### ISSUE TITLE
IllegalStateException while calling  FirebaseCrashlytics.getInstance ()

### ISSUE THREAD

**Issue by kangaman2205** [firebase/firebase-android-sdk#1823] opened 2020-07-27 12:40 UTC
We have migrated from Fabric to Firebase Crashlytics. We are seeing the following crash on Playstore while initializing Firebase Crashlytics instance. This seems to be caused by IllegalStateException while calling 
FirebaseCrashlytics.getInstance().

Crashlytics version used : com.google.firebase:firebase-crashlytics:17.0.0

java.lang.RuntimeException:
at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5911)
at android.app.ActivityThread.access$1100 (ActivityThread.java:200)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1660)
at android.os.Handler.dispatchMessage (Handler.java:106)
at android.os.Looper.loop (Looper.java:193)
at android.app.ActivityThread.main (ActivityThread.java:6762)
at java.lang.reflect.Method.invoke (Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
**Caused by: java.lang.IllegalStateException:
at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java:184)**
at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance (FirebaseCrashlytics.java:112)

Can you please look into this issue?

**Comment by ashwinraghav** [comment] 2020-07-27 19:08
Duplicate of https://github.com/firebase/firebase-android-sdk/issues/1766

**Closed by ashwinraghav** 2020-07-27 19:08 UTC
Labels: needs-triage
