### ISSUE TITLE
Lots of ANRs from `CommonComponentRegistrar.getComponents`

### ISSUE THREAD

**Issue by Thomas-Vos** [firebase/firebase-android-sdk#3381] opened 2022-01-29 16:59 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Bumbelbee 2021.1.1 RC 1
  * Firebase Components and versions:
```
"com.google.firebase:firebase-analytics-ktx:20.0.2"
"com.google.gms:google-services:4.3.10" (as plugin)
"com.google.firebase:firebase-crashlytics-ktx:18.2.6"
"com.google.firebase:firebase-crashlytics-gradle:2.8.1"
"com.google.firebase:firebase-inappmessaging-display-ktx:20.1.1"
"com.google.firebase:firebase-config-ktx:21.0.1"

"com.google.android.gms:play-services-location:19.0.0"
"com.google.android.gms:play-services-maps:18.0.2"
"com.google.android.gms:play-services-mlkit-barcode-scanning:16.2.0"
```

### [REQUIRED] Step 3: Describe the problem

Getting lots of ANRs like this reported through Firebase Crashlytics:

Example stack trace (they are a bit different sometimes):
```
main (runnable): tid=1 systid=15779
       at com.google.mlkit.common.internal.CommonComponentRegistrar.getComponents(com.google.mlkit:common@@17.2.0:3)
       at com.google.firebase.components.ComponentRuntime.discoverComponents(ComponentRuntime.java:109)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:91)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:45)
       at com.google.firebase.components.ComponentRuntime$Builder.build(ComponentRuntime.java:360)
       at com.google.mlkit.common.sdkinternal.MlKitContext.zza(MlKitContext.java:9)
       at com.google.mlkit.common.internal.MlKitInitProvider.onCreate(com.google.mlkit:common@@17.2.0:3)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2516)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2486)
       at com.google.mlkit.common.internal.MlKitInitProvider.attachInfo(com.google.mlkit:common@@17.2.0:3)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8198)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7704)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7458)
       at android.app.ActivityThread.access$1700(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2283)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

Screenshot from last 90 days:

![Screenshot 2022-01-29 at 17 55 12](https://user-images.githubusercontent.com/11077217/151669815-ce0c09ec-c30f-4054-876f-79c488ad171b.png)

I opened the ANR at the top with the most events:

![Screenshot 2022-01-29 at 17 55 51](https://user-images.githubusercontent.com/11077217/151669840-23ae05af-8ecf-4534-a939-accecf6e26be.png) ![Screenshot 2022-01-29 at 17 56 08](https://user-images.githubusercontent.com/11077217/151669842-b61cb81d-6b2d-4adb-96f9-815974957fbc.png) ![Screenshot 2022-01-29 at 17 58 47](https://user-images.githubusercontent.com/11077217/151669895-ab47c00b-686b-4d20-8b09-b07e6233739d.png)

#### Steps to reproduce:

No steps to reproduce as I am unable to do so myself.

#### Relevant Code:

No lines in stack trace are referencing my code.

**Comment by argzdev** [comment] 2022-01-31 09:57
Hi @Thomas-Vos, than you for reporting. May I ask what was the previous version you've used for the Firebase components before experiencing this issue?

Since multiple products are involved, what we could try is narrowing down the scope on which product and which version was the ANR was first encountered. This may be a long shot, but I have an idea in mind: 
- you could try using the old versions you've previously used for each product, and then use the latest version for only one specific product on different tests to see if which product on the latest version experiences the ANR.

Given the nature of ANRs, ANRs are difficult to investigate and I know this approaches require hefty amount of effort but this will be helpful for our engineering team to isolate the issue that caused the ANR.

**Comment by Thomas-Vos** [comment] 2022-01-31 10:30
Thanks for the response. I do not know in which version this started appearing. I only noticed this after upgrading craslytics with ANR support. 

Also, doesn't the stack trace show the issue is in mlkit? I forgot to add the mlkit components and versions to the issue, but I added them now.

**Comment by argzdev** [comment] 2022-01-31 13:38
Thanks for the extra details, @Thomas-Vos. I was confused for a moment and wondering about that since I didn't see mlkit in your components. With that said, any chance you could provide us an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or code snippet of this issue? It'll greatly help us in our investigation.

**Comment by Thomas-Vos** [comment] 2022-01-31 14:17
> I was confused for a moment and wondering about that since I didn't see mlkit in your components. 

Yes, sorry about that. It has a different module name that doesn't contain firebase, so I missed it while creating the issue.

> any chance you could provide us an MCVE or code snippet of this issue?

The stack trace doesn't reference any lines of my code, so I am not sure what it could be. As said before I am unable to reproduce the ANR myself. I know that without any code it would be hard for you to reproduce the issue, but I really don't know what code to show you for this issue. Any ideas what I could do to help? Is there anything in `getComponents` that could cause the ANR (on some devices)?

**Comment by Thomas-Vos** [comment] 2022-01-31 14:20
I see that the stack trace contains `MlKitInitProvider` which is a content provider. So I guess that would exclude any of my code being the issue, right? As content providers execute before I use any Firebase code.

**Comment by argzdev** [comment] 2022-01-31 17:04
Thanks for the extra details, @Thomas-Vos. Upon checking, even though mlkit is using Firebase components, the issue is not due to Firebase products. You could try creating an issue in https://github.com/googlesamples/mlkit/issues, they will be able to investigate this issue further. With that said, I'll be closing this issue.

**Closed by argzdev** 2022-01-31 17:04 UTC
Labels: api: core, api: mlkit, needs-attention, api: bom

**Comment by Thomas-Vos** [comment] 2022-02-01 00:08
Alright, created an issue at https://github.com/googlesamples/mlkit/issues/434. Thanks for the help, @argzdev.
