### ISSUE TITLE
OnePlus Device can't receive  token for Firebase Cloud Messaging

### ISSUE THREAD

**Issue by vitalerter** [firebase/firebase-android-sdk#3929] opened 2022-07-21 07:07 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Chipmunk 2021.2.1 Patch 1
  * Firebase Component: firebase-messaging
  * Component version: 23.0.6

### [REQUIRED] Step 3: Describe the problem
I can't receive token for few device such as OnePlus 3T Android version 9  
#### Steps to reproduce:

When i try to get Instance with  firebase registration in order to receive the token i get error :

log
`getInstanceId failed
    java.io.IOException: SERVICE_NOT_AVAILABLE
        at com.google.android.gms.cloudmessaging.zzv.then(com.google.android.gms:play-services-cloud-messaging@@17.0.0:5)
        at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:0)
        at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.1:5)
        at com.google.android.gms.tasks.zzw.zzi(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.android.gms.tasks.zzw.continueWith(com.google.android.gms:play-services-tasks@@18.0.1:4)
        at com.google.android.gms.cloudmessaging.Rpc.send(com.google.android.gms:play-services-cloud-messaging@@17.0.0:8)
        at com.google.firebase.iid.GmsRpc.startRpc(com.google.firebase:firebase-iid@@21.1.0:2)
        at com.google.firebase.iid.GmsRpc.getToken(com.google.firebase:firebase-iid@@21.1.0:1)
        at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$2$FirebaseInstanceId(com.google.firebase:firebase-iid@@21.1.0:1)
        at com.google.firebase.iid.FirebaseInstanceId$$Lambda$3.start(Unknown Source:10)
        at com.google.firebase.iid.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-iid@@21.1.0:7)
        at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$3$FirebaseInstanceId(com.google.firebase:firebase-iid@@21.1.0:5)
        at com.google.firebase.iid.FirebaseInstanceId$$Lambda$0.then(Unknown Source:6)
        at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.gms.cloudmessaging.zzq: Unable to bind to service
        at com.google.android.gms.cloudmessaging.zzm.zzb(com.google.android.gms:play-services-cloud-messaging@@17.0.0:6)
        at com.google.android.gms.cloudmessaging.zzm.zza(com.google.android.gms:play-services-cloud-messaging@@17.0.0:1)
        at com.google.android.gms.cloudmessaging.zzm.zzg(com.google.android.gms:play-services-cloud-messaging@@17.0.0:14)
        at com.google.android.gms.cloudmessaging.zzs.zzg(com.google.android.gms:play-services-cloud-messaging@@17.0.0:5)
        at com.google.android.gms.cloudmessaging.zzs.zzd(com.google.android.gms:play-services-cloud-messaging@@17.0.0:1)
        at com.google.android.gms.cloudmessaging.Rpc.send(com.google.android.gms:play-services-cloud-messaging@@17.0.0:7)
        at com.google.firebase.iid.GmsRpc.startRpc(com.google.firebase:firebase-iid@@21.1.0:2) 
        at com.google.firebase.iid.GmsRpc.getToken(com.google.firebase:firebase-iid@@21.1.0:1) 
        at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$2$FirebaseInstanceId(com.google.firebase:firebase-iid@@21.1.0:1) 
        at com.google.firebase.iid.FirebaseInstanceId$$Lambda$3.start(Unknown Source:10) 
        at com.google.firebase.iid.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-iid@@21.1.0:7) 
        at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$3$FirebaseInstanceId(com.google.firebase:firebase-iid@@21.1.0:5) 
        at com.google.firebase.iid.FirebaseInstanceId$$Lambda$0.then(Unknown Source:6) 
        at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.0.1:1) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2) 
        at java.lang.Thread.run(Thread.java:764) 
`
#### Relevant Code:

```
FirebaseMessaging.getInstance().getToken().addOnCompleteListener(task -> {
            if (!task.isSuccessful()) {
                Log.w(TAG, "getInstanceId failed", task.getException());
                return;
            }
            // Get new Instance ID token
            String token = Objects.requireNonNull(task.getResult());

            // Log
           Log.d(TAG, "Token:" + token);
            mSp.putStringIntoSharedPrefernces(getString(R.string.token), token);
            mSp.putStringIntoSharedPrefernces(getString(R.string.token_type), getString(R.string.token_type_firebase));
        });
```

**Comment by argzdev** [comment] 2022-07-21 11:38
Hi @vitalerter, thanks for reporting. Might be a duplicate of #3898. Just to confirm, does these devices have Google Play store installed? It looks like these issues appear when an emulator or physical device does not have Google Play Service. Could you check and see if it works?

**Comment by vitalerter** [comment] 2022-07-21 12:07
Hi,
This phone have no Google Play store installed.

**Closed** 2022-07-21 12:46 UTC
Labels: api: messaging, needs-attention
