### ISSUE TITLE
Lint warning for lint check "MediaCapabilities" in in-app-messaging component

### ISSUE THREAD

**Issue by mikehardy** [firebase/firebase-android-sdk#3833] opened 2022-06-22 18:02 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: chipmunk
  * Firebase Component: In-App Messaging
  * Component version: BoM 30.1.0 (current)

### [REQUIRED] Step 3: Describe the problem

```
/Users/mike/work/Invertase/react-native-firebase/packages/in-app-messaging/android/src/main/AndroidManifest.xml:4: Warning: The app accesses MediaStore.Video, but is missing a <property> tag with a android.content.MEDIA_CAPABILITIES declaration [MediaCapabilities]
  <application>
   ~~~~~~~~~~~

   Explanation for issues of type "MediaCapabilities":
   In Android 12 and higher, an app that opens media files should explicitly
   specify media formats that it doesn't support, so the OS can provide a
   transcoded file instead.

0 errors, 1 warnings
```

#### Steps to reproduce:

Set up `lintOptions` in your `android` block of `build.gradle` like so:

```groovy

        // Make sure our project are run through basic lint checks
        lintOptions {
          abortOnError = true
          warningsAsErrors false
          lintConfig file('./lint.xml')
          ignore 'UnknownNullness', 'SyntheticAccessor', 'LogConditional'
          checkReleaseBuilds = true
          checkAllWarnings true
          showAll true
          textReport true
          textOutput 'stdout'
          htmlReport true
        }
```

Put a reasonable `lint.xml` in place, you may see the one we use for react-native-firebase here: https://github.com/invertase/react-native-firebase/blob/main/tests/android/lint.xml

run `./gradlew lintAnalyzeDebug`

You can see it in our CI runs on react-native-firebase https://github.com/invertase/react-native-firebase/runs/7008347598?check_suite_focus=true#step:12:2190

#### Relevant Code:

Looks like the file here should have a property tag with the media types that in-app-messaging supports? https://github.com/firebase/firebase-android-sdk/blob/master/firebase-inappmessaging/src/main/AndroidManifest.xml

**Comment by argzdev** [comment] 2022-06-24 11:09
Thanks for reporting, @mikehardy! Using lint is kind of new to me, so please bear with me.

I've tried testing this setup in a new project with the dependencies of inappmessaging, but the `lintAnalyzeDebug` comes out clean. As of the moment, I'm still trying to make this work on the `firebase-android-sdk`.

I'm curious about the error states that the app accesses MediaStore.Video, when I tried looking this up within the repo, it comes out empty. From what I've gathered, it might be that the inappmessaging component is not using mediastore directly, but rather the dependencies are. I think there could be 2 solutions here. We can either "ignore" the mediastore usage, since this could be a false positive. e.g. 

```
<application
    tools:ignore="MediaCapabilities">
</application>
```

Or add a property tag with the media types like you've advised.
Either way, I'll notify our engineers about this.

**Comment by argzdev** [comment] 2022-08-09 17:00
Sorry for the silence here. I've consulted and confirmed with our engineer that we aren't using any `MediaCapabilities` in the in-app messaging component. So the likely issue here are the underlying dependencies in FIAM which are using `MediaCapabilities`. That being said, it was advised to ignore this lint warning, I think you may disable the check (via lint.xml, or from Gradle, via android.lintOptions.disable 'MediaCapabilities')

Also upon checking, the lint check for `MediaCapabilities` has been removed for [version 7.1](https://b.corp.google.com/issues/195242930).

I'll close this issue for now. Feel free to reopen if you think this is a mistake. Thanks!

**Closed by argzdev** 2022-08-09 17:00 UTC
Labels: api: inappmessaging
