### ISSUE TITLE
SQLiteEventStore.lambda$ensureBeginTransaction$24: android.database.sqlite.SQLiteDatabaseLockedException - database is locked (code 5 SQLITE_BUSY[5])

### ISSUE THREAD

**Issue by lklong1551019** [firebase/firebase-android-sdk#6021] opened 2024-06-07 04:17 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Jellyfish | 2023.3.1 Patch 1
Build #AI-233.14808.21.2331.11842104, built on May 15, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11572160 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
ide.instant.shutdown=false
debugger.new.tool.window.layout=true
ide.experimental.ui=true
ide.images.show.chessboard=true
Non-Bundled Plugins:
io.github.stefansjs.flatbuffersplugin (0.5+31)
name.kropp.intellij.makefile (233.13135.65)
  * Firebase Component: com.google.gms:google-services:4.4.2, com.google.firebase:firebase-crashlytics-gradle:3.0.1, org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.21, com.google.firebase:firebase-bom:33.1.0

### [REQUIRED] Step 3: Describe the problem
As for https://github.com/firebase/firebase-android-sdk/issues/6001, after updating to bom 33.1.0 we still experiencing this crash, here is example stack trace:

```
Fatal Exception: com.google.android.datatransport.runtime.synchronization.SynchronizationException
Timed out while trying to acquire the lock.
 Fatal Exception: com.google.android.datatransport.runtime.synchronization.SynchronizationException: Timed out while trying to acquire the lock.
       at com.google.android.datatransport.runtime.synchronization.SynchronizationException.<init>(SynchronizationException.java:20)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.lambda$ensureBeginTransaction$25(SQLiteEventStore.java:759)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.retryIfDbLocked(SQLiteEventStore.java:585)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.ensureBeginTransaction(SQLiteEventStore.java:753)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:766)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:164)
       at com.google.android.datatransport.runtime.ForcedSender.sendBlocking(ForcedSender.java:36)
       at com.google.firebase.crashlytics.internal.send.ReportQueue.lambda$flushScheduledReportsIfAble$0(ReportQueue.java:138)
       at java.lang.Thread.run(Thread.java:1012)


Caused by android.database.sqlite.SQLiteDatabaseLockedException
database is locked (code 5 SQLITE_BUSY[5])
Caused by android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY[5])
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:972)
       at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:325)
       at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:788)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:698)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.lambda$ensureBeginTransaction$24(SQLiteEventStore.java:755)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.retryIfDbLocked(SQLiteEventStore.java:582)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.ensureBeginTransaction(SQLiteEventStore.java:753)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:766)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:164)
       at com.google.android.datatransport.runtime.ForcedSender.sendBlocking(ForcedSender.java:36)
       at com.google.firebase.crashlytics.internal.send.ReportQueue.lambda$flushScheduledReportsIfAble$0(ReportQueue.java:138)
       at java.lang.Thread.run(Thread.java:1012)

```

<img width="1262" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/32784650/a0ec2c0c-5889-4fd8-9ea2-699c55c7a4ef">

<img width="458" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/32784650/3b31c5b6-397b-411d-a9de-e55be1da19d2">

<img width="642" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/32784650/be9e8221-ac44-4027-b163-4b6f6953d29c">

We cannot reproduce, any insight is appreciated, thanks.

**Comment by lehcar09** [comment] 2024-06-10 19:09
Hi @lklong1551019, thank you for filing the issue. I tried to reproduce the issue with the latest Firebase SDK version, but I still can't reproduce the issue. I'll check in with our engineers about this issue and get back to you. Thanks!

**Comment by lklong1551019** [comment] 2024-06-11 01:49
Thank you, I would like to add current status of this issue and I'm waiting for updates from you.

<img width="1265" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/32784650/d92c0b1f-8cf6-464d-9bab-2cf154771d51">

**Comment by lehcar09** [comment] 2024-06-11 13:38
According to our Engr, we have a fix for this issue and it will be included in the next release. We'll let you know when the fix is released. Thanks!

**Comment by lklong1551019** [comment] 2024-06-12 01:35
thank you, it's nice to hear that. We're waiting for the fix, cheers!

**Comment by Arumankumang** [comment] 2024-06-15 15:56
Terima Ricky semuanya aku nunggu

**Comment by annhienktuit** [comment] 2024-06-18 10:47
I got the same issue, when will the release of this fix will be rolled out? @lehcar09

**Comment by tuan25abc** [comment] 2024-06-20 03:51
@lehcar09 I'm experiencing this issue with almost 1,000 crashes per day. How is the release status?

**Comment by mrober** [comment] 2024-06-21 15:25
This issue is fixed in the latest version.

**Closed by mrober** 2024-06-21 15:25 UTC
Labels: api: crashlytics

**Comment by Arumankumang** [comment] 2024-06-22 09:37
Iya pak harus dibaiki semuanya situs dan web versi baru UI

**Comment by Arumankumang** [comment] 2024-07-01 00:11
filenames.libcxxabi.gni
