### ISSUE TITLE
FirebaseInstallations doesn't correctly close opened stream

### ISSUE THREAD

**Issue by lexer** [firebase/firebase-android-sdk#1325] opened 2020-03-08 04:31 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.1
  * Firebase Component: com.google.firebase:firebase-perf, com.google.firebase:firebase-messaging
  * Component version: 19.0.5, 20.1.2

### [REQUIRED] Step 3: Describe the problem

Firebase SDK crashes if StrictMode detectLeakedRegistrationObjects() policy is enabled.

#### Steps to reproduce:

Strict mode configuration:

```
val vmBuilder = VmPolicy.Builder()
                .detectActivityLeaks()
                .detectFileUriExposure()
                .detectLeakedClosableObjects()
                .detectLeakedRegistrationObjects()
                .detectLeakedSqlLiteObjects()
                .penaltyLog()
                .penaltyDeath()
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
  vmBuilder.detectContentUriWithoutPermission()
            }
 StrictMode.setVmPolicy(vmBuilder.build())
```

#### Relevant Code:

Crash log.
```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at java.util.zip.Inflater.finalize(Inflater.java:407)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at java.util.zip.Inflater.<init>(Inflater.java:122)
        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:64)
        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:484)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:661)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(com.google.firebase:firebase-installations@@16.0.0:154)
        at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(com.google.firebase:firebase-installations@@16.0.0:411)
        at com.google.firebase.installations.FirebaseInstallations.doRegistrationInternal(com.google.firebase:firebase-installations@@16.0.0:316)
        at com.google.firebase.installations.FirebaseInstallations.doGetId(com.google.firebase:firebase-installations@@16.0.0:280)
        at com.google.firebase.installations.FirebaseInstallations.access$lambda$0(Unknown Source:0)
        at com.google.firebase.installations.FirebaseInstallations$$Lambda$1.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by andirayo** [comment] 2020-03-08 17:28
Thank you for reporting this problem.
We will look into this and, if necessary, will try to release a fix next week.

**Comment by ankitaj224** [comment] 2020-03-09 20:19
Was this a warning or error? Also, did the app crash with this stack trace?

**Comment by ankitaj224** [comment] 2020-03-09 20:21
I tried reproducing but couldn't. Do you get this stack trace consistently?

**Comment by ankitaj224** [comment] 2020-03-09 21:04
whats the okhttp library version you are using?

**Comment by lexer** [comment] 2020-03-10 20:17
I have reproduced on an empty app. Here is instructions:

Create an App.kt

```
class App : Application() {
    override fun onCreate() {
        super.onCreate()

        val vmBuilder = StrictMode.VmPolicy.Builder()
            .detectActivityLeaks()
            .detectFileUriExposure()
            .detectLeakedClosableObjects()
            .detectLeakedRegistrationObjects()
            .detectLeakedSqlLiteObjects()
            .penaltyLog()
            .penaltyDeath()
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            vmBuilder.detectContentUriWithoutPermission()
        }

        StrictMode.setVmPolicy(vmBuilder.build())
        StrictMode.setThreadPolicy(
            StrictMode.ThreadPolicy.Builder()
                .detectAll()
                .penaltyLog()
                // https://issuetracker.google.com/issues/63298071
                // .penaltyDeath()
                .build()
        )

        FirebaseApp.initializeApp(
            this,
            FirebaseOptions.Builder()
                .setApplicationId("com.squareup.cash.beta.debug")
                .setProjectId(getString(R.string.firebase_project_id))
                .setApiKey(getString(R.string.firebase_api_key))
                .setGcmSenderId(getString(R.string.firebase_sender_id))
                .build()
        )

        FirebasePerformance.getInstance()
            .isPerformanceCollectionEnabled = true
    }
}
```

project build.gradle

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
  compileSdkVersion 29
  buildToolsVersion "29.0.2"

  defaultConfig {
    applicationId "com.squareup.cash"
    minSdkVersion 21
    targetSdkVersion 29
    versionCode 1
    versionName "1.0"

    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }

  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }
}

dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar'])
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
  implementation 'androidx.appcompat:appcompat:1.0.2'
  implementation 'androidx.core:core-ktx:1.0.2'
  implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
  implementation 'com.google.firebase:firebase-messaging:20.1.2'
  implementation 'com.google.firebase:firebase-perf:19.0.5'
  implementation 'com.squareup.okhttp3:okhttp:4.4.0'
  testImplementation 'junit:junit:4.12'
  androidTestImplementation 'androidx.test.ext:junit:1.1.1'
  androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

You need to make sure that valid Firebase configuration is used otherwise SDK won't send a request and app won't crash.

**Comment by ankitaj224** [comment] 2020-03-10 22:47
@lexer If you could archive and send me the github link that would be very helpful. I tried with the library version but still cant reproduce the exact violation you reported. 

Out of curiosity, does your app require to run with these strict mode violations or is it part of your dev testing?

**Comment by lexer** [comment] 2020-03-11 01:09
sounds good @ankitaj224 i will create a private repo with demo project and share it directly with you.

> Out of curiosity, does your app require to run with these strict mode violations or is it part of your dev testing?

Cash App team has a very high standard and tries to have 0 strict mode violations.

**Comment by lexer** [comment] 2020-03-11 01:14
@ankitaj224 you should have an invite to demo repo now. https://github.com/lexer/firebaseInstallations-crash-demo

**Comment by andirayo** [comment] 2020-03-11 01:17
@lexer : Please also invite @ChaoqunCHEN and myself.

**Comment by lexer** [comment] 2020-03-11 05:17
done :)

**Comment by ankitaj224** [comment] 2020-03-11 17:57
@lexer Is the demo repo missing a commit? I tried adding the changes you mentioned in https://github.com/firebase/firebase-android-sdk/issues/1325#issuecomment-597293291 . I ran into other strict mode violations than the one you raised. I would highly appreciate if you can take another look at the demo repo. Thanks.

**Comment by lexer** [comment] 2020-03-11 19:57
@ankitaj224 demo repo should be up to date.

I just re ran the app and get following crash that matches the previous one I mentioned:

```
D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at java.util.zip.Inflater.finalize(Inflater.java:407)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at java.util.zip.Inflater.<init>(Inflater.java:122)
        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:64)
        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:484)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:661)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(com.google.firebase:firebase-installations@@16.0.0:154)
        at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(com.google.firebase:firebase-installations@@16.0.0:411)
        at com.google.firebase.installations.FirebaseInstallations.doRegistrationInternal(com.google.firebase:firebase-installations@@16.0.0:316)
        at com.google.firebase.installations.FirebaseInstallations.doGetId(com.google.firebase:firebase-installations@@16.0.0:280)
        at com.google.firebase.installations.FirebaseInstallations.access$lambda$0(Unknown Source:0)
        at com.google.firebase.installations.FirebaseInstallations$$Lambda$1.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919) 
W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
I/Process: Sending signal. PID: 1990 SIG: 9
```

**Comment by lexer** [comment] 2020-03-11 20:01
I re ran it on Google pixel 4 device and get another error you might be talking about:

```
D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at java.util.zip.Inflater.finalize(Inflater.java:407)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at java.util.zip.Inflater.<init>(Inflater.java:122)
        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:64)
        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:484)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:661)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(com.google.firebase:firebase-config@@19.0.4:186)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(com.google.firebase:firebase-config@@19.0.4:278)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(com.google.firebase:firebase-config@@19.0.4:251)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchIfCacheExpiredAndNotThrottled(com.google.firebase:firebase-config@@19.0.4:191)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetch$0(com.google.firebase:firebase-config@@19.0.4:160)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$Lambda$1.then(Unknown Source:4)
        at com.google.android.gms.tasks.zzf.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919) 
W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
I/Process: Sending signal. PID: 4829 SIG: 9
```

**Comment by lexer** [comment] 2020-03-11 20:03
While stack traces are different I think it's a similar issue caused by not closing http stream.

**Comment by lexer** [comment] 2020-03-11 20:24
Since both jobs are running in parallel it is just a matter of what will crash first.

**Comment by ankitaj224** [comment] 2020-03-11 20:25
@lexer repo is still not updated. Can you please recheck the push once? Fix for this reported issue seems like closing the input stream

**Comment by lexer** [comment] 2020-03-11 20:31
@ankitaj224 i did not update the repo. I think I misunderstood your ask.

Do you want me to increase firebase version?

**Comment by ankitaj224** [comment] 2020-03-11 20:33
@lexer https://github.com/lexer/firebaseInstallations-crash-demo/blob/master/app/build.gradle

Repo is just an empty app with no strict violations enabled and firebase dependencies. Is that intended?

**Comment by lexer** [comment] 2020-03-11 20:34
There are two jobs in firebase sdk that violate close stream strict mode check:

```
2020-03-12 07:28:17.796 2694-2711/com.squareup.cash.beta.debug D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at java.util.zip.Inflater.finalize(Inflater.java:407)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at java.util.zip.Inflater.<init>(Inflater.java:122)
        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:64)
        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:484)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:661)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(com.google.firebase:firebase-installations@@16.0.0:154)
        at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(com.google.firebase:firebase-installations@@16.0.0:411)
        at com.google.firebase.installations.FirebaseInstallations.doRegistrationInternal(com.google.firebase:firebase-installations@@16.0.0:316)
        at com.google.firebase.installations.FirebaseInstallations.doGetId(com.google.firebase:firebase-installations@@16.0.0:280)
        at com.google.firebase.installations.FirebaseInstallations.access$lambda$0(Unknown Source:0)
        at com.google.firebase.installations.FirebaseInstallations$$Lambda$1.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919) 
2020-03-12 07:28:17.796 2694-2711/com.squareup.cash.beta.debug D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at java.util.zip.Inflater.finalize(Inflater.java:407)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at java.util.zip.Inflater.<init>(Inflater.java:122)
        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:64)
        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:484)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:661)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(com.google.firebase:firebase-config@@19.0.4:186)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(com.google.firebase:firebase-config@@19.0.4:278)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(com.google.firebase:firebase-config@@19.0.4:251)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchIfCacheExpiredAndNotThrottled(com.google.firebase:firebase-config@@19.0.4:191)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetch$0(com.google.firebase:firebase-config@@19.0.4:160)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$Lambda$1.then(Unknown Source:4)
        at com.google.android.gms.tasks.zzf.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by ankitaj224** [comment] 2020-03-11 20:36
I am working on the fix for the first/original violation this issue states. I can reach out to the remote config team to look into the second violation.
@clp93  Please take a look at this strict mode violation from RC.

**Comment by lexer** [comment] 2020-03-11 20:37
@ankitaj224 you are right. i think pushed a different sample app by accident. fixing.

**Comment by lexer** [comment] 2020-03-11 20:40
@ankitaj224 sorry about that. I pushed the correct repo. https://github.com/lexer/firebaseInstallations-crash-demo

**Comment by lexer** [comment] 2020-03-16 21:26
@ankitaj224 did my sample work to reproduce the issue for you?

**Comment by andirayo** [comment] 2020-03-17 17:25
@lexer :
Thank you for checking in! We got side-tracked by #1339 .
@ankitaj224 is finishing up a fix for #1339 today and then return to this issue.
Thanks again for your help and support reproducing the issue!

**Comment by lexer** [comment] 2020-03-18 17:56
Awesome. Thank you @andirayo!

**Comment by ankitaj224** [comment] 2020-03-20 17:15
@lexer Thanks for checking in and for the demo project. Extremely sorry for the delay. 

An update: I was able to reproduce the issue using the demo app you sent. But unable to catch the same through internal test app. I think it's the combination of okhttp library along with the Android version. I tried closing the http stream and the violation doesn't seem to be resolved. 

I will need some more time ( before end of next week) for analyzing and fixing the violation. Do you have any deliverables that are blocked by this issue?

**Comment by lexer** [comment] 2020-03-23 16:54
@ankitaj224 thank you!

Deliverables blocked:
1. We can't upgrade firebase messaging to most recent version.
2. Pilot firebase performance integration for network monitoring.

**Comment by ankitaj224** [comment] 2020-03-24 19:03
@lexer  Thanks for the information.

About upgrading to the latest version of firebase-messaging: The firebase-messaging v20.1.2 has a known bug  #1339 which is fixed and the new version will be publicly released this week. I would recommend waiting for the latest version. Although the new version will not contain the strict mode violation fix.

To unblock your pilot on Fireperf, you could lock in this version for firebase-iid: 20.0.2.

Please let me know if you have any questions.  

I will keep this thread posted on my progress with the strict mode violation and update which Firebase release will contain the fix.

**Comment by lexer** [comment] 2020-03-26 03:37
@ankitaj224 thank you.

Does locking in firebase-iid to 20.0.2 helps with violation issue?

**Comment by ankitaj224** [comment] 2020-04-01 22:40
@lexer Yes, that should definitely help. Let me know if it doesn't.

I had few more issues that came up due to the latest release. I haven't forgotten this open issue, its on my TODOs :)  I hope to get to this soon.

**Comment by lexer** [comment] 2020-04-06 19:50
Thanks @ankitaj224 

I'm currently using `com.google.firebase:firebase-perf:18.0.0` that doesn't have strict mode issue and doesn't require us to upgrade firebase messaging from 19.0.0.

**Comment by ankitaj224** [comment] 2020-04-06 21:41
@lexer 

My analysis on the strict mode issue:

Using your test demo, I was able to reproduce the issue for **Android API 26 and above**. On further analyzing FirebaseInstallationServiceClient that performs the network calls, I changed it to close all the streams and we still got this strict mode violation. 

My suspect then was the internal okhttp impl Android uses. You can find there was a similar error reported few years back in the okhttp library which was eventually fixed.
 
To validate my doubts: I ran the demo app against **Android API 24, 25** and it doesn't throw this strict mode violation.

Can you please validate the same for your app with **Android API 24, 25**?

**Comment by lexer** [comment] 2020-04-29 01:58
@ankitaj224 I ran it on Android API 22 emulator and it crashed.

@ankitaj224 it's suspicious since the issue does not exist in com.google.firebase:firebase-perf:18.0.0.

**Comment by ankitaj224** [comment] 2020-05-29 23:16
@lexer Could you please update the firebase-messaging:20.2.0 version and see if the demo app still complaints about Firebase-Installations Strict Mode violation?

**Comment by ankitaj224** [comment] 2020-05-29 23:32
Also, reason for com.google.firebase:firebase-perf:18.0.0 not resulting in the Strict mode violation is because the latest versions of Firebase SDKs introduced a new dependency: The Firebase Installations SDK (FIS).

Firebase Installations is an infrastructure service (identity provider and authentication scheme) that is used under the hood by many Firebase services (like Analytics). Usually, you do not need to explicitly include it, but you will get it as transitive dependency (through Firebase InstanceId).

The Strict Mode violation you identified is in Firebase Installations SDK. So, this issue does not exist in com.google.firebase:firebase-perf:18.0.0.

**Closed** 2020-06-17 01:04 UTC
Labels: closed-by-bot, firebase-installations, needs-info, no-recent-activity
