### ISSUE TITLE
RuntimeException: at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5@19.0.2:379

### ISSUE THREAD

**Issue by skkakadiya** [firebase/firebase-android-sdk#972] opened 2019-11-12 07:32 UTC
### [READ] Step 1: Are you in the right place?

Yes, this is an issue with Cloud Firestore's internal on-device SQLite database and this repository appears to contain all of the code required to manage that database.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5
  * Firebase Component: firebase-core(v16.0.9), messaging(v18.0.0), firebase-config(v17.0.0), database(v17.0.0), auth(v17.0.0), firestore(v19.0.2), firebase-inappmessaging-display(v17.2.0)
  * com.android.tools.build:gradle:3.2.1
  * com.google.gms:google-services:4.2.0
  * compileSdkVersion 28
  * buildToolsVersion '28.0.3'

### [REQUIRED] Step 3: Describe the problem

I got below error on Android vitals on Play store from Samsung Galaxy S10(beyond1q) running on Android 9. I got more than 3.5K crashes in the last 7 days.

#### Relevant Code:
Crashlytics Stack Trace
```
java.lang.RuntimeException: at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5(com.google.firebase:firebase-firestore@@19.0.2:379) 
at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run (Unknown Source:2)
at android.os.Handler.handleCallback (Handler.java:873)
at android.os.Handler.dispatchMessage (Handler.java:99)
at android.os.Looper.loop (Looper.java:214)
at android.app.ActivityThread.main (ActivityThread.java:7037)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)


Caused by: android.database.sqlite.SQLiteBlobTooBigException: 
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow (Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow (SQLiteConnection.java:1060)
at android.database.sqlite.SQLiteSession.executeForCursorWindow (SQLiteSession.java:836)
at android.database.sqlite.SQLiteQuery.fillWindow (SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow (SQLiteCursor.java:169)
at android.database.sqlite.SQLiteCursor.onMove (SQLiteCursor.java:131)
at android.database.AbstractCursor.moveToPosition (AbstractCursor.java:237)
at android.database.AbstractCursor.moveToNext (AbstractCursor.java:269)
at com.google.firebase.firestore.local.SQLitePersistence$Query.forEach
at com.google.firebase.firestore.local.SQLiteLruReferenceDelegate.removeOrphanedDocuments
at com.google.firebase.firestore.local.LruGarbageCollector.removeOrphanedDocuments
at com.google.firebase.firestore.local.LruGarbageCollector.runGarbageCollection
at com.google.firebase.firestore.local.LruGarbageCollector.collect
at com.google.firebase.firestore.local.LocalStore.lambda$collectGarbage$9
at com.google.firebase.firestore.local.LocalStore$$Lambda$10.get (Unknown Source:4)
at com.google.firebase.firestore.local.SQLitePersistence.runTransaction
at com.google.firebase.firestore.local.LocalStore.collectGarbage
at com.google.firebase.firestore.local.LruGarbageCollector$Scheduler.lambda$scheduleGC$0
at com.google.firebase.firestore.local.LruGarbageCollector$Scheduler$$Lambda$1.run (Unknown Source:2)
at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.handleDelayElapsed
at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.access$lambda$0 (Unknown Source)
at com.google.firebase.firestore.util.AsyncQueue$DelayedTask$$Lambda$1.run (Unknown Source:2)
at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:459)
at java.util.concurrent.FutureTask.run (FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run
at java.lang.Thread.run (Thread.java:764)
```

**Comment by schmidt-sebastian** [comment] 2019-11-13 17:17
Thanks for reporting! This is a duplicate of https://github.com/firebase/firebase-android-sdk/issues/706 and fixed in 21.2.0.

**Closed by schmidt-sebastian** 2019-11-13 17:17 UTC
Labels: needs-triage
