### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.NullPointerException

### ISSUE THREAD

**Issue by dummyco** [firebase/firebase-android-sdk#3372] opened 2022-01-27 11:06 UTC
### Environment

  * Android Studio version: `2021.2.1 Canary 7`
  * Firebase Component: `common`
  * Component version: `com.google.firebase:firebase-bom:29.0.4`

### Problem

R8 build (both for enabled and disabled `fullMode`) results in the app crash:

```
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.NullPointerException: Attempt to invoke interface method 'w8.a$a w8.a.g(java.lang.String, w8.a$b)' on a null object reference
        at android.app.ActivityThread.installProvider(ActivityThread.java:7436)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6948)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
        at android.app.ActivityThread.access$1500(ActivityThread.java:256)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'w8.a$a w8.a.g(java.lang.String, w8.a$b)' on a null object reference
        at q1.a0.a(R8$$SyntheticClass:5)
        at z8.x.a(OptionalProvider.java:3)
        at a9.a.<init>(AnalyticsDeferredProxy.java:6)
        at a9.c.g(R8$$SyntheticClass:18)
        at z8.i.get(R8$$SyntheticClass:3)
        at z8.s.get(Lazy.java:5)
        at z8.k.l(ComponentRuntime.java:5)
        at s8.b.e(FirebaseApp.java:23)
        at s8.b.f(FirebaseApp.java:23)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:8)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:3)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7431)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6948) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:256) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by argzdev** [comment] 2022-01-27 11:16
Hi @dummyco, thanks for the report. Any chance you can provide a code snippet or [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) of this issue? Thanks!

**Comment by dummyco** [comment] 2022-01-27 11:52
Hi @argzdev! It seems like there's no issue-specific code on the consumer side, probably it's initiated and thrown from the inside of Firebase?

I've discovered one more thing,
`-keep class com.google.firebase.analytics.connector.AnalyticsConnectorImpl { *; }`
resolves the issue (corresponds to mapped `w8.a`). Probably that can be helpful?

**R8 config snippet:**

```
-keepattributes SourceFile,LineNumberTable
-optimizationpasses 7
-allowaccessmodification
-verbose
-printseeds seeds.txt
-printusage usage.txt

# === Glide ===

-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

# === Gson ===

# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken

# === Navigation ===
-keep public class androidx.navigation.fragment.NavHostFragment { *; }

# === R8 ===
-keep class androidx.core.app.CoreComponentFactory { <init>(); }

# === Protobuf ===
-keepnames class * extends com.google.protobuf.GeneratedMessage { *; }
-keepnames class * extends com.google.protobuf.GeneratedMessageLite { *; }

# === Retrofit ===
-keepnames class io.reactivex.rxjava3.core.Single

# === Firebase ===
-keep class com.google.firebase.analytics.connector.AnalyticsConnectorImpl { *; }
```

**Plugins:**

```
        classpath "com.google.firebase:firebase-crashlytics-gradle:2.8.1"
        classpath "com.google.firebase:perf-plugin:1.4.1"
```
```
        apply plugin: "com.google.firebase.crashlytics"
        apply plugin: "com.google.firebase.firebase-perf"
```

**Dependencies:**

```
    implementation platform("com.google.firebase:firebase-bom:29.0.4")
    implementation "com.google.firebase:firebase-analytics-ktx"
    implementation "com.google.firebase:firebase-crashlytics"
    implementation "com.google.firebase:firebase-iid"
    implementation("com.google.firebase:firebase-perf") {
        exclude group: "com.google.protobuf"
    }
```

**Comment by eygraber** [comment] 2022-01-27 21:31
I had the same issue on Chipmunk Beta 1 and `-keep class com.google.firebase.analytics.connector.AnalyticsConnectorImpl { *; }` fixes the problem.

**Comment by argzdev** [comment] 2022-01-28 15:35
Thanks for the extra details @dummyco & @eygraber. Unfortunately, I'm unable to repro this issue on a clean project with the given relevant code. I'm probably missing something. Is there any specific code that used Firebase Analytics? A minimal repro will greatly help us in our investigation. Thanks in advance!

**Comment by eygraber** [comment] 2022-01-28 21:01
@dummyco were you using AGP 7.2.0-alpha07 or 7.2.0-beta01? I only see this issue on beta01. I'm seeing a lot of R8 issues with that version, and I'm assuming that's the root cause here.

@argzdev I'm not using Firebase Analytics directly, but it looks like Crashlytics is. Here's the unobfuscated stacktrace:

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.installProvider (ActivityThread.java:7427)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:6939)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6710)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:247)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2053)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7839)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: 
  at com.google.firebase.crashlytics.AnalyticsDeferredProxy.subscribeToAnalyticsEvents (AnalyticsDeferredProxy.java:164)
  at com.google.firebase.crashlytics.AnalyticsDeferredProxy.lambda$init$2 (AnalyticsDeferredProxy.java:100)
  at com.google.firebase.crashlytics.AnalyticsDeferredProxy$$InternalSyntheticLambda$2$ff62cfcd4321d3d2ae4ce280f2e2af4fe377196254af9275f1faaca52c2ffcb3$0.handle (AnalyticsDeferredProxy.java)
  at com.google.firebase.components.OptionalProvider.whenAvailable (OptionalProvider.java:77)
  at com.google.firebase.crashlytics.AnalyticsDeferredProxy.init (AnalyticsDeferredProxy.java:82)
  at com.google.firebase.crashlytics.AnalyticsDeferredProxy.<init> (AnalyticsDeferredProxy.java:63)
  at com.google.firebase.crashlytics.AnalyticsDeferredProxy.<init> (AnalyticsDeferredProxy.java:49)
  at com.google.firebase.crashlytics.FirebaseCrashlytics.init (FirebaseCrashlytics.java:83)
  at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics (CrashlyticsRegistrar.java:57)
  at com.google.firebase.components.Component$$InternalSyntheticLambda$0$0568d44f17f6b4fb3439fb348c6ed241ea29182f0658852873af49c8702503f4$0.create$bridge (Component.java)
  at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java:132)
  at com.google.firebase.FirebaseApp$$InternalSyntheticLambda$0$71683e65149879c2a3a667b3ffd09f03d246370863d48f7d8ead5ed5a13c6989$0.get$bridge (FirebaseApp.java)
  at com.google.firebase.components.Lazy.get (Lazy.java:53)
  at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents (ComponentRuntime.java:291)
  at com.google.firebase.components.ComponentRuntime.initializeEagerComponents (ComponentRuntime.java:281)
  at com.google.firebase.FirebaseApp.initializeAllApis (FirebaseApp.java:584)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:303)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:267)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:252)
  at com.google.firebase.provider.FirebaseInitProvider.onCreate (FirebaseInitProvider.java:51)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2404)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2374)
  at com.google.firebase.provider.FirebaseInitProvider.attachInfo (FirebaseInitProvider.java:45)
  at android.app.ActivityThread.installProvider (ActivityThread.java:7422)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:6939)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6710)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:247)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2053)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7839)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)
```

**Comment by dummyco** [comment] 2022-01-29 13:11
@eygraber, yep, that's `7.2.0-beta01`

**Comment by argzdev** [comment] 2022-02-01 12:41
Hi @dummyco and @eygraber, I'm unable to reproduce this issue, with that said, let's keep the ticket open for now in case our engineers might have an idea what the issue is. Feel free to add any questions or extra information. Thanks!

**Comment by eygraber** [comment] 2022-02-01 15:22
This has been fixed in a newer version of R8

https://issuetracker.google.com/issues/216790348

**Comment by argzdev** [comment] 2022-02-01 18:49
Thanks for the update, @eygraber ! Since this is fixed in the newer version, I'll close this issue for now.

**Closed by argzdev** 2022-02-01 18:49 UTC
Labels: api: analytics, api: crashlytics, needs-attention
