### ISSUE TITLE
FirebaseInstallation class crashing in Android 

### ISSUE THREAD

**Issue by AhmadIzaz** [firebase/firebase-android-sdk#2147] opened 2020-11-05 10:56 UTC
Environment and Components I am using are as below.

Firebase Crashlytics have been reporting this crash on huge number of devices having Android 8 and Android 6 on playstore.
We are using dexguard in the app too.

Project build.gradle

        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0' // Crashlytics plugin
        classpath 'com.google.firebase:perf-plugin:1.3.1'  // Performance Monitoring plugin

App build.gradle
     
    implementation 'com.google.firebase:firebase-messaging:20.2.1'
    implementation 'com.google.firebase:firebase-analytics:17.4.3'
    implementation 'com.google.firebase:firebase-crashlytics:17.1.0'
    implementation('com.google.firebase:firebase-perf:19.0.7'

These are the logs I am getting from Crashlytics.

**???
com.google.firebase.installations.FirebaseInstallations.INotificationSideChannel$Stub$Proxy**

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at com.google.firebase.installations.FirebaseInstallations.INotificationSideChannel$Stub$Proxy(:452)
       at com.google.firebase.installations.FirebaseInstallations.INotificationSideChannel$Stub$Proxy(:331)
       at com.google.firebase.installations.FirebaseInstallations.INotificationSideChannel$Stub$Proxy(:296)
       at com.google.firebase.installations.FirebaseInstallations$$Lambda$3.run(:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

It is not giving any hint so we can reproduce that crash on our devices but It is causing to a huge number of users.

**Comment by ankitaj224** [comment] 2020-11-05 23:14
@AhmadIzaz  Thanks for reaching out. I am from the Firebase Installations team, this issue is a duplicate of #1787.

Please update your app to depend on the latest version of Firebase libraries that will transitively update firebase-installations(FIS) i.e com.google.firebase:firebase-installations:16.3.3 dependency which contains the fix.

**Closed by ankitaj224** 2020-11-05 23:14 UTC
Labels: firebase-installations

**Comment by AhmadIzaz** [comment] 2020-11-06 06:39
@ankitaj224 Thankyou for quick response. I will update my Firebase libraries and will check the results.
