### ISSUE TITLE
Firebase InApp messaging addClickListener function not invoked(FirebaseInAppMessagingClickListener)

### ISSUE THREAD

**Issue by farazahmedfeb** [firebase/firebase-android-sdk#2466] opened 2021-02-25 15:08 UTC
### [READ] Step 1: Are you in the right place?

hi
Iam using the latest dependencies as per firebase documentation and when iam triggering the message from firebase console
it is visible on my app but when i click the button i wanted this FirebaseInAppMessagingClickListener function to invoke and but unfortunately its not happening

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.2
  * Firebase Component: InApp messaging
  * Component version: 26.5.0

#### Relevant Code:
In gradle

using latest dependencies
   

```
// TODO(you): code here to reproduce the problem
    implementation platform('com.google.firebase:firebase-bom:26.5.0')
    implementation 'com.google.firebase:firebase-inappmessaging-display-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
```
Implementation of FirebaseInAppMessagingClickListener

```
class MyFirebaseDisplay(val activity: KarmaActivity) : FirebaseInAppMessagingClickListener {
    override fun messageClicked(p0: InAppMessage, p1: Action) {
       Log.d("seeThis: ${p1.button!!.text}")
    }
}
```

Registering in onCreate of my main class:

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.MainActivity)
        var firebaseMessageClick = MyFirebaseDisplay(this)
        FirebaseInAppMessaging.getInstance().addClickListener(firebaseMessageClick)
}
```
I have followed the procedure from the doucmentation but its not working 
Please help me resolve this issue.

**Comment by MKelman** [comment] 2021-03-17 16:51
Same issue, occuring on 19.1.5 latest version of firebase-inappmessaging-display-ktx

**Comment by argzdev** [comment] 2023-01-18 14:32
Hi, this seems to be a duplicate of #2184. I'll close this now. Thanks!

**Closed by argzdev** 2023-01-18 14:32 UTC
Labels: api: inappmessaging
