### ISSUE TITLE
Firebase In-App Messaging errors

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-android-sdk#2107] opened 2020-10-27 08:40 UTC
We are receiving tons of error from Crashlytics and Cloud Console with In-App Messaging dependency and as I checked other report issue with In-App Messaging it seems no fix action has been taken. This module definitely need some revamp.

![image](https://user-images.githubusercontent.com/38008900/97276690-82849f00-1872-11eb-868a-14b60bb44d08.png)
![image](https://user-images.githubusercontent.com/38008900/97276759-96300580-1872-11eb-895f-5fa4f2188033.png)
![image](https://user-images.githubusercontent.com/38008900/97276922-cd061b80-1872-11eb-9d0b-d1633848f3cc.png)
![image](https://user-images.githubusercontent.com/38008900/97276967-d8f1dd80-1872-11eb-986c-0f0fedf4ce6a.png)
![image](https://user-images.githubusercontent.com/38008900/97277028-e909bd00-1872-11eb-93e9-9807c2ba4b18.png)
![image](https://user-images.githubusercontent.com/38008900/97277044-f030cb00-1872-11eb-9b47-2e54d985faab.png)
![image](https://user-images.githubusercontent.com/38008900/97277081-0179d780-1873-11eb-8121-6e5dadef7aca.png)
![image](https://user-images.githubusercontent.com/38008900/97277119-0dfe3000-1873-11eb-8234-cf73c50976f4.png)

**Comment by rlazo** [comment] 2021-01-22 15:59
Hi @ArcherEmiya05 what Firebase SDKs are you using? Which versions?  Thanks!

**Comment by prakhar1989** [comment] 2021-01-29 18:43
Hey @ArcherEmiya05 thanks for bringing this to our attention. Can you please share what SDK version are you seeing the crash on? Also from your crashlytics report, can you confirm what if there's a particular set of devices and/or Android OS version that this is prevalent on? It'll help us narrow down the issue faster.

Thanks!

**Comment by eldhosembabu** [comment] 2021-01-29 19:19
Hi @ArcherEmiya05 ,

Thanks for reporting this issue.

The issue is already fixed in the latest in-app-messaging version 19.1.4.

Please use that version and let us know whether its reproducible.

**Closed** 2021-02-12 02:01 UTC
Labels: api: inappmessaging, needs-info, no-recent-activity
