### ISSUE TITLE
injectCrashlyticsMappingFileIdRelease issue report

### ISSUE THREAD

**Issue by Psijic** [firebase/firebase-android-sdk#5100] opened 2023-06-23 07:23 UTC
Consider filing a bug to report this issue to the plugin developer.

```
At 10:19, Jun 23, 2023, Android Studio detected the following issue(s) with Gradle plugin com.google.firebase.crashlytics

Always-Run Tasks
This task might be setting its up-to-date check to always return false.

Plugin: com.google.firebase.crashlytics
Task: injectCrashlyticsMappingFileIdRelease
Task type: com.google.firebase.crashlytics.buildtools.gradle.tasks.InjectMappingFileIdTask
Issues for the same task were detected in 1 module(s), total execution time was <0.1s (0.1%), by module:
  Execution mode: FULL, time: <0.1s (0.1%), determines build duration: true, on critical path: true, issues: Always-Run Tasks

====Build information:====
Execution date: 23.06.2023, 10:19
Total build duration: 71.4s
Configuration time: 6.7s (9.4%)
Critical path tasks time: 64.3s (90.0%)
Critical path tasks size: 9
AGP versions: 8.0.2
====Platform information:====
AI-222.4459.24.2221.10121639, JRE 17.0.6+0-17.0.6b802.4-9586694x64 JetBrains s.r.o., OS Linux(amd64) v5.14.21-150500.53-default, screens 2560.0x1440.0

AS: Flamingo | 2022.2.1 Patch 2
Kotlin plugin: 222-1.8.20-release-AS3739.54
Android Gradle Plugin: 8.0.2
Gradle: 8.1
Gradle JDK: JetBrains Runtime version 17.0.6
NDK: from local.properties: (not specified), latest from SDK: (not found)
CMake: from local.properties: (not specified), latest from SDK: 3.22.1-g37088a8, from PATH: 3.20.4
```

**Comment by argzdev** [comment] 2023-06-23 14:21
Hi @Psijic, thanks for reaching out. It looks like a duplicate of https://github.com/firebase/firebase-android-sdk/issues/5083. For better tracking, kindly continue your report on that thread. Please do leave a thumbs up reaction emoji on the author's post so we can track the severity. I'll go ahead and close this one. Thanks!

**Closed by argzdev** 2023-06-23 14:21 UTC
Labels: api: crashlytics
