### ISSUE TITLE
[ANR] <PackageName>/com.google.android.datatra nsport.runtime.scheduling.jobscheduling.JobInfoSchedulerService

### ISSUE THREAD

**Issue by gouravsinghal92** [firebase/firebase-android-sdk#4227] opened 2022-10-20 12:19 UTC
Hi team,

We have released a build some weeks back in which there were no changes related to Firebase. But we got the ANR in play store console with title:

<PackageName>/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService

We searched it on google and saw that some people have asked about it in the past related to firebase. 

Some Info from my code:(from few files)

    ext.gradleFirebaseVersion = '2.7.1'
    classpath 'com.google.firebase:perf-plugin:1.4.0'
    implementation platform('com.google.firebase:firebase-bom:26.8.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics-ndk'
    implementation 'com.google.firebase:firebase-appindexing'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-perf'

Can you please guide us in some direction? Can it be related to firebase at all? If yes, what can we change at our end. FYIP again, we haven't changed anything in firebase versions in last 6 months at least but we got this ANR just few weeks back only after 1 release in which we had only basic changes(nothin which may cause ANR).

Thanks in advance.

**Comment by mrichards** [comment] 2022-10-20 17:38
@gouravsinghal92 You are using Firebase SDKs that are ~18 months old. I strongly recommend updating to the latest BoM (31.0.1).

It is hard to know for certain based on your report, but I believe the issue you are referencing was likely fixed in Crashlytics [18.2.8](https://firebase.google.com/support/release-notes/android#crashlytics_v18-2-8) or [18.2.10](https://firebase.google.com/support/release-notes/android#crashlytics_v18-2-10)

**Comment by gouravsinghal92** [comment] 2022-10-20 19:20
@mrichards really thanks for the details. But when we haven't made any change, then how come upgrading it will solve that issue? Can you please throw some light on this? 

Also, what all components version we need to update? Only BOM?

Really thanks in advance.

**Comment by argzdev** [comment] 2022-11-29 11:26
Hi @gouravsinghal92, sorry for the late response. We usually recommend upgrading to avoid issues that are already fixed in the most recent versions. 

This issue looks like it's related to #3910. Just gathering some further details, when you say "basic changes", were there any changes related to Firebase products? If so, could you share some code snippets? This might give us some clues what is causing this. Also any chance that you're able to reproduce the ANR?

**Closed** 2022-12-13 02:01 UTC
Labels: needs-info, no-recent-activity, api: datatransport
