### ISSUE TITLE
Auth does not correctly use emulator in 29.2.1+ including 30.0.0, works in 29.1.0

### ISSUE THREAD

**Issue by mikehardy** [firebase/firebase-android-sdk#3557] opened 2022-03-18 03:38 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Gradle 7.4.1, Android Gradle Plugin 7.0.4
  * Firebase Component: Auth + firebase-tools 10.4.0 (current)
  * Component version: BoM 29.2.1 (works in 29.1.0)

#### Steps to reproduce:

- create user in cloud auth user database
- start firebase emulator, clear all auth users
- call useEmulator on auth component
- attempt to create user with same email as user in cloud auth user database

Should work, does work in 29.1.0, 29.2.1 does not appear to actually use the auth emulator though. You get "email in use" error

#### Relevant Code:

I think the steps to reproduce should be quick enough to reproduce, but you can see the whole app that reproduces it in the react-native-firebase android tests app we use for e2e testing our exposure of all the APIs in your SDK here:

Full app so you may see dependencies etc:
https://github.com/invertase/react-native-firebase/tree/%40mikehardy/dependency-updates/tests/android

our useEmulator call
https://github.com/invertase/react-native-firebase/blob/8406336415511ce58d1611f94106cceaf920567e/packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java#L1562-L1567

The line that fails:
https://github.com/invertase/react-native-firebase/blob/8406336415511ce58d1611f94106cceaf920567e/packages/auth/e2e/auth.e2e.js#L29

**Comment by rosalyntan** [comment] 2022-03-21 22:53
Tracking internally at b/225972666.

**Comment by rosalyntan** [comment] 2022-03-22 00:02
Hi @mikehardy -- I tried testing with the Android quickstart built with BoM version 29.2.1 and was unable to reproduce this issue.

If you create a user with an email that is neither in the emulator database nor the prod database, where does the user appear?

**Comment by mikehardy** [comment] 2022-03-22 00:23
Oh, that's unexpected, I did double-check my environment prior to filing but obviously it needs a really careful triple check, thanks for the attempt and I'll let you know. Sorry for logging something that wasn't clear cut!

**Comment by mikehardy** [comment] 2022-03-24 12:00
I began pursuing this again yesterday after handling some iOS items, and I still reproduce this locally. 29.1.0 works perfectly in my testing, simply switching to 29.2.1 it starts to fail. *Why* is of course the open question and react-native-firebase may be the source of some really subtle error but it is quite odd that simply switching the dependency immediately causes the error, if it's in react-native-firebase.

**Comment by rosalyntan** [comment] 2022-03-24 18:31
Hmm I'll dig into this further. In the meantime, a quick question -- in manual testing for the `useEmulator` call with `29.2.1`, do you see created users appear in the emulator database or in the prod database?

**Comment by mikehardy** [comment] 2022-03-27 15:28
@rosalyntan sorry for the delay answering your question and thanks for your patience.
Today I tried a couple things:
- I tried it from windows just because I was temporarily on a windows laptop, to see if it registered a difference vs my  normal macOS development platform. I did not expect a change in behavior, and no change was noticed - same error, but thought I'd mention it
- I checked in our test project cloud auth database, to answer your question, and re-configured the test to use a new test email address (`rnfbtest20220327@example.com`) - sure enough, the user was created one time in the [cloud / prod auth database](https://console.firebase.google.com/u/0/project/react-native-firebase-testing/authentication/users) then failed on "user already exists". So it is definitely attempting to create the user in the cloud database even though when I inserted System.err.println statements in our native code wrapper here I can see the API is being called with the expected host/port and is returning success https://github.com/invertase/react-native-firebase/blob/ef7895cd49eed3a4d103df624e52315250c68ab3/packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java#L1562-L1567


Here's the temporary additions I made:

```java
  @ReactMethod
  public void useEmulator(String appName, String host, int port) {
    Log.d(TAG, "useEmulator");
    Log.d(TAG, "useEmulator temp log - appName: " + appName);
    FirebaseApp firebaseApp = FirebaseApp.getInstance(appName);
    FirebaseAuth firebaseAuth = FirebaseAuth.getInstance(firebaseApp);
    Log.d(TAG, "useEmulator temp log - host: " + host);
    Log.d(TAG, "useEmulator temp log - port: " + port);
    firebaseAuth.useEmulator(host, port);
    Log.d(TAG, "useEmulator temp log - after call, so, no exception...");
  }
```

Here's the interesting bits from logcat:

```

03-27 10:14:03.422 14973 15198 D Auth    : useEmulator
03-27 10:14:03.423 14973 15198 D Auth    : useEmulator temp log - appName: [DEFAULT]
03-27 10:14:03.423 14973 15198 D Auth    : useEmulator temp log - host: 10.0.2.2
03-27 10:14:03.423 14973 15198 D Auth    : useEmulator temp log - port: 9099
03-27 10:14:03.424 14973 15198 D Auth    : useEmulator temp log - after call, so, no exception...
03-27 10:14:03.427 14973 15198 D Auth    : createUserWithEmailAndPassword
03-27 10:14:03.427 14973 15199 W Firestore: (24.0.2) [FirebaseFirestore]: Host has been set in FirebaseFirestoreSettings and useEmulator, emulator host will be used.
03-27 10:14:03.435 14973 15203 W System  : Ignoring header X-Firebase-Locale because its value was null.
03-27 10:14:03.521   681   681 V ShadeControllerImpl: NotificationShadeWindow: com.android.systemui.statusbar.phone.NotificationShadeWindowView{2ef2cc3 I.E...... ......ID 0,0-1080,2220} canPanelBeCollapsed(): false
03-27 10:14:04.453 14973 14973 E Auth    : createUserWithEmailAndPassword:onComplete:failure
03-27 10:14:04.453 14973 14973 E Auth    : com.google.firebase.auth.FirebaseAuthUserCollisionException: The email address is already in use by another account.
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzth.zza(com.google.firebase:firebase-auth@@21.0.2:25)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzuf.zza(com.google.firebase:firebase-auth@@21.0.2:9)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzug.zzl(com.google.firebase:firebase-auth@@21.0.2:1)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzud.zzh(com.google.firebase:firebase-auth@@21.0.2:25)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zztf.zzh(com.google.firebase:firebase-auth@@21.0.2:1)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzpt.zza(com.google.firebase:firebase-auth@@21.0.2:2)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzuo.zza(com.google.firebase:firebase-auth@@21.0.2:22)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zztu.zzn(com.google.firebase:firebase-auth@@21.0.2:4)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzrk.zzl(com.google.firebase:firebase-auth@@21.0.2:5)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zztg.zzf(com.google.firebase:firebase-auth@@21.0.2:8)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzrp.zzc(com.google.firebase:firebase-auth@@21.0.2:1)
03-27 10:14:04.453 14973 14973 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzuh.run(com.google.firebase:firebase-auth@@21.0.2:1)
03-27 10:14:04.453 14973 14973 E Auth    :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-27 10:14:04.453 14973 14973 E Auth    :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-27 10:14:04.453 14973 14973 E Auth    :      at java.lang.Thread.run(Thread.java:923)
```

I had a hunch perhaps it was an async issue so I tried adding a main thread sleep after the useEmulator firebase-android-sdk call:

```java
  @ReactMethod
  public void useEmulator(String appName, String host, int port) {
    Log.d(TAG, "useEmulator");
    Log.d(TAG, "useEmulator temp log - appName: " + appName);
    FirebaseApp firebaseApp = FirebaseApp.getInstance(appName);
    FirebaseAuth firebaseAuth = FirebaseAuth.getInstance(firebaseApp);
    Log.d(TAG, "useEmulator temp log - host: " + host);
    Log.d(TAG, "useEmulator temp log - port: " + port);
    firebaseAuth.useEmulator(host, port);
    try { Thread.currentThread().sleep(5000); } catch (Exception e) { /* ignore interruptions */ }  // <--- added this
    Log.d(TAG, "useEmulator temp log - after call and sleep, so, no exception...");
  }
```

No behavior change except 5 more seconds pass:

```
03-27 10:24:14.411 15917 16143 D Auth    : useEmulator
03-27 10:24:14.411 15917 16143 D Auth    : useEmulator temp log - appName: [DEFAULT]
03-27 10:24:14.411 15917 16143 D Auth    : useEmulator temp log - host: 10.0.2.2
03-27 10:24:14.411 15917 16143 D Auth    : useEmulator temp log - port: 9099

...


03-27 10:24:19.413 15917 16143 D Auth    : useEmulator temp log - after call and sleep, so, no exception...
03-27 10:24:19.446 15917 16143 D Auth    : createUserWithEmailAndPassword
03-27 10:24:19.454 15917 16174 W System  : Ignoring header X-Firebase-Locale because its value was null.
03-27 10:24:20.267 15917 15917 E Auth    : createUserWithEmailAndPassword:onComplete:failure
03-27 10:24:20.267 15917 15917 E Auth    : com.google.firebase.auth.FirebaseAuthUserCollisionException: The email address is already in use by another account.
03-27 10:24:20.267 15917 15917 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzth.zza(com.google.firebase:firebase-auth@@21.0.2:25)
03-27 10:24:20.267 15917 15917 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzuf.zza(com.google.firebase:firebase-auth@@21.0.2:9)
03-27 10:24:20.267 15917 15917 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzug.zzl(com.google.firebase:firebase-auth@@21.0.2:1)
03-27 10:24:20.267 15917 15917 E Auth    :      at com.google.android.gms.internal.firebase-auth-api.zzud.zzh(com.google.firebase:firebase-auth@@21.0.2:25)
```

The auth module here is not open source, so I can't pursue it further. All I know is that even if I give a useEmulator call verified correct arguments, and give it ample time to execute (in case it is async) it simply is not taking effect, and I don't know why.

It works perfectly with bom 29.1.0, fails on 29.2.0 and 29.2.1

**Comment by mikehardy** [comment] 2022-03-27 15:31
Just in case you have a local environment with node v16+ installed and `yarn` (a possibility, since functions uses it?) it is possible to set up our full e2e test harness following this doc: https://github.com/invertase/react-native-firebase/blob/main/tests/README.md

Believe it or not, it's actually not too bad to set up, maybe just the work of 10 minutes or so, then you'll have a reproduction.
You may focus in the testing to a reproduction that works in about 1-2 seconds per execution by changing the `describe` right here to `describe.only`: https://github.com/invertase/react-native-firebase/blob/ef7895cd49eed3a4d103df624e52315250c68ab3/packages/auth/e2e/auth.e2e.js#L26

**Comment by rosalyntan** [comment] 2022-03-29 05:57
Hi @mikehardy -- I tried setting up an environment to run the React Native e2e tests, and am running into some trouble.

After running `yarn tests:android:test` with the `describe.only` change, I get:
```
rosalyntan-macbookpro3:react-native-firebase rosalyntan$ yarn tests:android:test
yarn run v1.22.18
$ cd tests && yarn detox test --configuration android.emu.debug
$ /Users/rosalyntan/react-native-firebase/tests/node_modules/.bin/detox test --configuration android.emu.debug
22:51:44.691 detox[53003] INFO:  [test.js] mocha --config e2e/.mocharc.js --configuration android.emu.debug --grep :ios: --invert --use-custom-logger true e2e
22:51:45.707 detox[53004] ERROR: at node_modules/mocha/lib/cli/run.js:376:13 
 
Error: Cannot find module '../../../.github/workflows/scripts/functions/lib/sample-data'
Require stack:
- /Users/rosalyntan/react-native-firebase/packages/functions/e2e/functions.e2e.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/rosalyntan/react-native-firebase/packages/functions/e2e/functions.e2e.js:18:21)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/Users/rosalyntan/react-native-firebase/tests/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/Users/rosalyntan/react-native-firebase/tests/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/Users/rosalyntan/react-native-firebase/tests/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/Users/rosalyntan/react-native-firebase/tests/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/rosalyntan/react-native-firebase/tests/node_modules/mocha/lib/cli/run.js:374:5)
22:51:45.727 detox[53003] ERROR: [cli.js] Command failed: mocha --config e2e/.mocharc.js --configuration android.emu.debug --grep :ios: --invert --use-custom-logger true e2e

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is the Firestore emulator necessary for the Android tests to run? I also got an error when running `yarn tests:emulator:start`.


On a separate note, Firebase Android 29.3.0 was released on March 24 -- can you check to see if that fixes anything? I'm not confident it will make a difference, but it's worth a shot.

**Comment by mikehardy** [comment] 2022-03-29 11:25
I have seen that error before but couldn't reproduce, i wonder if it's an assumption about cwd for the yarn script execution? I think this is something different regardless if you alter the auth e2e to be describe.only it won't run the functions test so those helpers will be skipped

This is all about the emulator connection though so if emulator startup had an issue it may be important to solve it

I'll see if I can reproduce this sample data thing and I will test the new SDK release

I appreciate the effort to get the rnfb e2e rig working, sorry it wasn't seemless, it's supposed to be a good new contribution experience so I'll do my best to iron it out

**Comment by mikehardy** [comment] 2022-03-29 12:45
I checked out react-native-firebase, specifically on the branch `@mikehardy/dependency-updates` into a clean / temp directory like this after starting an android emulator and it worked:

```bash
mkdir temp
cd temp
git clone git@github.com:invertase/react-native-firebase
cd react-native-firebase
git checkout @mikehardy/dependency-updates
yarn
yarn tests:andoid:build
yarn tests:emulator:start // <-- this consumes the Terminal, so open another terminal and cd into react-native-firebase dir
yarn tests:packager:jet // <-- consumes the Terminal, open new Terminal cd into react-native-firebase dir
adb reverse tcp:8081 tcp:8081 // <-- may not be necessary? I need it for android31 emulator, but react-native should handle it
yarn tests:android:test
```

of course worked just means I reproduced the error, but...that all worked for me as documented 🤔 

I also tried firebase-android-sdk 29.3.0 and it is not correctly using the auth emulator either (double 🤔 )

Our CI script is perhaps a separate way of completely specifying exactly how we run the e2e setup (successfully) since all versions of everything are available via reference or direct specification, and all steps are explicitly listed: https://github.com/invertase/react-native-firebase/blob/main/.github/workflows/tests_e2e_android.yml

**Comment by mikehardy** [comment] 2022-03-29 13:34
Oh! I finally connected the dots. Your emulator startup failure is linked to the test execution failure.
How? Not sure exactly how the emulator startup errored, but the emulator startup process *also* builds the local functions that we use inside the emulator to test.
They are in typescript, and the emulator-functions build installs yarn modules inside the emulator-functions package, and then does a typescript compile, which is *how* the `lib/sample-data` comes to exist, otherwise it's still in `src/...`

The emulator-functions build before firebase emulator startup:
https://github.com/invertase/react-native-firebase/blob/ef7895cd49eed3a4d103df624e52315250c68ab3/.github/workflows/scripts/start-firebase-emulator.sh#L13-L14

The typescript compile, run by that build:
https://github.com/invertase/react-native-firebase/blob/ef7895cd49eed3a4d103df624e52315250c68ab3/.github/workflows/scripts/functions/package.json#L4

The sample data that *should* then be compiled (via tsc) from src to lib:
https://github.com/invertase/react-native-firebase/blob/main/.github/workflows/scripts/functions/src/sample-data.ts

So, something about that isn't working but not sure what.

Also, if the `describe.only` change "took", then it shouldn't have run the functions tests anyway, so that's odd, but perhaps it's just part of the initial bundle build for it to spider out and reference all dependencies, unknown.

An alternative way to "focus" the testing down to just auth and remove reference to functions at all is to edit this file and comment out all the e2e test directory entries except the one for auth:
https://github.com/invertase/react-native-firebase/blob/ef7895cd49eed3a4d103df624e52315250c68ab3/tests/e2e/.mocharc.js#L18

**Comment by rosalyntan** [comment] 2022-04-25 23:14
Hi @mikehardy -- a fix for this issue should be included in the next release. Please re-open this issue if you still experience this!

**Comment by mikehardy** [comment] 2022-04-25 23:43
Wait wait! You mean you reproduced it :-)! Because I was literally just starting to lay issue reproduction tools out on the workbench last evening and was going to take it up again this evening. I definitely still see it now but of course you haven't had a release yet, so that makes sense if you fixed. Great news! This has been vexing me as it stops us from moving up to releases that include a firestore offline/online reconnection issue. Thanks @rosalyntan

**Comment by rosalyntan** [comment] 2022-05-10 20:43
Hi @mikehardy -- thank you for the update! Turns out that Firebase Auth was accidentally excluded from the 30.0.0 release. I'm working with the release team to get a new BoM version out that will have the new Firebase Auth version with the fix and will update here when it is published.

**Comment by mikehardy** [comment] 2022-05-10 20:46
I have to tell you, that's a relief, I am starting to doubt myself here on ability to test or reproduce anything 😅 
I'll stay tuned, thanks!

**Comment by rosalyntan** [comment] 2022-05-13 16:56
Hi @mikehardy -- the Firebase BoM 30.0.1 was published this morning and should contain the auth fix 🤞  Please let me know if there are any more issues!

**Closed by rosalyntan** 2022-05-13 16:56 UTC
Labels: api: auth, needs-attention, internal-bug-filed

**Comment by mikehardy** [comment] 2022-05-13 18:48
@rosalyntan It is a thing of beauty!

```

 Running "testing" with {"rootTag":1}
  auth()
    namespace
      ✔ accessible from firebase.app()
      ✔ supports multiple apps
    applyActionCode()
      - works as expected
      ✔ errors on invalid code
    checkActionCode()
      ✔ errors on invalid code
    reload()
      ✔ Meta data returns as expected with annonymous sign in (2144ms)
      ✔ Meta data returns as expected with email and password sign in (1110ms)
    confirmPasswordReset()
      ✔ errors on invalid code via API
    signInWithCustomToken()
      - signs in with a admin sdk created custom auth token
    onAuthStateChanged()
      - calls callback with the current user and when auth state changes
      ✔ accept observer instead callback as well (1627ms)
      ✔ stops listening when unsubscribed (2192ms)
      ✔ returns the same user with multiple subscribers #1815 (3146ms)
    onIdTokenChanged()
      ✔ calls callback with the current user and when auth state changes (1594ms)
      ✔ stops listening when unsubscribed (2214ms)
      ✔ listens to a null user when auth result is not defined
    onUserChanged()
      ✔ calls callback with the current user and when auth state changes (2111ms)
      ✔ stops listening when unsubscribed (2161ms)
    signInAnonymously()
      ✔ it should sign in anonymously
    signInWithEmailAndPassword()
      ✔ it should login with email and password
      ✔ it should error on login if user is disabled
      ✔ it should error on login if password incorrect (1067ms)
      ✔ it should error on login if user not found (1074ms)
    signInWithCredential()
      ✔ it should login with email and password
      ✔ it should error on login if user is disabled
      ✔ it should error on login if password incorrect (1063ms)
      ✔ it should error on login if user not found (1067ms)
    createUserWithEmailAndPassword()
      ✔ it should create a user with an email and password
      ✔ it should error on create with invalid email
      ✔ it should error on create if email in use (1065ms)
      ✔ it should error on create if password weak (1065ms)
    fetchSignInMethodsForEmail()
      ✔ it should return password provider for an email address
      ✔ it should return an empty array for a not found email
      ✔ it should return an error for a bad email address
    signOut()
      ✔ it should reject signOut if no currentUser
    delete()
      ✔ should delete a user
    languageCode
      ✔ it should change the language code (1509ms)
    getRedirectResult()
      ✔ should throw an unsupported error
    setPersistence()
      ✔ should throw an unsupported error
    signInWithPopup
      ✔ should throw an unsupported error
    sendPasswordResetEmail()
      ✔ should not error (1085ms)
      ✔ should verify with valid code
      ✔ should fail to verify with invalid code (1075ms)
      ✔ should change password correctly OOB (1145ms)
      ✔ should change password correctly via API (1583ms)
    signInWithRedirect()
      ✔ should throw an unsupported error
    useDeviceLanguage()
      ✔ should throw an unsupported error
    useUserAccessGroup()
      ✔ should return "null" when accessing a group that exists
      ✔ should throw when requesting an inaccessible group
    setTenantId()
      ✔ should return null if tenantId unset

13:47:54.184 detox[7740] INFO:  at e2e/init.js:55:11 
  ✨ Tests Complete ✨ 
13:47:54.603 detox[7740] INFO:  at e2e/init.js:77:15 
 Coverage data downloaded to: ./android/app/build/output/coverage//emulator_coverage.ec

  47 passing (55s)
  3 pending

✨  Done in 56.74s.
```

Thank you!
