### ISSUE TITLE
Crashlytics custom key not being set as expected

### ISSUE THREAD

**Issue by spectrl** [firebase/firebase-android-sdk#6341] opened 2024-10-03 11:56 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Ladybug
  * Firebase Component: Crashlytics
  * Component version: 33.3.0

### [REQUIRED] Step 3: Describe the problem

I'm trying to set a custom key temporarily per recorded log/exception and I'd expect the tag I have set prior to calling `log` or `recordException` to be present in the dashboard as I "send" (I know they get queued) the event immediately after setting the tag, but _before_ unsetting it. However the custom key that does actually get set is the empty string one "" (see screenshot).

The docs suggest this should not be the case:
> Sets a custom key and value that are associated with subsequent fatal, non-fatal, and ANR reports. Multiple calls to this method with the same key update the value for that key. The value of any key at the time of a fatal, non-fatal, or ANR event is associated with that event.

Is there a way to get this to work or is it inherently asynchronous somewhere?

#### Steps to reproduce: 

Run the code below.

#### Relevant Code:

```
val crashlytics = Firebase.crashlytics
val tagKey = "tag"
try {
    val logTag = "Some temporary tag"
    crashlytics.setCustomKey(tagKey, logTag)
    crashlytics.log(message)
    crashlytics.recordException(throwable)
} finally {
    crashlytics.setCustomKey(tagKey, "")
}
```

**Comment by lehcar09** [comment] 2024-10-08 11:22
Hi @spectrl, thank you for reaching out and reporting the issue. I was able to reproduce the issue in the Firebase SDK version BOM 33.3.0 you're using. 

However, the issue is fixed in the latest Firebase SDK version [BOM 33.4.0](https://firebase.google.com/support/release-notes/android#crashlytics_v19-2-0). Upon checking, with the code snippet you shared, the value `Some temporary tag` of custom key `tag` was retained even after setting the value to blank. Please update to the latest SDK version to get the latest improvements and fix that might be causing the issue.

That said, I’ll be closing the issue now. Let me know if there’s any misunderstanding or we need to reopen the issue for further investigation. Thanks!

**Closed by lehcar09** 2024-10-08 11:22 UTC
Labels: api: crashlytics
