### ISSUE TITLE
[Bug] InAppMessaging ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Nyankoo** [firebase/firebase-android-sdk#2509] opened 2021-03-02 20:32 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.21f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: InAppMessaging
  * Other Firebase Components in use: Firestore, Analytics, Crashlytics, Remote Config
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Some of our users getting crashes caused by the InAppMessaging package. When this is happening is currently unknown to us, as we can't replicate this on our end.

The devices the crashes happen on are:
- Huawei P10 lite (Android 8.0.0)
- Samsung Galaxy A51 (Android 10)
- Samsung Galaxy A5(2017) (Android 8.0.0)
- Samsung Galaxy Galaxy S7 (Android 8.0.0)
- Samsung Galaxy Note10 Lite (Android 11)
- Samsung Galaxy A50 (Android 10)
- Samsung Galaxy A21s (Android 10)
- Samsung Galaxy J8 (Android 10)
- Samsung Galaxy S8+ (Android 9)
- Samsung Galaxy A10 (Android 10)
- Xperia 1 II (Android 11)
- Xperia L3 (Android 8.1.0)
- Redmi 8 (Android 9)
- ZTE Blade 10 Vita (Android 9)
- Amazon Fire HD (Android 9)
- Moto C Plus (Android 7.0)
- LG Stylo 5 (Android 10)
- vivo 1904 (Android 9)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What happened? How can we make the problem occur?

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
       at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:507)
       at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
       at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
       at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
       at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:90)
       at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:104)
       at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
       at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:395)
       at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:403)
       at com.google.firebase.inappmessaging.CampaignAnalytics$Builder.setClientApp(CampaignAnalytics.java:1049)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.createCampaignAnalyticsBuilder(MetricsLoggerClient.java:193)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.createEventEntry(MetricsLoggerClient.java:170)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.lambda$logMessageClick$1(MetricsLoggerClient.java:126)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient$$Lambda$2.onSuccess(:6)
       at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by vimanyu** [comment] 2021-03-16 01:25
Moving this issue to firebase-android-sdk as this seems like something not caused by the C++/Unity layer. We haven't been able to reproduce this issue locally but we should keep an eye out for this just incase there are more occurrences. User pointed out it could be related to https://github.com/firebase/firebase-android-sdk/issues/2158 and I have confirmed that we are using the libraries with versions which should have the fix for that issue.

Something that could be related as per internal discussions is,
b/169066309

**Comment by Nyankoo** [comment] 2021-03-31 14:49
Any update on this?

**Comment by Nyankoo** [comment] 2021-05-08 22:15
@vimanyu @aguatno

**Comment by Nyankoo** [comment] 2021-05-10 19:38
@vimanyu @var-const This happened to a majority of our users and we needed to pull the plug by disabling all In-App Messaging setups in the Firebase Dashboard. Since then, we didn't try again.

**Comment by Nyankoo** [comment] 2021-07-07 18:06
@vimanyu @var-const @schmidt-sebastian Any update on this?

**Closed** 2024-10-30 20:06 UTC
Labels: api: inappmessaging
