### ISSUE TITLE
FirebaseModelDownloader throws 403 error with API Keys that have app restrictions

### ISSUE THREAD

**Issue by kabeer-uber** [firebase/firebase-android-sdk#2647] opened 2021-05-07 01:56 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.3
  * Firebase Component: FirebaseModelDownloader
  * Component version: 23.0.0

### [REQUIRED] Step 3: Describe the problem

getModel() with FirebaseModelDownloader throws a 403 error with Google API keys that have android app restrictions.

#### Steps to reproduce:

Create any project and add android app restrictions, use this API key with the FirebaseModelDownloader project to trigger ML model downlaods

![Screen Shot 2021-05-06 at 6 48 29 PM](https://user-images.githubusercontent.com/21314710/117386430-c00a5a80-ae9b-11eb-8f3c-3fc7b0a89c1f.png)

API keys without android app restrictions work, hence changing to None does not throw a 403 error.

![Screen Shot 2021-05-06 at 6 41 50 PM](https://user-images.githubusercontent.com/21314710/117386171-44a8a900-ae9b-11eb-8cdc-29388db19f35.png)

#### Relevant Code:

Code culprit is here as we aren't adding **X-Android-Package** and **X-Android-Cert** in the headers and adding only API key.

https://github.com/firebase/firebase-android-sdk/blob/976ea2fb443bbf7b5828f988275110b6b3b4b281/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java#L170

```
 @NonNull
  public Task<CustomModel> getCustomModelDetails(
      String projectNumber, String modelName, String modelHash) {
    try {
      URL url =
          new URL(String.format(DOWNLOAD_MODEL_REGEX, downloadHost, projectNumber, modelName));
      HttpURLConnection connection = (HttpURLConnection) url.openConnection();
      connection.setConnectTimeout(CONNECTION_TIME_OUT_MS);
      connection.setRequestProperty(ACCEPT_ENCODING_HEADER_KEY, GZIP_CONTENT_ENCODING);
      connection.setRequestProperty(CONTENT_TYPE, APPLICATION_JSON);
      if (modelHash != null && !modelHash.isEmpty()) {
        connection.setRequestProperty(IF_NONE_MATCH_HEADER_KEY, modelHash);
      }

      Task<InstallationTokenResult> installationAuthTokenTask =
          firebaseInstallations.getToken(false);
      return installationAuthTokenTask.continueWithTask(
          executorService,
          (CustomModelTask) -> {
            if (!installationAuthTokenTask.isSuccessful()) {
              ErrorCode errorCode = ErrorCode.MODEL_INFO_DOWNLOAD_CONNECTION_FAILED;
              String errorMessage = "Failed to get model due to authentication error";
              int exceptionCode = FirebaseMlException.UNAUTHENTICATED;
              if (installationAuthTokenTask.getException() != null
                  && (installationAuthTokenTask.getException() instanceof UnknownHostException
                      || installationAuthTokenTask.getException().getCause()
                          instanceof UnknownHostException)) {
                errorCode = ErrorCode.NO_NETWORK_CONNECTION;
                errorMessage = "Failed to retrieve model info due to no internet connection.";
                exceptionCode = FirebaseMlException.NO_NETWORK_CONNECTION;
              }
              eventLogger.logDownloadFailureWithReason(
                  new CustomModel(modelName, modelHash, 0, 0L), false, errorCode.getValue());
              return Tasks.forException(new FirebaseMlException(errorMessage, exceptionCode));
            }

            connection.setRequestProperty(
                INSTALLATIONS_AUTH_TOKEN_HEADER, installationAuthTokenTask.getResult().getToken());
            connection.setRequestProperty(API_KEY_HEADER, apiKey);
            return fetchDownloadDetails(modelName, connection);
          });

    } catch (IOException e) {
      eventLogger.logDownloadFailureWithReason(
          new CustomModel(modelName, modelHash, 0, 0L),
          false,
          ErrorCode.MODEL_INFO_DOWNLOAD_CONNECTION_FAILED.getValue());

      return Tasks.forException(
          new FirebaseMlException(
              "Error reading custom model from download service: " + e.getMessage(),
              FirebaseMlException.INVALID_ARGUMENT));
    }
  }
```

**Comment by aguatno** [comment] 2021-05-10 17:49
Hi @kabeer-uber thanks for reporting. Currently I wasn't able to reproduce the issue, could you help me? If you would be able to provide runnable sample code that would be great for the team.

**Comment by kabeer-uber** [comment] 2021-05-10 23:37
@aguatno I have pushed the code of the app here
https://github.com/kabeer-uber/firebase-ml-bug-2647

The code is pretty straightforward

```
        FirebaseApp.initializeApp(this)

        FirebaseModelDownloader.getInstance()
                .getModel("mv2_50_e47_q_v4_fix", DownloadType.LOCAL_MODEL_UPDATE_IN_BACKGROUND, CustomModelDownloadConditions.Builder().build())
                .addOnSuccessListener { model -> // Download complete. Depending on your app, you could enable the ML
                    Log.d(TAG, "onSuccess() called with: model = $model")
                }
                .addOnFailureListener { failure ->
                    Log.d(TAG, "onFailure() called with: failure = $failure")
                }
```

Please note the real issue is when you run this code with API Key restrictions such as shown below.

![image](https://user-images.githubusercontent.com/21314710/117737122-03bbd780-b1ae-11eb-8d6c-80f7993559b7.png)

**Comment by aguatno** [comment] 2021-09-13 17:54
Hi @kabeer-uber sorry for getting back late. Our engineers are still looking for potential solution and we are doing anything what we can, but I can't make any promises as to when this will be fixed.  We'll reach out to you as soon as there is an update on it. Internal Reference Bug#189321212.

**Comment by argzdev** [comment] 2023-01-18 14:34
Closing since this has already been merged. Thanks!

**Closed by argzdev** 2023-01-18 14:34 UTC
Labels: api: mlkit, internal-bug-filed
