### ISSUE TITLE
NullPointerException in Firebase AndroidConnectivityMonitor

### ISSUE THREAD

**Issue by brettwillis** [firebase/firebase-android-sdk#338] opened 2019-04-08 08:52 UTC
* Android Studio version: 3.3.2
  * Firebase Component: Firestore
  * Component version: 18.1.0
  * Android version: 9

I detected a crash in production code today:

    Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.firebase.firestore.g.j.accept(java.lang.Object)' on a null object reference
       at com.google.firebase.firestore.remote.AndroidConnectivityMonitor$DefaultNetworkCallback.onAvailable(AndroidConnectivityMonitor.java:103)
       at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3115)
       at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:3314)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by samtstern** [comment] 2019-04-08 13:25
@brettwillis thanks for reporting this.  It looks like your code is proguarded `com.google.firebase.firestore.g.j` ... do you know what method that corresponds to when it's not obfuscated?

**Comment by rsgowman** [comment] 2019-04-08 14:49
I think it must be c.g.f.f.util.Consumer. Here's the line of the crash:

https://github.com/firebase/firebase-android-sdk/blob/410feec24b64c86fa64b22a2300810dc6b9fce44/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AndroidConnectivityMonitor.java#L103

The only spot the callback list is populated is here:

https://github.com/firebase/firebase-android-sdk/blob/410feec24b64c86fa64b22a2300810dc6b9fce44/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java#L210

It doesn't seem possible that this would be null though...?

As a workaround, we could add a null check on AndroidConnectivityMonitor.java around line 103 to avoid the null pointer exception, but I'd be very curious to know how a null was getting in there in the first place.

@brettwillis, are you able to reproduce this issue? If not, do you know what conditions lead to this? (Based on the code path, this seems to be happening when the device is coming back online.)

**Comment by rsgowman** [comment] 2019-04-08 20:33
I don't know if this is the root cause or not, but if we assume this is a parallelism issue, then we have a potential fix: https://github.com/firebase/firebase-android-sdk/pull/341

It should go out in the next release.

For now, I'm going to close this issue, but if you have a way to reliably reproduce this issue, we'd still like to hear about it to ensure the issue you encountered is indeed fixed by #341.

**Closed by rsgowman** 2019-04-08 20:33 UTC
Labels: api: firestore, type: bug

**Comment by brettwillis** [comment] 2019-04-08 22:51
Unfortunately I cannot reproduce the issue. I have never seen it myself to know the conditions under which it happened. This was a report from Firebase Crashlytics in a production app.

The only extra information in the report was that the app was in a background state.

I'll monitor the issue after updating once this parallelism fix comes through.

Thanks for your support!
