### ISSUE TITLE
first_open events not being sent after initialization

### ISSUE THREAD

**Issue by Anooxi** [firebase/firebase-android-sdk#6049] opened 2024-06-19 14:04 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2023.3.1 patch 1
  * Firebase Component:  analytics, dynamic links, remote config
  * Component version:  bom 32.8.1

### [REQUIRED] Step 3: Describe the problem

Hello everyone,
we are using react-native-firebase/analytics for our react-native application. We updated recently to account for the changes of consent, however we found that our Android application no longer sends first_open events, it is the only event that has an anomaly in both of our apps.

After asking the question initially in here https://github.com/invertase/react-native-firebase/issues/7829, I got redirected to this repo

#### Steps to reproduce:

Set Analytics to disabled before consent is accepter -> enable analytics when consent is accepted -> no first_open event is sent -> other events are fine

#### Relevant Code:

You can find the analytics android library code here: https://github.com/invertase/react-native-firebase/tree/main/packages/analytics/android

and there is also more information on my original issue https://github.com/invertase/react-native-firebase/issues/7829

**Comment by lehcar09** [comment] 2024-06-19 16:00
Hi @Anooxi, thank you for reaching out. The behavior you're experiencing is working as intended. The consent is not applied retroactively. The first_open event is collected before the user grants the consent. The events (i.e. first_open/ session_start) collected before the consent is granted would not have some fields like DSID and app instance ID that subsequent events would have, due to consent being denied. 

That being said, I'll be closing this issue now. Let me know if there's any misunderstanding and we need to re-open the for further investigation. Thanks!

**Closed by lehcar09** 2024-06-19 16:00 UTC
Labels: api: analytics
