### ISSUE TITLE
Firebase Messaging issue in Android 12

### ISSUE THREAD

**Issue by liqiang1995** [firebase/firebase-android-sdk#3115] opened 2021-11-09 15:59 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2020.3.1 Patch 3 (Arctic Fox)
  * Firebase Component: firebase-messaging
  * Component version: 23.0.0

### [REQUIRED] Step 3: Describe the problem
I got many crashes from firebase crashytics.

Fatal Exception: java.lang.IllegalArgumentException: com.mcassemblies.AndroidToolbox: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
       at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
       at android.app.PendingIntent.getActivity(PendingIntent.java:444)
       at android.app.PendingIntent.getActivity(PendingIntent.java:408)
       at com.google.firebase.messaging.CommonNotificationBuilder.createContentIntent(CommonNotificationBuilder.java:125)
       at com.google.firebase.messaging.CommonNotificationBuilder.createNotificationInfo(CommonNotificationBuilder.java:27)
       at com.google.firebase.messaging.CommonNotificationBuilder.createNotificationInfo(CommonNotificationBuilder.java:9)
       at com.google.firebase.messaging.DisplayNotification.handleNotification(DisplayNotification.java:27)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:65)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:44)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:27)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:17)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:43)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(EnhancedIntentService.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:920)

How can I fix this?
Thank you.

**Comment by argzdev** [comment] 2021-11-09 16:20
Hi @liqiang1995, thanks for reporting. I'll try to investigate this and see what I could find. Meanwhile, could you share me steps to reproduce the issue, and any relevant code that encounters this issue? If it's possible to provide us a minimal repro, that'll greatly help us investigating this further.

**Comment by argzdev** [comment] 2021-11-09 16:52
If you're sending notifications, could you try checking the solution on this [link](https://stackoverflow.com/questions/67045607/how-to-resolve-missing-pendingintent-mutability-flag-lint-warning-in-android-a), and see if it helps? Thanks.

**Comment by liqiang1995** [comment] 2021-11-10 03:15
My target SDK is 31.
I could not replicate the issue, but I got this issue many times from firebase crashytics.
I think the firebase needs to fix this issue.
Please use PendingIntent.FLAG_IMMUTABLE in the firebase messaging SDK.
Thank you.

**Comment by argzdev** [comment] 2021-11-12 14:15
Hi @liqiang1995, I wasn't able to replicate the issue as well. Just to isolate the issue, are you using any PendingIntents in your app? or WorkManager?

**Comment by liqiang1995** [comment] 2021-11-12 14:29
![image](https://user-images.githubusercontent.com/54995513/141482763-0b1e27a0-0490-4abd-9e78-eed24199904f.png)
This error appears in only Android 12.
Please see the screenshot. It says firebase messaging has a problem.
Thank you.

**Comment by argzdev** [comment] 2021-11-12 15:04
I thought so as well. Thanks for confirming, We'll continue investigating.

**Comment by argzdev** [comment] 2021-11-12 15:32
Hi @liqiang1995, it looks like the code fix has been [implemented](https://github.com/firebase/firebase-android-sdk/blob/fe6475688d2a00c266f82a44005f1ac045eb729c/firebase-messaging/src/main/java/com/google/firebase/messaging/CommonNotificationBuilder.java#L539) in the repository. With that said, I can't provide any specific timeline as to when this fix will be released, but you may check out our release notes and official blog from time to time to get to know the latest features and bug fixes that we have for Firebase. If you have any other questions feel free to ask, thanks!

**Comment by argzdev** [comment] 2021-11-18 09:10
Since the fixed has been implemented, and we're waiting for the release. I'll be closing this ticket for now. Thanks!

**Closed by argzdev** 2021-11-18 09:10 UTC
Labels: api: messaging
