### ISSUE TITLE
IllegalStateException FirebaseCrashlytics.getInstance

### ISSUE THREAD

**Issue by ShivamPokhriyal** [firebase/firebase-android-sdk#1766] opened 2020-07-08 13:19 UTC
We recently migrated from Fabric to FirebaseCrashlytics and started seeing IllegalStateExceptions. 

Copying over the stacktrace from play console.  
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5929)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:209)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1681)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6724)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911)
Caused by: java.lang.IllegalStateException: 
  at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java:184)
  at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance (FirebaseCrashlytics.java:112)
  at <package_name>.CustomApplication.onCreate (CommCareApplication.java:195)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1154)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5924)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:209)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1681)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6724)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911)
```

This crash appears to be only happening for a particular device. 
```
Blackview BV5500Pro (Android 9)
```

I don't have any more details, neither do I have that device to test it out. So posting it here, if someone else also notices the issue on the same device or some other devices as well.

**Comment by janbolat** [comment] 2020-07-13 18:42
Same problem. Seeing tons of `java.lang.IllegalStateException` crashes on Google Play Console. This started happening recently after migrating to Crashlytics on all Android versions (6, 7, 8, 9, 10).

Using:
```
 implementation 'com.google.firebase:firebase-crashlytics:17.1.1'
 classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
```

Initializing in Application class:
`FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(BuildConfig.ENABLE_CRASHLYTICS); // true in release`

AndroidManifest:
`<meta-data android:name="firebase_crashlytics_collection_enabled" android:value="false" />`

Stacktrace on Android 8.0:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6637)
  at android.app.ActivityThread.-wrap2 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2066)
  at android.os.Handler.dispatchMessage (Handler.java:108)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7529)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
Caused by: java.lang.IllegalStateException: 
  at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java:184)
  at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance (FirebaseCrashlytics.java:229)
  at ***.App.initLibraries (App.java:93)
  at ***.App.onCreate (App.java:67)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1122)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6619)
  at android.app.ActivityThread.-wrap2 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2066)
  at android.os.Handler.dispatchMessage (Handler.java:108)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7529)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
```

**Comment by janbolat** [comment] 2020-07-13 18:46
@ashwinraghav @vkryachko @schmidt-sebastian please take a look

**Comment by vkryachko** [comment] 2020-07-13 19:11
Hey @janbolat @ShivamPokhriyal 

Looks like the exception is most likely thrown in this code block:
https://github.com/firebase/firebase-android-sdk/blob/8d864be70b245f46aac1730d27d7043740efe038/firebase-common/src/main/java/com/google/firebase/FirebaseApp.java#L181-L186

Can you verify if you have `google-services` plugin correctly configured in your app and that `FirebaseInitProvider` is in your manifest and is actually called(this is what initializes default FirebaseApp).

**Comment by janbolat** [comment] 2020-07-13 19:28
There shouldn't be a problem with `google-services`. 
How can it be related to a process issue if the it is a single process app? 
This crash is happening on user devices (my devices are fine), so I don't know exactly what is causing it. Can it be related to a direct boot issue? I have a few direct boot enabled components, therefore I initialize analytics&crashlytics only after user unlocks a device. But it wasn't an issue before. 

I will try to update with more information if I have. 

Thank you

**Comment by ShivamPokhriyal** [comment] 2020-07-14 06:06
> Can you verify if you have `google-services` plugin correctly configured in your app and that `FirebaseInitProvider` is in your manifest and is actually called(this is what initializes default FirebaseApp).

`google-services` is configured properly for me as well. And I don't have a `FirebaseInitProvider` in AndroidManifest explicitly. But it is present in the merged manifest so I think that should work right?

**Comment by vkryachko** [comment] 2020-07-14 16:14
@ShivamPokhriyal right, being present in the merged manifest is all that's needed, it does not need to be explicitly specified by your app.

**Comment by vkryachko** [comment] 2020-07-14 16:21
@janbolat 

> Can it be related to a direct boot issue (different context maybe)?

It actually does look like the issue. The default app does not initialize in direct boot mode as `FirebaseInitProvider` is not marked as `directBootAware`. So the result is that you're effectively calling `FirebaseCrashlytics.getInstance()` before the default `FirebaseApp` had a chance to initialize.

As a workaround I would suggest you try calling `FirebaseApp.initializeApp(getContext())` in your `onCreate` when in direct boot mode and please reply whether it fixes your issue.

@mrwillis21 Was `com.google.firebase:firebase-crashlytics:17.0.0-beta04` not part of component initialization yet, I am surprised that it was not affected by this.

**Comment by janbolat** [comment] 2020-07-14 17:40
@vkryachko I might be wrong about `com.google.firebase:firebase-crashlytics:17.0.0-beta04` because it was a different app with a small amount of users. 

So you suggest me to initialize Firebase in Application.onCreate() (as soon as it starts (even if it is in a direct boot mode), and then later when the device gets unlocked to initialize Crashlytics? If that is the case I will do so and let you know as soon as it gets published.

**Comment by vkryachko** [comment] 2020-07-14 17:44
@janbolat The suggestion to initialize in `onCreate` is based on the stacktrace in the original comment, but I just realized that it's not yours but rather it's @ShivamPokhriyal .

`initializeApp` does not have to be called in onCreate specifically, but **must** be called *before* you call into any firebase library.

**Comment by janbolat** [comment] 2020-07-14 17:47
@vkryachko Ok then the only thing I will do is explicitly call `initializeApp` before initializing Crashlytics (after device gets unlocked). Am I right?

**Comment by mrwillis21** [comment] 2020-07-14 20:26
@vkryachko No, FirebaseCrashlytics has always used component initialization: https://github.com/firebase/firebase-android-sdk/blob/8f02834e94f8b24a7cf0f777562cad73c6b9a40f/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java

@janbolat I believe you're correct, but I'll defer to @vkryachko to confirm.

**Comment by kangaman2205** [comment] 2020-07-28 02:28
@vkryachko We are also seeing similar crash on Playstore after migrating from Fabric to Firebase Crashlytics SDK. The crash is currently occurring for 2 devices: LGE LG G8 ThinQ™, Xiaomi Mi A1.

Firebase dependencies in build.gradle files are as follows:
App-level build.gradle:
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.1.1'

Project level build.gradle:
implementation ('com.google.firebase:firebase-crashlytics:17.0.0@aar'){
        transitive = true;
}
 implementation ('com.google.firebase:firebase-crashlytics-ndk:17.0.0@aar'){
        transitive = true;
}

Stack trace:
java.lang.RuntimeException:
at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5911)
at android.app.ActivityThread.access$1100 (ActivityThread.java:200)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1660)
at android.os.Handler.dispatchMessage (Handler.java:106)
at android.os.Looper.loop (Looper.java:193)
at android.app.ActivityThread.main (ActivityThread.java:6762)
at java.lang.reflect.Method.invoke (Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException:
at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java:184)
at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance (FirebaseCrashlytics.java:112)

**Comment by vkryachko** [comment] 2020-07-29 13:20
@kangaman2205 Just to clarify, does it only affect a subset of users on those devices or is the crash deterministic on those devices?

**Comment by vkryachko** [comment] 2020-07-29 13:23
@kangaman2205 additionally, your stacktrace contains `FirebaseCrashlytics.getInstance`, knowing what circumstances you're calling it in would greatly help. Also, is your app a `multiprocess` one by any chance?

**Comment by kangaman2205** [comment] 2020-07-29 15:13
@vkryachko It is affecting a subset of users on these devices. Apart from the above mentioned devices, the crash can be seen today for around 20 -25 other device types as well including Samsung Galaxy series, Huawei, etc.

FirebaseCrashlytics.getInstance() is called from onCreate() of our Application class. And the app is not multiprocess.
Stack Trace:
Caused by: java.lang.IllegalStateException: 
  at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java:184)
  at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance (FirebaseCrashlytics.java:112)
  at <package name>.utils.ARCrashlyticsUtils.initCrashlytics (ARCrashlyticsUtils.java:50)
  at <package name>.ARApp.onMAMCreate (ARApp.java:273)
  at com.microsoft.intune.mam.client.app.MAMApplication$Impl.onCreatePrimaryProcess (MAMApplication.java:163)
  at com.microsoft.intune.mam.client.app.MAMApplication$Impl.onCreate (MAMApplication.java:128)
  at com.microsoft.intune.mam.client.app.MAMApplication.onCreate (MAMApplication.java:57)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1190)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6710)
  at android.app.ActivityThread.access$1300 (ActivityThread.java:226)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1898)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7615)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)

**Comment by doubleo2** [comment] 2020-07-30 12:20
I just ran into this issue and it was during Direct Boot. You can work around it by passing a device protected storage context to `FirebaseApp.initializeApp(Context)` as suggested by @vkryachko but it only works if you use a specialised Application subclass like the one described here - https://stackoverflow.com/a/51461338/44816

I think the underlying issue is that the DataCollectionConfigStorage constructor created a device protected storage context but failed to use that context to get the shared preferences. It looks like it has been fixed here - https://github.com/firebase/firebase-android-sdk/commit/ed1b4ef82273ee3ccdc47836edbf0b687cd36c9c#diff-f7708d795eeeabeebd204add65e2f945 - but the latest firebase-common release (v19.3.0, November 2019) doesn't include the fix. Once 19.3.1 is released, this should be fixed.

**Comment by kangaman2205** [comment] 2020-07-31 11:20
Thanks for the reply @doubleo2 . There are no components marked as Direct Boot aware in our app's manifest. Can this issue arise still in such case? Also, I could not find "firebase-common" dependency in the app. It will be really helpful if you can elaborate in which library the fix will be available.
These are the firebase dependencies we are using:
    implementation 'com.google.firebase:firebase-ml-vision:24.0.3'
    implementation 'com.google.firebase:firebase-messaging:20.2.1'
    implementation 'com.google.firebase:firebase-core:17.4.3'
    implementation 'com.google.firebase:firebase-perf:19.0.7
    implementation ('com.google.firebase:firebase-crashlytics:17.0.0@aar'){
        transitive = true;
    }
    implementation ('com.google.firebase:firebase-crashlytics-ndk:17.0.0@aar'){
        transitive = true;
    }
  classpath 'com.google.firebase:firebase-crashlytics-gradle:2.1.1'

**Comment by rosariopfernandes** [comment] 2020-07-31 12:23
@kangaman2205 `firebase-common` is an internal library which all the other firebase components (including crashlytics) depend on. You don't really need to reference this library in your app, since crashlytics already does it for you.

But I don't think a new version of firebase-common needs to be released for crashlytics to use it. I expect crashlytics to pull the latest `firebase-common` code from the main branch, since no version was specified in its dependencies:

https://github.com/firebase/firebase-android-sdk/blob/f1e32c1a2183cb8cb86bffa416f0c63cf8234966/firebase-crashlytics/firebase-crashlytics.gradle#L60

But this is just a guess. I'll let @vkryachko confirm.

**Comment by vkryachko** [comment] 2020-07-31 14:26
@kangaman2205 if your app is not direct boot aware then it's unlikely the issue you're facing, although without any more data on the crash I am unable to either reproduce or even think of how it could even happen, as direct boot is the only time firebase does not initialize automatically and instead only initializes upon device unlock.

@doubleo2 thanks for the details, we will release firebase-common in an upcoming release within a few weeks.
One word of caution though: most firebase SDKs don't have official direct boot support, so they may or may not work, the only SDK that supports directboot explicitly are `firebase-common` and `firebase-messaging-directboot`.

@rosariopfernandes a release is required as each sdk depends on a specific version of `firebase-common`.

**Comment by kangaman2205** [comment] 2020-08-02 14:17
Thanks for the information @vkryachko . One more thing that does not seem to add up is, that Direct boot aware feature was added in Android 7. But this crash is seen on Android 6 devices as well.

**Comment by kangaman2205** [comment] 2020-08-05 09:47
@vkryachko Any further information as to why this crash is occurring on Android 6 devices although Direct boot aware feature was introduced later?

**Comment by vkryachko** [comment] 2020-08-06 00:50
@kangaman2205 Unfortunately without any additional information on the circumstances of the crash and/or repro steps I can't tell what could be going. So I would need that to proceed.

**Comment by flymonkey00** [comment] 2020-08-06 03:13
Our app also got this issue, and one more thing is that in our case the crash most happened in Android 6 version and we also not support direct-boot mode so should not relate to direct-boot

**Closed** 2020-08-19 01:01 UTC
Labels: api: core, closed-by-bot, needs-info, no-recent-activity

**Comment by DJHoltkamp** [comment] 2020-09-11 14:19
I am still getting a crash occasionally on my logs from Firebase. This particular log is coming from Android 7

`java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2927)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2988)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1631)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
Caused by: java.lang.IllegalStateException: 
  at com.google.firebase.FirebaseApp.getInstance
  at com.google.firebase.iid.FirebaseInstanceId.getInstance
  at org.cocos2dx.cpp.AppActivity.onCreate (AppActivity.java:135)
  at android.app.Activity.performCreate (Activity.java:6942)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1126)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2880)`

What is the recommended fix for this?
