### ISSUE TITLE
NullPointerException in FirebaseInstallations.registerFidWithServer 

### ISSUE THREAD

**Issue by stari4ek** [firebase/firebase-android-sdk#1915] opened 2020-08-24 19:27 UTC
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio 4.1 RC 1
  * Firebase Component: firebase-installations
  * Component version: 16.3.2 (indirect dependencies. version is extracted from bundled `firebase-installations.properties`)

### [REQUIRED] Step 3: Describe the problem

Huge spike in crashes for Xiaomi MiBox S (Android 9) starting from Aug'24 for app's version which was released 3 weeks ago and no crashes before it

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:452)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:331)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doGetId$1(FirebaseInstallations.java:296)
       at com.google.firebase.installations.FirebaseInstallations$$Lambda$3.run(FirebaseInstallations.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

![image](https://user-images.githubusercontent.com/327778/91087248-d7c8e800-e658-11ea-9367-3a40d0a54898.png)

#### Steps to reproduce:

I'm seeing this issue in Crashlytics.
Can not reproduce it locally.

**Comment by ankitaj224** [comment] 2020-08-26 19:06
@stari4ek Thanks for reaching out. I am from the Firebase Installations team, this issue is a duplicate of #1787. 

Please update your app to depend on the latest version of firebase-installations(FIS) i.e com.google.firebase:firebase-installations:16.3.3 which contains the fix.

**Closed by ankitaj224** 2020-08-26 19:06 UTC
Labels: firebase-installations, needs-attention
