### ISSUE TITLE
Fetching of data from Firebase realtime database in some devices is not happening

### ISSUE THREAD

**Issue by Abhaykulshrestha13** [firebase/firebase-android-sdk#3436] opened 2022-02-11 13:46 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:  Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
Windows 10 10.0
  * Firebase Component: Database 
  * Component version: 20.0.3

### [REQUIRED] Step 3: Describe the problem
So the problem is related to fetching data from the real-time database in some devices. It is working in other devices properly but with some particular cellular providers like Vodafone the app is not fetching data from the firebase real-time database. I searched for this problem's solution on the internet but there's no solution for this.

**Comment by argzdev** [comment] 2022-02-11 14:03
Hi @Abhaykulshrestha13, thanks for reporting. Could you provide more details about your issue? Can you provide a code snippet or [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? Also how often do you experience this issue? Thanks

**Comment by Abhaykulshrestha13** [comment] 2022-02-13 11:06
[memoneet_logs.txt](https://github.com/firebase/firebase-android-sdk/files/8055393/memoneet_logs.txt)
I have attached the log of the app so that you can easily understand the problem from that.

This is the basic code example


                 FirebaseDatabase.getInstance().getReference("users/" + user.getUid())
                    .addListenerForSingleValueEvent(new ValueEventListener() {
                        @Override
                        public void onDataChange(@NonNull DataSnapshot dataSnapshot) {

                            UserDetails userDetails = dataSnapshot.getValue(UserDetails.class);
                            sharedPreferences.edit().putString(Constant.USER_ID, user.getUid()).apply();

                            if (userDetails != null) {
                                sharedPreferences.edit().putString(Constant.USER_NAME, userDetails.getFirst_name() + " " + userDetails.getLast_name()).apply();
                                sharedPreferences.edit().putString(Constant.USER_EMAIL, userDetails.getEmail_id()).apply();
                                sharedPreferences.edit().putString(Constant.USER_MOBILE, "+91" + userDetails.getMobile_number()).apply();
                                sharedPreferences.edit().putString(Constant.BATCH, userDetails.getBatch()).apply();
                                sharedPreferences.edit().putString(Constant.STATE, userDetails.getState()).apply();
                                sharedPreferences.edit().putString(Constant.PARENT_MOBILE_NUMBER, userDetails.getParent_mobile_number()).apply();
                                sharedPreferences.edit().putString(Constant.USER_IMAGE_URI, (user.getPhotoUrl() != null) ? user.getPhotoUrl().toString() : "").apply();
                                if (userDetails.getPayment_details() != null) {
                                    for (Map.Entry<String, Long> subjectPaid : userDetails.getPayment_details().entrySet()) {
                                        if (subjectPaid.getKey().equalsIgnoreCase(Constant.DATETIME)) {
                                            sharedPreferences.edit().putLong(subjectPaid.getKey(), subjectPaid.getValue()).apply();
                                        } else {
                                            sharedPreferences.edit().putBoolean(subjectPaid.getKey(), true).apply();
                                        }
                                    }
                                }

                                if (userDetails.getReferred_to() != null) {
                                    sharedPreferences.edit().putInt(Constant.NO_OF_REFERRALS, userDetails.getReferred_to().size()).apply();
                                }
                                if (userDetails.getReferral_payment() != null) {
                                    sharedPreferences.edit().putInt(Constant.REFERRAL_PAYMENTS, userDetails.getReferral_payment().size()).apply();
                                }
                                if (userDetails.getTeacher() != null) {
                                    sharedPreferences.edit().putBoolean(Constant.TEACHER, true).apply();
                                }
                                if (userDetails.getReferred_by() != null) {
                                    sharedPreferences.edit().putString(Constant.REFERRED_BY, userDetails.getReferred_by()).apply();
                                }
                                if (userDetails.getReferral_automate() != 0) {
                                    sharedPreferences.edit().putInt(Constant.REFERRAL_AUTOMATE, userDetails.getReferral_automate()).apply();
                                }

                                if (userDetails.getAds() != null) {
                                    sharedPreferences.edit().putBoolean(Constant.ADS, true).apply();
                                }

                            } else {
                                sharedPreferences.edit().putString(Constant.USER_NAME, user.getDisplayName()).apply();
                                sharedPreferences.edit().putString(Constant.USER_EMAIL, user.getEmail()).apply();
                                sharedPreferences.edit().putString(Constant.USER_MOBILE, user.getPhoneNumber()).apply();
                                sharedPreferences.edit().putString(Constant.USER_IMAGE_URI, (user.getPhotoUrl() != null) ? user.getPhotoUrl().toString() : "").apply();
                            }

**Comment by argzdev** [comment] 2022-02-14 13:37
Hi @Abhaykulshrestha13, thanks for the extra details. 

Just to clarify, when a Vodafone provider is being used, no data is being retrieved from Firebase RTDB at all?

Unfortunately, due to this issue requiring specific providers to be used, I'm unable to reproduce this issue. As for the logs, I don't see any lines referencing Firebase RTDB, could you specify where in the logs did the issue occur?

**Comment by Abhaykulshrestha13** [comment] 2022-02-15 10:03
Yeah, no data is retrieving from Firebase RTDB at all and hence no fetching of data is happening.
Firebase is not working at all with the Vodafone providers. If we are changing the network provider or if we are using wifi instead of Vodafone provider then it is working fine but with network providers like Vodafone, it's not working.

**Comment by argzdev** [comment] 2022-02-15 10:13
Thanks for clarifying, @Abhaykulshrestha13. For now, let's keep this ticket open in case our engineers might have an idea what the issue is. Feel free to add any questions or extra information. Thanks!

**Comment by argzdev** [comment] 2022-04-01 16:14
Hi @Abhaykulshrestha13, it looks like this issue was a network issue which was resolved a few days ago. That being said, the issue isn't on the SDK side. If you encounter this again, please contact [Firebase support](https://firebase.google.com/support), they'll be able to assist you better. I'll close this now. Thank you!

**Closed by argzdev** 2022-04-01 16:14 UTC
Labels: api: database
