### ISSUE TITLE
Firebase & Facebook crash in latest dep update?

### ISSUE THREAD

**Issue by ColtonIdle** [firebase/firebase-android-sdk#4599] opened 2023-01-26 19:47 UTC
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Giraffe Canary1
  * Firebase Component: BOM with 
  implementation("com.google.firebase:firebase-firestore-ktx")
  implementation("com.google.firebase:firebase-storage-ktx")
  implementation("com.google.firebase:firebase-analytics-ktx")
  implementation("com.google.firebase:firebase-auth-ktx")
  implementation("com.google.firebase:firebase-messaging-ktx")
  implementation("com.google.firebase:firebase-crashlytics-ktx")
  implementation("com.google.firebase:firebase-perf-ktx")
  implementation("com.google.firebase:firebase-functions-ktx")
  implementation("com.google.firebase:firebase-config-ktx")

#### Steps to reproduce:

I updated
com.google.firebase:firebase-bom:31.1.1

to 31.2.0

as well as facebook dep from
  implementation("com.facebook.android:facebook-login:15.1.0")
  implementation("com.facebook.android:facebook-android-sdk:15.1.0")

to 15.2.0

#### Relevant Code:

```
Stacktrace on launch == instant crash:

2023-01-26 14:39:15.673 11025-11050/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.rollertoaster.android.internal, PID: 11025
    java.lang.NoClassDefFoundError: com.google.firebase.perf.config.RemoteConfigManager
        at com.google.firebase.perf.config.ConfigResolver.<init>(ConfigResolver.java:78)
        at com.google.firebase.perf.config.ConfigResolver.getInstance(ConfigResolver.java:86)
        at com.google.firebase.perf.application.AppStateMonitor.<init>(AppStateMonitor.java:98)
        at com.google.firebase.perf.application.AppStateMonitor.getInstance(AppStateMonitor.java:87)
        at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.<init>(NetworkRequestMetricBuilder.java:92)
        at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.builder(NetworkRequestMetricBuilder.java:84)
        at com.google.firebase.perf.network.FirebasePerfUrlConnection.instrument(FirebasePerfUrlConnection.java:186)
        at com.facebook.GraphRequest$Companion.createConnection(GraphRequest.kt:1054)
        at com.facebook.GraphRequest$Companion.toHttpConnection(GraphRequest.kt:748)
        at com.facebook.GraphRequest$Companion.executeBatchAndWait(GraphRequest.kt:836)
        at com.facebook.GraphRequest$Companion.executeBatchAndWait(GraphRequest.kt:811)
        at com.facebook.GraphRequest$Companion.executeBatchAndWait(GraphRequest.kt:794)
        at com.facebook.GraphRequest$Companion.executeAndWait(GraphRequest.kt:772)
        at com.facebook.GraphRequest.executeAndWait(GraphRequest.kt:1456)
        at com.facebook.internal.FetchedAppGateKeepersManager.getAppGateKeepersQueryResponse(FetchedAppGateKeepersManager.kt:221)
        at com.facebook.internal.FetchedAppGateKeepersManager.loadAppGateKeepersAsync$lambda-0(FetchedAppGateKeepersManager.kt:98)
        at com.facebook.internal.FetchedAppGateKeepersManager.$r8$lambda$Tw9JXEbPRzoud2mdIxizp6VF2V0(Unknown Source:0)
        at com.facebook.internal.FetchedAppGateKeepersManager$$ExternalSyntheticLambda0.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.lang.ExceptionInInitializerError
        at com.google.firebase.perf.config.RemoteConfigManager.getInstance(RemoteConfigManager.java:119)
        at com.google.firebase.perf.config.ConfigResolver.<init>(ConfigResolver.java:78)
        at com.google.firebase.perf.config.ConfigResolver.getInstance(ConfigResolver.java:86)
        at com.google.firebase.perf.application.AppStateMonitor.<init>(AppStateMonitor.java:98)
        at com.google.firebase.perf.application.AppStateMonitor.getInstance(AppStateMonitor.java:87)
        at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.<init>(NetworkRequestMetricBuilder.java:92)
        at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.builder(NetworkRequestMetricBuilder.java:84)
        at com.google.firebase.perf.network.FirebasePerfUrlConnection.instrument(FirebasePerfUrlConnection.java:186)
        at com.facebook.GraphRequest$Companion.createConnection(GraphRequest.kt:1054)
        at com.facebook.GraphRequest$Companion.toHttpConnection(GraphRequest.kt:748)
        at com.facebook.GraphRequest$Companion.executeBatchAndWait(GraphRequest.kt:836)
        at com.facebook.GraphRequest$Companion.executeBatchAndWait(GraphRequest.kt:811)
        at com.facebook.GraphRequest$Companion.executeBatchAndWait(GraphRequest.kt:794)
        at com.facebook.GraphRequest$Companion.executeAndWait(GraphRequest.kt:772)
        at com.facebook.GraphRequest.executeAndWait(GraphRequest.kt:1456)
        at com.facebook.internal.FetchedAppSettingsManager.getAppSettingsQueryResponse(FetchedAppSettingsManager.kt:288)
        at com.facebook.internal.FetchedAppSettingsManager.queryAppSettings(FetchedAppSettingsManager.kt:209)
        at com.facebook.UserSettingsManager.initializeCodelessSetupEnabledAsync$lambda-0(UserSettingsManager.kt:129)
        at com.facebook.UserSettingsManager.$r8$lambda$aplsConLqG69UDRfnzXKr1cLNq4(Unknown Source:0)
        at com.facebook.UserSettingsManager$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
        at java.lang.Thread.run(Thread.java:1012) 
2023-01-26 14:39:15.674 11025-11050/? E/AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.rollertoaster.android.internal. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
        at com.google.firebase.perf.config.RemoteConfigManager.getInitialStartupMillis(RemoteConfigManager.java:91)
        at com.google.firebase.perf.config.RemoteConfigManager.<init>(RemoteConfigManager.java:85)
        at com.google.firebase.perf.config.RemoteConfigManager.<clinit>(RemoteConfigManager.java:52)
        	... 23 more
```

I'm currently investigating more, and will leave comments with anything i find

**Comment by ColtonIdle** [comment] 2023-01-26 19:51
If I rollback facebook dep, no change. I still crash. 

If I rollback firebase BOM, then everything is good again. no crashing 😄 

looks like a firebase issue?

**Comment by argzdev** [comment] 2023-01-27 10:08
Thanks for reporting, @ColtonIdle. Might be an issue with Firebase Performance. Any code snippet or minimal repro you could share with us? I'm currently unable to reproduce this with the given dependencies.

**Comment by GianfrancoMS** [comment] 2023-01-27 21:21
Same issue with Firebase Performance 20.3.0

**Comment by ColtonIdle** [comment] 2023-02-03 03:28
@argzdev sorry. I haven't been able to come with any sort of a minimal repro. I'm going to give updating all my deps another try in the next day or so to see where we net out (crash or no crash)

**Comment by ratm** [comment] 2023-02-17 19:58
Same issue with BOM 31.2.2

**Comment by Hooooong** [comment] 2023-03-06 10:24
Same issue with BOM 31.2.3

**Comment by vramvoskanyan** [comment] 2023-03-20 06:25
Still exists on BOM 31.2.3

**Comment by vramvoskanyan** [comment] 2023-03-20 11:43
We found the crash reason, 
actually, we had an "AddTrace" annotation on the application's onCreate function, which sometimes calls before Firebase Performance initialization. 

However, these issues started to fire from the 31.2.0 version.

ApplicationClass
```
  @Override
  @AddTrace(name = "application_oncreate") // from com.google.firebase.perf.metrics
  public void onCreate() {
```

Crash log was:
```
Exception java.lang.ExceptionInInitializerError:
  at com.google.firebase.perf.config.RemoteConfigManager.getInstance (RemoteConfigManager.java:119)
  at com.google.firebase.perf.config.ConfigResolver.<init> (ConfigResolver.java:78)
  at com.google.firebase.perf.config.ConfigResolver.getInstance (ConfigResolver.java:86)
  at com.google.firebase.perf.application.AppStateMonitor.<init> (AppStateMonitor.java:98)
  at com.google.firebase.perf.application.AppStateMonitor.getInstance (AppStateMonitor.java:87)
  at com.google.firebase.perf.metrics.Trace.<init> (Trace.java:106)
  at com.google.firebase.perf.metrics.Trace.create (Trace.java:98)
  at com.google.firebase.perf.FirebasePerformance.startTrace (FirebasePerformance.java:213)
  at com.OURAPPLICATION.Application.onCreate (AbstractApplication.java:7)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1211)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7096)
  at android.app.ActivityThread.access$1700 (ActivityThread.java:277)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2170)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:211)
  at android.os.Looper.loop (Looper.java:300)
  at android.app.ActivityThread.main (ActivityThread.java:8282)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:576)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1074)
Caused by java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.OURAPPLICATION.ex. Make sure to call FirebaseApp.initializeApp(Context) first.
  at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java:179)
  at com.google.firebase.perf.config.RemoteConfigManager.getInitialStartupMillis (RemoteConfigManager.java:91)
  at com.google.firebase.perf.config.RemoteConfigManager.<init> (RemoteConfigManager.java:85)
  at com.google.firebase.perf.config.RemoteConfigManager.<clinit> (RemoteConfigManager.java:52)
```

**Comment by argzdev** [comment] 2023-03-20 12:12
Thanks for the extra details, @vramvoskanyan. This might be related to #4693. Specifically when adding `@AddTrace` in the Application class and then starting a new service.

As mentioned by [tevjef](https://github.com/tevjef) in this [comment](https://github.com/firebase/firebase-android-sdk/issues/4693#issuecomment-1450408323):
> @argzdev I believe the app has to startup a separate process where onCreate is called again. It seems Firebase now fails to initialize on non main processes.

**Comment by ColtonIdle** [comment] 2023-03-20 12:57
FWIW, we do not use any @AddTrace annotationss

**Comment by hellowwwwp** [comment] 2023-03-28 06:07
Make sure com.facebook.internal.**FacebookInitProvider** call after com.google.firebase.provider.**FirebaseInitProvider**

For example, you can disable two auto-initialized providers, and manually initialize them at the same time

eg: `
        
        <provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="${applicationId}.firebaseinitprovider"
            android:exported="false"
            android:initOrder="100"
            **tools:node="remove"** />

        
        <provider
            android:name="com.facebook.internal.FacebookInitProvider"
            android:authorities="${applicationId}.FacebookInitProvider"
            android:exported="false"
            **tools:node="remove"** />

==================================

class MyApp : Application(){

    override fun onCreate() {
        super.onCreate()
        ....
        FirebaseApp.initializeApp(this)
        FacebookSdk.sdkInitialize(this)
        ....
    }
}
`

**Comment by ColtonIdle** [comment] 2023-03-30 23:28
Thanks @hellowwwwp that worked!

**Comment by argzdev** [comment] 2023-05-22 11:44
Just bumping this thread. Thanks for providing a solution, @hellowwwwp. Since it looks like the mitigation is working, and I believe, our engineers won't be making any fixes/changes regarding this issue anytime soon, I'll close this for now. If this bothers a lot of our developers and would like to have a more solid proof solution, feel free to ask this to be reopened. Thanks all.

**Closed by argzdev** 2023-05-22 11:44 UTC
Labels: api: performance, needs-attention
