### ISSUE TITLE
SMS verification code request failed: unknown status code: 18002 Invalid PlayIntegrity token; app not Recognized by Play Store.

### ISSUE THREAD

**Issue by kakueki61** [firebase/firebase-android-sdk#4973] opened 2023-05-03 14:29 UTC
### [READ] Step 1: Are you in the right place?
yes

### [REQUIRED] Step 2: Describe your environment

Android Studio version: Electric Eel | 2022.1.1
Firebase Component: Firebase Authentication
Component version: Firebase Android BoM 31.5.0

### [REQUIRED] Step 3: Describe the problem
Even if a user has a device with Google Play services installed, phone verification with Recaptcha flow is triggered. 
In the logcat, there is a message.
```
[SmsRetrieverHelper] SMS verification code request failed: unknown status code: 18002 Invalid PlayIntegrity token; app not Recognized by Play Store.
```

According to this, should the app be delivered by Google Play?
I'm delivering the app without Google Play because this app is used only internally.

#### Steps to reproduce:

1. Sign in with phone authentication
2. Recaptcha flow will be triggered

#### Relevant Code:

```
val phoneWithCountryCode = getPhoneNumberWithCountryCode(phoneNumberText)

val auth = Firebase.auth
val optionsBuilder = PhoneAuthOptions.newBuilder(auth)
    .setPhoneNumber(phoneWithCountryCode)
    .setTimeout(120L, TimeUnit.SECONDS)
    .setCallbacks(object : PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
        override fun onVerificationCompleted(authCredential: PhoneAuthCredential) {
            onVerificationCompleted(authCredential)
        }

        override fun onVerificationFailed(e: FirebaseException) {
            e.printStackTrace()
            onVerificationFailed(e)
        }

        override fun onCodeSent(
            verificationId: String,
            token: PhoneAuthProvider.ForceResendingToken
        ) {
            super.onCodeSent(verificationId, token)
            forceResendingToken = token
            onCodeSent(verificationId, token)
        }

        override fun onCodeAutoRetrievalTimeOut(verificationId: String) {
            super.onCodeAutoRetrievalTimeOut(verificationId)
            onCodeAutoRetrievalTimeOut(verificationId)
        }
    })
    .setActivity(activity)
        
forceResendingToken?.let {
    optionsBuilder.setForceResendingToken(it)
}

val options = optionsBuilder.build()
PhoneAuthProvider.verifyPhoneNumber(options)
```

**Comment by NhienLam** [comment] 2023-05-04 23:35
Hi @kakueki61, thanks for reaching out! 
The error `[SmsRetrieverHelper] SMS verification code request failed: unknown status code: 18002 Invalid PlayIntegrity token; app not Recognized by Play Store.` is expected for apps that were not release from Play Store.

This error happens when Google Play Services is available and it first attempts PlayIntegrity. But since the app is not released from Play Store, that PlayIntegrity token will be treated as invalid and Recaptcha flow will be triggered.

**Comment by kakueki61** [comment] 2023-05-06 04:32
Does it behave according to specifications?

The [documentation](https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification) does not indicate about whether the app is released from Play Store or not.
On the app on which SafetyNet was available, Recaptcha flow isn't triggered even though the app isn't released from Play Store.
Was the behavior changed after Play Integrity is available?

**Comment by NhienLam** [comment] 2023-05-08 18:11
Hi @kakueki61. Yes, the behavior has changed and we just documented it in the same document https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification. 

> Some scenarios where reCAPTCHA is triggered:
If the end-user's device does not have Google Play services installed.
If the app is not distributed through Google Play store (on [Authentication SDK v21.2.0+](https://firebase.google.com/support/release-notes/android#auth_v21-2-0)).
If the obtained SafetyNet token was not valid (on Authentication SDK versions < v21.2.0).

Hope this helps.

**Comment by GrandeSamarone** [comment] 2023-05-09 19:25
hi i have the same problem, and how is it done to test?
my app is still in debug mode and before it works normally,
I'm using flutter

**Comment by NhienLam** [comment] 2023-05-09 20:30
Hi @GrandeSamarone, by development mode, do you mean you're running on emulator or your app is not yet distributed through Google Play Store, correct?

If you're running on emulator, the emulator will likely not have Google Play services installed so you should see this error message.
If your app is not distributed through Google Play Store, you should also see this error message.

`Invalid PlayIntegrity token; app not Recognized by Play Store` error message indicates that Play Integrity flow is triggered and working as intended. We cannot verify your app in the above scenarios, so you can only ensure that you see this Play Integrity error and the reCAPTCHA flow is triggered and working correctly. That’s the most you can test in these scenarios.

Hope this helps.

**Comment by GrandeSamarone** [comment] 2023-05-09 22:36
> reCAPTCHA

I'm testing the app on a physical cell phone, the reCAPTCHA appears and after a few seconds it disappears (without having to do anything) and the cod does not arrive,
In that case, how can I test it?

what I want to understand is from now on how will the tester in app development mode auth phone?
was it to do some action on reCAPTCHA?

**Comment by NhienLam** [comment] 2023-05-09 22:53
>the reCAPTCHA appears and after a few seconds it disappears (without having to do anything)

This is expected, but the SMS verification code should be sent and you should be able to use that verification code to complete the Phone Auth sign in flow.

Testing the flow with our test app seems to work fine. I could see the code sent once reCAPTCHA was triggered. If you still have this issue, could you open a new issue and give us more information? Thank you.

**Comment by NhienLam** [comment] 2023-05-10 00:30
Closing this issue since this is expected behavior. Feel free to ask this to be reopened if you think this is a mistake. Thanks!

**Closed by NhienLam** 2023-05-10 00:30 UTC
Labels: api: auth

**Comment by argzdev** [comment] 2023-05-10 10:31
Hi @GrandeSamarone, you can always use `Phone number for testing` section if you'd like to test out phone authentication. In our Firebase Console, this is available when enabling Phone provider in our Sign-in providers

<img width="1240" alt="Screenshot 2023-05-10 at 6 27 23 PM" src="https://github.com/firebase/firebase-android-sdk/assets/93124282/5995b9bb-e14e-4ff7-9693-302ac83a030c">
