### ISSUE TITLE
loadBundle() with UTF8 chars throw error on android

### ISSUE THREAD

**Issue by aBuder** [firebase/firebase-android-sdk#2805] opened 2021-07-07 11:53 UTC
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Describe the bug**
loadBundle() function works fine on iOS and throws an error on android. I have the special character `Ö` in the text of the Cloud Firestore document. If I remove this character `Ö` it will work on android. It looks like UTF-8 chars not working.

### Screenshot Cloud Firestore Document
<img width="577" alt="Bildschirmfoto 2021-07-02 um 17 18 27" src="https://user-images.githubusercontent.com/1265139/124295822-91d28f80-db59-11eb-9e79-597233d95478.png">

Via an external tool, we create a bundle file of Cloud Firestore collections. If I  load the bundle on iOS it works fine, but on Android, I get this error:

```log
Exception has occurred.
FirebaseException ([cloud_firestore/load-bundle-error] Client specified an invalid argument. Note that this differs from failed-precondition. invalid-argument indicates arguments that are problematic regardless of the state of the system (e.g., an invalid field name).)
```

### Bundle file content

```txt
142{"metadata":{"id":"entries-1.bin","createTime":{"seconds":"1625237175","nanos":286628000},"version":1,"totalDocuments":1,"totalBytes":"1164"}}205{"documentMetadata":{"name":"projects/healadvisor-analyse-bef33/databases/(default)/documents/entries/000599d22b9a76bc5021e63e285b2664","readTime":{"seconds":"1625237175","nanos":286628000},"exists":true}}953{"document":{"name":"projects/healadvisor-analyse-bef33/databases/(default)/documents/entries/000599d22b9a76bc5021e63e285b2664","fields":{"texts":{"mapValue":{"fields":{"en_EN":{"mapValue":{"fields":{"problem":{"stringValue":"Test"},"solutionDescription":{"nullValue":"NULL_VALUE"},"bgInfo":{"nullValue":"NULL_VALUE"},"problemDescription":{"nullValue":"NULL_VALUE"},"solution":{"nullValue":"NULL_VALUE"}}}},"de_DE":{"mapValue":{"fields":{"problem":{"stringValue":"Öffne mich"},"problemDescription":{"nullValue":"NULL_VALUE"},"bgInfo":{"nullValue":"NULL_VALUE"},"solutionDescription":{"nullValue":"NULL_VALUE"},"solution":{"nullValue":"NULL_VALUE"}}}}}}},"editedAt":{"timestampValue":{"seconds":"1619433798","nanos":411000000}},"symbols":{"nullValue":"NULL_VALUE"},"createdAt":{"timestampValue":{"seconds":"1496158950","nanos":104000000}}},"createTime":{"seconds":"1625039472","nanos":253980000},"updateTime":{"seconds":"1625225415","nanos":239443000}}}
```

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2.1
  * Firebase Component:  `Cloud Firestore`
  * Component version: `com.google.firebase:firebase-bom:28.1.0`

We also tried this on native Android way with same problem.

```java
package de.timewaver.timewaver;
import android.os.AsyncTask;
import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;
import androidx.navigation.fragment.NavHostFragment;
import com.google.android.gms.tasks.Continuation;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.LoadBundleTask;
import com.google.firebase.firestore.LoadBundleTaskProgress;
import com.google.firebase.firestore.Query;
import com.google.firebase.firestore.QuerySnapshot;
import com.google.firebase.firestore.Source;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import de.timewaver.timewaver.databinding.FragmentFirstBinding;

public class FirstFragment extends Fragment {
    private FragmentFirstBinding binding;
    @Override
    public View onCreateView(
            LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState
    ) {
        binding = FragmentFirstBinding.inflate(inflater, container, false);
        return binding.getRoot();
    }
    public void onViewCreated(@NonNull View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        binding.buttonFirst.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                NavHostFragment.findNavController(FirstFragment.this)
                        .navigate(R.id.action_FirstFragment_to_SecondFragment);
            }
        });
        AsyncTask.execute(new Runnable() {
            @Override
            public void run() {
                try {
                    fetchBundleFrom();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

    }
    public InputStream getBundleStream(String urlString) throws IOException {
        URL url = new URL(urlString);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        return connection.getInputStream();
    }

    public void fetchBundleFrom() throws IOException {
        FirebaseFirestore db = FirebaseFirestore.getInstance();
        final InputStream bundleStream = getBundleStream("https://firebasestorage.googleapis.com/v0/b/healadvisor-analyse-bef33.appspot.com/o/bundles%2Fbundle-2.bundle?alt=media&token=aa1c4377-7c62-46c6-bca2-29948969f9b8");
        LoadBundleTask loadTask = db.loadBundle(bundleStream);
        loadTask.addOnCompleteListener(task -> {
            Log.i("TAG","");
        });
    }
    @Override
    public void onDestroyView() {
        super.onDestroyView();
        binding = null;
    }
}
```

**Comment by dconeybe** [comment] 2021-07-07 17:02
@aBuder Thank you for filing this issue. We will investigate. In the meantime, could you please edit the first comment to add the information requested in the new issue template (e.g. version numbers)? This could help with investigation.

**Comment by aBuder** [comment] 2021-07-07 18:03
@dconeybe done

**Comment by wu-hui** [comment] 2021-07-07 18:05
I cannot reproduce this myself, with the UTF-8 string you provided. Do you have the exception message when you try with you native Android reproductio?

**Comment by aBuder** [comment] 2021-07-08 06:19
@wu-hui Will it work on you site if you use this file?

https://firebasestorage.googleapis.com/v0/b/healadvisor-analyse-bef33.appspot.com/o/bundles%2Fbundle-2.bundle?alt=media&token=aa1c4377-7c62-46c6-bca2-29948969f9b8

**Comment by aBuder** [comment] 2021-07-08 06:39
```log
I think this is part of logs that you need
2021-07-08 09:33:48.378 3218-3697/de.timewaver.timewaver W/Firestore: (23.0.1) [Firestore]: Loading bundle failed : java.lang.NumberFormatException: For input string: "﻿144"
2021-07-08 09:33:48.381 3218-3218/de.timewaver.timewaver W/TAG: Bundle loading failed
    com.google.firebase.firestore.FirebaseFirestoreException: Bundle failed to load
        at com.google.firebase.firestore.core.SyncEngine.loadBundle(SyncEngine.java:552)
        at com.google.firebase.firestore.core.FirestoreClient.lambda$loadBundle$15$FirestoreClient(FirestoreClient.java:276)
        at com.google.firebase.firestore.core.-$$Lambda$FirestoreClient$y3T-AxVDw6TfryjSGP9EpirI0CY.run(Unknown Source:6)
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:436)
        at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$Y9GO7zO2DX6MzQJ5TbKtKW_NzO0.call(Unknown Source:2)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:322)
        at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$SynchronizedShutdownAwareExecutor$pKSAgg-ozJ8RbUveSl-44aUfFQw.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NumberFormatException: For input string: "﻿144"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.google.firebase.firestore.bundle.BundleReader.readNextElement(BundleReader.java:104)
        at com.google.firebase.firestore.bundle.BundleReader.getBundleMetadata(BundleReader.java:58)
        at com.google.firebase.firestore.core.SyncEngine.loadBundle(SyncEngine.java:518)
        at com.google.firebase.firestore.core.FirestoreClient.lambda$loadBundle$15$FirestoreClient(FirestoreClient.java:276)
        at com.google.firebase.firestore.core.-$$Lambda$FirestoreClient$y3T-AxVDw6TfryjSGP9EpirI0CY.run(Unknown Source:6)
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:436)
        at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$Y9GO7zO2DX6MzQJ5TbKtKW_NzO0.call(Unknown Source:2)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:322)
        at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$SynchronizedShutdownAwareExecutor$pKSAgg-ozJ8RbUveSl-44aUfFQw.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
        at java.lang.Thread.run(Thread.java:923)
2021-07-08 09:33:48.387 3218-3684/de.timewaver.timewaver W/waver.timewave: Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
2021-07-08 09:33:48.408 3218-3684/de.timewaver.timewaver I/ProviderInstaller: Installed default security provider GmsCore_OpenSSL
2021-07-08 09:33:48.517 3218-3646/de.timewaver.timewaver W/System: A resource failed to call close.
2021-07-08 09:33:48.517 3218-3646/de.timewaver.timewaver W/System: A resource failed to call close.
```


This is the code we used.

```java
[08:37] Yaroslav Kushnir (DE)
    I used this code to get the logs



final InputStream bundleStream = getBundleStream("https://firebasestorage.googleapis.com/v0/b/healadvisor-analyse-bef33.appspot.com/o/bundles%2Fbundle-2.bundle?alt=media&token=aa1c4377-7c62-46c6-bca2-29948969f9b8");
LoadBundleTask loadTask = db.loadBundle(bundleStream);
//LoadBundleTask loadTask = db.loadBundle(BUNDLE_TEMPLATES.getBytes(StandardCharsets.UTF_8));
loadTask.continueWithTask(new Continuation<LoadBundleTaskProgress, Task<Query>>() {​​​​​​​​
    @Override
public Task<Query> then(@NonNull Task<LoadBundleTaskProgress> task) throws Exception {​​​​​​​​
        // Close the stream
bundleStream.close();
// Calling getResult() propagates errors
LoadBundleTaskProgress progress = task.getResult(Exception.class);
// Get the named query from the bundle cache
return db.getNamedQuery("latest-stories-query");
}​​​​​​​​
}​​​​​​​​).continueWithTask(new Continuation<Query, Task<QuerySnapshot>>() {​​​​​​​​
    @Override
public Task<QuerySnapshot> then(@NonNull Task<Query> task) throws Exception {​​​​​​​​
        Query query = task.getResult(Exception.class);
// get() the query results from the cache
return query.get(Source.CACHE);
}​​​​​​​​
}​​​​​​​​).addOnCompleteListener(new OnCompleteListener<QuerySnapshot>() {​​​​​​​​
    @Override
public void onComplete(@NonNull Task<QuerySnapshot> task) {​​​​​​​​
        if (!task.isSuccessful()) {​​​​​​​​
            Log.w("TAG", "Bundle loading failed", task.getException());
            return;
}​​​​​​​​
        // Get the QuerySnapshot from the bundle
QuerySnapshot storiesSnap = task.getResult();
// Use the results
        // ...
}​​​​​​​​
}​​​​​​​​);




```

**Comment by wu-hui** [comment] 2021-07-09 11:20
So looks like this exception is thrown by JDK `Integer.parseInt` where it complains "144" is not a valid number format. This is pretty bizarre.

Can you let me know your JDK version? Also, can you try some different environments to see if the problem reproduces?

**Comment by wu-hui** [comment] 2021-07-09 18:41
![Screen Shot 2021-07-09 at 2 37 55 PM](https://user-images.githubusercontent.com/53845758/125122453-73bddf80-e0c3-11eb-846f-2236374a5c35.png)

You bundle file appears to have some extra bytes at the beginning. They are not printable, but JDK sees them. Do you know where they come from?

I still do not know why iOS works though, are you sure you loaded the same bundle for both iOS and Android?

**Comment by dconeybe** [comment] 2021-07-09 18:55
`EF BB BF` is the BOM for UTF-8. My guess is that it works on iOS because it recognizes the BOM and uses it to select the correct character encoding.

https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8

I'm not sure where it would have come from though. Maybe if the bundle file was opened in Windows Notepad then saved as "UTF-8" it could have added the BOM.

**Comment by wu-hui** [comment] 2021-07-10 00:42
Hah, I did not know that. I think the leading bytes here is a distraction, maybe the iOS app was connecting directly to storage, while Android app tried to read from a save file for debugging. 

Either way, I can confirm there is an issue loading `Öffne mich`, that is the real issue. Will prepare a fix.

**Comment by aBuder** [comment] 2021-07-10 18:01
Yes that could be possible. I was creating bundle file with UTF-8 BOM and without. Booth are not working on Android but on iOS.

So you can reproduce issue with **Öffne mich** text, is that right? Or do you need ne bundle from me?

**Comment by wu-hui** [comment] 2021-07-14 18:02
The fix for this is merged yesterday, and will be available from the next release.

If you want, you can build the SDK from github to verify the issue is gone.

**Closed by wu-hui** 2021-07-14 18:02 UTC
Labels: api: firestore
