### ISSUE TITLE
leakcary of

### ISSUE THREAD

**Issue by billdizl** [firebase/firebase-android-sdk#5591] opened 2023-12-06 06:55 UTC
`┬───
│ GC Root: System class
│
├─ android.content.res.ResourcesImpl class
│ Leaking: NO (a class is never leaking)
│ ↓ static ResourcesImpl.mAppContext
│ ~~~~~~~~~~~
├─ android.app.ContextImpl instance
│ Leaking: UNKNOWN
│ Retaining 1.8 kB in 16 objects
│ mOuterContext instance of com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService
│ ContextImpl.mOuterContext is an instance of com.google.android.datatransport.runtime.scheduling.jobscheduling.
│ JobInfoSchedulerService
│ ↓ ContextImpl.mOuterContext
│ ~~~~~~~~~~~~~
╰→ com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService instance
​ Leaking: YES (ObjectWatcher was watching this because com.google.android.datatransport.runtime.scheduling.
​ jobscheduling.JobInfoSchedulerService received Service#onDestroy() callback and Service not held by
​ ActivityThread)
​ Retaining 197 B in 4 objects
​ key = 0ae2fef3-41bf-4b1e-b503-a4fc5f6e9bd9
​ watchDurationMillis = 18518
​ retainedDurationMillis = 13502
​ mApplication instance of com.xx.xxl.view.BaseApplication
​ mBase instance of android.app.ContextImpl
METADATA
                                                                                                
                                                                                                Build.VERSION.SDK_INT: 31
                                                                                                Build.MANUFACTURER: realme
                                                                                                LeakCanary version: 2.12
                                                                                                App process name: com.xx.xx
                                                                                                Class count: 54038
                                                                                                Instance count: 326157
                                                                                                Primitive array count: 238069
                                                                                                Object array count: 53794
                                                                                                Thread count: 115
                                                                                                Heap total bytes: 55253487
                                                                                                Bitmap count: 132
                                                                                                Bitmap total bytes: 62467348
                                                                                                Large bitmap count: 0
                                                                                                Large bitmap total bytes: 0
                                                                                                Db 1: closed /data/user/0/xx/databases/google_app_measurement_local.db
                                                                                                Db 2: open /data/user/0/xx/databases/com.google.android.datatransport.events
                                                                                                Db 3: open /data/user/0/xx/databases/sensorsdata
                                                                                                Db 4: open /data/user/0/xx/databases/emas_accs.db
                                                                                                Stats: LruCache[maxSize=3000,hits=133823,misses=292310,hitRate=31%]
                                                                                                RandomAccess[bytes=14832299,reads=292310,travel=231421585202,range=60743210,size=77942949]
                                                                                                Analysis duration: 14422 ms
`

**Comment by billdizl** [comment] 2023-12-06 06:56
https://github.com/square/leakcanary/issues/2589

**Comment by argzdev** [comment] 2023-12-06 09:21
Duplicate of #5590

**Closed by argzdev** 2023-12-06 09:21 UTC
Labels: api: core
