### ISSUE TITLE
android FCM, how to work with more than one FCM projects in a app

### ISSUE THREAD

**Issue by lannyf77** [firebase/firebase-android-sdk#4794] opened 2023-03-16 15:19 UTC
In one android app, it has dependencies on some libraries and the library may have integrated with its own FCM project (should have its own pushtoken, and and its own backend to send the push against the respected pushtoken).

So each library has its own goole-services.json generated from its FCM project.
and has its own token listener, e.g.
```
class Proj_x_FirebaseMessagingService : FirebaseMessagingService {

    @Override public void onNewToken(String s) {
        ...
    }
    @Override public void onMessageReceived(RemoteMessage var1) { ...}
}
``` 

But when run the app only one library gets the FCM pushtoken.

ref: https://stackoverflow.com/questions/42117592/receive-push-notifications-on-one-android-app-from-two-firebase-projects,
mentioned about using `getToken("2xxxxx3344", "FCM")` but [it is deprecated][1] 

There is also [use multiple projects in your application][2]
But not really sure how to use it. the `FirebaseApp secondary = FirebaseApp.getInstance("secondary");` got error
```
Cannot access 'getInstance': it is package-private in 'FirebaseMessaging'
```
And especially looks like this approach will  requires change inside the depended libraries.

How to work with multiple FCM projects in one app?

  [1]: https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#getToken(java.lang.String,%20java.lang.String)
  [2]: https://firebase.google.com/docs/projects/multiprojects

**Comment by atakankaya** [comment] 2023-03-16 23:36
@lannyf77  
We have a similar ticket: https://github.com/firebase/firebase-android-sdk/issues/4316 

I think you are calling [FirebaseMessaging.getInstance(FirebaseApp)](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java#L156) but getting that error since this constructor is package-protected. Instead you can call [FirebaseApp.get(FirebaseMessaging.class)](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-common/src/main/java/com/google/firebase/FirebaseApp.java#L338) for your secondary projects. However, this API is public but hidden since it is marked with `@KeepForSdk` annotation. Still you wouldn't get any compilation error and it works fine. (But also note that [FirebaseMessagingService.onNewToken(token)](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService#public-void-onnewtoken-string-token) is only getting called for the default project. Therefore, you have to implement a mechanism yourself to manually check if token was changed for secondary apps.) 

Alternative was to migrate to a "single project - multiple service accounts" setup suggested by @argzdev at https://github.com/firebase/firebase-android-sdk/issues/4316#issuecomment-1433653251. But after contacting Firebase support (internal case #10217803); we came to the conclusion that this setup is also not well supported. 
- There is no pre-defined proper role, so you have to create a custom role with only the `cloudmessaging.messages.create` permission
- You have no way of knowing which server sent the message since all servers would use a single Firebase project. Therefore, you have to work with your vendors to define/change the message format that also contains the sender info. (That said, when the service account private keys are compromised, an attacker can still send a message impersonating a different server which you can't detect...)
- Further, this option is very costly and complex to implement/migrate for Android apps already live with multiple projects setup.

Therefore, I asked yesterday ( https://github.com/firebase/firebase-android-sdk/issues/4316#issuecomment-1470352040)  to @argzdev if it is OK to use [FirebaseApp.get(FirebaseMessaging.class)](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-common/src/main/java/com/google/firebase/FirebaseApp.java#L338) API even if it is hidden. This option works and implied in these Firebase docs [here ](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/FCM_TOKENS_CHANGE.md) and [here](https://firebase.google.com/docs/projects/multiprojects#use_multiple_projects_in_your_application).  Others seem to be already using that option on prod: https://github.com/firebase/firebase-android-sdk/issues/4450 (but with some rare issues)

**Comment by argzdev** [comment] 2023-03-20 09:23
Thanks for reporting, @lannyf77. As stated, this is roughly a duplicate of #4316. Thank you for providing your alternative workaround, @atakankaya. In order to avoid duplication, I'll close this for now. Feel free to continue the report on #4316, so we can compile the interests of our developers in this type of feature.

**Closed by argzdev** 2023-03-20 09:23 UTC
Labels: api: messaging
