### ISSUE TITLE
Firebase Auth not working on android firefox with BoM added

### ISSUE THREAD

**Issue by liorla1** [firebase/firebase-android-sdk#2901] opened 2021-08-12 08:21 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 11.0.10
  * Firebase Component: firebase-auth and many more (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
added Firebase BoM to get auth working on firefox browser on android device.
i still get the same error.
#### Steps to reproduce:
1. add FB BoM
2. remove firebase library versions 
3. deploy the app on HUAWEI BLA-L09 device
4. click "get sms code" button
5. get the "Unable to procss request due to missing initial state. This may happne if browser sessionStorage is inaccessible or accidentally cleared"
6. 
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:
these are my dependencies on app/build.gradle file:
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation "com.google.code.gson:gson:2.8.6"
    implementation 'com.google.android.material:material:1.3.0-alpha04'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'

    // Import the Firebase BoM
    implementation platform('com.google.firebase:firebase-bom:26.0.0')

    implementation "com.google.firebase:firebase-analytics"
    implementation "com.google.firebase:firebase-core"
    implementation "com.google.firebase:firebase-storage"
    implementation "com.google.firebase:firebase-database"
    implementation "com.google.firebase:firebase-auth"
    implementation "com.google.firebase:firebase-config"
    implementation "com.google.firebase:firebase-inappmessaging"
    implementation "com.google.firebase:firebase-crashlytics"
    implementation "com.google.firebase:firebase-invites"
    implementation "com.google.firebase:firebase-perf"
    implementation "com.google.firebase:firebase-firestore"
    implementation "com.google.firebase:firebase-messaging"
    implementation "com.google.firebase:firebase-functions"
    implementation 'com.github.chrisbanes.photoview:library:1.2.4'
    implementation 'androidx.browser:browser:1.2.0'
    implementation 'com.google.android.gms:play-services-base:17.6.0'
    //implementation "com.google.android.gms:play-services-analytics:15.0.1"

    // Dagger dependencies
    annotationProcessor "com.google.dagger:dagger-compiler:$rootProject.daggerVersion"
    annotationProcessor 'org.glassfish:javax.annotation:10.0-b28'
    implementation "com.google.dagger:dagger:$rootProject.daggerVersion"
    implementation "com.google.dagger:dagger-android:$rootProject.daggerVersion"
    implementation "com.google.dagger:dagger-android-support:$rootProject.daggerVersion"
    annotationProcessor "com.google.dagger:dagger-android-processor:$rootProject.daggerVersion"

    implementation "com.daimajia.swipelayout:library:1.2.0@aar"
    implementation 'com.yarolegovich:sliding-root-nav:1.1.0'
    implementation 'jp.wasabeef:glide-transformations:3.3.0'
    implementation "com.github.bumptech.glide:glide:$rootProject.glideVersion"
    annotationProcessor "com.github.bumptech.glide:compiler:$rootProject.glideVersion"
    implementation "io.reactivex.rxjava2:rxandroid:$rootProject.rxAndroidVersion"
    // Because RxAndroid releases are few and far between, it is recommended you also
    // explicitly depend on RxJava's latest version for bug fixes and new features.
    implementation "io.reactivex.rxjava2:rxjava:$rootProject.rxJavaVersion"
    implementation 'com.azoft.carousellayoutmanager:carousel:1.2.1'
    implementation 'com.github.Mariovc:ImagePicker:1.2.2'
    implementation 'com.airbnb.android:lottie:2.5.3'

    //square fab
    implementation 'com.robertlevonyan.view:CustomFloatingActionButton:2.1.1'

    // Analytics
    implementation 'com.cooladata.android:android-sdk:2.2.3'

    //Photo editor
    implementation 'ja.burhanrashid52:photoeditor:0.3.3'
    implementation 'com.theartofdev.edmodo:android-image-cropper:2.7.0'
    implementation 'io.michaelrocks:libphonenumber-android:8.12.11'
}
apply plugin: 'com.google.gms.google-services'

```
// TODO(you): code here to reproduce the problem
```

thanks for the help :)

**Comment by aguatno** [comment] 2021-08-12 19:25
Hi @liorla1 I looked at the error message that you shared with me and this issue seems related to the browser. So far, we received some reports about this, and our engineers are currently looking into it. Also note, that this is a duplicate of [#4256](https://github.com/firebase/firebase-js-sdk/issues/4256). Closing this in favor of that issue. Please upvote there instead. Thanks.

**Closed by aguatno** 2021-08-12 19:25 UTC
Labels: api: auth

**Comment by liorla1** [comment] 2021-08-12 19:31
thanks @ aguatno!
sorry for short site on that duplicate :)
