### ISSUE TITLE
Firebase App Distribution BUG: missing app ID on GitHub Actions

### ISSUE THREAD

**Issue by PavlosTze** [firebase/firebase-android-sdk#3403] opened 2022-02-04 16:26 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Bumblebee | 2021.1.1
  * Firebase Component: Firebase App Distribution
  * Component version: 3.0.0

### [REQUIRED] Step 3: Describe the problem

Just like this [StackOverFlow issue](https://stackoverflow.com/questions/70838922/firebaseappdistribution-with-github-actions-throwing-error-missing-app-id-eve), I have followed your guide for distributing builds through Firebase, and I also used GitHub actions for that. It was working smoothly for 3-4 months, until I recently upgraded to the 3.0.0 version of Firebase App Distribution.

As soon as I did it, I can no longer push builds through firebase as I get the following error on GitHub:
`* What went wrong:
Execution failed for task ':app:appDistributionRemoteDevDebug'.
> Missing app id. Please check that it was passed in and try again`

The following code on Android Studio's terminal (which is the same code I have in the GitHub action) works properly.
`gradlew :app:assembleRemoteDevDebug :app:appDistributionUploadRemoteDevDebug`
#### Steps to reproduce:

1. Create a GitHub action that distributes a build in firebase
2. You will get the following error `Missing app id. Please check that it was passed in and try again`
3. Running the same code that builds the project and uploads it in the Firebase, in the terminal in Android Studio, gives no error at all.

**Comment by umesh0492** [comment] 2022-02-08 18:21
Happening the same issue with https://github.com/Triple-T/gradle-play-publisher. I thinks this is some firebase issue only if same is happening with multiple libs

**Comment by argzdev** [comment] 2022-02-08 18:36
Hi @PavlosTze & @umesh0492, thanks for reporting. I'm unable to reproduce this issue on my own repo. Could you check what I'm missing?

GitHub Actions:
```
name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build
    - name: Upload with Release 
      run: |
        export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
        ./gradlew :app:assembleDemoRelease :app:appDistributionUploadDemoRelease      
```

module build.gradle:
```
android {
...
    buildTypes {
        debug {
            firebaseAppDistribution {
                artifactType="APK"
            }
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            firebaseAppDistribution {
                artifactType="APK"
            }
        }
    }

    flavorDimensions "version"
    productFlavors {
        demo {
            dimension "version"
            firebaseAppDistribution {
                releaseNotes="Release notes for demo version"
            }
        }
        full {
            dimension "version"
            firebaseAppDistribution {
                releaseNotes="Release notes for full version"
            }
        }
    }
...
}
```

project build.gradle:
```
dependencies {
        classpath "com.android.tools.build:gradle:7.0.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
        classpath 'com.google.firebase:firebase-appdistribution-gradle:3.0.0'
        classpath 'com.google.gms:google-services:4.3.10'
    }
```

Thanks!

**Comment by mtrakal** [comment] 2022-02-08 21:35
I'm able to reproduce with:

app/build.gradle:
```
apply plugin: 'com.google.firebase.appdistribution'

android {
   compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
        freeCompilerArgs += "-Xopt-in=kotlin.RequiresOptIn"
    }

    buildTypes {
         distribution {
            firebaseAppDistribution {
                serviceCredentialsFile = "firebase_distribution_api_key.json"
            }
        }

    flavorDimensions "api"
    productFlavors {
        staging {
            firebaseAppDistribution {
                releaseNotesFile = "${rootDir}/firebase_release_notes.txt"
                groups = "internal-testing"
            }
        }
    }
}
```

build.gradle
```
buildscript {
    ext.kotlin_version = '1.6.10'

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.gms:google-services:4.3.10"
        classpath 'com.google.firebase:firebase-appdistribution-gradle:3.0.0'
    }
}
```

`google-services.json` is located in `/app/google-services.json`

command to fire upload to Firebase App Distribution in my bitbucket pipeline:
`./gradlew assembleStagingDistribution appDistributionUploadStagingDistribution`

Same configuration just with `classpath 'com.google.firebase:firebase-appdistribution-gradle:2.2.0'` work like a charm. Only chnage to 3.0.0 made a failed upload with same error: `Missing app id. Please check that it was passed in and try again`

The biggest difference is, that I use 2 times firebaseAppDistribution (flavor + build type) and use **serviceCredentialsFile** instead of token. Or maybe location of google-services.json file? Because App ID is specified in this file.

**Comment by PavlosTze** [comment] 2022-02-09 00:04
@argzdev Here is also my code snippet related to the Firebase distribution that reproduces the issue:

**project build.gradle:**
```
dependencies {
        classpath "com.android.tools.build:gradle:7.1.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
        classpath "com.google.gms:google-services:4.3.10"
        classpath "com.google.firebase:firebase-appdistribution-gradle:3.0.0"
    }
```

**module build.gradle:**

```
android {
    flavorDimensions "mode", "server"

    productFlavors {
       local {
            dimension "mode"
        }
        remote {
            dimension "mode"
        }
        dev {
            dimension "server"
            firebaseAppDistribution {
                artifactType = "APK"
                serviceCredentialsFile = "${rootDir.path}/ci-service-account.json"
            }
        }
        prod {
            dimension "server"
            firebaseAppDistribution {
                artifactType = "APK"
                serviceCredentialsFile = "${rootDir.path}/ci-service-account.json"
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
        debug {
            // Change minifyEnabled to true if you want to test code obfuscation in debug mode
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        // Enable support for the new language APIs
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }
}
```

Also as @mtrakal said:

My `google-services.json` is located also in `/app/google-services.json`

The upload command of Firebase App Distribution in the GitHub action is:
`./gradlew :app:assembleRemoteDevRelease :app:appDistributionUploadRemoteDevRelease`

Using `'com.google.firebase:firebase-appdistribution-gradle:2.2.0'` works like a charm. Updating to '3.0.0' gives the error I described.

Also, I share the biggest differences of @mtrakal , I have also 2 flavors and I authorize via the serviceCredentialsFile.

**Comment by argzdev** [comment] 2022-02-09 18:09
Thank you for the extra details, @PavlosTze & @mtrakal. I tried replacing the authorization via token with `serviceCredentialsFile` including the project and app module `build.gradle` relevant code, however, even with the setup you've provided I'm unable to repro this issue. Perhaps, you could provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) of this issue, it'll greatly help us in our investigation. Thanks!

**Comment by argzdev** [comment] 2022-02-10 09:14
This has been acknowledged by our engineers and a fix is on the way. We'll post back here once we get updates. Thanks!

**Comment by argzdev** [comment] 2022-03-14 16:09
Hi all, since the issue has been resolved, I'll be closing this now.

**Closed by argzdev** 2022-03-14 16:09 UTC
Labels: type: bug, api: appdistro
