### ISSUE TITLE
Uncaught exception in Firebase Database runloop (19.2.0)

### ISSUE THREAD

**Issue by chitra-bahadur** [firebase/firebase-android-sdk#958] opened 2019-11-04 11:57 UTC
* Android Studio version: 3.5.1
  * Firebase Component: Database, Storage
  * Component version: 19.2.0

getting following error

java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (19.2.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
        at com.google.firebase.database.android.AndroidPlatform$1$1.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NoSuchMethodError: No virtual method object()Lsh0; in class Lsh0; or its super classes (declaration of 'sh0' appears in base.apk!classes2.dex)
        at com.google.firebase.database.util.JsonMapper.serializeJsonValue(SourceFile:13)
        at com.google.firebase.database.util.JsonMapper.serializeJsonValue(SourceFile:9)
        at com.google.firebase.database.util.JsonMapper.serializeJson(SourceFile:1)
        at com.google.firebase.database.connection.WebsocketConnection.send(SourceFile:2)
        at com.google.firebase.database.connection.Connection.sendData(SourceFile:5)
        at com.google.firebase.database.connection.Connection.sendRequest(SourceFile:4)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendSensitive(SourceFile:6)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendAction(SourceFile:1)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendStats(SourceFile:4)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendConnectStats(SourceFile:6)
        at com.google.firebase.database.connection.PersistentConnectionImpl.onReady(SourceFile:5)
        at com.google.firebase.database.connection.Connection.onConnectionReady(SourceFile:3)
        at com.google.firebase.database.connection.Connection.onHandshake(SourceFile:7)
        at com.google.firebase.database.connection.Connection.onControlMessage(SourceFile:11)
        at com.google.firebase.database.connection.Connection.onMessage(SourceFile:7)
        at com.google.firebase.database.connection.WebsocketConnection.appendFrame(SourceFile:8)
        at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(SourceFile:6)
        at com.google.firebase.database.connection.WebsocketConnection.access$500(SourceFile:1)
        at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(SourceFile:1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by aguatno** [comment] 2019-11-07 11:58
Hi @chitra-bahadur thank you for taking the time to submit this issue. The error logs somehow related to [issue#890](https://github.com/firebase/firebase-android-sdk/issues/890). 

To check whether this is a function implementation issue, could you try to remove all third-party APIs and follow this [Quickstart guide](https://github.com/firebase/quickstart-android) and see if you'll still encounter the issue?

Thanks

**Comment by chitra-bahadur** [comment] 2019-11-07 13:28
Hi,
It was causing issue because of RazorPay Java SDK. We checked if its
dependent on any firebase api but couldn't find. We removed "minifyenabled
= true" and "shrinikingResourecse = true" from build.gradle . it was
working fine.

Thanks
Chitra Bahadur

**Comment by aguatno** [comment] 2019-11-07 16:30
It sounds like you already figured out the issue, could you confirm if there's anything else we can help you with?

**Comment by chitra-bahadur** [comment] 2019-11-08 04:04
Hi,

In android app we have to remove "minifyEnabled, shrinkingResources" due to
which app size is increasing. We think this issues is related with
Proguards. Crashes are pointing to JSONMapper class. It would be great we
can get help to resolve this issue.

Thanks

**Comment by aguatno** [comment] 2019-11-11 13:57
Hi @chitra-bahadur Unfortunately, I wasn't able to reproduce the error, could you please
[A minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-exampl) of the issue (please make it minimal and remove any third party libraries), and then we can look at it further. Thanks

**Comment by chitra-bahadur** [comment] 2019-11-11 14:10
Hi as I said before error is because of 3rd party sdk. So we make changes
in build.gradle as mentioned in previous mail it works but app size
increased. You can reproduce the error using razor pay java sdk in
production apk

**Comment by schmidt-sebastian** [comment] 2019-11-13 17:22
Unfortunately, we won't be able to debug build issues that occur due to bundling with other (non-Firebase) SDKs. If there is a dependency conflict that we can solve by updating one of our dependencies, please let us know and we can do so. 

I will close this issue for now but we can follow up if there is a conflicting dependency.

**Closed** 2019-11-13 17:22 UTC
Labels: api: database, needs-attention
