### ISSUE TITLE
Unable to connect to the server. Check your connection and try again.

### ISSUE THREAD

**Issue by johnjeremih** [firebase/firebase-android-sdk#5625] opened 2024-01-04 15:46 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2023.1.1
  * Firebase Component: Remote config
  * Component version: com.google.firebase:firebase-config-ktx:21.4.1

#### Steps to reproduce:
I'm using real-time remote config and I'm getting these errors  

![image](https://github.com/firebase/firebase-android-sdk/assets/4177453/f7882646-904b-4d46-b202-753d71698e80)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

![image](https://github.com/firebase/firebase-android-sdk/assets/4177453/e879f4c3-41f8-496c-85ca-d168f7c79255)
![image](https://github.com/firebase/firebase-android-sdk/assets/4177453/7c208a01-b16a-42b3-be49-cd7b1f1e0ae0)

**Comment by argzdev** [comment] 2024-01-09 18:11
Hey @johnjeremih, thanks for reaching out. Looking through your code snippet, at first glance there doesn't appear to be any obvious reason why this issue is happening. Are you constantly able to reproduce this behavior? Or is there a certain condition to encounter this behavior?

**Comment by johnjeremih** [comment] 2024-01-09 20:04
@argzdev 
these are the errors I'm getting on Firebase
![image](https://github.com/firebase/firebase-android-sdk/assets/4177453/8be740ee-0b8b-4e14-8330-315b5daed869)

**Comment by lehcar09** [comment] 2024-01-12 16:47
Hi @johnjeremih, thank you for those details. I was able to encounter the issue once in the BOM version 32.2.0, however, I wasn’t able to reproduce the issue. 

It seems to me that the behavior you’re experiencing is similar to this report ([#5159](https://github.com/firebase/firebase-android-sdk/issues/5159)). Based on this [comment](https://github.com/firebase/firebase-android-sdk/issues/5159#issuecomment-1652224630), according to the investigation of our engineers, the behavior is intended. 

>“The reason why Crashlytics says it in the background for these exceptions could be due to a race condition between when our SDK thinks it's in the background compared to when Crashlytics is in the background. In the stack trace, there is a reference to a method called notifyRCInstances. This method is only called when the app switches from background to foreground or vice versa. And in the case of background to foreground we retry the connection automatically which is what it looks like is happening. So in conclusion I think connections aren't being made in the background, it just looks that way due to a race condition between real-time and crashlytics logging.”

As mentioned in case, It should be safe to ignore. 

With that, I'll close this ticket now. Feel free to let me know if you think this is a mistake. If so, please provide with us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) or steps to reproduce this behavior showing repeated calling of the exception.

**Comment by johnjeremih** [comment] 2024-01-16 15:20
![image](https://github.com/firebase/firebase-android-sdk/assets/4177453/f2f4bb25-e65c-46fc-ad8d-8c9017a99011)

I just got this error "Config update error with code: CONFIG_UPDATE_STREAM_ERROR"

**Comment by cotchoninha** [comment] 2024-03-21 19:35
I'm having the same problem, but on my iOS application. The config listener used to work in the past and now I keep getting 
`Optional(Error Domain=com.google.remoteconfig.update.ErrorDomain Code=8001 "Unable to connect to the server. Check your connection and try again." UserInfo={NSLocalizedDescription=Unable to connect to the server. Check your connection and try again.})`

**Comment by asetiyadi-MLB** [comment] 2024-06-22 15:35
I have similar error in iOS and it is happening whenever the app is brought into the foreground from background mode.
```
Error Domain=com.google.remoteconfig.update.ErrorDomain Code=8001 "Unable to connect to the server. Check your connection and try again." UserInfo={NSLocalizedDescription=Unable to connect to the server. Check your connection and try again.}
```

**Comment by lehcar09** [comment] 2024-07-19 09:28
> ![image](https://private-user-images.githubusercontent.com/4177453/297101723-f2f4bb25-e65c-46fc-ad8d-8c9017a99011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODEzNjYsIm5iZiI6MTcyMTM4MTA2NiwicGF0aCI6Ii80MTc3NDUzLzI5NzEwMTcyMy1mMmY0YmIyNS1lNjVjLTQ2ZmMtYWQ4ZC04YzkwMTdhOTkwMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMDkyNDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTExMjcwMWVmNzgxNDA4Nzg1YTgwYWFkNzRiYzM0NmJkOTE5MzRlZmQxMjg1NWEwYWJmNjIwZWVhMWEwNzQ1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6Mh6cMNtTHeKmA4ucfbyAE5ZhCfHGk_OWu3cfSiOnDY)
> 
> I just got this error "Config update error with code: CONFIG_UPDATE_STREAM_ERROR"

Hey @johnjeremih, this looks like a different issue to me. Please file a new issue with the details to help us conduct initial investigation.

**Comment by lehcar09** [comment] 2024-07-19 09:39
Hi @cotchoninha and @asetiyadi-MLB, as mentioned in my [comment](https://github.com/firebase/firebase-android-sdk/issues/5625#issuecomment-1889632626), this is an intended behavior and is safe to ignore.

If you can provide with us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) or steps to reproduce this behavior showing repeated calling of the exception we can open an investigation. Also, I would suggest filing the issue to the [Firebase iOS Repository](https://github.com/firebase/firebase-ios-sdk/issues) for better tracking and have the right set of Engineers to investigate the issue. Thanks!

**Closed by lehcar09** 2024-07-19 09:39 UTC
Labels: api: remoteconfig
