### ISSUE TITLE
Old version of Jackson leaked into classpath causing compatibility issues

### ISSUE THREAD

**Issue by eygraber** [firebase/firebase-android-sdk#3004] opened 2021-09-26 22:39 UTC
This plugin (as of v 2.2.0) is leaking an older version of jackson (2.10.2) via `com.google.api-client:google-api-client:1.30.9` and this is causing incompatibilities with other libraries that use newer versions of Jackson.

**Comment by aguatno** [comment] 2021-09-28 14:06
@eygraber thanks for reporting. I'd like to clarify about this plugin that leads to incompatibilities? It would be better if you can provide [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) and s so we can have a better look. Thanks.

**Comment by eygraber** [comment] 2021-10-05 19:13
[MCVE firebase-3004.zip](https://github.com/firebase/firebase-android-sdk/files/7288615/firebase-3004.zip)


If you run `gradle :app:firebase3004` you will get the error:

`'com.fasterxml.jackson.core.util.JacksonFeatureSet com.fasterxml.jackson.core.JsonParser.getReadCapabilities()'`

If you uncomment the explicit classpath dependency in the root build.gradle.kts and run `gradle :app:firebase3004` the error does not occur.

**Comment by eygraber** [comment] 2022-12-16 04:47
Updating to `com.google.api-client:google-api-client:1.30.10` should fix this issue (unless the version of Jackson it uses has become an issue in the year+ since I filed this).

**Comment by argzdev** [comment] 2022-12-16 10:04
Thanks for notifying us, @eygraber. Let me try and ask our engineers to see if we have any feedback/updates regarding this.

**Comment by argzdev** [comment] 2022-12-16 15:13
It seems that this has been fixed in version [2.1.2](https://firebase.google.com/support/release-notes/android#appdistro_gradle_plugin_v2-1-2). Please do note that the current latest version is now at `3.1.1`, we recommend using the latest version to avoid bugs that has already been fixed in the most recent version. That said, since this has been resolved, I'll close this issue for now. Feel free to ask this to be reopened if you think this is a mistake. Thanks!

**Closed by argzdev** 2022-12-16 15:13 UTC
Labels: type: bug, needs-attention, External Dependency, api: appdistribution

**Comment by eygraber** [comment] 2022-12-16 20:11
Oh interesting, don't know how I missed that. Thank you!
