### ISSUE TITLE
Crashlytics multi process support

### ISSUE THREAD

**Issue by Yang-yongwen** [firebase/firebase-android-sdk#1592] opened 2020-05-26 04:21 UTC
## What feature would you like to see?

I found that Crashlytics only can be init in main process, but we want to collect crash info(java & native ) in other process. Besides, we want to init Crashlytics by self, not init by content provider automatically, because we want to disable Crashlytics in some devices (firebase_crashlytics_collection_enabled flag only disable report and will init normally).

## How would you use it?

Use Crashlytics in other process and can be disable crashlytics in some devices

**Comment by ashwinraghav** [comment] 2020-05-26 16:51
Duplicate of #1545

**Closed by ashwinraghav** 2020-05-26 16:51 UTC
Labels: needs-triage
