### ISSUE TITLE
Upgraded version Exception occurred

### ISSUE THREAD

**Issue by tanxicheng** [firebase/firebase-android-sdk#1730] opened 2020-06-29 02:26 UTC
java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzji@d886c18
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1759)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1786)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:751)
        at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
        at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
        at com.google.android.gms.measurement.internal.zzir.zzah(com.google.android.gms:play-services-measurement-impl@@17.4.3:251)
        at com.google.android.gms.measurement.internal.zzir.zzam(com.google.android.gms:play-services-measurement-impl@@17.4.3:268)
        at com.google.android.gms.measurement.internal.zzir.zzc(com.google.android.gms:play-services-measurement-impl@@17.4.3:335)
        at com.google.android.gms.measurement.internal.zziq.zza(com.google.android.gms:play-services-measurement-impl@@17.4.3:2)
        at com.google.android.gms.measurement.internal.zzaj.run(com.google.android.gms:play-services-measurement-impl@@17.4.3:7)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.android.gms.measurement.internal.zzfz.run(com.google.android.gms:play-services-measurement-impl@@17.4.3:21)

   'com.google.firebase:firebase-messaging:20.2.1'
    'com.google.firebase:firebase-core:17.4.3'
    com.google.firebase:firebase-core:17.4.3

**Comment by ashwinraghav** [comment] 2020-06-29 18:19
Duplicate of #1662

**Closed by ashwinraghav** 2020-06-29 18:19 UTC
Labels: needs-triage
