### ISSUE TITLE
putFile(Uri) failed : UploadTask: could not retrieve file size for upload android.resource://com.package.name/drawable/ic_drawable

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-android-sdk#3121] opened 2021-11-10 16:18 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: 20.0.0 (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
val uploadUri = mProfilePicURI ?: Uri.Builder()
                                .scheme(ContentResolver.SCHEME_ANDROID_RESOURCE)
                                .authority(resources.getResourcePackageName(R.drawable.ic_user))
                                .appendPath(resources.getResourceTypeName(R.drawable.ic_user))
                                .appendPath(resources.getResourceEntryName(R.drawable.ic_user))
                                .build()
```

```
W/UploadTask: could not retrieve file size for upload android.resource://com.myapp.sample/drawable/ic_user
    java.io.FileNotFoundException: Resource does not exist: android.resource://com.myapp.sample/drawable/ic_user
```
    

The Uri coming from drawable resource is not working while Uri from file manager, gallery, camera return by ActivityResult works fine such as `file:///data/data/com.sample.app/cache/cropped-1168776960.jpg`.

What could be the reason behind this? I can use the `Uri.Builder` value to `imagVeiew.setImageUri(uriBuild)` so the expectation of it working is reasonable.

Is there a specific format when using Uri? Thanks.

Note: Uploading works successfully despite the issue but the file itself which in this case is an image is not valid file that cannot be viewed or download.

**Comment by argzdev** [comment] 2021-11-10 16:37
Hi @ArcherEmiya05, thanks for reporting. I'd like to ask for more clarification about the issue, so I can investigate this further. I noticed that there's no mention of any Firebase product in your relevant code section, may I ask where or how is Uri being used in regards to Firebase products?

**Comment by argzdev** [comment] 2021-11-10 17:42
Hi @ArcherEmiya05, I tried testing this with our quickstart and this seems to work. I'm guessing the main issue is on the path of your Uri. You could try checking out this [link](https://stackoverflow.com/a/4896272/14129564) on how to properly setup your Uri. 

Relevant code:
```
val storageRef = Firebase.storage.reference
var path = Uri.parse("android.resource://com.google.firebase.quickstart.firebasestorage/" + R.drawable.ic_check_white_24)

val fileRef = storageRef.child("images/${path.lastPathSegment}")
var uploadTask = fileRef.putFile(path)

uploadTask.addOnFailureListener {
    Log.d(TAG, "upload: failed")
}.addOnSuccessListener { taskSnapshot ->
    Log.d(TAG, "upload: worked")
}
```

As for why the task was successful, the status depends on the upload if it successful or not. The credibility of the file is not verified on the upload. With that said, I'll be closing the case now.

**Comment by ArcherEmiya05** [comment] 2021-11-10 18:34
> Uri

Thanks, but the Uri sample above (android.resource://com.myapp.sample/drawable/ic_user) seems working just fine when using it in imageView so I wonder if there is a specified format of Uri that Firebase Storage accept.

**Comment by ArcherEmiya05** [comment] 2021-11-10 18:47
Not working, using API 21

`Uri.parse("android.resource://${packageName}/" + R.drawable.ic_user)`

```
W/UploadTask: could not retrieve file size for upload android.resource://com.sample.app/2131230864
    java.io.FileNotFoundException: Resource does not exist: android.resource://com.sample.app/2131230864
```

**Comment by argzdev** [comment] 2021-11-10 18:47
I think the format is the same as how an imageView accepts the Uri. As a test, I tried your code and this seems to work. There could be an underlying code issue on your side.

Relevant code:
```
val uploadUri = Uri.Builder()
    .scheme(ContentResolver.SCHEME_ANDROID_RESOURCE)
    .authority(resources.getResourcePackageName(R.drawable.ic_file_upload_white_24dp))
    .appendPath(resources.getResourceTypeName(R.drawable.ic_file_upload_white_24dp))
    .appendPath(resources.getResourceEntryName(R.drawable.ic_file_upload_white_24dp))
    .build()

val storageRef = Firebase.storage.reference

val fileRef = storageRef.child("images/${uploadUri.lastPathSegment}")
var uploadTask = fileRef.putFile(uploadUri)

uploadTask.addOnFailureListener {
    Log.d(TAG, "upload: failed")
}.addOnSuccessListener { taskSnapshot ->
    Log.d(TAG, "upload: worked")
}
```

**Comment by ArcherEmiya05** [comment] 2021-11-10 18:48
> uploadUri

Is the file uploaded correct and a valid image?

**Comment by argzdev** [comment] 2021-11-10 18:51
Yes, I've checked correct file and valid image. Perhaps you could provide us an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), so we can investigate this deeper.

**Comment by ArcherEmiya05** [comment] 2021-11-10 19:12
> 
> 
> Yes, I've checked correct file and valid image. Perhaps you could provide us an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), so we can investigate this deeper.

That is really weird, there should be no discrepancy anymore at this moment. Can you show me perhaps the image being downloadable or viewable either screenshot or its download uri? I can upload the image but the image itself is not valid

**Comment by ArcherEmiya05** [comment] 2021-11-10 19:25
I will open the issue again and wait for the other, please do not prematurely close it. Thanks

**Comment by ArcherEmiya05** [comment] 2021-11-10 19:47
I will open the issue again and wait for the other, please never prematurely close the issue unless stale or resolve . Thanks

**Comment by argzdev** [comment] 2021-11-11 09:15
Hi @ArcherEmiya05, thanks for getting back to me. I'll reopen this ticket and mark the other one as duplicate.

As for the issue, since there is a difference in our test results. Could you create a sample repro with the issue so I can check?

**Comment by ArcherEmiya05** [comment] 2021-11-11 17:29
> 
> 
> Hi @ArcherEmiya05, thanks for getting back to me. I'll reopen this ticket and mark the other one as duplicate.
> 
> As for the issue, the uploaded image is visible in the Firebase storage console, it is also downloadable as well. Since there's clearly a difference in our test results, I'd really like to investigate this deeper, but since I can't reproduce this issue on my side, may I ask if you could create a sample repro with the issue that you could share with me so I can check what's going on?
> 
> You may also try our [quickstart](https://github.com/firebase/quickstart-android) to discard a problem with the service, the quickstart is a good tool to compare your code/environment to see if something is missing.

Thanks for your interest, but I already checked the quickstart years ago and I believed that there is probably wrong with the SDK in terms of handling Uri. Would you mind to send me your sample project instead so I can checked it and see it by myself?

**Comment by ArcherEmiya05** [comment] 2021-11-11 17:29
Heads up. Another related issue has been reported from [SO](https://stackoverflow.com/q/38381438/12204620) which I also experienced.

**Comment by argzdev** [comment] 2021-11-11 19:14
Hi @ArcherEmiya05, it would be best that you provide a minimal reproducible project since you're the one experiencing an issue with the SDK and this would be helpful for us to analyze what's causing this behavior.

Just to add insight, our quickstart guides changes and improves over time since we always update this to work with our latest SDK.

Unfortunately I cannot validate the StackOverflow case since it was reported way back in 2016. We always ask our developers to try the latest version of SDK in order to avoid previous issues since multiple changes have been done on the SDK over the years. This way we can investigate the issue on the latest source code.

**Comment by ArcherEmiya05** [comment] 2021-11-11 19:18
> 
> 
> Hi @ArcherEmiya05, it would be best that you provide a minimal reproducible project since you're the one experiencing an issue with the SDK and this would be helpful for us to analyze what's causing this behavior.
> 
> Just to add insight, our quickstart guides changes and improves over time since we always update this to work with our latest SDK.
> 
> Unfortunately I cannot validate the StackOverflow case since it was reported way back in 2016. We always ask our developers to try the latest version of SDK in order to avoid previous issues since multiple changes have been done on the SDK over the years. This way we can investigate the issue on the latest source code.

I already pin point the issue I guess, the uploaded file is in `application/octet-stream MIME type`. I guess Firebase Storage do not fully supported Android Uri as I checked that similar report also exist in React. I suggest having documentation about this will be really helpful.

**Comment by argzdev** [comment] 2021-11-12 13:11
Hi @ArcherEmiya05, thanks for your findings. That is insightful, I'll wait for your repro so I can have it discussed with an engineer. Thanks!

**Closed** 2021-11-26 02:01 UTC
Labels: api: storage, needs-info, no-recent-activity
