### ISSUE TITLE
"pendingDynamicLinkData" is null when not use dynamic links launching

### ISSUE THREAD

**Issue by akihiyo76** [firebase/firebase-android-sdk#3324] opened 2022-01-19 06:17 UTC
### Environment

  * Android Studio version: Arctic Fox | 2020.3.1 patch 3
  * Firebase Component: dynamic links
  * Component version:  following version

https://firebase.google.com/docs/dynamic-links/android/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk

```
dependencies {
    // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:29.0.3')

    // Declare the dependencies for the Dynamic Links and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-dynamic-links-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
}
```

### Problem

At doc, indicating following introduction code, application initial launching occur NullPointer Exception.

`pendingDynamicLinkData` is Null. 

```
Firebase.dynamicLinks
        .getDynamicLink(intent)
        .addOnSuccessListener(this) { pendingDynamicLinkData ->
            // Get deep link from result (may be null if no link is found)
            var deepLink: Uri? = null
            if (pendingDynamicLinkData != null) {
                deepLink = pendingDynamicLinkData.link
            }
        }
        .addOnFailureListener(this) { e -> Log.w(TAG, "getDynamicLink:onFailure", e) }

```

Correctly, `pendingDynamicLinkData` is optional value.

```
Firebase.dynamicLinks
        .getDynamicLink(intent)
        .addOnSuccessListener(this) { pendingDynamicLinkData ->
            // pendingDynamicLinkData is null !!
            val deepLink: Uri? = pendingDynamicLinkData?.link
        }
        .addOnFailureListener(this) { e -> Log.w(TAG, "getDynamicLink:onFailure", e) }
```

#### Steps to reproduce:

It is happened by following code. `pendingDynamicLinkData` is not optional value.

```
Firebase.dynamicLinks
        .getDynamicLink(intent)
        .addOnSuccessListener(this) { pendingDynamicLinkData ->
            // pendingDynamicLinkData is not optional value.
            val deepLink: Uri = pendingDynamicLinkData.link
        }
        .addOnFailureListener(this) { e -> Log.w(TAG, "getDynamicLink:onFailure", e) }
```

Exception
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: jp.co.sample, PID: 10182
    java.lang.NullPointerException: pendingDynamicLinkData must not be null
```

#### Relevant Code:

Please fix `var1` to optional value.

```
public interface OnSuccessListener<TResult> {
    void onSuccess(@RecentlyNonNull TResult var1);
}
```

**Comment by argzdev** [comment] 2022-01-19 09:12
Hi @akihiyo76, thanks for the report. This looks like a duplicate of #2992. You could try the workaround solution in the link and continue your report there. With that said, I'll be closing this now. Thanks!

**Closed by argzdev** 2022-01-19 09:12 UTC
Labels: needs-triage
