### ISSUE TITLE
TFLite crash on `listDownloadedModels` 

### ISSUE THREAD

**Issue by amol-tw** [firebase/firebase-android-sdk#4475] opened 2022-12-20 13:51 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Electric Eal beta 2
  * Firebase Component: Tensorflow lite with play-services
  * Component version: 16.1.0

### [REQUIRED] Step 3: Describe the problem
I am using tensorflow-lite with play services to download and run a custom ML model. It works well for most of my usecases, but this rare exception was reported recently on a phone.

#### Steps to reproduce:

Haven't been able to reproduce this locally, and didn't see many instances of the crash. 

```Device
Brand:Xiaomi
Model:Redmi Note 11 4G
Orientation: Portrait
RAM free: 989.18 MB
Disk free: 26.97 GB
Operating system
Version:Android 11
Orientation: Portrait
Rooted:No
Crash

Fatal Exception: java.lang.IllegalArgumentException: column local_filename is not allowed in queries
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
       at android.content.ContentProviderProxy.query(ContentProviderProxy.java:472)
       at android.content.ContentResolver.query(ContentResolver.java:1195)
       at android.content.ContentResolver.query(ContentResolver.java:1127)
       at android.content.ContentResolver.query(ContentResolver.java:1083)
       at android.app.DownloadManager$Query.runQuery(DownloadManager.java:1510)
       at android.app.DownloadManager.query(DownloadManager.java:1740)
       at android.app.DownloadManager.query(DownloadManager.java:1722)
       at com.google.firebase.ml.modeldownloader.internal.ModelFileDownloadService.getDownloadingModelStatusCode(ModelFileDownloadService.java:315)
       at com.google.firebase.ml.modeldownloader.internal.ModelFileDownloadService.maybeCheckDownloadingComplete(ModelFileDownloadService.java:361)
       at com.google.firebase.ml.modeldownloader.FirebaseModelDownloader.listDownloadedModels(FirebaseModelDownloader.java:445)
```

#### Relevant Code:
This happens when I list downloaded models to decide if a new download is required or not:
```
downloader.listDownloadedModels().addOnCompleteListener { task ->
            val downloadedModel = task.result.find { it.name == modelName }
            if (downloadedModel == null) {
                downloader.getModel(
                    modelName,
                    DownloadType.LOCAL_MODEL_UPDATE_IN_BACKGROUND,
                    conditions
                ).addOnSuccessListener { model ->
                    // Callback 
                }
            } else {
                    // Callback 
            }
        }
```

**Comment by argzdev** [comment] 2022-12-20 14:22
Thanks for reporting, @amol-tw. This seems to be a duplicate of #4203. Based on my previous investigation:

>  it seems that the main issue is somewhere within the native Android OS retrieving the `COLUMN_LOCAL_FILENAME` in `DownloadManager`. I did also notice that `COLUMN_LOCAL_FILENAME` is now deprecated.

> Our SDK can't avoid this issue since we are not using COLUMN_LOCAL_FILENAME directly, and this is the default way of filtering by Id e.g. `setFilterById(downloadingId)`.

FWIW, the latest version of `com.google.firebase:firebase-ml-modeldownloader` is currently `24.1.1`, could you try updating to the latest version and see if that helps?

Given that the occurrence of the issue is rare, and we have no reproducible example. Unfortunately, there's not much I can do here. That said, I'll close this issue now since I believe the issue is not specifically in the SDK. Feel free to ask this to be reopened if you think this is a mistake. Thanks!

**Closed by argzdev** 2022-12-20 14:22 UTC
Labels: api: mlkit
