### ISSUE TITLE
Firestore Internal Error (21.1.1)

### ISSUE THREAD

**Issue by ccjernigan** [firebase/firebase-android-sdk#875] opened 2019-10-02 19:56 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5
  * Firebase Component: Firestore (Database, Firestore, Storage, Functions, etc)
  * Component version: 21.1.1

### [REQUIRED] Step 3: Describe the problem

Firestore is crashing sporadically in production.  I'm seeing the following stack traces together in Crashlytics.

```
Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (21.1.1).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:529)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(AsyncQueue.java:2000)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

```
com.google.firebase.firestore.core.SyncEngine.handleCredentialChange (SyncEngine.java:599)
com.google.firebase.firestore.core.FirestoreClient.lambda$new$0 (FirestoreClient.java:105)
com.google.firebase.firestore.core.FirestoreClient$$Lambda$15.run (FirestoreClient.java:3599)
com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2 (AsyncQueue.java:431)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call (AsyncQueue.java:2000)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1 (AsyncQueue.java:317)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run (AsyncQueue.java:2317)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:459)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run (AsyncQueue.java:224)
java.lang.Thread.run (Thread.java:764)
```

#### Steps to reproduce:

This is happening in production and being reported back to my via Crashlytics.

**Comment by schmidt-sebastian** [comment] 2019-10-03 20:26
@ccjernigan Sorry to hear about your troubles and thank you for filing this report!

I looked through the Stacktrace and am unfortunately not able to decipher what is going on. I suspect your Stracktrace may be missing a line. Can you double check? It would be very helpful if you could share the exception that occurred in `SyncEngine.handleCredentialChange (SyncEngine.java:599)`? Thank you?

**Comment by ccjernigan** [comment] 2019-10-03 20:52
It says it is an NullPointerException, but then its an obfuscated class name in my package namespace.

"Attempt to read from field 'com.me.kG com.me.lj.ᐝ' on a null object reference"

**Comment by schmidt-sebastian** [comment] 2019-10-03 21:08
Can you confirm that the full stacktrace contains essentially no more than:

```
Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (21.1.1).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:529)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(AsyncQueue.java:2000)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.me.kG com.me.lj.ᐝ' on a null object reference
       at com.google.firebase.firestore.core.SyncEngine.handleCredentialChange (SyncEngine.java:599)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0 (FirestoreClient.java:105)
       at com.google.firebase.firestore.core.FirestoreClient$$Lambda$15.run (FirestoreClient.java:3599)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2 (AsyncQueue.java:431)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call (AsyncQueue.java:2000)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1 (AsyncQueue.java:317)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run (AsyncQueue.java:2317)
       at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:459)
       at java.util.concurrent.FutureTask.run (FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run (AsyncQueue.java:224)
       at java.lang.Thread.run (Thread.java:764)
```

**Comment by ccjernigan** [comment] 2019-10-03 21:16
Sorry there is one more.  Same NPE with the trace:
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1 (AsyncQueue.java:320)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run (AsyncQueue.java:2320)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:459)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run (AsyncQueue.java:224)
java.lang.Thread.run (Thread.java:764)

**Comment by schmidt-sebastian** [comment] 2019-10-04 21:08
Sorry, I haven't been able to make a lot of progress on this. To me, it looks like the NullPointerException occurs in your code (if com.me.kG is your package), but it someone ends up crashing our Event loop. This indicates that a) there is a problem in your code and b) we are somehow running you code on our Executor.

Does that sound plausible to you? If so, do you have any insight what callback we could be running on our Executor? Are you using any of the new functionality (such as  FirebaseFirestore.waitForPendingWrites())?

**Comment by ccjernigan** [comment] 2019-10-04 21:52
So I went back and looked at my mapping file on my CI server.  The kG class is com.google.firebase.firestore.auth.FirebaseAuthCredentialsProvider

It looks like the lj class is com.google.firebase.firestore.core.TransactionRunner

I'm having a hard time finding ᐝ to figure out what that is.

I'm not using `waitForPendingWrites` currently.

**Comment by schmidt-sebastian** [comment] 2019-10-04 22:47
Unfortunately, even with the extra knowledge that this is related to TransactionRunner or FirebaseAuthCredentialsProvider,  I am still unable able to decipher from your stacktrace what causes the NullPointerException. It would be helpful to know if you see this error again and have a different stacktrace. 

In the meantime, you might be able to go back to 21.0.0 and work around this issue. TransactionRunner is a new class we shipped with 21.1.0.

Thanks for all your help so far and sorry that we haven't been able to find the root cause yet.

**Comment by ccjernigan** [comment] 2019-10-05 00:29
I've been seeing this since 21.0.0 as well.

Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (21.0.0).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:513)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(AsyncQueue.java:2000)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:7029)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'com.twofortyfouram.locale.x.kG com.twofortyfouram.locale.x.lc.ॱॱ' on a null object reference
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:315)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(AsyncQueue.java:2315)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:219)
       at java.lang.Thread.run(Thread.java:764)
Caused by java.lang.NullPointerException: Attempt to read from field 'com.twofortyfouram.locale.x.kG com.twofortyfouram.locale.x.lc.ॱॱ' on a null object reference
       at com.google.firebase.firestore.core.SyncEngine.handleCredentialChange(SyncEngine.java:561)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0(FirestoreClient.java:103)
       at com.google.firebase.firestore.core.FirestoreClient$$Lambda$14.run(FirestoreClient.java:3561)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:423)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(AsyncQueue.java:2000)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:312)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(AsyncQueue.java:2312)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:219)
       at java.lang.Thread.run(Thread.java:764)

**Comment by schmidt-sebastian** [comment] 2019-10-07 17:35
Unfortunately, I am still not able to pinpoint the root cause.

If you want us to investigate further, can you answer the following:

- Is this a new issue as of 21.1.0? 
- Is `com.twofortyfouram.locale.x.kG` an obfuscated Firebase class? Can you share (some) of the contents, such a string constants that could help us decipher what this class is?
- What do you see in line ` com.google.firebase.firestore.core.SyncEngine.handleCredentialChange(SyncEngine.java:561)`. The JAR that we shipped with 21.1.0 only shows [453 lines](https://gist.github.com/schmidt-sebastian/31d2719320933ab6928b07b1358d4685) for SyncEngine, and line 567 in our public sources at the time is for [updateTrackedLimboDocuments() ](https://github.com/firebase/firebase-android-sdk/blob/47def6d06943fb41ec21b0cf936421195b590ec4/firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java#L561).
- And finally, just to help us understand: Do you know why some of your stracktrace is obfuscated, while the Firestore sources are not? Are you using multiple levels of obfuscation?

**Comment by ccjernigan** [comment] 2019-10-08 11:33
I was delayed updating to the Android X version of Play Services and Firebase, due to a bug in Play Services Awareness packaging that didn’t get fixed until August.  The issue was not occurring when I was using Firestore 19.0.2.  I upgraded to 20.2.0 in August.  The first record I have of this issue occurring is with version 20.2.0.

Yes it is an obfuscated Firebase class.
```
com.google.firebase.firestore.auth.User -> com.twofortyfouram.locale.x.kG:
    com.google.firebase.firestore.auth.User UNAUTHENTICATED -> ˋ
    java.lang.String uid -> ˊ
    32:34:void <init>(java.lang.String) -> <init>
    46:54:boolean equals(java.lang.Object) -> equals
    59:59:int hashCode() -> hashCode
    64:64:java.lang.String toString() -> toString
    26:26:void <clinit>() -> <clinit>
```

I've found that line numbers don't always match up, especially if there is inlining or merging of classes during the optimization process of the obfuscator.

Those names are obfuscated because they are part of the error message string, rather than the stack trace.  Crashlytics would benefit from a greedier deobfuscator.

**Comment by schmidt-sebastian** [comment] 2019-10-11 16:18
Unfortunately, I haven't been able to determine the root cause. I will keep you updated if I do.

**Comment by MattSkala** [comment] 2019-10-12 20:16
We have been seeing similar crashes in production for several months now. If it helps, it seems that all of them happen when the app is launched in background using `BroadcastReceiver`. We are considering to deploy the app with de-obfuscated Firestore classes in the next release, so we can get a better stack trace.

For now, my guess is that `user` is `null` here:

https://github.com/firebase/firebase-android-sdk/blob/9ce9c184263d8a48ce0da26e70920650a6c95d84/firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java#L107

```
Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (21.1.1).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:529)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(AsyncQueue.java:2)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Caused by java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.firebase.firestore.i0.m0.a(com.google.firebase.firestore.h0.f)' on a null object reference
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:320)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(AsyncQueue.java:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:224)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.firebase.firestore.i0.m0.a(com.google.firebase.firestore.h0.f)' on a null object reference
       at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0(FirestoreClient.java:105)
       at com.google.firebase.firestore.core.FirestoreClient$$Lambda$15.run(FirestoreClient.java:4)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:431)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(AsyncQueue.java:2)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:317)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(AsyncQueue.java:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:224)
       at java.lang.Thread.run(Thread.java:764)

```

**Comment by schmidt-sebastian** [comment] 2019-10-15 20:40
@MattSkala Thanks for the hint with `BroadcastReceiver`. Fix for this NPE is coming.

**Closed** 2019-10-15 22:00 UTC
Labels: api: firestore, needs-info, type: bug
