### ISSUE TITLE
Lots of ANRs on handleUncaughtException

### ISSUE THREAD

**Issue by casolorz** [firebase/firebase-android-sdk#2709] opened 2021-06-02 22:59 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2.1
  * Firebase Component: Crashlytics
  * Component version: 2.1.1

#### Relevant Code:

This is the ANR I get. Have lots of those on the Play Store Console. 

  ```
at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException (CrashlyticsController.java)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.onUncaughtException (CrashlyticsController.java:1)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException (CrashlyticsUncaughtExceptionHandler.java:4)
  at com.facebook.ads.redexgen.X.8c.A03 (:18538)
  at com.facebook.ads.redexgen.X.8c.uncaughtException (:18556)
  at org.chromium.base.JavaExceptionReporter.uncaughtException (chromium-Monochrome.aab-stable-447207720:6)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1068)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1063)
  at java.lang.Thread.dispatchUncaughtException (Thread.java:1955)
```

**Comment by casolorz** [comment] 2021-06-07 18:47
I released an update with Crashlytics 2.6.1 and the ANR is still happening. Only seeing it on the Play Store Console. 

 ```
 at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException (CrashlyticsController.java)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.onUncaughtException (CrashlyticsController.java:1)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException (CrashlyticsUncaughtExceptionHandler.java:4)
  at com.facebook.ads.redexgen.X.8c.A03 (:18538)
  at com.facebook.ads.redexgen.X.8c.uncaughtException (:18556)
  at org.chromium.base.JavaExceptionReporter.uncaughtException (chromium-TrichromeWebViewGoogle.aab-stable-447208830:6)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1073)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1068)
  at java.lang.Thread.dispatchUncaughtException (Thread.java:2187)
```

**Comment by aguatno** [comment] 2021-06-07 19:37
Hi @casolorz Thanks for reporting this issue. I tried reproducing it on a blank app but could not. Was wondering if you mind sharing some info in order to help me reproduce?

Here are some of the things which could be helpful. Feel free to skip any of them which you cannot share.

1. Other dependencies of the app (maybe the gradle file)
2. A sample app on which the error could be reproduced.

**Comment by casolorz** [comment] 2021-06-07 20:36
Unfortunately I don't have any extra info on that since I can't reproduce it myself, I just have the ANR reports from the Play Store. However I noticed every single one of the ANR reports has Facebook on the stacktrace before Crashlytics. I do use Facebook Audience Network. 

The only ones that look different look like this but doesn't make much sense it mentions Flurry, which is totally separate ad network. 

  ```
at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException (CrashlyticsController.java)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.onUncaughtException (CrashlyticsController.java:358)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException (CrashlyticsUncaughtExceptionHandler.java:54)
  at com.facebook.ads.redexgen.X.IY.A03 (:29120)
  at com.facebook.ads.redexgen.X.IY.uncaughtException (:29143)
  at org.chromium.base.JavaExceptionReporter.uncaughtException (chromium-Monochrome.aab-stable-438910520:6)
  at com.flurry.sdk.ew$a.uncaughtException (ew.java:2088)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1068)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1063)
```

**Comment by casolorz** [comment] 2021-06-15 16:15
While looking at this ANR I noticed a different thread has a stacktrace that hopefully will help:

 ```
 at sun.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt (AbstractQueuedSynchronizer.java:868)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1023)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1334)
  at java.util.concurrent.CountDownLatch.await (CountDownLatch.java:232)
  at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread (Utils.java:5)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException (CrashlyticsController.java:6)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController$1.onUncaughtException (CrashlyticsController.java:1)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException (CrashlyticsUncaughtExceptionHandler.java:4)
  at com.facebook.ads.redexgen.X.8c.A03 (:18538)
  at com.facebook.ads.redexgen.X.8c.uncaughtException (:18556)
  at org.chromium.base.JavaExceptionReporter.uncaughtException (chromium-TrichromeWebViewGoogle.aab-stable-447208830:6)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1073)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1068)
  at java.lang.Thread.dispatchUncaughtException (Thread.java:2187)
```

**Comment by casolorz** [comment] 2021-07-07 21:24
Since I keep getting that ANR, I looked at more threads to see what they are doing, another one I saw had:

  ```
at java.io.StringWriter.write (StringWriter.java:77)
  at android.util.JsonWriter.string (JsonWriter.java:452)
  at android.util.JsonWriter.name (JsonWriter.java:289)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.internalAddIgnoreNullValues (JsonValueObjectEncoderContext.java:2)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:14)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:28)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEventApplicationExecutionThreadFrameEncoder.encode (AutoCrashlyticsReportEncoder.java:3)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEventApplicationExecutionThreadFrameEncoder.encode (AutoCrashlyticsReportEncoder.java:1)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.doEncode (JsonValueObjectEncoderContext.java:2)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:94)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:81)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.internalAddIgnoreNullValues (JsonValueObjectEncoderContext.java:3)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:14)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:28)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEventApplicationExecutionThreadEncoder.encode (AutoCrashlyticsReportEncoder.java:4)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEventApplicationExecutionThreadEncoder.encode (AutoCrashlyticsReportEncoder.java:1)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.doEncode (JsonValueObjectEncoderContext.java:2)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:94)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:81)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.internalAddIgnoreNullValues (JsonValueObjectEncoderContext.java:3)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:14)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:28)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEventApplicationExecutionEncoder.encode (AutoCrashlyticsReportEncoder.java:2)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEventApplicationExecutionEncoder.encode (AutoCrashlyticsReportEncoder.java:1)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.doEncode (JsonValueObjectEncoderContext.java:2)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:94)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.internalAddIgnoreNullValues (JsonValueObjectEncoderContext.java:3)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:14)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:28)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEventApplicationEncoder.encode (AutoCrashlyticsReportEncoder.java:2)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEventApplicationEncoder.encode (AutoCrashlyticsReportEncoder.java:1)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.doEncode (JsonValueObjectEncoderContext.java:2)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:94)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.internalAddIgnoreNullValues (JsonValueObjectEncoderContext.java:3)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:14)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:28)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEventEncoder.encode (AutoCrashlyticsReportEncoder.java:4)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEventEncoder.encode (AutoCrashlyticsReportEncoder.java:1)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.doEncode (JsonValueObjectEncoderContext.java:2)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:94)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:81)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.internalAddIgnoreNullValues (JsonValueObjectEncoderContext.java:3)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:14)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:28)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEncoder.encode (AutoCrashlyticsReportEncoder.java:11)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportSessionEncoder.encode (AutoCrashlyticsReportEncoder.java:1)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.doEncode (JsonValueObjectEncoderContext.java:2)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:94)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.internalAddIgnoreNullValues (JsonValueObjectEncoderContext.java:3)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:14)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:28)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportEncoder.encode (AutoCrashlyticsReportEncoder.java:8)
  at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportEncoder.encode (AutoCrashlyticsReportEncoder.java:1)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.doEncode (JsonValueObjectEncoderContext.java:2)
  at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add (JsonValueObjectEncoderContext.java:94)
  at com.google.firebase.encoders.json.JsonDataEncoderBuilder$1.encode (JsonDataEncoderBuilder.java:3)
  at com.google.firebase.encoders.json.JsonDataEncoderBuilder$1.encode (JsonDataEncoderBuilder.java:6)
  at com.google.firebase.crashlytics.internal.model.serialization.CrashlyticsReportJsonTransform.reportToJson (CrashlyticsReportJsonTransform.java:1)
  at com.google.firebase.crashlytics.internal.send.DataTransportCrashlyticsReportSender.lambda$static$0 (DataTransportCrashlyticsReportSender.java:1)
  at com.google.firebase.crashlytics.internal.send.a.apply (lambda)
  at com.google.android.datatransport.runtime.SendRequest.getPayload (SendRequest.java:1)
  at com.google.android.datatransport.runtime.TransportRuntime.convert (TransportRuntime.java:5)
  at com.google.android.datatransport.runtime.TransportRuntime.send (TransportRuntime.java:3)
  at com.google.android.datatransport.runtime.TransportImpl.schedule (TransportImpl.java:9)
  at com.google.firebase.crashlytics.internal.send.DataTransportCrashlyticsReportSender.sendReport (DataTransportCrashlyticsReportSender.java:5)
  at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.sendReports (SessionReportingCoordinator.java:6)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2$1.then (CrashlyticsController.java:7)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2$1.then (CrashlyticsController.java:1)
  at com.google.android.gms.tasks.zzo.run
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun (ExecutorUtils.java:1)
  at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run (BackgroundPriorityRunnable.java:2)
  at java.lang.Thread.run (Thread.java:919)
```

**Comment by aguatno** [comment] 2021-08-02 17:46
Hi @casolorz Apologies for the late reply. It’s quite hard to conclude if this is due to a conflict with a third party library without confirming using MCVE. There are also instances in which there might've been too many API calls done within the Crashlytics SDK which could also trigger an ANR in the app.

It'll be a great help to us in our investigation If you could provide the MCVE. If possible, could you also try running your stress test on our Crashlytics Android quickstart app to see if the issue can be replicated. If so, the issue would have to be escalated to the engineering team.

It's also worth noting that there were a few similar reports regarding this issue before which suggest that it's commonly happening when ANR is detecting dependency conflicts between a certain Firebase SDK and a third party library. However, it's possible that your issue may fall under a different scenario.

**Comment by casolorz** [comment] 2021-08-02 20:33
Unfortunately this has never happened to me, I only see the reports on the Play Store Console.

**Comment by aguatno** [comment] 2021-08-04 19:32
Hi @casolorz Thanks for the update. Glad to hear the error no longer showed up. It might be because of other dependencies (most likely non-Firebase dependencies). 

If no more help is needed. I'll be closing this issue for now, but feel free to leave a comment here if it still exists and we're happy to reopen it.

**Closed by aguatno** 2021-08-04 19:32 UTC
Labels: api: crashlytics, needs-attention

**Comment by casolorz** [comment] 2021-08-04 20:10
Sorry for the misunderstanding, I didn't mean that it isn't happening anymore, just that it has never happened to me. I've only seen the issue on the Play Store Console and still continue to see it there. It is one of my top ANRs. In fact right now it is my third top ANR. It always seems to be a Facebook ads crash that it is trying to report.
