### ISSUE TITLE
Topic sync or token retrieval failed on hard failure exceptions: java.util.concurrent.ExecutionException: java.io.IOException: AUTHENTICATION_FAILED. Won't retry the operation.

### ISSUE THREAD

**Issue by YogeshByndoor** [firebase/firebase-android-sdk#5711] opened 2024-02-14 07:25 UTC
This crash issue was caused while fetching the token from the  FirebaseMessaging.getInstance().getToken(). 

This task.isComplete() &&  task.isSuccessFull()  return true 
But while calling task.getResult() it is crashing. 

After clicking on playstore icon and try to sign up (Not completing the sign up ). This issue gets resolved  automatically. 

Before fetching the token we have the check if google Service is enabled or not.

final int PLAY_SERVICES_RESOLUTION_REQUEST = 9000;
        GoogleApiAvailability apiAvailability = GoogleApiAvailability.getInstance();
        int resultCode = apiAvailability.isGooglePlayServicesAvailable(activity);
        if (resultCode != ConnectionResult.SUCCESS) {
            if (apiAvailability.isUserResolvableError(resultCode)) {
                apiAvailability.getErrorDialog(activity, resultCode, PLAY_SERVICES_RESOLUTION_REQUEST).show();
            } else {
                Log.e("TAG":, "This device is not supported for GCM services");
            }
            return false;
        }
 

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:  HedgeHog
  * Firebase Component:
   implementation 'com.google.firebase:firebase-messaging:23.4.0'

    // Firebase Crashlytics SDK.
    implementation 'com.google.firebase:firebase-crashlytics:18.6.1'

    implementation 'com.google.android.gms:play-services-location:21.0.1'

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

`  FirebaseMessaging.getInstance().getToken().addOnCompleteListener(new OnCompleteListener<String>() {
            @Override
            public void onComplete(@NonNull Task<String> task) {
                if(task.isComplete() && task.getResult() != null){
                    String token = task.getResult();
                    if (!TextUtils.isEmpty(token)) {
                        RegisterPushNotifications.registrationId = token;
                        registerForPushNotification(token);
                    }
                }
            }
        });
// TODO(you): code here to reproduce the problem
According to firebase crashlytics , Mostly crash found on Samsung device (Android 14) . We have other versions and phone makers which is also having crashes. 

It is very hard to reproduce.  According to our analysis , We see that this issue happens only for new users, who is registering for the first time.

**Comment by lehcar09** [comment] 2024-02-14 14:47
Hi @YogeshByndoor, thanks for reporting. This seems to be a duplicate of [#3040](https://github.com/firebase/firebase-android-sdk/issues/3040). Could you try the solution provided in [here](https://github.com/firebase/firebase-android-sdk/issues/3040#issuecomment-948845234)? Thanks.

**Closed** 2024-02-28 02:02 UTC
Labels: api: messaging, needs-info, no-recent-activity
