### ISSUE TITLE
Firebase automatically replacing the user email provider when using Sign In with Apple

### ISSUE THREAD

**Issue by rodrigmatrix** [firebase/firebase-android-sdk#1176] opened 2020-01-29 21:34 UTC
* Android Studio version: 3.5
  * Firebase Component: Auth
  * Component version: 19.2.0

#### The issue:

The issue happens when the user has an email on firebase and tries to login with sign in with apple, the user is automatically replaced and linked with the apple auth provider. It is odd because on the documentation it says that if I want to link the user, I should do so using the linkWithCredential() method. I'm using the startActivityForSignInWithProvider() method and when the sign in process ends, the user is automatically replaced by the apple provider and the email provider no longer shows up on the firebase console

#### Relevant Code:

``` Kotlin
val provider = OAuthProvider.newBuilder("apple.com")
auth.startActivityForSignInWithProvider(this, provider.build())
             .addOnSuccessListener { authResult ->
                   // At this point, the user was already replaced in the firebase console
                    signInWithCredentialApple(authResult)
              }
```

**Comment by ReginaldoAlves** [comment] 2020-01-29 21:36
Same problem here :(

**Comment by aguatno** [comment] 2020-01-30 11:00
Hi @rodrigmatrix thank you for taking time filling this issue. For the case wherein Apple provider overrides the existing Email/Password account, this is the intended behavior because Apple accounts are considered verified.

For security reasons, if a user signs up with unverified email/password, and then the user signs in with Apple using the same email, the email/password provider will be removed as we can't verify that the original user owns that email. The user should have verified the email before signing in with Apple if they want to keep the password provider as well.

**Comment by aguatno** [comment] 2020-01-30 14:52
@rodrigmatrix I'm closing this issue since it's WAI. If you want to continue the discussion just leave a comment here and we are happy to re-open this.

**Closed by aguatno** 2020-01-30 14:52 UTC
Labels: api: auth
