### ISSUE TITLE
Firebase Performance on HMS device:  java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.perf.network.FirebasePerfOkHttpClient"

### ISSUE THREAD

**Issue by yavski** [firebase/firebase-android-sdk#2091] opened 2020-10-22 12:59 UTC
### Step 2: Describe your environment

  * Android Studio version: 4.1 #AI-201.8743.12.41.6858069, built on September 23, 2020 
  * Firebase Component: Firebase Performance Plugin 
  * Component version: 
plugin: com.google.firebase:perf-plugin:1.3.1
lib: com.google.firebase:firebase-perf:19.0.8

### Step 3: Describe the problem

I have been working on an architecture that supports both Google Mobile Services (GMS) and Huawei Mobile Services (HMS). Here is the issue I have noticed with the Firebase Performance plugin:

**GIVEN**
I add Firebase performance plugin to my project and Firebase Performance dependency to my project's GMS variants only
**WHEN**
I assemble a HMS variant and install it to a Huawei device that has only HMS services (released post 16 March 2019)
**THEN**
the application crashes with the following exception:
FATAL EXCEPTION: AGC-Https-Thread
    Process: tech.hmsfirebaseservices.dev, PID: 9182
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/perf/network/FirebasePerfOkHttpClient;
        at com.huawei.agconnect.https.d$1.a(Unknown Source:33)
        at com.huawei.agconnect.https.d$1.call(Unknown Source:0)
        at com.huawei.hmf.tasks.a.j$1.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.perf.network.FirebasePerfOkHttpClient" on path: DexPathList[[zip file "/data/app/tech.hmsfirebaseservices.dev-FWFpuR8G_Nwi7KwHCfN81Q==/base.apk"],nativeLibraryDirectories=[/data/app/tech.hmsfirebaseservices.dev-FWFpuR8G_Nwi7KwHCfN81Q==/lib/arm64, /system/lib64, /hw_product/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.huawei.agconnect.https.d$1.a(Unknown Source:33) 
        at com.huawei.agconnect.https.d$1.call(Unknown Source:0) 
        at com.huawei.hmf.tasks.a.j$1.run(Unknown Source:4) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929) 

#### Steps to reproduce:

1. Check out [hms-firebase-services](https://github.com/yavski/hms-firebase-services)
2. Switch to  firebase-perf-plugin-issue branch
3. Comment out l. 120 in app/build.gradle, i.e. remove the dependency on firebase perf lib from the huawei variant
4. Assemble a build for one of the Huawei variants (devHuawei*, uatHuawei*, prodHuawei*)
5. Install the build to Huawei devices supporting only HMS
6. Open the app
7. Boom

#### Relevant Code:

build.gradle.kts
app/build.gradle.kts

**Expected result:**
The app should not crash

**Actual result**
The app crashes

```

**Comment by birender-s** [comment] 2020-10-27 10:50
any update ?

**Comment by jposuna** [comment] 2020-11-04 01:41
Hi @yavski, @birender-s, I believe the issue is that the perf plugin is being applied on the HMS variant as well as the GMS variant, but the SDK is not present in the HMS variant (after removing the line you mentioned). Our plugin works in tandem with our SDK, and assumes that it is present (you can read more about how the plugin works here: https://firebase.google.com/docs/perf-mon/get-started-android#add-perfmon-plugin). Since the plugin is applied, but the SDK is not present, there is a missing class that the plugin assumes is present, which is what is causing the exception and the crash.

To fix this, please follow the steps here: https://firebase.google.com/docs/perf-mon/disable-sdk?platform=android#extension-property-flag. Basically, you will need to disable instrumentation for the HMS variant, which should prevent the ClassNotFoundException.

I believe this will fix the issue for you, so I'm closing the issue for now, but please reopen it if it doesn't, and I'll be happy to help you find a fix.

**Closed by jposuna** 2020-11-04 01:41 UTC
Labels: api: performance

**Comment by yavski** [comment] 2020-11-05 07:26
@jposuna thank you very much, this was helpful. Just leaving one more comment for anyone wondering how to configure the plugin with Kotlin DSL:
`withGroovyBuilder {
   "FirebasePerformance" {
       invokeMethod("setInstrumentationEnabled", false)
    }
}`
There is more examples [here](https://docs.gradle.org/5.0/userguide/kotlin_dsl.html#sec:interoperability).
