### ISSUE TITLE
Dynamic Link SDK cannot received `utm_term`, `utm_content` properly

### ISSUE THREAD

**Issue by studiogaram** [firebase/firebase-android-sdk#4637] opened 2023-02-09 05:28 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: checking...
  * Firebase Component: DynamicLinks
  * Component version: firebaseBillOfMaterialsVersion 29.3.1 
#### Steps to reproduce:

The iOS SDK was[ upgraded in December 2022 to receive utm_content, utm_term included in DynamicLink.](https://github.com/firebase/firebase-ios-sdk/pull/10413)
Unlike the iOS SDK, when using the getUtmParameters() function in the Android SDK, we could not check utm_content, utm_term, and only utm_campaign, utm_source, and utm_medium from received dynamic link even if iOS was able to receive all kinds of utm parameters.

Is there a reason why utm_content, utm_term are missing from Android? I wonder if it's a simple bug or a policy.

#### Relevant Code:

```
Bundle[{scionData=Bundle[{dynamic_link_app_open=Bundle[{medium=utmMedium, dynamic_link_accept_time=1675903774355, source=utmSource, campaign=utmCampaign, dynamic_link_link_name=, dynamic_link_link_id=[https://banksalad.page.link/qTQJ}](https://example.page.link/qTQJ%7D)], _cmp=Bundle[{medium=utmMedium, source=utmSource, campaign=utmCampaign, _cis=fdl_integration}]}], com.google.firebase.appinvite.fdl.extension.InvitationId=}]
```

**Comment by argzdev** [comment] 2023-02-09 14:26
Seems like a duplicate of #3482. There is an issue where the dynamic link is processed differently when:
1. Opening the dynamic link and then installing the app from the store. The utm params are retrieved via:
```
Firebase.dynamicLinks
    .getDynamicLink(intent)
    .addOnSuccessListener(this) { /* ... */ }
```
2. Opening the dynamic link when the app is already installed. The utm params are only retrieved via:
```
intent.data?.let { it ->
    Firebase.dynamicLinks
        .getDynamicLink(it)
        .addOnSuccessListener(this) { /* ... */ }
}
```
This might be the issue you're experiencing. and while this is still being worked on, can you try this workaround and see if it works?

```
intent.data?.let { it ->
    getDynamicLinkDetails(it)
} ?: run {
    getDynamicLinkDetails()
}

private fun getDynamicLinkDetails(uri: Uri){
    Firebase.dynamicLinks
        .getDynamicLink(uri)
        .addOnSuccessListener(this) { }
}    

private fun getDynamicLinkDetails() {
    Firebase.dynamicLinks
        .getDynamicLink(intent)
        .addOnSuccessListener(this) { }
```

**Closed** 2023-02-22 02:02 UTC
Labels: api: dynamiclinks, needs-info, no-recent-activity

**Comment by ShuheiSuzuki-07** [comment] 2023-03-07 06:01
結局これはバグということで間違いないでしょうか？
顧客に説明したいです。

**Comment by argzdev** [comment] 2023-03-07 10:37
Yes, @ShuheiSuzuki-07. While our engineers work on this. You could use this workaround for now:

```
intent.data?.let { it ->
    getDynamicLinkDetails(it)
} ?: run {
    getDynamicLinkDetails()
}

private fun getDynamicLinkDetails(uri: Uri){
    Firebase.dynamicLinks
        .getDynamicLink(uri)
        .addOnSuccessListener(this) { }
}    

private fun getDynamicLinkDetails() {
    Firebase.dynamicLinks
        .getDynamicLink(intent)
        .addOnSuccessListener(this) { }
```

**Comment by ShuheiSuzuki-07** [comment] 2023-03-08 07:48
@argzdev
 First of all, it is good to know that this is a disorder. Thank you for taking the time to reply!
