### ISSUE TITLE
Google service file missing certificate hash 

### ISSUE THREAD

**Issue by Yazan99sh** [firebase/firebase-android-sdk#2551] opened 2021-03-28 21:56 UTC
### Firebase console 
When I add new SHA-1 key it shows that had been added but when we download the google-service file it missing certificate hash and that effect on a lot of firebase features  and it's very big issue 
Don't close this without fix this problem 
Its happening too to my friends

**Comment by aguatno** [comment] 2021-03-29 12:19
Hi @Yazan99sh thanks for reporting. Currently, we haven't received similar reports. I tried to download google-service file and certificate_hash was there. I'd like to help you out, but I sense this may be a problem better suited to [Firebase support](https://firebase.google.com/support/troubleshooter/contact) because they have tools and expertise to troubleshoot issues related to the Firebase project (including google-service file) and the right venue to share your project details.

**Comment by Yazan99sh** [comment] 2021-03-29 13:55
> Hi @Yazan99sh thanks for reporting. Currently, we haven't received similar reports. I tried to download google-service file and certificate_hash was there. I'd like to help you out, but I sense this may be a problem better suited to [Firebase support](https://firebase.google.com/support/troubleshooter/contact) because they have tools and expertise to troubleshoot issues related to the Firebase project (including google-service file) and the right venue to share your project details.

try to add new app to your project then download the google-service file and I'm trying to contact with firebase support

**Comment by aguatno** [comment] 2021-03-30 17:26
Hi @Yazan99sh this seems unusual since the SHA-1 certificate added in your apps should also be contained as certificate_hash in the config file. To rule out the possibility that the issue is browser or connection related, please try the following troubleshooting steps:

- Clear your browser's cache.
- Try using a different supported browser.
-Connect using a different network or device.

If after trying the suggestions above and the issue persists, please reach out to Firebase support so that they can verify what's causing the issue. 

I'll be closing this for now since this is likely to be a Firebase project issue rather than SDK.

**Closed by aguatno** 2021-03-30 17:26 UTC
Labels: contact-support-instead
