### ISSUE TITLE
So many OutOfMemoryError [Copy]

### ISSUE THREAD

**Issue by 0xera** [firebase/firebase-android-sdk#4612] opened 2023-01-31 10:31 UTC
This is a copy https://github.com/firebase/firebase-android-sdk/issues/4388#issue-1471700615

We rolled back the bom to 29.3.0 after we started getting a lot of OOM. After several Firebase releases, we decided to update the bom version, and OOM immediately and noticeably began to increase. It's so sad that now we need to update the libraries individually, with our release cycle, upgrading to the newest version will take a long time. D
o you track OOM in the sdk? What do you use for this? The OOM is not displayed in Firebase Crashlytics

<img width="933" alt="Снимок экрана 2023-01-31 в 13 02 56" src="https://user-images.githubusercontent.com/56160164/215758077-69ccc65e-3ed5-4813-b805-a3476c8aa779.png">

**Comment by argzdev** [comment] 2023-02-02 08:59
Thanks for getting back to us, @0xera. We currently don't support reporting OOM crashes. Our team is working on towards the goal of having this in the future, but there's no timeline yet.

I can only advise using the [memory-profiler](https://developer.android.com/studio/profile/memory-profiler) tool of Android Studio. Since this is occurring to Android 10 devices, hopefully you might be able to reproduce this on your side.

Also do you have any code snippet related to Firebase Performance? Perhaps that'll help us narrow down what's causing the issue.

**Comment by 0xera** [comment] 2023-02-14 12:23
@argzdev 
We found that most of the OOM is on these devices: 
INTEL MOBILE LIMITED telL 6006
Xiaomi M2006C3MNG
TECHNO MOBILE LIMITED TECNO LC7
itel itel L6502.  

When the Firebase version is upgraded on these devices, the number of OOM increases more than on the rest.

**Comment by argzdev** [comment] 2023-02-27 09:49
Thanks for the extra details, @0xera. At the moment, investigating this issue is difficult without a minimal reproducible example and we don't have the said brand model of the devices for testing. Therefore, it's challenging to determine the root cause. That said, what we can do is keep this issue open for now in case our engineers or anyone else has an idea of what might be causing the issue.

**Comment by argzdev** [comment] 2023-05-22 11:38
Hi just bumping this thread, given that there's no update, no code snippets, no minimal reproducible example, no said devices, there's really nothing we can do here. That said, I'll close this issue for now. If there are other's who experience the same behavior, then we can probably prioritize a deeper investigation. For now, I'll close this since no action can be done.

**Closed by argzdev** 2023-05-22 11:38 UTC
Labels: api: performance, needs-attention
