### ISSUE TITLE
I'm getting the same issue:

### ISSUE THREAD

**Issue by vidya1415** [firebase/firebase-android-sdk#1809] opened 2020-07-23 08:13 UTC
I'm getting the same issue:

```
CollectionReference dbUsers = FirebaseFirestore.getInstance().collection("Users");
Map<String, Object> user = new HashMap<>();
user.put("email", request.getEmail());
user.put("name", request.getName());
user.put("dpUrl", request.getDpUrl());
dbUsers.document(chatterId)
     .set(user)
     .addOnSuccessListener(new OnSuccessListener<Void>() {
                    @Override
                    public void onSuccess(Void aVoid) {
                        callback.onCallSuccess(
                                new GetChatterIdResponse(chatterId)
                        );
                    }
                })
     .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        callback.onCallFailed(e);
                    }
                });
```

**Crash log:**

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/type/LatLng;
        at com.google.firestore.v1.Value.dynamicMethod(Value.java:1626)
        at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:252)
        at com.google.protobuf.GeneratedMessageLite.buildMessageInfo(GeneratedMessageLite.java:280)
        at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:60)
        at com.google.protobuf.ManifestSchemaFactory$CompositeMessageInfoFactory.messageInfoFor(ManifestSchemaFactory.java:143)
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:55)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:171)
        at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:391)
        at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:399)
        at com.google.firebase.firestore.UserDataReader.parseScalarValue(UserDataReader.java:403)
        at com.google.firebase.firestore.UserDataReader.parseData(UserDataReader.java:278)
        at com.google.firebase.firestore.UserDataReader.parseMap(UserDataReader.java:297)
        at com.google.firebase.firestore.UserDataReader.parseData(UserDataReader.java:251)
        at com.google.firebase.firestore.UserDataReader.convertAndParseDocumentData(UserDataReader.java:232)
        at com.google.firebase.firestore.UserDataReader.parseSetData(UserDataReader.java:75)
        at com.google.firebase.firestore.DocumentReference.set(DocumentReference.java:166)
        at com.google.firebase.firestore.DocumentReference.set(DocumentReference.java:146)
```

My Gradle dependencies:
```
implementation 'com.google.firebase:firebase-config:19.2.0'

    implementation 'com.android.volley:volley:1.1.1' //network
    implementation "androidx.security:security-crypto:1.1.0-alpha01"

    //chat
    implementation 'com.google.firebase:firebase-auth:19.3.2'
    implementation 'com.firebaseui:firebase-ui-database:6.2.1'
    implementation 'com.google.firebase:firebase-firestore:21.5.0'
    implementation 'com.google.protobuf:protobuf-lite:3.0.1'
    implementation 'com.google.android.gms:play-services-auth:18.1.0'
    implementation 'com.google.android.gms:play-services-maps:15.0.1'
```

_Originally posted by @ankurgecr in https://github.com/firebase/firebase-android-sdk/issues/1780#issuecomment-660233415_

**Comment by ankurgecr** [comment] 2020-07-23 08:17
@vidya1415 do you have any `implementation.exclude` in your `build.gradle` file?

**Comment by vidya1415** [comment] 2020-07-23 15:42
> @vidya1415 do you have any `implementation.exclude` or any `exclude group: "_any_package_with_proto_""` in your `build.gradle` file?

My build.gradle file(app): YES 

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.0"

    configurations {
        implementation.exclude module: 'proto-google-common-protos'
        implementation.exclude module: 'protolite-well-known-types'
        implementation.exclude module: 'protobuf-lite'
    }

    defaultConfig {
        applicationId "com.example.evcharge"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'com.google.firebase:firebase-auth:19.3.2'
    implementation 'com.google.firebase:firebase-firestore:21.5.0'
    implementation 'com.google.firebase:firebase-storage:19.1.1'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.navigation:navigation-fragment:2.3.0'
    implementation 'androidx.navigation:navigation-ui:2.3.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.google.android.libraries.places:places:2.3.0'
    implementation 'com.google.protobuf:protobuf-javalite:3.11.0'
    implementation("com.google.api.grpc:proto-google-common-protos:1.17.0"){
        exclude group: "com.google.protobuf", module: "protobuf-java"
    }

    implementation 'com.google.maps.android:android-maps-utils:2.0.3'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.android.volley:volley:1.1.1'

}

**Comment by ashwinraghav** [comment] 2020-07-23 23:07
Duplicate of https://github.com/firebase/firebase-android-sdk/issues/1780#issuecomment-660233415

**Closed** 2020-07-23 23:09 UTC
Labels: needs-triage

**Comment by ankurgecr** [comment] 2020-07-24 03:02
@vidya1415 as a workaround comment first two lines of your `implementation.exclude` and keep only third one. I.e.
```
    configurations {
        // implementation.exclude module: 'proto-google-common-protos'
        // implementation.exclude module: 'protolite-well-known-types'

        implementation.exclude module: 'protobuf-lite'
    }
```

This should not give any compile error as well as it should stop the crash as one include of `protobuf` lib will be in the dependencies. 

Meanwhile #1780  is already open, so let the developers fix that as better solution.
