### ISSUE TITLE
[Android][FLUTTER] Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException

### ISSUE THREAD

**Issue by kivocsa99** [firebase/firebase-android-sdk#4160] opened 2022-10-01 01:38 UTC
### Describe your environment

  * Android Studio version: 2021.2.1
  * Firebase Component: _____ Firestore
  * Component version: _____ 

#### Steps to reproduce:

iam working on a flutter app and i don't think this is a flutterfire problem  , just initialized firebase for my project , added the packages and did not execute any code but `  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);`

#### error Code:

```
/ManagedChannelImpl(23932): [{0}] Failed to resolve name. status={1}
W/Firestore(23932): (24.3.1) [WatchStream]: (5cc1395) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(23932): 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
W/Firestore(23932): 	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
W/Firestore(23932): 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
W/Firestore(23932): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Firestore(23932): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Firestore(23932): 	at java.lang.Thread.run(Thread.java:920)
W/Firestore(23932): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(23932): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
W/Firestore(23932): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/Firestore(23932): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
W/Firestore(23932): 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
W/Firestore(23932): 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
W/Firestore(23932): 	... 5 more


```
and the error goes on and on and on till the app crashes , and if i opened any connection with firestore it won't get the data 
NOTE : i have a stable internet fiber connection so i don't this is the issue

**Comment by SOG-web** [comment] 2022-10-02 17:44
please am also facing this issue, is there any solution please

**Comment by argzdev** [comment] 2022-10-03 09:55
Hi @kivocsa99, thanks for reporting. Might be related to #3302 which is a grpc issue. I'll let our engineers know about this.

**Comment by argzdev** [comment] 2022-10-03 09:59
Got it, @kivocsa99. Thanks for the quick response!

**Comment by kivocsa99** [comment] 2022-10-03 10:01
@argzdev no worries !  i think it might be an emulator issue .

**Comment by argzdev** [comment] 2022-10-03 10:23
Thanks for providing extra details, @kivocsa99. That's a good first step.

Is it only reproducible on emulators? Have you tried with other physical devices?

**Comment by kivocsa99** [comment] 2022-10-03 10:27
yes it's only on emulator , no problems whatsoever on physical device but i can't just work on my physical device cuz it's my daily device use , though there are some guys on stackoverflow says than downgrading the emulator version work , or turning of the wifi , but non of this actually worked with me

**Comment by argzdev** [comment] 2022-10-03 10:36
Just to test this issue further, did you happen to try on different Android versions and see if the issue persists?

**Comment by kivocsa99** [comment] 2022-10-03 10:42
@argzdev yes i have 30 , 31 ,32 , 29 and on multiple emulator devices all with the same issue

**Comment by argzdev** [comment] 2022-10-03 10:50
Thanks again, @kivocsa99, and no worries! We'll let you know any findings once our engineers have updates.

**Comment by kivocsa99** [comment] 2022-10-03 10:52
@argzdev Thanks for the hard work , waiting ....

**Comment by argzdev** [comment] 2022-10-03 14:40
Hi @kivocsa99, our engineers have responded:
> This seems to be something on the flutter layer IMO, because `initializeApp` with the native android API should not be trying to create the firestore streams at all

That said, could you try opening an issue in the [flutterfire](https://github.com/firebase/flutterfire/issues) repository? They'll be able to assist you better since this is something being handled in the flutter layer. 

I'll close this issue for now.  Feel free to ask this to be reopened if the flutterfire team have verified that this issue is on the native android side.

**Closed by argzdev** 2022-10-03 14:40 UTC
Labels: api: firestore, needs-attention

**Comment by argzdev** [comment] 2022-10-03 15:25
Hi @SOG-web, could you try opening an issue in the [flutterfire](https://github.com/firebase/flutterfire/issues) repository? They'll be able to assist you better since this is something being handled in the flutter layer.

**Comment by SOG-web** [comment] 2022-10-04 07:57
@argzdev thanks I have done that

**Comment by SOG-web** [comment] 2022-10-04 07:57
@argzdev Thanks, I have done that
