### ISSUE TITLE
FirebaseAuth.getInstance().getCurrentUser().getUid() returning numbers in place of actual user id

### ISSUE THREAD

**Issue by gitton** [firebase/firebase-android-sdk#1927] opened 2020-09-01 04:03 UTC
### [REQUIRED] Step 2: Describe your environment

 com.google.firebase:firebase-auth:19.2.0

### [REQUIRED] Step 3: Describe the problem

Using FirebaseAuth.getInstance().getCurrentUser().getUid()  to get the user id of the user. This method is returning numbers instead of the actual user id in some case. Also, we find the users token is still valid but the user id returning from the SDK is of number example: 101528418014522522531

#### Steps to reproduce:

Sorry, not able to reproduce the issue and was got from Crashlytics for some users

#### Relevant Code:

```
 FirebaseAuth.getInstance().getCurrentUser().getUid()
```

**Comment by malcolmdeck** [comment] 2020-09-21 18:28
Hey gitton,

I've filed b/169072058 to track this internally. This is really weird - if you stumble across any insight as to when this happens, that would be very useful.

Thanks,
~Malcolm

**Comment by samhorlbeck** [comment] 2020-09-23 16:10
One more question-- how often is this showing up in Crashlytics?

**Comment by gitton** [comment] 2020-09-24 04:50
Last 90 days we had seen this had affected around 150 users. @samhorlbeck

**Comment by samhorlbeck** [comment] 2020-09-24 16:12
Okay thanks, I'll update the tracking bug with that info

**Comment by pberrospi** [comment] 2020-10-08 21:58
Hi,
I have the same problem to get the ID of the profile of Facebook and use it to get the picture of the profile. It returns  https://graph.facebook.com/10223852407640502/picture and it is the same which other providers. 

I used to use the version: com.google.firebase:firebase-auth:19.4.0.

Problem in this code
![Error Firebase](https://user-images.githubusercontent.com/2231032/95517849-739f8080-0987-11eb-9a43-8aeee88a6216.PNG)

FirebaseAuth.getInstance().getCurrentUser().getUid()

**Comment by malcolmdeck** [comment] 2020-11-04 23:08
Ok, for the initial issue, this may be true for some users if they were created by the Admin SDK - you can set any UID there. I haven't been able to reproduce this issue at all, so if we can't find any more information on what types of users this is affecting or where those other IDs may be coming from, I don't really know how to proceed here.

As for the issue you're talking about pberrospi, I'm not sure that that's the Firebase UID. It appears to perhaps be the Facebook UID, given that that photoURL is, in fact, a valid Facebook Photo URL. I'm unsure of how one would map to the other - if you have any steps on how to reproduce your issue, please let me know

**Comment by pberrospi** [comment] 2020-11-04 23:38
> Ok, for the initial issue, this may be true for some users if they were created by the Admin SDK - you can set any UID there. I haven't been able to reproduce this issue at all, so if we can't find any more information on what types of users this is affecting or where those other IDs may be coming from, I don't really know how to proceed here.
> 
> As for the issue you're talking about pberrospi, I'm not sure that that's the Firebase UID. It appears to perhaps be the Facebook UID, given that that photoURL is, in fact, a valid Facebook Photo URL. I'm unsure of how one would map to the other - if you have any steps on how to reproduce your issue, please let me know

I don't know if the issue was corrected but currently it is working good and the issue is not happen again.

Thanks.

**Comment by malcolmdeck** [comment] 2020-11-05 01:50
I'm glad to hear it - I'll close this issue, then :)

**Closed by malcolmdeck** 2020-11-05 01:50 UTC
Labels: api: auth, internal-bug-filed, needs-attention
