### ISSUE TITLE
FirebaseAnalytics#getAppInstanceId ：On Android 9 devices, new AppInstanceId will not be generated after uninstallation and reinstallation

### ISSUE THREAD

**Issue by miejiededaxiang** [firebase/firebase-android-sdk#4516] opened 2023-01-04 07:46 UTC
### [READ] Step 1: Are you in the right place?

I think so.

### [REQUIRED] Step 2: Describe your environment

  * Firebase Component: Analytics
  * Component version: 19.0.1
  * Device version： Android9
  * Device model： OnePlus 6 和 RedMi Note4X

### [REQUIRED] Step 3: Describe the problem

With Android 9, no new AppInstanceId will be generated after uninstalling and reinstalling. This problem will not occur in other versions. After uninstalling and reinstalling, a new AppInstanceId will be generated

#### Steps to reproduce:

1. Call FirebaseAnalytics#getAppInstanceId
2. Call FirebaseAnalytics#getAppInstanceId after unloading and reinstalling
3. The AppInstanceId obtained twice is different
4. Only Android 9 has this problem

#### Relevant Code:

```
FirebaseAnalytics.getInstance(context).getAppInstanceId().addOnCompleteListener(new OnCompleteListener<String>() {
            @Override
            public void onComplete(@NonNull Task<String> task) {
                if (task.isSuccessful()) {
                    mInstanceId = task.getResult();
                }
            }
        });
```

Why does Android 9 not generate a new InstanceId? Other versions are OK.

**Comment by argzdev** [comment] 2023-01-04 10:26
Hi @miejiededaxiang, thanks for reporting. I'm unable to reproduce this behavior that you're experiencing even with Android 9.0, I've tried testing this with emulators but it seems to work just fine. Could it this be a device specific issue? Have you tried using emulators or other devices? If you're able to reproduce this with other devices, could you provide us with a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so we can investigate this further? Thanks!

**Comment by miejiededaxiang** [comment] 2023-01-05 02:42
> 

A total of 4 Android 9 devices are used： Redmi Note 8 Pro，vivo Y3，OnePlus 6 ，Redmi Note 4X。

RedmiNote8 and VivoY3 will generate new AppInstanceId after unloading and reinstalling, and OnePlus6 and RedmiNote4X will not generate new AppInstanceId

All these devices have Google Play installed, and the versions are 33.6.13

You can try OnePlus6 and RedmiNote4X to see if they will reappear

**Comment by argzdev** [comment] 2023-01-06 16:43
Thanks for the extra details, @miejiededaxiang. I tested this with a Redmi Note 8 Pro but on Android 11.0, so as expected, I'm unable to reproduce this behavior. It seems to me that it has to be specifically on Android 9.0 and only on selected devices. Since the issue is device specific, there's not much I can do given that I don't have the mentioned devices. I'll try and consult with our team and see how we can proceed. For now, I'll leave this issue open in case any engineer might have an idea what the issue is.

**Comment by wugj1004** [comment] 2023-02-16 03:34
Firebase Analytics first_open 事件发送一个参数 previous_first_open_count .

从值"0"开始(在生命周期内首次安装/新用户).
以及随后以1、2、3等递增"1".每次删除时，请重新安装该应用程序.
有人可以分享SDK如何管理信息，以保持用户过去安装该应用的频率(基本上触发了 first_open ).AFAIK，一旦删除了该应用，所有的应用数据都将被保存.删除..甚至每次删除时都会重新生成 app_instance_id 
目前发现Firebase firtst_open 事件在Android9 设备上无法上报，
session_start这个事件会增加，但是first_open事件不会增加，
目前发现 Android9有问题，测试了安卓8、安卓9、安卓10、安卓12，只有安卓9有问题
一加6、红米Note4X两台安卓9都查不到FirstOpen上报。
所以 firest_open 在卸载重装后没有增加，和getinstanceid没有发生变化可能是同一个问题！

**Comment by argzdev** [comment] 2023-05-22 12:29
> The Firebase Analytics first_open event sends a parameter previous_first_open_count .

> Starts with value "0" (first install/new user in lifetime).
and subsequent increments of "1" by 1, 2, 3, etc. Each time you delete, reinstall the app.
Can someone share how the SDK manages the information to keep how often the app has been installed by the user in the past (basically triggering first_open). AFAIK, once the app is deleted, all app data will be saved. Deleted.. even every time it is deleted Will regenerate app_instance_id
It is currently found that the Firebase first_open event cannot be reported on Android9 devices.
The session_start event will increase, but the first_open event will not increase,
At present, it is found that there is a problem with Android9, and Android 8, Android 9, Android 10, and Android 12 have been tested, and only Android 9 has a problem
OnePlus 6, Redmi Note 4X, two Android 9s cannot find the FirstOpen report.
So fire_open did not increase after uninstalling and reinstalling, and it may be the same problem as getinstanceid has not changed!

It looks like this issue only affects Chinese OEMs. There's nothing we can do for issues that are due to the manufacturer's limitation. That said, I'll close this issue now. If this affects more devices in the future, then we can probably prioritize a deeper investigation. Thanks.

**Closed by argzdev** 2023-05-22 12:29 UTC
Labels: api: analytics
