### ISSUE TITLE
FirebaseABTesting getAllExperiments always returns an empty list

### ISSUE THREAD

**Issue by jd565** [firebase/firebase-android-sdk#2556] opened 2021-03-30 10:26 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2020.3.1 Canary 12
  * Firebase Component: firebase-abt (Database, Firestore, Storage, Functions, etc)
  * Component version: 20.0.0

### [REQUIRED] Step 3: Describe the problem

I want to be able to query firebase for all the running AB tests, so that the app can report to our server what variant the app is using for each active test. The AB tests are the remote config types.

I can see (with debugger) the the remote config coming in has experiments, and the replaceAllExperiments function is being called on the FirebaseABTesting class, but when I later call the getAllExperiments function I get an empty list.

Is this supposed to be a public API? Or is there a different way of achieving what I am attempting to do?

If this is supposed to be a public API there is also an issue that the AbtExperimentInfo class has all the getters as package-private, so even if the data were returned, users of the API cannot use the data that comes out.

#### Steps to reproduce:

Turn on an AB test for a user, check that the user is in the AB test (checking the new remote config is set), and then call FirebaseABTesting.getAllExperiments.

**Comment by aguatno** [comment] 2021-04-22 14:22
Hi @jd565 Currently, A/B Testing doesn't have API support for process integration and/or automation. Given that the product is under Beta, I can file a feature request on your behalf. For now, you can only use the Firebase console to access the experiments.

**Comment by aguatno** [comment] 2021-04-28 17:58
I'll be closing the issue since this is a working as intended. Please keep an eye on our release notes for future updates. Thanks

**Closed by aguatno** 2021-04-28 17:58 UTC
Labels: api: abtesting
