### ISSUE TITLE
com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred.

### ISSUE THREAD

**Issue by ashique-perumbavoor** [firebase/firebase-android-sdk#2865] opened 2021-07-28 03:09 UTC
* Android Studio version: Android Studio Artic fox 2020.3.1 RC 1
  * Firebase Component: 
    implementation 'com.google.firebase:firebase-bom:28.3.0'
    implementation 'com.google.firebase:firebase-auth-ktx:21.0.1'

Firebase is constantly failing to send the OTP when the device is in wifi. It is not affecting all the wifi connections, But affected ones are not working at all. It works fine on mobile internet.

I cannot explain how to reproduce this because it is not affecting all the wifi connections and mobile internet.

**Comment by aguatno** [comment] 2021-07-30 11:26
Hi @ashique-perumbavoor We've received some reports about this, and our engineers are currently looking into it. Also note, that this is a duplicate of #2251. Closing this in favor of that issue. Please upvote there instead.

**Closed by aguatno** 2021-07-30 11:26 UTC
Labels: api: auth
