### ISSUE TITLE
Coroutine never finished when saving data while offline

### ISSUE THREAD

**Issue by risalfajar** [firebase/firebase-android-sdk#4835] opened 2023-03-30 07:47 UTC
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Flamingo | 2022.2.1 RC 1
  * Firebase Component: Database & Firestore
  * Component version: bom:31.2.0

### [REQUIRED] Step 3: Describe the problem
Saving data when offline using Kotlin coroutines works, but the coroutines never finished. I suspect this is because `addOnCompleteListener` never got called.

#### Steps to reproduce:
1. Create an Android project that use Firestore and RTDB
2. Enable offline persistence for RTDB (Firestore is enabled by default)
3. Create code to save data to RTDB or Firestore, writes a Log.d when saving has finished.
4. Try to save data while offline
5. The log never shows.

In my app, I show a Circular Progress when data is saving, but the progress never disappears.

#### Relevant Code:

```kotlin
import kotlinx.coroutines.tasks.await // Coroutine helper for Tasks

// RTDB
    suspend fun set(item: MaterialOpname) = withContext(Dispatchers.IO) {
        documentReference.child(item.id)
            .setValue(item)
            .await()
    }

// Firestore
    suspend fun save(location: Location) {
        documentReference
            .update("locations.${location.name}", location)
            .await()
    }
```

**Comment by thatfiredev** [comment] 2023-03-30 16:13
@risalfajar Can you update your code to provide a more complete example? i.e. the snippets where you write a Log.d and hide the circular progress. That would help us debug your issue.

**Comment by milaGGL** [comment] 2023-03-30 17:31
Hi @thatfiredev, for Firestore, it is an expected behaviour. The tasks do not complete until you go online, and the data is written to the server. 
However, if all you want is that the data is written to the local cache and queued for synchronization with the server, there is no need to await() anything. Because during the update() call,  the local cache gets written to synchronously.

**Comment by argzdev** [comment] 2023-03-30 17:36
Hi, I was able to reproduce the same behavior. As @milaGGL have stated, I was able to verify that once the internet is enabled back on the app the addOnCompleteListener queued will also complete.

Code snippet:
```
    suspend fun save(test: String) {
        delay(3000)
        db.collection("test")
            .document("random_document")
            .update("test_string", "123456")
            .addOnCompleteListener{
                Log.d(TAG, "save: completed")
            }
            .await()
    }

    fun test(view: View) {
        scope.launch {
            runOnUiThread {
                pb.visibility = View.VISIBLE
            }

            save("test")

            runOnUiThread {
                pb.visibility = View.INVISIBLE
            }
        }
    }
```

That said, since this is working as intended, I'll close this issue now. Feel free to reopen if you think this is a mistake. Thanks!

**Comment by risalfajar** [comment] 2023-03-30 19:42
@thatfiredev sorry I put that in ViewModel, basically after `await()` I called `Log.d()`

**Comment by risalfajar** [comment] 2023-03-30 19:44
@milaGGL @argzdev So we must handle the offline scenario manually, right? Maybe by checking network state, then decide whether to call `await()` or not.

But can't we just make the SDK handle this for us?

**Comment by milaGGL** [comment] 2023-03-31 02:05
@risalfajar, Firestore SDK does handle the offline scenario for users. Any writes have been made offline will be synched into local cache right away for future reads, even though those writes may not be written back to the server yet. And once user come back online, those queued mutations will be send to server on behalf. 

Based on the code snippet, you should be able to just skip the `await()`, and it will handle both online and offline situations. Please let me know if this resolves the problem.

**Comment by risalfajar** [comment] 2023-03-31 10:41
Yes, that's what I intended to do, to skip the `await` when client is offline or giving some timeout to it. But I have questions:

1. If I skip the `await()` call, will the data saved to local cache synchronously?
2. How to catch errors when client has back online and the “writes” are being sent to the server?

**Comment by milaGGL** [comment] 2023-03-31 22:02
> 1. If I skip the `await()` call, will the data saved to local cache synchronously?

yes, it does.

> 2. How to catch errors when client has back online and the “writes” are being sent to the server?

The ` addOnCompleteListener` [argzdev](https://github.com/argzdev) used in the code is a very good way to track the status of the mutations send to server **after you come back online.**  It can help you track both success and failure of the task. For more information, please see [Task ](https://developers.google.com/android/reference/com/google/android/gms/tasks/Task#public-tasktresult-addoncompletelistener-oncompletelistenerlttresultgt-listener)

**Comment by risalfajar** [comment] 2023-04-01 09:17
For answer number 2, Can we persist the `Task` so that we can handle `onComplete` across app restarts?

**Comment by milaGGL** [comment] 2023-04-04 19:01
Hi @risalfajar, unfortunately, we cannot persist the Task across restarts. [`waitForPendingWrites()`](https://firebase.google.com/docs/reference/node/firebase.firestore.Firestore#waitforpendingwrites) will enable you to do that, but it wouldn't tell you the status of each individual mutation, only indicate if all pending writes have been successfully written to the server or not.

We have included this in our backlog for future development. For internal users, please refer to b/276604997. However, I cannot guarantee a specific timeline for resolving this matter. I am closing this issue, but please feel free to reopen it if you have further questions.

**Closed by milaGGL** 2023-04-04 19:01 UTC
Labels: api: firestore, needs-attention
