### ISSUE TITLE
FCM token is invalid in short time, even a few seconds

### ISSUE THREAD

**Issue by 42thcoder** [firebase/firebase-android-sdk#5569] opened 2023-11-22 15:11 UTC
SDK version: +--- com.google.firebase:firebase-messaging -> 23.1.1

# Current Approach

1. On app startup, the client calls the getToken method to obtain the token and reports it to the server.
2. The client registers onNewToken during app startup and reports the obtained token to the server upon receiving the callback.
3. Upon receiving the token, the server stores it in the database and performs a soft delete on the previous token.
4. When a push notification needs to be sent to a user, the server retrieves the token from the database based on the user's userId and uses the Firebase API to send the push notification. If the API returns a 404 error, the token is marked as invalid.

# Current Issue
From the database data, it is observed that some tokens reported by the client become invalid after a few seconds to minutes or even hours. This results in an error (status code 404) when calling the Firebase server API.

Users have also reported intermittent push notification delivery issues during app usage, with notifications sometimes being received and sometimes not.

PS: We use FCM not only to display notifications to users when the app is closed but also to deliver messages while the app is in use or in the foreground, for updating unread message counts, for example.

# Specific User's Detailed Information

The following information is based on log and database data:

1. 2023-11-21T23:01:05.575+00:00: Client reports token. The source of the token obtained by the client is onNewToken. The token is d4iH6_m9QbK0HLRzpp0sTk:APA91bGpzOM5cQ2by3riSO74WiV4Yszi4hnZ_9VGzWSgsnbN-7wLQwt0BYKetDinwIsZTKKgUuQ4AS-jvIBNQgWp3mhxlwb_LG3QjUOCoIYhESofqDdtBEpQtc8o3lUum74jXFEbwlhC.
2. 2023-11-21T23:01:05.672+00:00: Client reports token. The source of the token obtained by the client is getToken. The token is d4iH6_m9QbK0HLRzpp0sTk:APA91bGpzOM5cQ2by3riSO74WiV4Yszi4hnZ_9VGzWSgsnbN-7wLQwt0BYKetDinwIsZTKKgUuQ4AS-jvIBNQgWp3mhxlwb_LG3QjUOCoIYhESofqDdtBEpQtc8o3lUum74jXFEbwlhC.
3. The server stores this token in the database and successfully sends a push notification using the Firebase API.
4. 2023-11-21 23:06:11.926379: The server calls the Firebase API to send a push notification and receives a 404 error.
5. 2023-11-22T01:21:13.382+00:00: The client reports a new token. The client obtains the token from getToken and onNewToken. The token is d4iH6_m9QbK0HLRzpp0sTk:APA91bFnZPeZgS6lW-PC4BW-TMpS-C9GHr7YfOz894wwUun26G_8xcjJBrQiyg0-yMZHVpBoiaj8VTu8dPytSuukBpWLY2V6Y3lHURm5Soa4_yqOKluTAymERGYnFuoW_xtp5Lti_TQo.
6. The new token successfully sends a push notification using the Firebase API.
7. The new token becomes invalid again after one minute. The server calls the Firebase API to send a push notification and receives a 404 error.

We would appreciate some assistance in understanding why the tokens reported by the client become invalid within such a short period of time.

Thank you very much.

**Comment by zenglihao** [comment] 2023-11-23 14:57
I also encountered this problem...

**Comment by argzdev** [comment] 2023-11-23 15:48
Hi @42thcoder, thanks for reaching out. So normally, an existing token may be changed for the [following reasons](https://firebase.blog/posts/2023/04/managing-cloud-messaging-tokens/#:~:text=There%20are%20scenarios%20when%20the%20existing%20token%20is%20changed%3A):
1. The app is restored on a new device
2. The user uninstalls/reinstall the app
3. The user clears app data
4. Certain device hardware failures can result in new tokens being created as a mechanism to work around the failures
FCM may also force tokens to change by calling this method as part of their operations. An example of this is: if the token encryption key is compromised, FCM rolls out new tokens to all app instances.

However, in your case, I don't think the user would've been able to clear the app data or uninstall/install a new app immediately to trigger this issue. I'm wondering if the issue might be due to a hardware limitation. With that said, could you answer a few questions below:
1. Are you able to reproduce this behavior?
2. Is this only affecting a subset of users? Also is it only affecting the same users?
3. I noticed that your version `23.1.1` is an old version that was released (Dec. 2022). Could you try using the latest version `23.3.1` and see if this helps? This is so that we may avoid issues that might have been fixed in the past.

Thanks!

**Comment by 42thcoder** [comment] 2023-11-24 09:11
@argzdev 

1. We have been trying for a long time but couldn't reproduce it.
2. Hundreds of users have experienced this situation.These users do not have any particularly distinctive characteristics.
3. Is the upgrade causing any incompatible failures?

**Comment by argzdev** [comment] 2023-11-24 09:23
Thanks for the extra details @42thcoder, for #3, I'm not sure actually, however I'm trying to check all possibilities that may be an SDK issues but from your details I'm thinking that there shouldn't be any problem with the SDK since this is working for a majority of your user base. 

Was this only a recent issue that happened or has this issue been active for quite some time now? I was informed that there are some experiments being done on FCM backend, I'm not sure if this is the reason that's causing issues.

**Closed** 2023-11-24 09:49 UTC
Labels: api: messaging, needs-info
