### ISSUE TITLE
Firebase Database - Uncaught exception in Firebase Database runloop (19.3.0)

### ISSUE THREAD

**Issue by pankajmuneshwar** [firebase/firebase-android-sdk#1903] opened 2020-08-20 18:09 UTC
My project has implemented firebase data before (11.8.0) and run normally. I recently add firebase crashlytics sdk (database update to 19.3.0) and get crash when running project with release mode (minifyEnable = true).

2020-08-20 23:29:26.892 27768-27878/E/RunLoop: Uncaught exception in Firebase Database runloop (19.3.1). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
    java.lang.NoSuchMethodError: No virtual method object()Lim4; in class Lim4; or its super classes (declaration of 'im4' appears in /data/app/~~CbOypRPo9CEv-AzzfcMsRA==/xxxxxxxxxxxxxxxxx-bqZk2dLE4rM8ZhjLQX_4jg==/base.apk!classes2.dex)
        at hv1.a(JsonMapper.java:14)
        at hv1.a(JsonMapper.java:10)
        at hv1.a(JsonMapper.java:1)
        at er1.a(WebsocketConnection.java:20)
        at uq1.a(Connection.java:40)
        at uq1.b(Connection.java:6)
        at br1.a(PersistentConnectionImpl.java:164)
        at br1.a(PersistentConnectionImpl.java:158)
        at br1.c(PersistentConnectionImpl.java:20)
        at br1.l(PersistentConnectionImpl.java:8)
        at br1.a(PersistentConnectionImpl.java:11)
        at uq1.a(Connection.java:35)
        at uq1.d(Connection.java:7)
        at uq1.b(Connection.java:17)
        at uq1.a(Connection.java:15)
        at er1.a(WebsocketConnection.java:34)
        at er1.c(WebsocketConnection.java:7)
        at er1.a(WebsocketConnection.java:3)
        at er1$e$b.run(WebsocketConnection.java:1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2020-08-20 23:29:26.933 27768-27768/ E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 27768
    java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (19.3.1). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
        at gq1$a$a.run(AndroidPlatform.java:1)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7464)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
     Caused by: java.lang.NoSuchMethodError: No virtual method object()Lim4; in class Lim4; or its super classes (declaration of 'im4' appears in /data/app/~~CbOypRPo9CEv-AzzfcMsRA==/com.xxxxxxxxxxx-bqZk2dLE4rM8ZhjLQX_4jg==/base.apk!classes2.dex)
        at hv1.a(JsonMapper.java:14)
        at hv1.a(JsonMapper.java:10)
        at hv1.a(JsonMapper.java:1)
        at er1.a(WebsocketConnection.java:20)
        at uq1.a(Connection.java:40)
        at uq1.b(Connection.java:6)
        at br1.a(PersistentConnectionImpl.java:164)
        at br1.a(PersistentConnectionImpl.java:158)
        at br1.c(PersistentConnectionImpl.java:20)
        at br1.l(PersistentConnectionImpl.java:8)
        at br1.a(PersistentConnectionImpl.java:11)
        at uq1.a(Connection.java:35)
        at uq1.d(Connection.java:7)
        at uq1.b(Connection.java:17)
        at uq1.a(Connection.java:15)
        at er1.a(WebsocketConnection.java:34)
        at er1.c(WebsocketConnection.java:7)
        at er1.a(WebsocketConnection.java:3)
        at er1$e$b.run(WebsocketConnection.java:1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by ashwinraghav** [comment] 2020-08-21 03:22
Duplicate of #1582

**Closed by ashwinraghav** 2020-08-21 03:22 UTC
Labels: needs-triage
