### ISSUE TITLE
SQLiteReadOnlyDatabaseException in Cloud Firestore (22.0.0)

### ISSUE THREAD

**Issue by akshay-kapase** [firebase/firebase-android-sdk#2320] opened 2021-01-13 18:48 UTC
[INSERT INTO mutations (uid, batch_id, mutations) VALUES (?, ?, ?)] attempt to write a readonly database
android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)

App is crashing randomly because of this

**Comment by makuchaku** [comment] 2021-01-14 21:35
Hi @akshay-kapase  thanks for the report. To help you better, we need more information. Can you fill in details that our issue template recommends?
 
```
### [READ] Step 1: Are you in the right place?
 
Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:
 
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).
 
### [REQUIRED] Step 2: Describe your environment
 
  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____
 
### [REQUIRED] Step 3: Describe the problem
 
#### Steps to reproduce:
 
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
 
#### Relevant Code:
 
// TODO(you): code here to reproduce the problem
```

**Comment by DAKSHSEMWAL** [comment] 2021-01-21 05:46
@makuchaku sorry for the delay from Akshay's Side.I'll provide you with the details.

**Comment by DAKSHSEMWAL** [comment] 2021-01-21 05:49
Android Studio version: 4.1.1
  * Firebase Component:Firestore and Analytics
  * Component version: 22.0.0,18.0.0

**Comment by DAKSHSEMWAL** [comment] 2021-01-21 05:57
[INSERT INTO mutations (uid, batch_id, mutations) VALUES (?, ?, ?)] attempt to write a readonly database
2021-01-12 12:45:32.930 17112-17112/me.dozee.dozee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.dozee.dozee, PID: 17112
    java.lang.RuntimeException: Internal error in Cloud Firestore (22.0.0).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:534)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7829)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:986)
white_tick
eyes
raised_hands





11:26
we dont have such table mutations

**Comment by DAKSHSEMWAL** [comment] 2021-01-21 05:59
sample code for data storage used by us

`fun insertAction(action: String, result: String?, reason: String?) {
        try {
            val userDetailsModel = RealmUtils.getInstance().currentUser
            if (userDetailsModel != null) {
                val email = userDetailsModel.email
                if (email != null) {
                    val mapAction: MutableMap<String, Any> = HashMap()
                    mapAction["email"] = email
                    mapAction["os"] = OS
                    mapAction["timestamp"] = System.currentTimeMillis() / 1000
                    mapAction["action"] = action
                    mapAction["result"] = result!!
                    mapAction["reason"] = reason!!
                    FirebaseHelper.colRefActions().add(mapAction)
                            .addOnSuccessListener { Log.i(TAG, "onSuccess: action added") }
                            .addOnFailureListener { e: Exception? -> Log.i(TAG, "onFailure: failed to add action", e) }
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }`

**Comment by DAKSHSEMWAL** [comment] 2021-01-21 05:59
Sample Code for data storage by us

fun insertAction(action: String, result: String?, reason: String?) {
        try {
            val userDetailsModel = RealmUtils.getInstance().currentUser
            if (userDetailsModel != null) {
                val email = userDetailsModel.email
                if (email != null) {
                    val mapAction: MutableMap<String, Any> = HashMap()
                    mapAction["email"] = email
                    mapAction["os"] = OS
                    mapAction["timestamp"] = System.currentTimeMillis() / 1000
                    mapAction["action"] = action
                    mapAction["result"] = result!!
                    mapAction["reason"] = reason!!
                    FirebaseHelper.colRefActions().add(mapAction)
                            .addOnSuccessListener { Log.i(TAG, "onSuccess: action added") }
                            .addOnFailureListener { e: Exception? -> Log.i(TAG, "onFailure: failed to add action", e) }
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

**Comment by DAKSHSEMWAL** [comment] 2021-01-21 06:00
public class FirebaseHelper {

    private static FirebaseFirestore getFirestore(){
        return FirebaseFirestore.getInstance();
    }

    public static CollectionReference colRefUsers(){
        return getFirestore().collection("users");
    }

    public static CollectionReference colRefSessions(){
        return getFirestore().collection("sessions");
    }

    public static CollectionReference colRefActions(){
        return getFirestore().collection("actions");
    }

    public static CollectionReference colRefSleepMusic(){
        return getFirestore().collection("testing");
    }

    public static CollectionReference colRefGuidedMeditation(){
        return getFirestore().collection("testing_meditation");
    }

}

**Comment by wilhuff** [comment] 2021-01-21 19:14
Firestore uses SQLite for its offline storage and the `mutations` table is a part of its schema.

Looking at your sample code, you're not doing anything unconventional or that would otherwise cause this--you're just adding a document to a collection. Adding a document to a collection does write to the `mutations` table, so this issue is related to the action you've taken, but the cause is something else.

Googling around for possible causes, it seems that if you're getting a `SQLiteReadOnlyDatabaseException`, something in your application is either actually moving the database files or potentially closing Firestore's SQLite connection out from underneath it. If you see `SQLiteLog` warnings in the log with text like `file unlinked while open` that would confirm it.

One potential cause of this is the activity that owns the context used to open Firestore has been destroyed. Is your app changing locales or making other changes that might cause the activity to be recreated? If you're not sure, you could add log entries to your main Activity's `onDestroy` method. If those changes are intentional, you may need to add a call to [`FirebaseFirestore.terminate()`](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#terminate()) in your activity's `onDestroy` method.

This is the first we're hearing of this kind of issue related to Firestore, so if that advice doesn't help, we'll need your help to narrow down what's going wrong. You say that this happens "randomly"--it would be helpful to try to figure out the circumstances that cause this. For example, does it happen when launching your app from a notification, or while in the background, or any other circumstance? If you can find a circumstance where this is more probable we may be able to figure out what's causing this. Another alternative is to put together a small app that reproduces the issue.

Please let us know your findings and we can figure out next steps.

**Comment by DAKSHSEMWAL** [comment] 2021-01-22 05:07
Sure @wilhuff

**Comment by DAKSHSEMWAL** [comment] 2021-01-22 12:21
Hi @wilhuff this happened again. This time it happened when I had a network selection menu opened and I switched from the app to the phone app and the app crashed. giving this error 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.dozee.dozee, PID: 8003
    java.lang.RuntimeException: Internal error in Cloud Firestore (22.0.0).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:534)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.RuntimeException: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database - SQLITE_READONLY_DBMOVED (Sqlite code 1032 SQLITE_READONLY_DBMOVED), (OS error - 2:No such file or directory)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:325)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database - SQLITE_READONLY_DBMOVED (Sqlite code 1032 SQLITE_READONLY_DBMOVED), (OS error - 2:No such file or directory)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:875)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:776)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1900)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1872)
        at com.google.firebase.firestore.local.SQLitePersistence.execute(SQLitePersistence.java:349)
        at com.google.firebase.firestore.local.SQLiteMutationQueue.addMutationBatch(SQLiteMutationQueue.java:190)
        at com.google.firebase.firestore.local.LocalStore.lambda$writeLocally$1(LocalStore.java:236)
        at com.google.firebase.firestore.local.LocalStore$$Lambda$2.get(Unknown Source:8)
        at com.google.firebase.firestore.local.SQLitePersistence.runTransaction(SQLitePersistence.java:207)
        at com.google.firebase.firestore.local.LocalStore.writeLocally(LocalStore.java:207)
        at com.google.firebase.firestore.core.SyncEngine.writeMutations(SyncEngine.java:270)
        at com.google.firebase.firestore.core.FirestoreClient.lambda$write$11(FirestoreClient.java:204)
        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$11.run(Unknown Source:6)
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:436)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(Unknown Source:2)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:322)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(Unknown Source:4) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229) 
        at java.lang.Thread.run(Thread.java:929) 
E/FirebaseCrashlytics: Tried to write a fatal exception while no session was open.
I/Process: Sending signal. PID: 8003 SIG: 9
`

**Comment by wilhuff** [comment] 2021-01-22 17:53
I'm glad you're able to reproduce this, but you'll need to take some of the troubleshooting steps I've outlined to figure out what it is about your application that's causing this interaction. We're not seeing this exception ourselves in our testing.

**Comment by DAKSHSEMWAL** [comment] 2021-01-29 05:13
The team is currently in between deploying other features. So we weren't able to apply the above fixes. I Will get back to you as soon as we work on this. Thanks for the patience.

**Comment by DAKSHSEMWAL** [comment] 2021-02-01 10:10
Hey @wilhuff  is this the correct implementation 

```
override fun onDestroy()
 {
        FirebaseFirestore.getInstance().terminate()
        super.onDestroy()
 }

```
 I have inserted this code in the BaseActivity of our project

**Closed** 2021-02-15 02:01 UTC
Labels: api: firestore, needs-info, no-recent-activity
