### ISSUE TITLE
Failing to initialize Crashlytics due to an exception on datatransport Logging.isLoggable (API 24)

### ISSUE THREAD

**Issue by fpitters** [firebase/firebase-android-sdk#3830] opened 2022-06-22 11:16 UTC
Similar to https://github.com/firebase/firebase-android-sdk/issues/3716 but for API 24.
We are getting:
```
Initializing Firebase Crashlytics 18.2.11 for no.tv2.sumo
Crashlytics report could not be enqueued to DataTransport
java.lang.IllegalArgumentException: Log tag "TRuntime.SQLiteEventStore" exceeds limit of 23 characters

    at android.util.Log.isLoggable(Native Method)
    at com.google.android.datatransport.runtime.logging.Logging.d(Logging.java:64)
    at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.persist(SQLiteEventStore.java:104)
    at com.google.android.datatransport.runtime.scheduling.DefaultScheduler.lambda$schedule$0$com-google-android-datatransport-runtime-scheduling-DefaultScheduler(DefaultScheduler.java:83)
    at com.google.android.datatransport.runtime.scheduling.DefaultScheduler$$ExternalSyntheticLambda0.execute(D8$$SyntheticClass)
    at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:754)
    at com.google.android.datatransport.runtime.scheduling.DefaultScheduler.lambda$schedule$1$com-google-android-datatransport-runtime-scheduling-DefaultScheduler(DefaultScheduler.java:81)
    at com.google.android.datatransport.runtime.scheduling.DefaultScheduler$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
    at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

We have seen it only on a Sagemcom device with a custom firmware 7.0 so it could be is specific to this device.

For now we are removing the `isLoggable` with R8 rules now.

**Comment by argzdev** [comment] 2022-06-22 11:29
Thanks for reporting, @fpitters. This issue is a duplicate of #3823. The pull request for this has been merged a few days ago, however I can't provide any specific timeline when this fix will be available, but you may keep an eye out on our [release notes](https://firebase.google.com/support/releases) from time to time to check out the latest features and bug fixes.

**Closed by argzdev** 2022-06-22 11:29 UTC
Labels: api: datatransport
