### ISSUE TITLE
How do I manually parse the symbol table based on the data provided by the Firebase Console

### ISSUE THREAD

**Issue by hjlove** [firebase/firebase-android-sdk#2511] opened 2021-03-16 10:25 UTC
Native Crash occurred without uploading the symbol table to Firebase.
The Firebase Console TXT column shows that the log is not being parsed properly by the addr2line script.

Below is the Native Crash log I copied from Firebase Crashlytics, How can I parse it correctly?

Crashed: Thread :  SIGABRT  0x0000000000000000
#00 pc 0x7e2712d2a8 libc.so 
#01 pc 0x7e2712d278 libc.so 
#02 pc 0x7e2712d9e8 libc.so 
#03 pc 0x7d30f3d480 libglipcore.so 
#04 pc 0x7d2c1b0820 libglipcore.so 
#05 pc 0x7da6555350 libart.so

**Comment by aguatno** [comment] 2021-03-16 11:04
Thanks for reporting. It seems that you've also asked this issue on a separate ticket. I'm going to close as this duplicate of #2512

**Closed by aguatno** 2021-03-16 11:04 UTC
Labels: api: crashlytics

**Comment by hjlove** [comment] 2021-03-16 14:14
Okay, thank you
