### ISSUE TITLE
Firebase realtime database is not retrieveing data from firebase

### ISSUE THREAD

**Issue by friday-dev** [firebase/firebase-android-sdk#1941] opened 2020-09-05 16:52 UTC
Firebase  database is not loading any values. Everything was fine 2ago. If I run in emulator it is working fine . If I switch back to my mobile network Vodafone it is not working.

**Comment by schmidt-sebastian** [comment] 2020-09-18 20:47
Duplicate of https://github.com/firebase/firebase-android-sdk/issues/1961

**Closed by schmidt-sebastian** 2020-09-18 20:47 UTC
Labels: api: database
