### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered: lu@5bcf89b

### ISSUE THREAD

**Issue by GrahamDi** [firebase/firebase-android-sdk#2244] opened 2020-12-09 10:27 UTC
### My environment

flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.20270.1], locale en-ZA)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android
    • ANDROID_SDK_ROOT = D:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\dicki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (2 available)
    • FIG LX1 (mobile)             • HBEDU18117010246 • android-arm64 • Android 9 (API 28)
    • AOSP on IA Emulator (mobile) • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

**Ignore the Android Studio errors shown above as this is simply a reporting error in Flutter doctor in version 1.22.4. The plugins are installed and fully working**

  ****************************************************************************
  * Flutter Packages: Google Firebase, Firestore, Authentication, etc.
  ****************************************************************************
  cloud_functions: ^0.7.2
  firebase_analytics: ^6.3.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_database: ^4.4.0
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  google_sign_in: ^4.5.6
 
  ****************************************************************************
  * build.gradle dependencies
  ****************************************************************************
  implementation platform('com.google.firebase:firebase-bom:26.1.0')
  // When using the BoM, you don't specify versions in Firebase library dependencies
  implementation 'com.google.firebase:firebase-analytics'
  implementation 'com.google.firebase:firebase-auth'
  implementation 'com.google.firebase:firebase-crashlytics'
  implementation 'com.google.firebase:firebase-database'
  implementation 'com.google.firebase:firebase-firestore'
  implementation 'com.google.firebase:firebase-messaging'
  implementation 'com.google.firebase:firebase-storage'

  def billing_version = "3.0.0"
  implementation 'com.android.billingclient:billing:$billing_version'
  implementation 'com.google.android.gms:play-services-basement:17.5.0'

### Describe the problem

The following warning messages are shown repeatedly while trying to debug an app on emulators or physical devices. Makes the debugging process / experience less than ideal.

W/ConnectionTracker(12809): Exception thrown while unbinding
W/ConnectionTracker(12809): java.lang.IllegalArgumentException: Service not registered: lu@5bcf89b
W/ConnectionTracker(12809): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1755)
W/ConnectionTracker(12809): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1925)
W/ConnectionTracker(12809): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
W/ConnectionTracker(12809): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):1)
W/ConnectionTracker(12809): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):2)
W/ConnectionTracker(12809): 	at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):9)
W/ConnectionTracker(12809): 	at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):3)
W/ConnectionTracker(12809): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):3)
W/ConnectionTracker(12809): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
W/ConnectionTracker(12809): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(12809): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):5)

This similar issue https://github.com/firebase/firebase-android-sdk/issues/1662 was raised 6 months ago and has **many** people waiting for a solution. However, there is still no one assigned nor is the single contributor responding to questions on progress. I am therefore raising a new issue in the hope that it will receive some attention.

Many thanks.

#### Steps to reproduce:

Run debug (in VSCode in my case) on the emulator or a USB connected device and the messages will soon appear, and continue to do so.

#### Relevant Code:

Not applicable - see environment details above for gradle dependencies.

**Comment by deepak786** [comment] 2020-12-09 15:48
Have the same issue:

<img width="976" alt="Screen Shot 2020-12-09 at 8 30 01 PM" src="https://user-images.githubusercontent.com/14223997/101652179-f0bca400-3a63-11eb-98bd-06dfbfec38bb.png">


``` 
    firebase_core: ^0.5.3
    firebase_auth: ^0.18.4+1
    firebase_analytics: ^6.3.0
    firebase_database: ^4.4.0
    firebase_storage: ^5.2.0
```

**Comment by kbokarius** [comment] 2020-12-09 17:04
Same issue here.

**Comment by al-sadi** [comment] 2020-12-09 18:23
Same here as well

**Comment by Akiat** [comment] 2020-12-09 23:47
Same here with:

  firebase_core: ^0.5.3
  firebase_messaging: 8.0.0-dev.10

**Comment by Enghow** [comment] 2020-12-10 07:03
I am facing this issue as well and it really bothers as I'm not sure if it's the code issues or what. For me, I've tested a couple of times regarding the dependencies and turns out removing the firebase analytics works for me. Hope it helps

**Comment by dariowskii** [comment] 2020-12-10 08:07
Same issue:

```
firebase_core: ^0.5.3
firebase_auth: ^0.18.4
cloud_firestore: ^0.14.4
```

**Comment by satyajitghana** [comment] 2020-12-10 16:01
same here:

```
  # firebase
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
```

**Comment by gjae** [comment] 2020-12-10 23:13
Same issue, i just use   `firebase_messaging: ^7.0.3`

**Comment by NarHakobyan** [comment] 2020-12-11 10:21
Any news? I have the same issue

`W/ConnectionTracker(30432): Exception thrown while unbinding
W/ConnectionTracker(30432): java.lang.IllegalArgumentException: Service not registered: lu@af38353
W/ConnectionTracker(30432): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1870)
W/ConnectionTracker(30432): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1848)
W/ConnectionTracker(30432): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:755)
W/ConnectionTracker(30432): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):1)
W/ConnectionTracker(30432): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):2)
W/ConnectionTracker(30432): 	at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):9)
W/ConnectionTracker(30432): 	at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):3)
W/ConnectionTracker(30432): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):3)
W/ConnectionTracker(30432): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(30432): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(30432): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):5)`

**Comment by GrahamDi** [comment] 2020-12-11 10:31
@NarHakobyan Seems like https://github.com/firebase/firebase-android-sdk/issues/1662 has started up again so hopefully we'll get resolution there. @ashwinraghav is responding on that issue.

**Comment by NarHakobyan** [comment] 2020-12-11 10:33
@GrahamDi thanks for info 🙋‍♂️

**Comment by amiruljack** [comment] 2020-12-13 04:24
same here

**Comment by LN-Dark** [comment] 2020-12-13 20:02
Same here

W/ConnectionTracker( 6660): Exception thrown while unbinding
W/ConnectionTracker( 6660): java.lang.IllegalArgumentException: Service not registered: ls@612e5ea
W/ConnectionTracker( 6660): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757)
W/ConnectionTracker( 6660): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1874)
W/ConnectionTracker( 6660): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
W/ConnectionTracker( 6660): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204713097@20.47.13 (150400-0):1)
W/ConnectionTracker( 6660): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204713097@20.47.13 (150400-0):2)
W/ConnectionTracker( 6660): 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204713097@20.47.13 (150400-0):9)
W/ConnectionTracker( 6660): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204713097@20.47.13 (150400-0):3)
W/ConnectionTracker( 6660): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204713097@20.47.13 (150400-0):3)
W/ConnectionTracker( 6660): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker( 6660): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 6660): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204713097@20.47.13 (150400-0):5)

**Comment by baharudin-yusup** [comment] 2020-12-14 06:31
Same Here

W/ConnectionTracker(22108): Exception thrown while unbinding
W/ConnectionTracker(22108): java.lang.IllegalArgumentException: Service not registered: ls@30256f4
W/ConnectionTracker(22108): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1759)
W/ConnectionTracker(22108): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1787)
W/ConnectionTracker(22108): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:751)
W/ConnectionTracker(22108): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):1)
W/ConnectionTracker(22108): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):2)
W/ConnectionTracker(22108): 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):9)
W/ConnectionTracker(22108): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):3)
W/ConnectionTracker(22108): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):3)
W/ConnectionTracker(22108): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(22108): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(22108): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):5)

**Comment by benyaminbeyzaie** [comment] 2020-12-14 10:04
same here

**Comment by benyaminbeyzaie** [comment] 2020-12-14 10:04
same here

**Comment by vkryachko** [comment] 2020-12-14 13:12
Duplicate of #1662

**Closed by vkryachko** 2020-12-14 13:12 UTC
Labels: needs-triage

**Comment by danielgchap** [comment] 2020-12-16 18:14
Ditto!
`java.lang.IllegalArgumentException: Service not registered: lu@6ca864b`
