### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteException: cannot commit - no transaction is active (code 1 SQLITE_ERROR)

### ISSUE THREAD

**Issue by hram** [firebase/firebase-android-sdk#4496] opened 2022-12-23 12:55 UTC
BOM verion is 31.1.0

I have many crash reports

Fatal Exception: android.database.sqlite.SQLiteException: cannot commit - no transaction is active (code 1 SQLITE_ERROR)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:403)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:585)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:772)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:121)
       at com.google.android.datatransport.runtime.ForcedSender.sendBlocking(ForcedSender.java:31)
       at com.google.**firebase**.**crashlytics**.internal.send.ReportQueue.lambda$flushScheduledReportsIfAble$0$com-google-firebase-crashlytics-internal-send-ReportQueue(ReportQueue.java:128)
       at com.google.**firebase**.**crashlytics**.internal.send.ReportQueue$$ExternalSyntheticLambda1.run(:4)
       at java.lang.Thread.run(Thread.java:919)

I have no idea how to reproduce this one

**Comment by argzdev** [comment] 2022-12-23 14:32
Thanks for reporting, @hram. Could you answer a few questions below:
1. Which version where you previously using before experiencing this issue?
2. Do you have any code snippets related to Firebase Crashlytics?

These might give us a hint what the issue is. Thanks!

**Comment by hram** [comment] 2022-12-23 15:42
1. before experiencing this issue I using bom version 30.1.0
2. no code related with this issue, in addition I can say that exception occurs immediately after the application starts

**Comment by argzdev** [comment] 2022-12-23 15:51
Thanks for the immediate response, @hram. I'll notify our engineers and see what we can do here.

**Comment by mrober** [comment] 2023-01-12 15:15
This should be fixed in the next release. If you still experience this after, please reopen this issue.

**Closed by mrober** 2023-01-12 15:15 UTC
Labels: api: crashlytics
