### ISSUE TITLE
NullPointerException on 

### ISSUE THREAD

**Issue by vyguera** [firebase/firebase-android-sdk#2249] opened 2020-12-11 15:04 UTC
I've recently received an exception on my app apparently not related to any particular feature on my side.

This is the exception:

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getQueryParameter(java.lang.String)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2735)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getQueryParameter(java.lang.String)' on a null object reference
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver.onReceive(AlarmManagerSchedulerBroadcastReceiver.java:31)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2728)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

These are my firebase versions:
```
    implementation 'com.google.firebase:firebase-messaging:20.3.0'
    implementation 'com.google.firebase:firebase-core:17.5.1'
    implementation 'com.google.firebase:firebase-crashlytics:17.2.2'
    implementation 'com.google.firebase:firebase-analytics:17.6.0'
```

I am unable to reproduce the crash, and I have no idea what the problem could came but let me know if I can give any further information.

**Comment by Michael-ortega1** [comment] 2020-12-19 02:42
I just encountered this crash in my app on Android Marshmallow that uses Firebase. Nothing in my code could be causing this naturally

**Comment by willme1** [comment] 2021-01-01 08:19
Same issue here on a  Nexus 4 with 6.0.1

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getQueryParameter(java.lang.String)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2735)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Enstone** [comment] 2021-01-01 20:57
Same issue on a Nexus 4 with 6.0.1
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getQueryParameter(java.lang.String)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2735)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getQueryParameter(java.lang.String)' on a null object reference
       at com.google.android.datatransport.runtime.AutoValue_TransportContext$Builder.setExtras(AutoValue_TransportContext.java)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2728)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by dbdevtop** [comment] 2021-01-02 09:10
Same issue on a Nexus 4, Android 6.0.1

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getQueryParameter(java.lang.String)' on a null object reference

**Comment by diegocidm4** [comment] 2021-01-02 13:38
Same issue on a Nexus 4, Android 6.0.1
Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getQueryParameter(java.lang.String)' on a null object reference

**Comment by freakdragon** [comment] 2021-01-13 06:45
Have the same issue on a Nexus 4, Android 6.0.1.

In a minute after this error there is occurs error like this:

Fatal Exception: java.lang.RuntimeException: Unable to instantiate service com.google.android.gms.analytics.AnalyticsService: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.analytics.AnalyticsService" on path: DexPathList[[zip file "/data/app/ru.bundle.name-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.bundle.name-1/lib/x86, /data/app/ru.bundle.name-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2865)
       at android.app.ActivityThread.-wrap4(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by matpag** [comment] 2021-02-01 08:15
We have the same crash, it seems only the Nexus 4 with Android 6.0.1 is affected from this.
Is there something we can do to mitigate this crash in the meantime?

**Comment by kimrtaylor** [comment] 2021-02-01 13:25
Same for us, on Nexus 4 Android 6.0.1

**Comment by DaphnevdVeeke** [comment] 2021-02-04 22:48
Same issue for me, just on Nexus 4 Android 6.0.1

**Comment by diegogarciar** [comment] 2021-02-05 01:03
I did some research, nexus 4 has no official support Android 6. So users that have that combination might have tricked the os. Could this be the cause for the issue?

**Comment by VinayGuthal** [comment] 2021-02-05 17:55
Hey thanks for posting this issue. I will have a look at this and get back to this thread :)

**Comment by VinayGuthal** [comment] 2021-11-15 18:57
The code seems fine and this issue seems to be happening only on nexus 4 devices since it has no official support for Android 6 and the intent data might be lost in this case bcz of this. Closing this issue for now

**Closed by VinayGuthal** 2021-11-15 18:57 UTC
Labels: api: core

**Comment by coolchengc** [comment] 2021-12-01 08:08
I encountered a similar problem and couldn't find the problem, so I ask for help. this is log 
===================================================================
java.lang.RuntimeException: Unable to start receiver com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver: java.lang.NumberFormatException: s == null
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4977)
	at android.app.ActivityThread.access$2800(ActivityThread.java:278)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:296)
	at android.app.ActivityThread.main(ActivityThread.java:8875)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)
Caused by: java.lang.NumberFormatException: s == null
	at java.lang.Integer.parseInt(Integer.java:577)
	at java.lang.Integer.valueOf(Integer.java:801)
	at com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver.onReceive(AlarmManagerSchedulerBroadcastReceiver.java:3)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4968)
