### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.common.internal.zzf@47729ac

### ISSUE THREAD

**Issue by Roy1994419** [firebase/firebase-android-sdk#1388] opened 2020-03-25 02:47 UTC
Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.common.internal.zzf@47729ac
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1680)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
       at com.google.android.gms.common.stats.ConnectionTracker.unbindService(:25)
       at com.google.android.gms.common.internal.zzf.zzf(:41)
       at com.google.android.gms.common.internal.zze.handleMessage(:45)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at com.google.android.gms.internal.common.zze.dispatchMessage(:8)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7094)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by ashwinraghav** [comment] 2020-04-09 21:47
Hi,
To help you better, we need more information. Can you fill in details that our issue template recommends?
```
<!-- DO NOT DELETE 
validate_template=true
template_path=.github/ISSUE_TEMPLATE/bug.md
-->

### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
```

**Comment by TOPWN** [comment] 2020-04-19 07:22
Same issue, please  fix this

**Comment by DaveBoy** [comment] 2020-04-24 01:27
i found the same issue after i change applicationid 、 packagename 、and google-services.json 。it happen after i change the language and clean all activity to start a new activity。then the app crash happen after 10s（probably） 。
then the app crash every time when i start the app 10s。unless i clear the data from setting。

i don‘t know wt cause it。

![image](https://user-images.githubusercontent.com/16101638/80165182-7ee73580-860d-11ea-9e2c-4223e0fc810b.png)

**Comment by DaveBoy** [comment] 2020-04-24 05:31
i solve this bug for me，it because i'm update the library [utilcode 1.28.1](https://github.com/Blankj/AndroidUtilCode/tree/master/lib/utilcode)  from 1.26.0.when i down the utilcode version .this crash not happen. but i can't found how it cause the bug.

this version of firebase  i have used:
![image](https://user-images.githubusercontent.com/16101638/80176026-eca15a80-8629-11ea-9c34-d3baefa7a45a.png)

**Comment by ashwinraghav** [comment] 2020-05-29 20:35
Based on @DaveBoy 's comment, the bug seems to be triggered by a library external to Firebase itself. We are not super familiar with [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode/issues/1223). Feel free to propose a fix that will make Firebase compatible with the version that's failing for you.

**Comment by TOPWN** [comment] 2020-06-09 09:06
https://github.com/firebase/firebase-android-sdk/issues/1348#issuecomment-632062876

**Comment by ashwinraghav** [comment] 2020-06-09 18:32
Duplicate of #1348

**Closed by ashwinraghav** 2020-06-09 18:32 UTC
Labels: needs-info, needs-triage
