### ISSUE TITLE
Firestore is not working after WebRTC disconnection

### ISSUE THREAD

**Issue by Sonumohammad** [firebase/firebase-android-sdk#3092] opened 2021-11-01 09:46 UTC
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: Firestore
  * Component version: 23.0.4

### [REQUIRED] Step 3: Describe the problem

I am using WebRTC in WebView, using the [simple-peer.js](https://github.com/feross/simple-peer) library.
After calling peer.destroy() (javascript), Firestore (android) is not working properly.
Snapshot listener is not firing new document changes, but I can see changes in the console.

#### Steps to reproduce:

1. Write a simple javascript program using simple peer library.

2. Add Html and js files to app assets.

3. Open the js program with webview.

4. Do signaling and connect two peers.

5. Call `webview.evaluate("peer.destroy()")`

Now Firestore snapshot listener stops working.

We have to do this to listen again:
snapshotListenerRegistration.remove()
`snapshotListenerRegistration = documentReference.addSnapshotListener(...)`
But doing this every time WebRTC disconnects, for multiple listeners costs extra document reads

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment] 2021-11-01 18:37
Hi @Sonumohammad, thanks for the report. I'll try to replicate this issue, and see what I can find. If you could provide us an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), that would be very helpful as well. Thanks.

**Comment by argzdev** [comment] 2021-11-01 18:41
Hi @Sonumohammad, thanks for reporting. I'll try replicating the issue and see what I can find. In the meantime, if you could provide us an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), that'll be very helpful for us. Thanks.

**Comment by argzdev** [comment] 2021-11-02 14:14
Hi @Sonumohammad, I was able to make the simple peer work on two browsers. However, 
I'm unable to run the simple-peer html file on an Android device; an issue is encountered when I add this to a WebView.

`"Uncaught Error: No WebRTC support: Not a supported browser", source: https://appassets.androidplatform.net/assets/simplepeer.min.js `

Here is my code snippet:
```
WebView mWebView = findViewById(R.id.webview);
mWebView.getSettings().setJavaScriptEnabled(true);
final WebViewAssetLoader assetLoader = new WebViewAssetLoader.Builder()
    .addPathHandler("/assets/", new WebViewAssetLoader.AssetsPathHandler(this))
    .build();

mWebView.setWebViewClient(new LocalContentWebViewClient(assetLoader));
mWebView.loadUrl("https://appassets.androidplatform.net/assets/index.html");
```

Am I missing anything?

**Comment by Sonumohammad** [comment] 2021-11-02 16:03
Your WebView version doesn't support WebRTC.
Update WebView and Chrome apps from PlayStore.

**Comment by argzdev** [comment] 2021-11-03 09:09
Hi @Sonumohammad, thanks for the advice. I'm able to run the simple peer on an Android device now, however I’m unable to replicate this issue.

The following steps were what I tried:
1. Open a simple peer on a Chrome browser on a computer as a receiver
2. Open a simple peer via WebView as the initiator on an Android device. Once the app has been opened, Firestore Database connection is also established.
3. Connect both devices
4. Try sending messages to both devices to confirm connectivity is working.
5. Click Destroy Peer on Android device to close connection
6. Sending messages should fail since connection has been closed
7. Manually update Firestore Database values on the Firebase console to see if connection has been severed.
8. Was still able to receive logs regarding the update in addSnapshotListener

The connection was not severed, perhaps there are other library dependencies that are conflicting with your setup. You could try creating a new Android project with only Firestore Database and the simple peer program to cross check what issue might be conflicting with your project.

If you’d like us to further investigate this, kindly provide us with an MCVE. Thanks.

**Comment by Sonumohammad** [comment] 2021-11-03 09:22
In step 7, instead of manually changing in console, change programmatically.
After peer.onClose() i am informing it to WebAppInsterface.
`Android.close()` (javascript)
In WebAppInterface
`@JavaScriptInterface
public void close() {
        // update document and check if snapShotListener updates
}`

**Comment by argzdev** [comment] 2021-11-03 12:22
I'm unable to replicate the issue even by updating it programmatically via WebAppInterface. I've tried 2 scenarios where in the 1st scenario, closing the peer connection within the javascript file, and the 2nd scenario closing the peer connection via Android layout (mWebView.evaluateJavascript...). In both scenarios, Firestore Database was still functioning properly after severing the connection.

This code snippet is for destroying the peer connection within the javascript file:
```
function destroyPeer(){
  p.destroy();
}
```

This code snippet is for destroying the peer connection when clicking a button on an Android layout:
```
public void destroyPeer(View view) {
    mWebView.evaluateJavascript("p.destroy()", value -> Log.d(TAG, "onReceiveValue: " + value));
}
```

If I try a 3rd scenario, which is to execute peer.close via WebAppInterface. An error is encountered:
`java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'JavaBridge'. All WebView methods must be called on the same thread.`

Code Snippet:
```
@JavascriptInterface
public void closeConnection(){
    mWebView.evaluateJavascript("p.destroy()", value -> Log.d(TAG, "onReceiveValue: " + value));
}
```

With that said, is there any particular reason why peer.close is being called via WebAppInterface? Since this can be called directly within the javascript function, and then additional codes can be invoked in WebAppInterface. (e.g. Scenario 1 or 2)

**Comment by argzdev** [comment] 2021-11-03 16:36
You could try adding [setLoggingEnabled](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#public-static-void-setloggingenabled-boolean-loggingenabled) in your code to investigate this further. If you can provide us some stack trace of the Cloud Firestore during the time of the disconnection, that would be helpful as well.

**Comment by Sonumohammad** [comment] 2021-11-11 05:45
Here are the logs.
But I can see changes in the Firebase Firestore console.

1636606931.461 I/chromium: [INFO:CONSOLE(51)] "error: ERR_DATA_CHANNEL - Transport channel closed", source: file:///android_asset/WebRTC.js (51)
1636606931.465 I/chromium: [INFO:CONSOLE(46)] "close", source: file:///android_asset/WebRTC.js (46)
1636606931.471 I/Firestore: (23.0.4) [Persistence]: Starting transaction: Locally write mutations
1636606931.501 I/Firestore: (23.0.4) [Persistence]: Starting transaction: notifyLocalViewChanges
1636606931.528 I/Firestore: (23.0.4) [WriteStream]: (1334db4) Stream sending: # com.google.firestore.v1.WriteRequest@3fc467c8
    stream_token: "\020\006\031\020hB\002\201\364\265\265"
    writes {
      current_document {
        exists: true
      }
      // removed document data.
      // After disconnecting, the document should be updated.
      // for example, status=disconnected
    }
1636606931.678 I/Firestore: (23.0.4) [WriteStream]: (1334db4) Stream received: # com.google.firestore.v1.WriteResponse@dd6d23c5
    commit_time {
      nanos: 420107000
      seconds: 1636606797
    }
    stream_token: "\020\a\031\020hB\002\201\364\265\265"
    write_results {
      transform_results {
        integer_value: 0
      }
      update_time {
        nanos: 420107000
        seconds: 1636606797
      }
    }
1636606931.681 I/Firestore: (23.0.4) [Persistence]: Starting transaction: Acknowledge batch
1636606931.720 I/Firestore: (23.0.4) [Persistence]: Starting transaction: notifyLocalViewChanges
1636606942.058 I/Firestore: (23.0.4) [Persistence]: Starting transaction: Collect garbage
1636606942.070 I/Firestore: (23.0.4) [LruGarbageCollector]: Garbage collection skipped; Cache size 2433024 is lower than threshold 104857600
1636606983.472 I/Firestore: (23.0.4) [WatchStream]: (268d8a) Performing stream teardown
1636606983.473 I/Firestore: (23.0.4) [WatchStream]: (268d8a) Closing stream client-side
1636606983.578 I/Firestore: (23.0.4) [WatchStream]: stream callback skipped by CloseGuardedRunner.
1636606991.725 I/Firestore: (23.0.4) [WriteStream]: (1334db4) Performing stream teardown
1636606991.731 I/Firestore: (23.0.4) [WriteStream]: (1334db4) Stream sending: # com.google.firestore.v1.WriteRequest@84d97dce
    stream_token: "\020\a\031\020hB\002\201\364\265\265"
1636606991.737 I/Firestore: (23.0.4) [WriteStream]: (1334db4) Closing stream client-side
1636606991.819 I/Firestore: (23.0.4) [WriteStream]: stream callback skipped by CloseGuardedRunner.

**Comment by argzdev** [comment] 2021-11-11 09:30
Hi @Sonumohammad, there's clearly something going on here, and I'd like to investigate this deeper. But since I'm unable to reproduce this issue, do you think you could share me a sample repro with this issue so I can check this?

**Closed** 2021-11-25 02:01 UTC
Labels: api: firestore, needs-info, no-recent-activity
