### ISSUE TITLE
ANR triggered by a deadlock involving the main thread

### ISSUE THREAD

**Issue by JonathanKranz** [firebase/firebase-android-sdk#4834] opened 2023-03-30 02:57 UTC
Firebase version: com.google.firebase:firebase-bom:31.2.2

main (blocked):tid=1 systid=8074 | waiting to lock <0x06bf4b42> (java.lang.Class<sh.a>) held by thread 35
       at com.google.firebase.perf.config.ConfigResolver.getInstance(ConfigResolver.java)
       at com.google.firebase.perf.FirebasePerfEarly.<init>(FirebasePerfEarly.java:41)
       at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(FirebasePerfRegistrar.java:75)
       at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:140)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
       at com.camerasideas.baseutils.FirebaseInit.initializeApp(FirebaseInit.java:24)
       at com.camerasideas.startup.InitializeApmTask.initializeApp(InitializeApmTask.java:59)
       at com.camerasideas.startup.InitializeApmTask.run(InitializeApmTask.java)
       at com.effective.android.anchors.task.Task.run(Task.kt:69)
       at com.effective.android.anchors.AnchorsRuntime.tryRunBlockTask$anchors_release(AnchorsRuntime.java:115)
       at com.effective.android.anchors.AnchorsManager.start(AnchorsManager.java:111)
       at com.camerasideas.startup.StartupInitializer.initialize(StartupInitializer.java:45)
       at com.camerasideas.instashot.InstashotApplication.onCreate(InstashotApplication.java:38)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6986)
       at android.app.ActivityThread.access$1700(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

XXXXAsyncTask #2 (blocked):tid=35 systid=30635 | waiting to lock <0x0f5ba890> (java.lang.Object) held by thread 1
       at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:173)
       at com.google.firebase.perf.config.RemoteConfigManager.getInitialStartupMillis(RemoteConfigManager.java:91)
       at com.google.firebase.perf.config.RemoteConfigManager.<init>(RemoteConfigManager.java:85)
       at com.google.firebase.perf.config.RemoteConfigManager.<clinit>(RemoteConfigManager.java:52)
       at com.google.firebase.perf.config.ConfigResolver.<init>(ConfigResolver.java:78)
       at com.google.firebase.perf.config.ConfigResolver.getInstance(ConfigResolver.java:86)
       at com.google.firebase.perf.application.AppStateMonitor.<init>(AppStateMonitor.java:98)
       at com.google.firebase.perf.application.AppStateMonitor.getInstance(AppStateMonitor.java:87)
       at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.<init>(NetworkRequestMetricBuilder.java:92)
       at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.builder(NetworkRequestMetricBuilder.java:84)
       at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.<init>(InstrumentOkHttpEnqueueCallback.java:42)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.enqueue(FirebasePerfOkHttpClient.java:73)
       at retrofit2.OkHttpCall.enqueue(OkHttpCall.java:117)
       at com.camerasideas.baseutils.network.retrofit.RealDownloadCall.enqueue(RealDownloadCall.java)
       at com.camerasideas.baseutils.network.retrofit.RealDownloadCall.enqueue(RealDownloadCall.java)
       at com.camerasideas.instashot.store.festival.FestivalInfoLoader.download(FestivalInfoLoader.java:457)
       at com.camerasideas.instashot.store.festival.FestivalInfoLoader.prepareInfo(FestivalInfoLoader.java:483)
       at com.camerasideas.instashot.store.festival.FestivalInfoLoader.access$100(FestivalInfoLoader.java:83)
       at com.camerasideas.instashot.store.festival.FestivalInfoLoader$1.run(FestivalInfoLoader.java:169)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
![WX20230330-105727@2x](https://user-images.githubusercontent.com/17563004/228716786-db770615-ec45-406c-a960-a65b1c56f8fc.png)

**Comment by argzdev** [comment] 2023-03-30 09:29
Thanks for reporting, @JonathanKranz. This seems to be a duplicate of #4831. That said, can you continue your report on that thread? We'll close this for better tracking. Please also leave a thumbs up emoji on the author's main post of #4831 so we can prioritize our investigation depending on severity. Thanks!

**Closed by argzdev** 2023-03-30 09:29 UTC
Labels: needs-triage

**Comment by argzdev** [comment] 2023-03-31 10:08
Hi @JonathanKranz, just wondering, what Firebase BoM version where you previously using before encountering this issue? Also is there any code snippets you could share with us, maybe that'll give us a hint of what's causing the issue.
