### ISSUE TITLE
Remote Config Realtime is Trying to make connection when app is in Background

### ISSUE THREAD

**Issue by dhruvkaushal11** [firebase/firebase-android-sdk#5159] opened 2023-07-13 08:03 UTC
Hi, we are observing this in non fatal in 95% of the background after firebase remote config real-time feature implementation on Production for Android.

com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient.makeRealtimeHttpConnection

As per documentation, it states 

> Although you can manually stop listening for updates, it's often not necessary. Real-time Remote Config automatically stops listening for updates when the app enters the background and restarts when the app is foregrounded.

But I guess this is not happening as expected. We are using 21.3.0 of Remote Config.

<img width="1105" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/16204255/e6c656a5-7b31-4050-871c-c8339deae023">

**Comment by argzdev** [comment] 2023-07-13 09:58
Thanks for reaching out, @dhruvkaushal11. This seems like a major obstacle. Could you help us answer a few questions below. These will help us understand to see what went wrong:

1. What was the prior version you were using before your developers started to exhibit this issue?
2. Can you share code snippets on how your team has implemented our real-time feature?
3. Are there any steps to reproduce this behavior? Any chance you could share with us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? It'll help us speed up the investigation a lot. Thanks!

**Comment by dhruvkaushal11** [comment] 2023-07-14 03:48
Hi @argzdev 
1. Previously we were using 21.1.0
2. We are setting this listener from our Application class. 
**Code Snippet:**
`
     

        PaytmLogs.d("fb_realtime", "Firebase Register Realtime Listener")
        mFirebaseRemoteConfig.addOnConfigUpdateListener(object : ConfigUpdateListener {
            override fun onUpdate(configUpdate : ConfigUpdate) {
                PaytmLogs.d("fb_realtime", "Firebase Fetch Complete:" + configUpdate.updatedKeys) if( configUpdate.updatedKeys.contains(FIREBASE_REALTIME_KEY)){
                    //activate firebase when this key is found
                    PaytmLogs.d("fb_realtime",  "Activating Firebase")
                    mFirebaseRemoteConfig.activate()
                }
                AppManagerHelper.getImplListener().logFirebaseRealtimeRemoteConfigFetchCallEvent(configUpdate.updatedKeys.toString(), true, 0)

            }

            override fun onError(error : FirebaseRemoteConfigException) {
                PaytmLogs.d("fb_realtime",  "Config update error with code: " + error.code, error)
                PaytmCrashlytics.logException(error)
                AppManagerHelper.getImplListener().logFirebaseRealtimeRemoteConfigFetchCallEvent("",false, error.code.value())
            }
        })` 
3. Not sure. Will check and post here. If I am able to reproduce.

**Comment by argzdev** [comment] 2023-07-14 09:34
Thanks for sharing with us these details, @dhruvkaushal11. I forgot to ask, but could you share with us the stacktrace as well?

**Comment by dhruvkaushal11** [comment] 2023-07-14 11:55
Sure here are the logs. 
```
Non-fatal Exception: com.google.firebase.remoteconfig.FirebaseRemoteConfigClientException: Unable to connect to the server. Check your connection and try again.
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient.makeRealtimeHttpConnection(ConfigRealtimeHttpClient.java:361)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient.retryHttpConnectionWhenBackoffEnds(ConfigRealtimeHttpClient.java:341)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient.beginRealtimeHttpStream(ConfigRealtimeHttpClient.java:454)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient$1.run(ConfigRealtimeHttpClient.java:355)
       at com.google.firebase.concurrent.DelegatingScheduledExecutorService.lambda$schedule$0(DelegatingScheduledExecutorService.java:116)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:923)
``` 

Another similar log is: (99% background, 32% Android 12)
```
Non-fatal Exception: com.google.firebase.remoteconfig.FirebaseRemoteConfigServerException: Unable to connect to the server. Try again in a few minutes. HTTP status code: 400
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient.beginRealtimeHttpStream(ConfigRealtimeHttpClient.java:506)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient$1.run(ConfigRealtimeHttpClient.java:355)
       at com.google.firebase.concurrent.DelegatingScheduledExecutorService.lambda$schedule$0(DelegatingScheduledExecutorService.java:116)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by argzdev** [comment] 2023-07-14 13:36
Ah, it looks like the exception should've been caught on this condition before being propagated:

https://github.com/firebase/firebase-android-sdk/blob/3dd80b1824e083126a0dc590c9faa5cb414ea28d/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java#L386

So the most likely issue here is that the `isInBackground` is not being set correctly during state change. I'll let our engineers know about this and see what we can do. Thanks!

**Comment by dhruvkaushal11** [comment] 2023-07-25 04:41
Hi Team,
Any ETA when this can be fixed? We are now reaching this as 2,742,829 non-fatal events affecting 1,606,209 users

**Comment by argzdev** [comment] 2023-07-26 17:28
Hi @dhruvkaushal11, after the investigation of our engineers, we've come to the conclusion that this is not a bug but just an intended behavior. 

> The reason why Crashlytics says it in the background for these exceptions could be due to a race condition between when our SDK thinks it's in the background compared to when Crashlytics is in the background. In the stack trace, there is a reference to a method called `notifyRCInstances`. This method is only called when the app switches from background to foreground or vice versa. And in the case of background to foreground we retry the connection automatically which is what it looks like is happening. So in conclusion I think connections aren't being made in the background, it just looks that way due to a race condition between real-time and crashlytics logging.

Since this is the case, then it would be expected that on each session of each user the worst case scenario they will most likely encounter this exception behavior once or twice during state change of background to foreground or vice versa, but never a continuous call for updates. Also it should be noted that these api calls also implement back off retries with limited retry counts, so ultimately it will not lead to an infinite call.

That said, I'll close this ticket now. Feel free to let me know if you think this is a mistake. If so, please provide with us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) or steps to reproduce this behavior showing repeated calling of the exception.

**Closed by argzdev** 2023-07-26 17:28 UTC
Labels: api: remoteconfig, needs-attention

**Comment by dhruvkaushal11** [comment] 2023-07-27 05:20
Thanks for the update @argzdev.
So, is it safe to ignore this warning as of now? As this non fatal are in millions now for our app.

**Comment by argzdev** [comment] 2023-07-27 10:09
Yes, @dhruvkaushal11. It should be safe to ignore. If the non fatals seems too much, you could specifically filter these types of exceptions, maybe a conditional checker on the `onError` method, however this will entirely depend on what you'd want to achieve.
