### ISSUE TITLE
firebase/firestore: Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.protobuf.GeneratedMessageLite$MethodToInvoke.ordinal()' on a null object reference

### ISSUE THREAD

**Issue by mgenov** [firebase/firebase-android-sdk#442] opened 2019-05-16 08:46 UTC
### Version Information
  * Firebase Component: Firestore
  * Component version: 18.2.0
  * Affected Android Versions: 4.2.2, 5.1.1

### Description

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.protobuf.GeneratedMessageLite$MethodToInvoke.ordinal()' on a null object reference
       at com.google.firebase.firestore.proto.MaybeDocument.dynamicMethod(com.google.firebase:firebase-firestore@@18.2.0:693)
       at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:288)
       at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1353)
       at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1432)
       at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1449)
       at com.google.firebase.firestore.proto.MaybeDocument.parseFrom(com.google.firebase:firebase-firestore@@18.2.0:380)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.decodeMaybeDocument(com.google.firebase:firebase-firestore@@18.2.0:162)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.lambda$getAllDocumentsMatchingQuery$2(com.google.firebase:firebase-firestore@@18.2.0:139)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache$$Lambda$3.accept(com.google.firebase:firebase-firestore@@18.2.0)
       at com.google.firebase.firestore.local.SQLitePersistence$Query.forEach(com.google.firebase:firebase-firestore@@18.2.0:431)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.getAllDocumentsMatchingQuery(com.google.firebase:firebase-firestore@@18.2.0:125)
       at com.google.firebase.firestore.local.LocalDocumentsView.getDocumentsMatchingCollectionQuery(com.google.firebase:firebase-firestore@@18.2.0:182)
       at com.google.firebase.firestore.local.LocalDocumentsView.getDocumentsMatchingQuery(com.google.firebase:firebase-firestore@@18.2.0:140)
       at com.google.firebase.firestore.local.SimpleQueryEngine.getDocumentsMatchingQuery(com.google.firebase:firebase-firestore@@18.2.0:39)
       at com.google.firebase.firestore.local.LocalStore.executeQuery(com.google.firebase:firebase-firestore@@18.2.0:583)
       at com.google.firebase.firestore.core.SyncEngine.initializeViewAndComputeSnapshot(com.google.firebase:firebase-firestore@@18.2.0:189)
       at com.google.firebase.firestore.core.SyncEngine.listen(com.google.firebase:firebase-firestore@@18.2.0:179)
       at com.google.firebase.firestore.core.EventManager.addQueryListener(com.google.firebase:firebase-firestore@@18.2.0:91)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$listen$6(com.google.firebase:firebase-firestore@@18.2.0:152)
       at com.google.firebase.firestore.core.FirestoreClient$$Lambda$6.run(com.google.firebase:firebase-firestore@@18.2.0)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$4(com.google.firebase:firebase-firestore@@18.2.0:311)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$4.call(com.google.firebase:firebase-firestore@@18.2.0)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3(com.google.firebase:firebase-firestore@@18.2.0:287)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(com.google.firebase:firebase-firestore@@18.2.0)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@18.2.0:205)
       at java.lang.Thread.run(Thread.java:818)
```

#### Steps to reproduce:
Happened on slow mobile connection during saving of new documents in the firestore.

**Comment by mikelehen** [comment] 2019-05-16 17:13
@mgenov Thanks for the report. We haven't seen this before and it's a bit strange. One theory we have come up with  is that it could be a mismatch between Firestore and the version of com.google.protobuf that's getting pulled into your app.  Could you provide your gradle dependency tree via https://stackoverflow.com/questions/21645071/using-gradle-to-find-dependency-tree ?  Thanks!

**Comment by mgenov** [comment] 2019-05-17 06:23
@mikelehen here is the releaseRuntimeClasspath:
```
+--- project :react-native-fabric
|    +--- com.facebook.react:react-native:+ -> 0.59.8
|    |    +--- com.facebook.infer.annotation:infer-annotation:0.11.2
|    |    |    \--- com.google.code.findbugs:jsr305:3.0.1 -> 3.0.2
|    |    +--- javax.inject:javax.inject:1
|    |    +--- com.android.support:appcompat-v7:28.0.0
|    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    +--- com.android.support:support-compat:28.0.0
|    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    +--- com.android.support:collections:28.0.0
|    |    |    |    |    \--- com.android.support:support-annotations:28.0.0
|    |    |    |    +--- android.arch.lifecycle:runtime:1.1.1
|    |    |    |    |    +--- android.arch.lifecycle:common:1.1.1
|    |    |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    |    |    |    +--- android.arch.core:common:1.1.1
|    |    |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    |    |    \--- com.android.support:versionedparcelable:28.0.0
|    |    |    |         +--- com.android.support:support-annotations:28.0.0
|    |    |    |         \--- com.android.support:collections:28.0.0 (*)
|    |    |    +--- com.android.support:collections:28.0.0 (*)
|    |    |    +--- com.android.support:cursoradapter:28.0.0
|    |    |    |    \--- com.android.support:support-annotations:28.0.0
|    |    |    +--- com.android.support:support-core-utils:28.0.0
|    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    +--- com.android.support:documentfile:28.0.0
|    |    |    |    |    \--- com.android.support:support-annotations:28.0.0
|    |    |    |    +--- com.android.support:loader:28.0.0
|    |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    |    +--- android.arch.lifecycle:livedata:1.1.1
|    |    |    |    |    |    +--- android.arch.core:runtime:1.1.1
|    |    |    |    |    |    |    +--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    |    |    |    |    |    \--- android.arch.core:common:1.1.1 (*)
|    |    |    |    |    |    +--- android.arch.lifecycle:livedata-core:1.1.1
|    |    |    |    |    |    |    +--- android.arch.lifecycle:common:1.1.1 (*)
|    |    |    |    |    |    |    +--- android.arch.core:common:1.1.1 (*)
|    |    |    |    |    |    |    \--- android.arch.core:runtime:1.1.1 (*)
|    |    |    |    |    |    \--- android.arch.core:common:1.1.1 (*)
|    |    |    |    |    \--- android.arch.lifecycle:viewmodel:1.1.1
|    |    |    |    |         \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    |    |    +--- com.android.support:localbroadcastmanager:28.0.0
|    |    |    |    |    \--- com.android.support:support-annotations:28.0.0
|    |    |    |    \--- com.android.support:print:28.0.0
|    |    |    |         \--- com.android.support:support-annotations:28.0.0
|    |    |    +--- com.android.support:support-fragment:28.0.0
|    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    +--- com.android.support:support-core-ui:28.0.0
|    |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    |    +--- com.android.support:support-core-utils:28.0.0 (*)
|    |    |    |    |    +--- com.android.support:customview:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    |    |    \--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    |    +--- com.android.support:viewpager:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    |    |    \--- com.android.support:customview:28.0.0 (*)
|    |    |    |    |    +--- com.android.support:coordinatorlayout:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    |    |    \--- com.android.support:customview:28.0.0 (*)
|    |    |    |    |    +--- com.android.support:drawerlayout:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    |    |    \--- com.android.support:customview:28.0.0 (*)
|    |    |    |    |    +--- com.android.support:slidingpanelayout:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    |    |    \--- com.android.support:customview:28.0.0 (*)
|    |    |    |    |    +--- com.android.support:interpolator:28.0.0
|    |    |    |    |    |    \--- com.android.support:support-annotations:28.0.0
|    |    |    |    |    +--- com.android.support:swiperefreshlayout:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    |    |    \--- com.android.support:interpolator:28.0.0 (*)
|    |    |    |    |    +--- com.android.support:asynclayoutinflater:28.0.0
|    |    |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    |    |    \--- com.android.support:support-compat:28.0.0 (*)
|    |    |    |    |    \--- com.android.support:cursoradapter:28.0.0 (*)
|    |    |    |    +--- com.android.support:support-core-utils:28.0.0 (*)
|    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    +--- com.android.support:loader:28.0.0 (*)
|    |    |    |    \--- android.arch.lifecycle:viewmodel:1.1.1 (*)
|    |    |    +--- com.android.support:support-vector-drawable:28.0.0
|    |    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    |    \--- com.android.support:support-compat:28.0.0 (*)
|    |    |    \--- com.android.support:animated-vector-drawable:28.0.0
|    |    |         +--- com.android.support:support-vector-drawable:28.0.0 (*)
|    |    |         \--- com.android.support:support-core-ui:28.0.0 (*)
|    |    +--- com.facebook.fresco:fresco:1.10.0
|    |    |    +--- com.facebook.fresco:fbcore:1.10.0
|    |    |    +--- com.facebook.fresco:drawee:1.10.0
|    |    |    |    +--- com.facebook.fresco:fbcore:1.10.0
|    |    |    |    \--- com.facebook.fresco:imagepipeline:1.10.0
|    |    |    |         +--- com.facebook.fresco:imagepipeline-base:1.10.0
|    |    |    |         |    +--- com.facebook.soloader:soloader:0.5.0 -> 0.6.0
|    |    |    |         |    +--- com.parse.bolts:bolts-tasks:1.4.0
|    |    |    |         |    \--- com.facebook.fresco:fbcore:1.10.0
|    |    |    |         +--- com.facebook.soloader:soloader:0.5.0 -> 0.6.0
|    |    |    |         +--- com.parse.bolts:bolts-tasks:1.4.0
|    |    |    |         \--- com.facebook.fresco:fbcore:1.10.0
|    |    |    +--- com.facebook.fresco:imagepipeline:1.10.0 (*)
|    |    |    \--- com.facebook.soloader:soloader:0.5.0 -> 0.6.0
|    |    +--- com.facebook.fresco:imagepipeline-okhttp3:1.10.0
|    |    |    +--- com.squareup.okhttp3:okhttp:3.10.0 -> 3.12.1
|    |    |    |    \--- com.squareup.okio:okio:1.15.0
|    |    |    +--- com.facebook.fresco:fbcore:1.10.0
|    |    |    \--- com.facebook.fresco:imagepipeline:1.10.0 (*)
|    |    +--- com.facebook.soloader:soloader:0.6.0
|    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    +--- com.squareup.okhttp3:okhttp:3.12.1 (*)
|    |    +--- com.squareup.okhttp3:okhttp-urlconnection:3.12.1
|    |    |    \--- com.squareup.okhttp3:okhttp:3.12.1 (*)
|    |    \--- com.squareup.okio:okio:1.15.0
|    \--- com.crashlytics.sdk.android:crashlytics:2.9.2 -> 2.9.9
|         +--- io.fabric.sdk.android:fabric:1.4.8
|         +--- com.crashlytics.sdk.android:beta:1.2.10
|         +--- com.crashlytics.sdk.android:crashlytics-core:2.6.8
|         |    +--- io.fabric.sdk.android:fabric:1.4.8
|         |    \--- com.crashlytics.sdk.android:answers:1.4.7
|         |         \--- io.fabric.sdk.android:fabric:1.4.8
|         \--- com.crashlytics.sdk.android:answers:1.4.7 (*)
+--- project :react-native-sketch-draw
|    \--- com.facebook.react:react-native:+ -> 0.59.8 (*)
+--- project :react-native-version-check
|    \--- com.facebook.react:react-native:0.20.+ -> 0.59.8 (*)
+--- project :react-native-device-info
|    +--- com.facebook.react:react-native:+ -> 0.59.8 (*)
|    \--- com.google.android.gms:play-services-gcm:+ -> 16.1.0
|         +--- com.google.android.gms:play-services-base:16.0.1 -> 16.1.0
|         |    +--- com.google.android.gms:play-services-basement:16.2.0
|         |    |    \--- com.android.support:support-v4:26.1.0 -> 28.0.0
|         |    |         +--- com.android.support:support-compat:28.0.0 (*)
|         |    |         +--- com.android.support:support-media-compat:28.0.0
|         |    |         |    +--- com.android.support:support-annotations:28.0.0
|         |    |         |    +--- com.android.support:support-compat:28.0.0 (*)
|         |    |         |    \--- com.android.support:versionedparcelable:28.0.0 (*)
|         |    |         +--- com.android.support:support-core-utils:28.0.0 (*)
|         |    |         +--- com.android.support:support-core-ui:28.0.0 (*)
|         |    |         \--- com.android.support:support-fragment:28.0.0 (*)
|         |    \--- com.google.android.gms:play-services-tasks:16.0.1
|         |         \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         +--- com.google.android.gms:play-services-iid:[16.0.1] -> 16.0.1
|         |    +--- com.google.android.gms:play-services-base:16.0.1 -> 16.1.0 (*)
|         |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    +--- com.google.android.gms:play-services-stats:16.0.1
|         |    |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|         \--- com.google.android.gms:play-services-stats:16.0.1 (*)
+--- project :react-native-keyevent
|    \--- com.facebook.react:react-native:+ -> 0.59.8 (*)
+--- project :react-native-vector-icons
|    \--- com.facebook.react:react-native:+ -> 0.59.8 (*)
+--- project :react-native-keychain
|    +--- com.facebook.react:react-native:+ -> 0.59.8 (*)
|    \--- com.facebook.conceal:conceal:1.1.3
+--- project :react-native-config
|    \--- com.facebook.react:react-native:+ -> 0.59.8 (*)
+--- project :react-native-camera
|    +--- com.facebook.react:react-native:0.19.+ -> 0.59.8 (*)
|    +--- com.google.zxing:core:3.2.1
|    \--- com.drewnoakes:metadata-extractor:2.9.1
|         \--- com.adobe.xmp:xmpcore:5.1.2
+--- com.android.support:appcompat-v7:28.0.0 (*)
+--- project :react-native-exception-handler
|    \--- com.facebook.react:react-native:+ -> 0.59.8 (*)
+--- project :@react-native-community_netinfo
|    \--- com.facebook.react:react-native:+ -> 0.59.8 (*)
+--- project :@react-native-community_async-storage
|    \--- com.facebook.react:react-native:+ -> 0.59.8 (*)
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21
|         +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21
|         \--- org.jetbrains:annotations:13.0
+--- com.facebook.react:react-native:+ -> 0.59.8 (*)
+--- project :react-native-firebase
|    +--- com.facebook.react:react-native:+ -> 0.59.8 (*)
|    +--- com.android.support:support-v4:28.0.0 (*)
|    \--- com.android.support:multidex:1.0.2 -> 1.0.3
+--- com.google.firebase:firebase-core:16.0.8
|    \--- com.google.firebase:firebase-analytics:16.4.0
|         +--- com.google.android.gms:play-services-measurement:16.4.0
|         |    +--- com.google.android.gms:play-services-basement:16.2.0 (*)
|         |    +--- com.google.android.gms:play-services-measurement-base:[16.4.0] -> 16.4.0
|         |    |    \--- com.google.android.gms:play-services-basement:16.2.0 (*)
|         |    +--- com.google.android.gms:play-services-measurement-impl:[16.4.0] -> 16.4.0
|         |    |    +--- com.google.android.gms:play-services-ads-identifier:16.0.0
|         |    |    |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    |    +--- com.google.android.gms:play-services-basement:16.2.0 (*)
|         |    |    +--- com.google.android.gms:play-services-measurement-base:[16.4.0] -> 16.4.0 (*)
|         |    |    \--- com.google.android.gms:play-services-stats:16.0.1 (*)
|         |    \--- com.google.android.gms:play-services-stats:16.0.1 (*)
|         +--- com.google.android.gms:play-services-measurement-api:16.4.0
|         |    +--- com.google.android.gms:play-services-basement:16.2.0 (*)
|         |    +--- com.google.android.gms:play-services-measurement-base:[16.4.0] -> 16.4.0 (*)
|         |    +--- com.google.android.gms:play-services-measurement-impl:[16.4.0] -> 16.4.0 (*)
|         |    +--- com.google.android.gms:play-services-measurement-sdk-api:[16.4.0] -> 16.4.0
|         |    |    +--- com.google.android.gms:play-services-basement:16.2.0 (*)
|         |    |    \--- com.google.android.gms:play-services-measurement-base:[16.4.0] -> 16.4.0 (*)
|         |    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|         |    +--- com.google.firebase:firebase-common:16.0.3 -> 16.1.0
|         |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    |    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|         |    |    \--- com.google.auto.value:auto-value-annotations:1.6
|         |    +--- com.google.firebase:firebase-iid:17.0.3
|         |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    |    +--- com.google.android.gms:play-services-stats:16.0.1 (*)
|         |    |    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|         |    |    +--- com.google.firebase:firebase-common:16.0.3 -> 16.1.0 (*)
|         |    |    \--- com.google.firebase:firebase-iid-interop:16.0.1
|         |    |         +--- com.google.android.gms:play-services-base:16.0.1 -> 16.1.0 (*)
|         |    |         \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    \--- com.google.firebase:firebase-measurement-connector:17.0.1
|         |         \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         \--- com.google.android.gms:play-services-measurement-sdk:16.4.0
|              +--- com.google.android.gms:play-services-basement:16.2.0 (*)
|              +--- com.google.android.gms:play-services-measurement-base:[16.4.0] -> 16.4.0 (*)
|              +--- com.google.android.gms:play-services-measurement-impl:[16.4.0] -> 16.4.0 (*)
|              \--- com.google.android.gms:play-services-measurement-sdk-api:[16.4.0] -> 16.4.0 (*)
+--- com.google.android.gms:play-services-base:16.1.0 (*)
+--- com.google.firebase:firebase-auth:16.2.1
|    +--- com.google.android.gms:play-services-base:16.0.1 -> 16.1.0 (*)
|    +--- com.google.android.gms:play-services-basement:16.1.0 -> 16.2.0 (*)
|    +--- com.google.android.gms:play-services-flags:16.0.1
|    |    +--- com.google.android.gms:play-services-base:16.0.1 -> 16.1.0 (*)
|    |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    +--- com.google.firebase:firebase-auth-interop:16.0.1
|    |    +--- com.google.android.gms:play-services-base:16.0.1 -> 16.1.0 (*)
|    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|    |    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    |    \--- com.google.firebase:firebase-common:16.0.3 -> 16.1.0 (*)
|    \--- com.google.firebase:firebase-common:16.0.3 -> 16.1.0 (*)
+--- com.google.firebase:firebase-database:16.1.0
|    +--- com.google.android.gms:play-services-base:16.0.1 -> 16.1.0 (*)
|    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    +--- com.google.firebase:firebase-common:16.1.0 (*)
|    \--- com.google.firebase:firebase-database-collection:16.0.1
+--- com.google.firebase:firebase-firestore:18.2.0
|    +--- com.google.android.gms:play-services-base:16.0.1 -> 16.1.0 (*)
|    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    +--- com.google.firebase:firebase-auth-interop:16.0.1 (*)
|    +--- com.google.firebase:firebase-common:16.1.0 (*)
|    +--- com.google.firebase:firebase-database-collection:16.0.1
|    +--- com.google.firebase:protolite-well-known-types:16.0.1
|    |    \--- com.google.protobuf:protobuf-lite:3.0.1
|    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    +--- com.squareup.okhttp:okhttp:2.7.5
|    |    \--- com.squareup.okio:okio:1.6.0 -> 1.15.0
|    +--- io.grpc:grpc-android:1.16.1
|    |    \--- io.grpc:grpc-core:[1.16.1] -> 1.16.1
|    |         +--- io.grpc:grpc-context:1.16.1
|    |         +--- com.google.code.gson:gson:2.7
|    |         +--- com.google.errorprone:error_prone_annotations:2.2.0
|    |         +--- com.google.code.findbugs:jsr305:3.0.2
|    |         +--- org.codehaus.mojo:animal-sniffer-annotations:1.17
|    |         +--- com.google.guava:guava:26.0-android
|    |         |    +--- org.checkerframework:checker-compat-qual:2.5.2
|    |         |    \--- com.google.j2objc:j2objc-annotations:1.1
|    |         +--- io.opencensus:opencensus-api:0.12.3
|    |         |    \--- com.google.errorprone:error_prone_annotations:2.2.0
|    |         \--- io.opencensus:opencensus-contrib-grpc-metrics:0.12.3
|    |              +--- com.google.errorprone:error_prone_annotations:2.2.0
|    |              \--- io.opencensus:opencensus-api:0.12.3 (*)
|    +--- io.grpc:grpc-okhttp:1.16.1
|    |    +--- io.grpc:grpc-core:[1.16.1] -> 1.16.1 (*)
|    |    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    |    \--- com.squareup.okio:okio:1.13.0 -> 1.15.0
|    +--- io.grpc:grpc-protobuf-lite:1.16.1
|    |    +--- io.grpc:grpc-core:1.16.1 (*)
|    |    +--- com.google.protobuf:protobuf-lite:3.0.1
|    |    \--- com.google.guava:guava:26.0-android (*)
|    \--- io.grpc:grpc-stub:1.16.1
|         \--- io.grpc:grpc-core:1.16.1 (*)
+--- com.crashlytics.sdk.android:crashlytics:2.9.9 (*)
+--- com.android.support:multidex:1.0.3
\--- com.android.support:multidex:1.0.2 -> 1.0.3

```

Hope this information will help.

**Comment by wilhuff** [comment] 2019-05-17 15:04
Thanks. The hypothesis was that there was a version substitution of the protobuf-related libraries and a mismatch between the version we built with and the version used at runtime could cause this error.

Such a substitution would have looked something like this: `com.squareup.okio:okio:1.6.0 -> 1.15.0`.

In the case of the protobuf library there's no substitution: `com.google.protobuf:protobuf-lite:3.0.1`.

**Comment by mikelehen** [comment] 2019-05-17 17:03
@mgenov Given this doesn't seem to be a version mismatch, I've logged a bug against protobuf to see if they can shed any light on this stacktrace.  In the meantime, could you shed any more light on the circumstances under which you hit this? E.g.:

1. Can you reliably reproduce this?  Or did it only happen once?  You listed 2 android versions, so I guess you've hit it on at least 2 devices?
2. If you disable persistence (`FirebaseFirestore.getInstance().setSettings(new FirebaseFirestoreSettings.Builder().setPersistenceEnabled(false).build())`) does everything work?
3. Anything else notable you can think of on the device(s) that hit this?

Thanks!

**Comment by mikelehen** [comment] 2019-05-17 22:15
@BSBandme has [suggested](https://github.com/protocolbuffers/protobuf/issues/6149#issuecomment-493605058) this could be proguard-related.  Are you using [proguard](https://developer.android.com/studio/build/shrink-code) (i.e. do you have minifyEnabled in your gradle file?).  Could you try disabling it and see if that makes the problem go away?

**Comment by mgenov** [comment] 2019-05-19 16:49
Yes, proguard is used in the app and minifyEnabled is set to true. The problem is that the issue was encountered single time in a single user and checking by disabling of proguard will add additional overhead to the app for all our users. 

I may test it with local build by simulating call to:GeneratedMessageLite.dynamicMethod but not sure which API I have to call to invoke this part of the code. 

I've also looked for specific **proguard** rules to add:
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/proguard.txt

but not able to find something concrete.

**Comment by mikelehen** [comment] 2019-05-20 15:36
@mgenov Ahh, I see.  In that case, I am afraid this probably isn't actionable.  If it only happened for one user a single time, it's probably not a proguard issue (or at least not a straightforward one).  I'm going to close this since we have no way to reproduce it to get to the bottom of it.  If you see more occurrences of the crash or gather any additional data about what caused it, please do let us know.  Thanks and sorry we can't be of more help.

**Closed by mikelehen** 2019-05-20 15:36 UTC
Labels: api: firestore
