### ISSUE TITLE
Some clients repeatedly firing google.firestore.v1.Firestore.Listen requests

### ISSUE THREAD

**Issue by nbransby** [firebase/firebase-android-sdk#3718] opened 2022-05-12 04:38 UTC
We have started to received a huge amount of read requests from certain users (+-8k a minute) and have started looking in to the audit logs

We looked into 2 hours worth of audit logs and found that there was one user making just short of 1 million listen requests. We dug deeper and saw that 2/3 of the requests were errors and the majority of these had the error message of "null". 

All of the queries we make from the client had around 35k of these null errors. Other things to note:
- these requests are occuring on a path we only add a single listener to on start of the app 
- this data never changes 
- we appear to be being charged for these requests
- the same logic using the js sdk doesn't reproduce the same issue 

Even disregarding the null errors we would assume that there should only be 2 reads per client here, one to setup the listener and another to receive the the data (as it never changes), this is the behavior we see from the js sdk.

**Comment by dconeybe** [comment] 2022-05-12 13:55
Hello @nbransby. I'm sorry for this awful problem you're experiencing with Firestore. I'll be looking into it. In the meantime, could you fill out the issue template and post a new comment with that additional information? Thank you.

**Comment by dconeybe** [comment] 2022-05-12 14:14
Note to Googlers: This issue is being tracked internally by b/232395729

**Comment by dconeybe** [comment] 2022-05-12 15:12
@nbransby From some internal discussion I was able to see some of the logs you submitted. It appears that your product is using a very old version of the Firestore Android SDK: 23.0.3, released July 2021 (https://firebase.google.com/support/release-notes/android#firestore_v23-0-3).

This version is almost 1 year old. Before I do more investigation, please upgrade to the latest version, which is 24.1.2 at the moment, and see if you can reproduce. This is also important because if there is a fix in the Android SDK then you will need to upgrade to pick up that fix anyways.

Please let me know if this is something you can try out.

**Comment by nbransby** [comment] 2022-05-12 15:36
> This version is almost 1 year old. Before I do more investigation, please upgrade to the latest version, which is 24.1.2 at the moment, and see if you can reproduce. This is also important because if there is a fix in the Android SDK then you will need to upgrade to pick up that fix anyways.

The above reproducer still occurs on 24.1.2 but understand this might be a red herring. Could we get confirmation of that in the meantime?

> Please let me know if this is something you can try out.

Will do but as we need to get it into production it will take a while.

**Comment by nbransby** [comment] 2022-05-17 15:06
We have updated to the latest version of the firestore library and can confirm it's still an issue

**Comment by dconeybe** [comment] 2022-05-17 15:53
Thank you for trying the latest version. Are you able to enable debug logging and capture the logs?

To enable debug logging, call `FirebaseFirestore.setLoggingEnabled(true)`

https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#setLoggingEnabled(boolean)

**Comment by nbransby** [comment] 2022-05-19 18:33
I wanted to share our latest findings from enabling the audit logs for an
hour yesterday, these are entries grouped by user agent.

- The query_count column is the highest number of log entries from a single
user with that user agent.

- The user_count shows the total number of unique users from which we
selected the one with the most entries for query_count

I suspect the query_count rises with the user_count because a bigger sample
size is more likely to find users affected by the issue.

The third row shows with latest firestore version there are 148,455 log
entries for a single user, that's ~2,500 per minute.

To reiterate these are listen requests to the path specified in the table,
the listener is added once on start of app and the document never changes.

![image](https://user-images.githubusercontent.com/1386607/169374583-906c94a9-07e8-4100-8223-8153688aaaf7.png)

**Comment by dconeybe** [comment] 2022-05-19 19:50
Just FYI the investigation has been handed off to @ehsannas.

But one thing that stands out from the screenshot in your last comment is that the user agents suggest that the requests are coming from the server SDKs, not the Android client. The user agent of "grpc-java-netty" would come from the Java Server SDK (or Java Admin SDK) and the user agent "grpc-node-js" would come from the Node Server SDK (or Node Admin SDK). I'd expect that requests from the Android client would have "grpc-java-okhttp" user agents. I could be wrong about this, but it may be something to look into.

Again, this is merely an idea and I may be wrong about the user agents. But if you are using one of the server or admin SDKs (e.g. via cloud functions), is it possible that one of those is responsible for this spamming? We have seen cases where cloud functions end up triggering themselves and get into a tight loop. Anyways, hope this helps.

**Comment by ehsannas** [comment] 2022-05-19 20:20
This is actually a very important point and should be looked into. @nbransby can you please confirm
1- is this traffic coming from server SDKs or Android SDK?
2- do you have a Cloud Function triggered by Firestore events?

**Comment by nbransby** [comment] 2022-05-19 21:31
I can comfirm both are client sdks, the confusion is because they are
running on desktop, electron and JVM respectively

**Comment by nbransby** [comment] 2022-05-19 22:44
> 2- do you have a Cloud Function triggered by Firestore events?

Only client side code refers to versions collection / documents

**Comment by dconeybe** [comment] 2022-06-29 18:51
We have discovered the root cause of this issue. To fix, you must enable Firestore persistence.

Enabling persistence allows Firestore listeners to re-use the documents downloaded for previously-executed queries. Without persistence being enabled, the Firestore client is forced to re-run the query from scratch each time.

Since I believe the immediate problem reported in this issue is resolved, I'm going to close the issue. Thank you for working with our team and our sincere apologies for the inconvenience this has caused you.

**Closed by dconeybe** 2022-06-29 18:51 UTC
Labels: api: firestore, internal-bug-filed
