### ISSUE TITLE
Cloud Messaging: After receiving push and proceed data app prccess doesn't ended

### ISSUE THREAD

**Issue by siper** [firebase/firebase-android-sdk#4559] opened 2023-01-13 09:18 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1, Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
  * Firebase Component: Cloud Messaging
  * Component version: 
  com.google.firebase:firebase-messaging-ktx:23.1.1
  com.google.gms:google-services:4.3.14

### [REQUIRED] Step 3: Describe the problem

After received push (notification or data) and proceed push data, app prccess doesn't ended.

#### Steps to reproduce:

1. Run application from: https://github.com/siper/test_fcm
2. Send push with any data 

#### Relevant Code:

All source code available here: https://github.com/siper/test_fcm

**Comment by argzdev** [comment] 2023-01-13 09:45
Thanks for reporting, @siper. Could you explain what do you mean by app process doesn't end? And what is the expected behavior you're looking for? Thanks!

**Comment by siper** [comment] 2023-01-13 09:58
After we procced all push data, system should kill process because it do nothing. Now, system not kill proccess, and it seems, that cloud messaging sdk do it own work.

**Comment by argzdev** [comment] 2023-01-13 10:08
Can you show me logs or stacktrace where you see that the process is still active or doing extra work? So that I can investigate this further? Thanks!

**Comment by siper** [comment] 2023-01-13 10:43
[logcat.txt](https://github.com/firebase/firebase-android-sdk/files/10410698/logcat.txt)
[process.txt](https://github.com/firebase/firebase-android-sdk/files/10410700/process.txt)

In logcat.txt logs from app with StrictMode enabled, it says that Closable not closed. In process.txt dump from `adb shel ps -A` after push received when app (ru.stersh.testfcm) exists.

**Comment by argzdev** [comment] 2023-01-13 17:56
Thanks for the extra details, @siper. 

Sending push notifications does not trigger the violation. Upon testing, it seems that re-running the app from the project will trigger this.

I was able to reproduce the `StrictMode policy violation: android.os.strictmode.LeakedClosableViolation`. However, this issue doesn't seem related to FCM.

Steps to reproduce:
1. Open app, make sure app is on foreground
2. Re-run the app from the project will already trigger the `StrictMode policy violation`

Interestingly, if we haven't encountered the violation and we just close the app then reopen it from the phone, the violation is not triggered. However, once the strictmode has been triggered, any succeeding reopen will trigger the same violation.

I tried removing FCM and I was still able to reproduce the same violation, even with a clean project without any dependencies or libraries. 

I found a [bug](https://issuetracker.google.com/issues/167533582) that is currently tracking this issue, it seems that this is affecting API 30 devices. That said, since this is not an issue specifically for FCM, I'll be closing this now. Feel free to ask this to be reopened if you think this is a mistake, or if you have further information that shows that FCM is the one causing this issue. Thanks

**Comment by siper** [comment] 2023-01-13 18:15
Ok, push notifications does't trigger `android.os.strictmode.LeakedClosableViolation`, but proccess doesn't stops anyway after push received.

**Comment by siper** [comment] 2023-01-16 06:18
Issue not resolved, reopen it please.

**Comment by argzdev** [comment] 2023-01-16 15:07
Hi @siper, for the second issue, I was able to reproduce the behavior. I'll notify our engineers and see what we can do here.

Scenario 1:
--
1. App is installed but not opened app
2. Send notification via Firebase Console
3. Do not check phone notification

Run `adb shell ps -A`
Expected Behavior: app process should not appear after a few minutes after receiving the notification
Actual Behavior: (Incorrect) app process is retained even after 10 minutes

Scenario 2:
--
1. App is installed but not opened app
2. Send notification via Firebase Console
3. Check phone notification (without opening the notification)

Run `adb shell ps -A`
Expected Behavior: app process should not appear after a few minutes after receiving the notification
Actual Behavior: (Correct) app process is terminated a few minutes after the user checks the notification

Interestingly, somehow checking the notification "triggers" a termination flag and allows the process to be terminated after sometime.

**Comment by argzdev** [comment] 2023-01-16 15:19
Hi @siper, for the second issue, I was able to reproduce the behavior. I'll notify our engineers and see what we can do here.

Scenario 1:
--
1. App is installed but not opened app
2. Send notification via Firebase Console
3. Do not check phone notification

Run `adb shell ps -A`
Expected Behavior: app process should not appear after a few minutes after receiving the notification
Actual Behavior: (Incorrect) app process is retained even after 10 minutes

Scenario 2:
--
1. App is installed but not opened app
2. Send notification via Firebase Console
3. Check phone notification (without opening the notification)

Run `adb shell ps -A`
Expected Behavior: app process should not appear after a few minutes after receiving the notification
Actual Behavior: (Correct) app process is terminated a few minutes after the user checks the notification

Interestingly, somehow checking the notification "triggers" a termination flag and allows the process to be terminated after sometime.

**Comment by argzdev** [comment] 2023-01-17 17:35
Hi @siper, our engineers have responded back regarding this issue.

> There is no guarantee around when processes are killed, so there should be no expectations that a process is killed (or not) in any of these circumstances. The behavior also likely depends on the state of the device and what device it is (different Android versions and manufacturers may prioritize processes differently).

Also after further testing, it seems that the app process only stays active when the app is idle and is not sleeping. If the phone dozes or goes to sleep, the app process is terminated.

**Closed by argzdev** 2023-01-17 17:35 UTC
Labels: api: messaging
