### ISSUE TITLE
[Error generating dynamic link] 400: We could not match param

### ISSUE THREAD

**Issue by JurajBegovac** [firebase/firebase-android-sdk#4215] opened 2022-10-18 05:36 UTC
### Step 2: Describe your environment

Doesn't matter

  * Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1
  * Firebase Component: Dynamic links
  * Component version: Any

### Step 3: Describe the problem

From **yesterday (17 Oct 2022)** we're suddenly getting this exception:
```
com.google.android.gms.common.api.ApiException: 400: We could not match param
```
**Also on iOS!** 

I think the generated regex on the firebase console is not good. 
I'll give our example.

1. So we want to create a short dynamic link from the link that looks like this:

```
https://our-domain.com?group_invite_code=...
```

2. We added our link to `Set your allowed domains` like this (see screenshot below):
our-domain.com

3. The problem is that the generated regex (that we cannot control, see screenshot below) looks like this:
```
^https{0,1}:\/\/our-domain\.com(\/.*){0,1}$
```
That regex won't match:
```
https://our-domain.com?group_invite_code=...
```
But it would match:
```
https://our-domain.com/some-page?group_invite_code=...
```
But we don't have additional path `/some-page` for our dynamic links.
This is really **critical** because we have it in our production apps and it stopped working **yesterday**.

Screenshot from firebase console:
![Screenshot 2022-10-18 at 07 35 18](https://user-images.githubusercontent.com/8510212/196344083-08a191a0-8dbd-4c80-92c1-cb7b3488938d.png)

**Comment by argzdev** [comment] 2022-10-18 14:39
Hi @JurajBegovac, thanks for reporting. This looks like it's working as intended. Just to give some insights, the reason the regex is designed in this pattern is because:

> When you configure Dynamic Links to use a particular URL prefix, all URLs that begin with that prefix are treated as Dynamic Links, so you can't use URLs with that prefix to point to ordinary hosted content.

> For example, if you want to create a Dynamic Link to the resource `https://example.com/my-resource` (a web page, Universal Link, or App Link), you can't use `https://example.com/` as the Dynamic Links URL prefix, because doing so would cause `https://example.com/my-resource` to be treated as a Dynamic Link. Instead, you must use a URL prefix with either a different domain or a different path prefix.

Here are some examples of working URL prefix:
- `https://link.example.com/?link=https://example.com/my-resource`
- `https://example.com/links/?link=https://example.com/my-resource`
- `https://ex.amp.le/?link=https://example.com/my-resource`

You can read more about the proper setup of URL prefix on our [documentations](https://firebase.google.com/docs/dynamic-links/custom-domains#using_your_web_domain_for).

If I'm not mistaken you can add a URL prefix via Firebase Console > Dynamic Links > Add URL prefix, and it would look something like this:

<img width="1044" alt="Screen Shot 2022-10-18 at 10 27 24 PM" src="https://user-images.githubusercontent.com/93124282/196459126-dbbf6435-ab85-4faa-be5d-62ca3de0fd7e.png">

If you ever encounter issues like this, it would be best to reach out to our [Firebase Support](https://firebase.google.com/support). Since this doesn't look like an issue on the SDK side, and they have visibility on your project details, they'll be able to assist you better.

That said, I'll close this issue for now. Feel free to ask this to be reopened if you think this is a mistake. Thanks!

**Closed by argzdev** 2022-10-18 14:39 UTC
Labels: api: dynamiclinks

**Comment by JurajBegovac** [comment] 2022-10-18 18:41
But this stopped working yesterday. We used links for 2 years and it was fine. The problem is that we cannot fix it without publishing a new app version (and adoption is not so fast).

I will open an issue on firebase support then...

**Comment by argzdev** [comment] 2022-10-18 20:10
I'm assuming if it suddenly stopped working when you didn't do any changes on your new app (plus this affects iOS), then I'm sure this is a backend issue. Reaching out to [Firebase support](https://firebase.google.com/support) is the right choice here since they have visibility on your project, and changes done on the backend will reflect immediately. 

As far as SDK is concern, also there's not much we can do.
