### ISSUE TITLE
App crashing when installing from Google Play store

### ISSUE THREAD

**Issue by shahzad1** [firebase/firebase-android-sdk#5021] opened 2023-05-21 20:09 UTC
### [READ] Step 1: Are you in the right place?
yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Flamingo | 2022.2.1 Canary 10
  * Firebase Component:  (Database)
  * Component version: 20.2.1

#### Steps to reproduce:

What happened? How can we make the problem occur?
When I directly install app from Android Studio but when I upload to the play store and run the app, I'm getting this crash on App Startup:
java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.2.1). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
	at a5.i$a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: java.lang.NoSuchMethodError: No virtual method object()Lq8/JSONStringer; in class Lq8/JSONStringer; or its super classes (declaration of 'q8.JSONStringer' appears in base.apk!classes2.dex)
	at o5.a.c(SourceFile:5)
	at o5.a.b(SourceFile:60)
	at c5.n.l(SourceFile:95)
	at c5.a.e(SourceFile:242)
	at c5.a.c(SourceFile:102)
	at c5.a.f(SourceFile:52)
	at c5.u.b(SourceFile:83)
	at c5.w.run(SourceFile:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by argzdev** [comment] 2023-05-22 09:46
Thanks for reaching out, @shahzad1. I can see in your stacktrace that the error is due to `Caused by: java.lang.NoSuchMethodError: No virtual method object()Lq8/JSONStringer; in class Lq8/JSONStringer; or its super classes (declaration of 'q8.JSONStringer' appears in base.apk!classes2.dex)`.

This is a duplicate issue of #3688. You should be able to resolve this following the solution [provided](https://github.com/firebase/firebase-android-sdk/issues/3688#issuecomment-1119494623). That said, I'll close this issue for now. Feel free to come back here you feel that this is a mistake or if you have any other questions regarding the SDK. Thanks!

**Closed by argzdev** 2023-05-22 09:46 UTC
Labels: api: database
