### ISSUE TITLE
A problem was found with the configuration of task ':app:uploadCrashlyticsMappingFileRelease' (type 'UploadMappingFileTask').   - Type 'UploadMappingFileTask' property 'googleServicesResourceRoot' doesn't have a configured value.

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-android-sdk#2721] opened 2021-06-07 02:55 UTC
After updating to `classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.0'`

```
A problem was found with the configuration of task ':app:uploadCrashlyticsMappingFileRelease' (type 'UploadMappingFileTask').
  - Type 'UploadMappingFileTask' property 'googleServicesResourceRoot' doesn't have a configured value.
```

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:uploadCrashlyticsMappingFileRelease' (type 'UploadMappingFileTask').
  - Type 'UploadMappingFileTask' property 'googleServicesResourceRoot' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'googleServicesResourceRoot'.
      2. Mark property 'googleServicesResourceRoot' as optional.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#value_not_set for more details about this problem.

```

I tried to read the documentation and changelog, however none of them help on how to fix the problem.

**Comment by ArcherEmiya05** [comment] 2021-06-07 13:56
Any support?

**Comment by aokudan** [comment] 2021-06-07 20:41
Help please

**Comment by ArcherEmiya05** [comment] 2021-06-07 21:01
We cannot compile/build a release aab with this version.

**Comment by LouisCAD** [comment] 2021-06-08 08:32
Hello, I'm affected as well since upgrading the Firebase Crashlytics Gradle plugin from 2.6.1 to 2.7.0.

Looks like that 2.7.0 version didn't undergo end-to-end testing… I have no choice but to revert the upgrade.

**Comment by ouchadam** [comment] 2021-06-08 17:10
same issue, using gradle 7.0.2

**Comment by tasomaniac** [comment] 2021-06-08 17:12
The tests probably did not find this issue since the firebase repo is not on Gradle 7 yet. It's actually on Gradle 5.x

**Comment by LouisCAD** [comment] 2021-06-08 17:23
Gradle 5 is like 2 years old now? Maybe it's time to move to Gradle 6. Testing on latest Gradle release would be nice too.

**Comment by aguatno** [comment] 2021-06-08 17:42
Hi @ArcherEmiya05 thanks reporting, we're currently looking into this. Quick question, may we know what Gradle version you are using when the error occurs? Thanks

**Comment by LouisCAD** [comment] 2021-06-08 19:07
Using Gradle 7.0.2 in my case.

**Comment by ArcherEmiya05** [comment] 2021-06-09 03:13
> 
> 
> Hi @ArcherEmiya05 thanks reporting, we're currently looking into this. Quick question, may we know what Gradle version you are using when the error occurs? Also I tried the quickstart app with 7.0.1 Gradle Version and crashlytics-gradle:2.7.0 but I was not able to reproduce the issue. It would be great if you can provide a sample project where the issue is reproducible. Thanks

Gradle Plugin
`7.1.0-alpha01`

Gradle version
`7.0`

**Comment by mitaichik** [comment] 2021-06-09 15:21
It happens on gradle 6.7.1 too

**Comment by pvtai** [comment] 2021-06-11 09:30
Same to me

**Comment by vudzkostek** [comment] 2021-06-11 10:01
It happens on Gradle 6.9 also

**Comment by ubuntudroid** [comment] 2021-06-15 14:47
I'm on `firebase-crashlytics-gradle` 2.6.1 (not 2.7.0!) and am also affected. Seems the culprit is in `firebase-crashlytics` packaged in the 28.1.0 BOM rather than in `firebase-crashlytics-gradle`? 🤔  Didn't happen with the 28.0.1 BOM, but started to happen consistently right after updating the BOM.

**Comment by aguatno** [comment] 2021-06-15 19:11
Per checking it seems to be a compatibility issue with the Android Gradle plugin, though not 100% guaranteed since I can't reproduce locally. Let me assign for now. @mrichards could you have a look at this? (looks like a similar issue reported via support portal b/186748865).

**Comment by dmessano** [comment] 2021-06-16 01:36
Found a fix for me.
AS 4.2.1Buld May 10,2021
Gradle Plugin 4.2.1
Gradle Version 7.1
com.google.firebase:firebase-crashlytics-gradle:2.7.0

This produces the error
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.firebase-perf'
```

While this does not, note com.google.gms.google-services is now ABOVE com.google.firebase.crashlytics

```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
```

When you update to com.google.firebase:firebase-crashlytics-gradle:2.7.0 and sync the changes you are given an message stating that is the fix. 

```Configure project :app
Crashlytics could not find Google Services plugin task: processReleaseGoogleServices. Make sure com.google.gms.google-services is applied BEFORE com.google.firebase.crashlytics. If you are not using the Google Services plugin, you must explicitly declare `googleServicesResourceRoot` inputs for Crashlytics upload tasks.```

**Comment by vudzkostek** [comment] 2021-06-16 08:30
> ```
> Crashlytics could not find Google Services plugin task: processReleaseGoogleServices. Make sure com.google.gms.google-services is applied BEFORE com.google.firebase.crashlytics. If you are not using the Google Services plugin, you must explicitly declare `googleServicesResourceRoot` inputs for Crashlytics upload tasks.```
> ```

This does not sound like a fix, it's just causing a crash a bit earlier, before crashlytics plugin configuration will try to get missing property.

**Comment by dmessano** [comment] 2021-06-16 11:14
Sorry my comment might not have been clear, if you put com.google.firebase.crashlytics before com.google.gms.google-services you get that warning. (then if you try to build your project you get the error) If you put it how it tells you, then you don't get the warning or the build error.

**Comment by frett** [comment] 2021-06-16 15:38
I can verify that reordering the order that the google plugins are applied solved the issue for me.

**Comment by LouisCAD** [comment] 2021-06-16 17:34
There's a `plugins.withId` API in Gradle on `Project` to avoid this kind of issues that the CrashLytics plugin can take advantage of.

**Comment by mrichards** [comment] 2021-06-16 20:08
Yes, @dmessano has it correct. The order in which the plugins are applied is now relevant; this (ironically) is a side-effect of a change that will make it easier for customers to avoid using the GMS plugin if they choose. It also fixed a configuration cache issue in Gradle 7.

Are some builds not displaying the logged error with the directions on how to fix? ("Make sure com.google.gms.google-services is applied BEFORE com.google.firebase.crashlytics.") We were hoping this message would be sufficient to prevent support requests, but if it is not printing for folks, please let me know as I'd like to understand how to ensure it gets produced for your specific configuration.

**Comment by LouisCAD** [comment] 2021-06-16 23:48
It's not showing up for me at least.

Did you test the error cases on your end to ensure the proper message is shown instead of another puzzling failure occuring before?

**Comment by dmessano** [comment] 2021-06-17 05:14
The warning only shows up when you change and re-sync your gradle, it is also very easy to miss as it isn't red text and if you don't have the build window open it doesn't auto open. I didn't notice it until I went looking for a warning or error to see why my build was failing.

I can reproduce the warning without fail each time I put them in the wrong order and re-sync. 
![warning](https://user-images.githubusercontent.com/2214693/122335439-47ba9e80-cf09-11eb-9d1a-c77dcd1ab2c6.png)

**Comment by peterhav** [comment] 2021-06-21 11:48
I've changed the build file and put this in place:

plugins {
    id 'com.google.gms.google-services'
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'com.google.firebase.crashlytics'
    ....

Now LINT complains with the following warning: "Please apply google-services plugin at the bottom of the build file."

What to do?

**Comment by ubuntudroid** [comment] 2021-06-21 12:00
@peterhav Try putting the crashlytics plugin at the very bottom of the plugin list and the google-services plugin right above that.

**Comment by peterhav** [comment] 2021-06-21 12:07
Hi @ubuntudroid, changed to:

```
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
```

at the end of the file; but this gives the same lint warning: 'Please apply google-services plugin at the bottom of the build file.'

**Comment by peterhav** [comment] 2021-06-21 12:13
Thanks, that worked. I now have:

```
plugins {
    ....
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}
```

**Comment by mrichards** [comment] 2021-06-24 16:29
The message is logged as a warning, not an error, because in some cases the build should be able to continue successfully. We'll consider changing the logic a bit to ensure it is logged as an error if the end result will be a failed build.

I'm going to close this issue as the root cause has been identified and the original issue is resolved. Please re-open if you believe this is in error.

**Closed by mrichards** 2021-06-24 16:29 UTC
Labels: api: crashlytics, needs-info

**Comment by LouisCAD** [comment] 2021-06-24 17:09
In which version has the issue been resolved?
