### ISSUE TITLE
FirebaseMessagingService and OkHttp crash

### ISSUE THREAD

**Issue by pnkshir** [firebase/firebase-android-sdk#1428] opened 2020-04-07 06:43 UTC
* Android Studio version: _____3.6
  * Firebase Component: _____ firebase-messaging
  * Component version: _____"20.1.0"
We are using firebase for push notifications,  we are getting this crash randomly as collected on crashlytics
This is not reproducible, but on production few of the users are getting this issue
 Below are the logs : 
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: size=0 offset=0 byteCount=2048
       at com.android.okhttp.okio.Util.checkOffsetAndCount(Util.java:30)
       at com.android.okhttp.okio.Buffer.write(Buffer.java:1178)
       at com.android.okhttp.okio.Buffer.read(Buffer.java:1221)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:55)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393)
       at com.android.okhttp.internal.Util.skipAll(Util.java:159)
       at com.android.okhttp.internal.Util.discard(Util.java:141)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:410)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:396)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:384)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(zzk.java:4)
       at com.google.firebase.messaging.zzm.close(zzm.java:37)
       at com.google.firebase.messaging.zzd.zza(zzd.java:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(FirebaseMessagingService.java:69)
       at com.google.firebase.messaging.zze.run(zze.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:764)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by andirayo** [comment] 2020-04-09 21:48
Note: Does not seem to be FIS related, but v20.1.0 was the first version of IID to use FIS.

**Comment by pnkshir** [comment] 2020-05-26 10:49
Hello @ciarand could you please suggest further on this

**Comment by ashwinraghav** [comment] 2020-05-29 20:39
Duplicate of #1478

**Closed** 2020-05-29 20:41 UTC
Labels: api: messaging, needs-triage
