### ISSUE TITLE
"Circular dependency" with `injectCrashlyticsMappingFileId` task in `firebase-crashlytics-gradle` version `3.0.0` 

### ISSUE THREAD

**Issue by yogurtearl** [firebase/firebase-android-sdk#5930] opened 2024-05-03 19:23 UTC
### [READ] Step 1: Are you in the right place?
yes

### [REQUIRED] Step 2: Describe your environment

Using https://github.com/android/nowinandroid on `main` at commit `afad1b9a` 

### [REQUIRED] Step 3: Describe the problem

Upgrading from `2.9.9` to `3.0.0` of `firebase-crashlytics-gradle` with no other changes cause the builds to fail with this message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:app:extractDeepLinksDemoDebug
\--- :app:injectCrashlyticsMappingFileIdDemoDebug
     \--- :app:kspDemoDebugKotlin
          \--- :app:processDemoDebugResources
               +--- :app:mapDemoDebugSourceSetPaths
               |    \--- :app:injectCrashlyticsMappingFileIdDemoDebug (*)
               +--- :app:mergeDemoDebugResources
               |    \--- :app:injectCrashlyticsMappingFileIdDemoDebug (*)
               +--- :app:parseDemoDebugLocalResources
               |    \--- :app:packageDemoDebugResources
               |         \--- :app:injectCrashlyticsMappingFileIdDemoDebug (*)
               +--- :app:processDemoDebugManifest
               |    \--- :app:processDemoDebugMainManifest
               |         \--- :app:extractDeepLinksDemoDebug (*)
               \--- :app:processDemoDebugManifestForPackage
                    \--- :app:processDemoDebugManifest (*)
```

#### Steps to reproduce:

Clone https://github.com/android/nowinandroid and upgrade to `firebase-crashlytics-gradle` version `3.0.0`

**Comment by thatfiredev** [comment] 2024-05-03 20:41
@yogurtearl Thanks for reporting! I think this is a duplicate of #5925

**Comment by mrober** [comment] 2024-05-07 15:52
Closing since this is the same issue.

**Closed by mrober** 2024-05-07 15:52 UTC
Labels: api: crashlytics
