### ISSUE TITLE
firebase/firestore: getting internal error from AsyncQueue

### ISSUE THREAD

**Issue by mgenov** [firebase/firebase-android-sdk#382] opened 2019-04-27 17:00 UTC
### Version Information
  * Firebase Component: Firestore
  * Component version: 18.2.0
  * Affected Android Versions: 4.2.2, 5.1.1

### Description

It happens rarely and this is the stack trace from crashlytics:

```
Fatal Exception: java.lang.RuntimeException: Internal error in Firestore (18.2.0).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5(com.google.firebase:firebase-firestore@@18.2.0:379)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(com.google.firebase:firebase-firestore@@18.2.0)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```

```
Caused by android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
       at android.database.CursorWindow.<init>(CursorWindow.java:108)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
       at com.google.firebase.firestore.local.SQLitePersistence$Query.forEach(com.google.firebase:firebase-firestore@@18.2.0:430)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.getAll(com.google.firebase:firebase-firestore@@18.2.0:98)
       at com.google.firebase.firestore.local.LocalStore.lambda$applyRemoteEvent$5(com.google.firebase:firebase-firestore@@18.2.0:385)
       at com.google.firebase.firestore.local.LocalStore$$Lambda$6.get(com.google.firebase:firebase-firestore@@18.2.0)
       at com.google.firebase.firestore.local.SQLitePersistence.runTransaction(com.google.firebase:firebase-firestore@@18.2.0:195)
       at com.google.firebase.firestore.local.LocalStore.applyRemoteEvent(com.google.firebase:firebase-firestore@@18.2.0:328)
       at com.google.firebase.firestore.core.SyncEngine.handleRemoteEvent(com.google.firebase:firebase-firestore@@18.2.0:327)
       at com.google.firebase.firestore.core.FirestoreClient.handleRemoteEvent(com.google.firebase:firebase-firestore@@18.2.0:260)
       at com.google.firebase.firestore.remote.RemoteStore.raiseWatchSnapshot(com.google.firebase:firebase-firestore@@18.2.0:545)
       at com.google.firebase.firestore.remote.RemoteStore.handleWatchChange(com.google.firebase:firebase-firestore@@18.2.0:454)
       at com.google.firebase.firestore.remote.RemoteStore.access$100(com.google.firebase:firebase-firestore@@18.2.0:53)
       at com.google.firebase.firestore.remote.RemoteStore$1.onWatchChange(com.google.firebase:firebase-firestore@@18.2.0:176)
       at com.google.firebase.firestore.remote.WatchStream.onNext(com.google.firebase:firebase-firestore@@18.2.0:109)
       at com.google.firebase.firestore.remote.WatchStream.onNext(com.google.firebase:firebase-firestore@@18.2.0:39)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onNext$1(com.google.firebase:firebase-firestore@@18.2.0:119)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$Lambda$2.run(com.google.firebase:firebase-firestore@@18.2.0)
       at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(com.google.firebase:firebase-firestore@@18.2.0:67)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onNext(com.google.firebase:firebase-firestore@@18.2.0:110)
       at com.google.firebase.firestore.util.FirestoreChannel$1.onMessage(com.google.firebase:firebase-firestore@@18.2.0:150)
       at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
       at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
       at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
       at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
       at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@18.2.0:205)
       at java.lang.Thread.run(Thread.java:818)
```

![image](https://user-images.githubusercontent.com/209223/56852766-d9c94c80-6927-11e9-94b7-57b90eaf613b.png)

#### Steps to reproduce:
It's caused during fetching from firestore. As this thread says: https://stackoverflow.com/questions/11340257/sqlite-android-database-cursor-window-allocation-of-2048-kb-failed

it may be caused due Cursor leak in the code.

**Comment by wilhuff** [comment] 2019-04-29 19:51
We're pretty careful about not leaking cursors. In this particular case we're using [`forEach`](https://github.com/firebase/firebase-android-sdk/blob/1b6c34f7a867039f6b2cef5bcd06fb5e2230a0c7/firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java#L426) to iterate over the complete result set and it already uses the suggested pattern.

I've added code to our integration tests in #386 to detect whether or not we're leaking and I'm not seeing any failures. I don't think leaked cursors are the issue.

Even though we're not leaking cursors, it is possible that _other_ leaks are causing us to be unable to perform this allocation. If you profile memory usage in your app, are you otherwise leak free?

I've seen elsewhere that this can happen if memory is otherwise scarce. Is there a pattern to the devices on which you're seeing this error? For example, are they older devices with less RAM? A possible resolution there is to disable persistence if there's not enough RAM available. We'd need more data to support this hypothesis though.

**Comment by mgenov** [comment] 2019-05-02 11:07
I'm not sure that it's related to memory usage. Here are the device details from the crash:

![image](https://user-images.githubusercontent.com/209223/57071452-24114b80-6ce3-11e9-914f-f578c6801c05.png)

My app is using react-native (react-native-firebase respectively as lib) and most of the code is JS code. The issue may be caused and by react-native-firebase but I'm not at 100% sure about that.

**Comment by mgenov** [comment] 2019-05-02 11:10
This is the data in crashlytics:

![image](https://user-images.githubusercontent.com/209223/57071739-0e505600-6ce4-11e9-8f2c-fa5a5831ff19.png)

**Comment by var-const** [comment] 2019-05-03 17:30
SQLite has some limitations on the maximum number of elements in a query, so one possibility is that the issue may be triggered by a database with a very large number of documents. I will test out this hypothesis and post an update here.

**Comment by var-const** [comment] 2019-05-07 03:57
Update: I couldn't reproduce the issue. I tried reading a collection with ~10K documents, as well as a 100MB collection, neither of those led to "cursor window allocation" problem in SQLite.

**Comment by wilhuff** [comment] 2019-05-10 16:27
@mgenov We're not able to reproduce this problem essentially no matter what we throw at it: large documents, lots of small documents, etc. Even after consulting with our in-house SQLite experts, we're out of ideas for what this could be.

From what I can see there must be something specific to your application that's causing this. This could take a number of forms:

  * Specific data--either in kind, size, or number
  * Other activity going on
  * Some other resource starvation that manifests as OutOfMemory

If you can come up with a way to reproduce this (or even to cause it to happen more frequently) we'll be able to help you more.

Absent that, given this and #405 showing memory-related issues, your next best course of action may be to run your application under a memory profiler to see if anything stands out.

**Comment by mgenov** [comment] 2019-05-14 07:44
Today we got another error on this and I think that I might have an idea for the cause.

The structure of the document is the following and it represents Items and an Inventory system:
```jsx
 {
      id: '0DmAN4',
      incoming: 0,
      onHand: 0,
      committed: 10,
      packSizeItems: {}
    },
    {
      id: '12ExMW',
      onHand: 0,
      committed: 0,
      incoming: 0,
      processedItems: [],
      packSizeItems: {
        '1rXmJW': {
          incoming: 0,
          onHand: 23,
          packSizeId: '1rXmJW',
          committed: 24
        }
      }
    },
```
The number of items in the inventory is between 50 and 150 and the Android App is watching for changes in the inventory.

There is a backend side which updates the inventory and it is performing updates per item or pack:

e.g If the app receives an order for 10-20 items, then the backend performs 10-20 updates and watch is called 10-20 times concurrently and the Android app might not be able to handle all of them.

Hope this information might help.

**Comment by mikelehen** [comment] 2019-05-14 21:52
@mgenov Thanks for the added info.  I looked over the React Native code you linked, but nothing is jumping out to me as particularly suspicious.  Your description of the data and queries your doing isn't really jumping out as a concern to me either.  And so unfortunately I think this bug still isn't quite actionable for us.  I apologize for putting the burden onto you, but I think to move forward we'll really need to somehow get a concrete repro that demonstrates the issue... or else find some other smoking gun that points us to the issue.

**Comment by mgenov** [comment] 2019-05-29 18:29
Recently my app gets a lot of such crashes and my customers are experiencing bad UX. 

I've ran app in StrictMode with:
```java
   StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                .detectDiskReads()
                .detectDiskWrites()
                .detectNetwork()   // or .detectAll() for all detectable problems
                .penaltyLog()
                .build());
        StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                .detectLeakedSqlLiteObjects()
                .detectLeakedClosableObjects()
                .penaltyLog()
                .penaltyDeath()
                .build());
```

to detect some leaks and this is what I got:
```
05-29 21:22:15.232 11164 11172 E StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
05-29 21:22:15.232 11164 11172 E StrictMode: java.lang.Throwable: Explicit termination method 'end' not called
05-29 21:22:15.232 11164 11172 E StrictMode:    at dalvik.system.CloseGuard.open(CloseGuard.java:180)
05-29 21:22:15.232 11164 11172 E StrictMode:    at java.util.zip.Inflater.<init>(Inflater.java:82)
05-29 21:22:15.232 11164 11172 E StrictMode:    at java.util.zip.ZipFile.getInputStream(ZipFile.java:343)
05-29 21:22:15.232 11164 11172 E StrictMode:    at java.util.jar.JarFile.getInputStream(JarFile.java:390)
05-29 21:22:15.232 11164 11172 E StrictMode:    at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
05-29 21:22:15.232 11164 11172 E StrictMode:    at java.net.URL.openStream(URL.java:470)
05-29 21:22:15.232 11164 11172 E StrictMode:    at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
05-29 21:22:15.232 11164 11172 E StrictMode:    at java.lang.Class.getResourceAsStream(Class.java:1169)
05-29 21:22:15.232 11164 11172 E StrictMode:    at com.google.android.gms.common.internal.LibraryVersion.getVersion(Unknown Source)
05-29 21:22:15.232 11164 11172 E StrictMode:    at com.google.firebase.auth.api.internal.zzeg.zzcb(Unknown Source)
05-29 21:22:15.232 11164 11172 E StrictMode:    at com.google.firebase.auth.api.internal.zzeg.zzef(Unknown Source)
05-29 21:22:15.232 11164 11172 E StrictMode:    at com.google.firebase.auth.api.internal.zzds.getGetServiceRequestExtraArgs(Unknown Source)
05-29 21:22:15.232 11164 11172 E StrictMode:    at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(Unknown Source)
05-29 21:22:15.232 11164 11172 E StrictMode:    at com.google.android.gms.common.api.internal.zabo.run(Unknown Source)
05-29 21:22:15.232 11164 11172 E StrictMode:    at android.os.Handler.handleCallback(Handler.java:739)
05-29 21:22:15.232 11164 11172 E StrictMode:    at android.os.Handler.dispatchMessage(Handler.java:95)
05-29 21:22:15.232 11164 11172 E StrictMode:    at com.google.android.gms.internal.base.zap.dispatchMessage(Unknown Source)
05-29 21:22:15.232 11164 11172 E StrictMode:    at android.os.Looper.loop(Looper.java:148)
05-29 21:22:15.232 11164 11172 E StrictMode:    at android.os.HandlerThread.run(HandlerThread.java:61)
05-29 21:22:15.232 11164 11172 W System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
```

e.g the code that could be considered is this one:
com.google.firebase.auth.api.internal.zzds.getGetServiceRequestExtraArgs(Unknown Source)

Any ideas?

**Comment by mgenov** [comment] 2019-05-31 11:35
Tried to switch to 19.0.1 to see how it behaves and this is the result: (note it shows 18.3.0 as version)

```
Fatal Exception: java.lang.RuntimeException: Internal error in Firestore (18.3.0).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5(com.google.firebase:firebase-firestore@@19.0.1:379)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(com.google.firebase:firebase-firestore@@19.0.1)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```

```
Caused by android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
       at android.database.CursorWindow.<init>(CursorWindow.java:108)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
       at com.google.firebase.firestore.local.SQLitePersistence$Query.forEach(com.google.firebase:firebase-firestore@@19.0.1:455)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.getAll(com.google.firebase:firebase-firestore@@19.0.1:98)
       at com.google.firebase.firestore.local.LocalDocumentsView.getDocuments(com.google.firebase:firebase-firestore@@19.0.1:100)
       at com.google.firebase.firestore.local.LocalStore.lambda$writeLocally$1(com.google.firebase:firebase-firestore@@19.0.1:207)
       at com.google.firebase.firestore.local.LocalStore$$Lambda$2.get(com.google.firebase:firebase-firestore@@19.0.1)
       at com.google.firebase.firestore.local.SQLitePersistence.runTransaction(com.google.firebase:firebase-firestore@@19.0.1:200)
       at com.google.firebase.firestore.local.LocalStore.writeLocally(com.google.firebase:firebase-firestore@@19.0.1:201)
       at com.google.firebase.firestore.core.SyncEngine.writeMutations(com.google.firebase:firebase-firestore@@19.0.1:227)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$write$11(com.google.firebase:firebase-firestore@@19.0.1:215)
       at com.google.firebase.firestore.core.FirestoreClient$$Lambda$11.run(com.google.firebase:firebase-firestore@@19.0.1)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$4(com.google.firebase:firebase-firestore@@19.0.1:311)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$4.call(com.google.firebase:firebase-firestore@@19.0.1)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3(com.google.firebase:firebase-firestore@@19.0.1:287)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(com.google.firebase:firebase-firestore@@19.0.1)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@19.0.1:205)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by wilhuff** [comment] 2019-07-19 21:30
@mgenov these last traces don't include the usual strict mode policy violation message (i.e. "A resource was acquired at attached stack trace but never released"). Are these just further instances of the exception you initially reported?

I've raised the strict mode policy violation with our Auth team, but that doesn't seem related to this issue.

**Comment by mgenov** [comment] 2019-07-20 03:59
> @mgenov these last traces don't include the usual strict mode policy violation message (i.e. "A resource was acquired at attached stack trace but never released"). Are these just further instances of the exception you initially reported?

I've used Strict mode locally and this is the trace: https://github.com/firebase/firebase-android-sdk/issues/382#issuecomment-497055967

Here is a complete set of dependencies and their versions:
```groovy
// Authentication
implementation "com.google.firebase:firebase-auth:17.0.0"
// Real-time Database
implementation "com.google.firebase:firebase-database:17.0.0"
// Cloud Firestore
implementation "com.google.firebase:firebase-firestore:19.0.2"
```

**Comment by deputat007** [comment] 2019-11-19 08:38
`Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (21.3.0).
       at com.google.firebase.firestore.util.AsyncQueue.createAndScheduleDelayedTask(AsyncQueue.java)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(AsyncQueue.java)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6253)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)`
`Caused by android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=416 (# cursors opened by this proc=416)
       at android.database.CursorWindow.<init>(CursorWindow.java:108)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:225)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:143)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
       at com.google.firebase.firestore.local.SQLitePersistence$Query.binding(SQLitePersistence.java)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.add(SQLiteRemoteDocumentCache.java)
       at com.google.firebase.firestore.local.LocalStore.applyWriteToRemoteDocuments(LocalStore.java)
       at com.google.firebase.firestore.local.LocalStore.acknowledgeBatch(LocalStore.java)
       at com.google.firebase.firestore.local.LocalStore$$Lambda$3.get(LocalStore.java)
       at com.google.firebase.firestore.local.SQLitePersistence.access$000(SQLitePersistence.java)
       at com.google.firebase.firestore.local.LocalStore.acknowledgeBatch(LocalStore.java)
       at com.google.firebase.firestore.core.SyncEngine.addUserCallback(SyncEngine.java)
       at com.google.firebase.firestore.core.FirestoreClient.getDocumentFromLocalCache(FirestoreClient.java)
       at com.google.firebase.firestore.remote.RemoteStore.access$000(RemoteStore.java)
       at com.google.firebase.firestore.remote.RemoteStore.access$000(RemoteStore.java)
       at com.google.firebase.firestore.remote.RemoteStore$2.onClose(RemoteStore.java)
       at com.google.firebase.firestore.remote.WriteStream.inhibitBackoff(WriteStream.java)
       at com.google.firebase.firestore.remote.WriteStream.inhibitBackoff(WriteStream.java)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onClose$3(AbstractStream.java)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$Lambda$2.run(AbstractStream.java)
       at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onClose$3(AbstractStream.java)
       at com.google.firebase.firestore.remote.FirestoreChannel$1.onClose(FirestoreChannel.java)
       at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java)
       at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java)
       at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java)
       at io.grpc.internal.ContextRunnable.run(ContextRunnable.java)
       at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java)
       at java.lang.Thread.run(Thread.java:761)`

`
    // Firebase
    implementation 'com.google.firebase:firebase-analytics:17.2.1'
    implementation 'com.google.firebase:firebase-ads:18.3.0'
    implementation 'com.google.firebase:firebase-database:19.2.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.1'
    implementation 'com.google.firebase:firebase-firestore:21.3.0'
    implementation 'com.google.firebase:firebase-storage:19.1.0'
    implementation 'com.firebaseui:firebase-ui-storage:4.3.2'
    implementation 'com.google.firebase:firebase-config:19.0.3'`

**Comment by mikelehen** [comment] 2019-11-20 16:34
I'm going to close this issue and ask folks hitting `CursorWindowAllocationException` issues to comment on #629 instead just to keep that conversation in one place.

Unfortunately, despite many attempts we have not been able to reproduce the CursorWindowAllocationException issue and our working theory at this point is this is possibly just a symptom of overall low memory availability causing the app to crash.  This _could_ be due to your Firestore usage patterns but it could also be due to other memory-intensive operations (or leaks) in the app.  We're eager for more information that could prove or disprove this though (including anybody that can provide a way to reproduce the issue).

**Closed by mikelehen** 2019-11-20 16:34 UTC
Labels: api: firestore, needs-attention
