### ISSUE TITLE
Failed to get Firebase Instance ID token for fetch. FIS_AUTH_ERROR when fetching remote config

### ISSUE THREAD

**Issue by franvis** [firebase/firebase-android-sdk#1776] opened 2020-07-16 11:00 UTC
* Android Studio version: 4.0
* Firebase Component: Config
* Component version: 19.1.4

At the time of doing a `fetchAndActivate()`, the task finishes not successful with the following exception inside:

`Failed to get Firebase Instance ID token for fetch. FIS_AUTH_ERROR`

**Comment by rlazo** [comment] 2020-07-16 12:59
Hi @franvis, does this happen in `19.2.0` too? Also, are you using any other Firebase component?

**Comment by franvis** [comment] 2020-07-17 09:37
Hello @rlazo, thanks for the quick response. I will update the dependency to `19.2.0` and see what happens. 
We are using these other firebase components:
Performance: 19.0.7
Config: 19.1.4
Messaging: 20.2.0
Analytics: 17.4.2

**Comment by franvis** [comment] 2020-07-24 06:47
@rlazo Hello! We updated the version, and now in production we still have the same insane amount of failures but with this exception:
```
Firebase Installations failed to get installation auth token for fetch.
java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: AndroidOpenSSL, class: com.android.org.conscrypt.DefaultSSLContextImpl)
Error constructing implementation (algorithm: Default, provider: AndroidOpenSSL, class: com.android.org.conscrypt.DefaultSSLContextImpl)
java.security.KeyStoreException: BKS not found
BKS not found
BKS KeyStore not available
```

**Comment by cwliu** [comment] 2020-08-12 04:49
@franvis, I am also facing the same problem today. It turns out that it's the permission of the API key used in firebase.

I changed the following two settings on https://console.cloud.google.com/apis/credentials/key/

![image](https://user-images.githubusercontent.com/1084330/89976071-a8e26780-dc91-11ea-8860-5b8ddde38f82.png)

It's working now. You can also check this post: https://stackoverflow.com/a/61309137/475242

**Comment by franvis** [comment] 2020-08-13 08:26
Hello @cwliu, thank you very much for your advice. I had previously tried updating the google-services.json and didn't work. I added the restrictions now and updated again the json file just in case but I still see quite a lot of errors such as:
`The client had an error while calling the backend!
Unable to resolve host "firebaseremoteconfig.googleapis.com": No address associated with hostname
android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)`
`The client had an error while calling the backend!
failed to connect to firebaseremoteconfig.googleapis.com/172.217.17.42 (port 443) from /192.168.2.19 (port 48574) after 10000ms`
`Firebase Installations failed to get installation auth token for fetch.
null`

I'm starting to give up on Firebase, our top crash and top error log in our app are both related to it with really not clear ways to fix them.

**Comment by franvis** [comment] 2020-08-14 09:27
@rlazo @danasilver anything related to this please? We keep having lots of errors...

**Comment by ankitaj224** [comment] 2020-08-14 18:43
@franvis Extremely sorry to hear that you have been running into these issues with Firebase. I think #1626 and this issue are related, not 100% sure.  Can you please check if your app is implementing SSL pinning using self-signed or public certificates? 

My question is based on SO: https://stackoverflow.com/questions/59031966/self-signed-certificated-java-security-nosuchalgorithmexception-error-constru

FYI: I have internally raised a bug with Android Crypto & TLS (Conscrypt) library team regarding both these stack traces. I am waiting for their response.

**Comment by franvis** [comment] 2020-08-17 09:15
Hello @ankitaj224! Thank you for answering. 
As far as I can see we don't have anything related to SSL pinning in our production release. We do have some network configurations for our instrumented test but only for our debug build type so it's not reaching production.
Since the last thing I tried, which was @cwliu suggestion, we are spiking even more with our failures related to firebase (Almost 9k logs per day of failures) so we really need to work around this to make remote config work fine. 
Is there any other suggestion or thing we can try?

**Comment by ashwinraghav** [comment] 2020-08-19 03:40
@franvis thank you for your patience. Can you share whether you have enabled any restrictions on the API key that you are using on the client ? Based on the conversation above, It seems like you may have. 
Have you tried disabling these restrictions to determine whether the failures are caused by the restrictions?
Related, It's also worth checking your metrics on the Google cloud API console and determining whether the installations API backend is throwing errors. That should help isolate causes better.

**Comment by franvis** [comment] 2020-08-19 08:16
Hello @ashwinraghav, thank you very much for your answer and suggestion. 
Regarding your first question: 
I tried what it was suggested above by updating our google-services.json, and applying the restrictions but I removed them as soon as I realised that our error logs were increasing fast. So now we don't have any restriction in our API Key but still we have really a lot of errors per day coming from our users.

Related to your second suggestion: 
On the other hand I saw in google cloud api that the CreateInstallation is throwing some errors according to the metrics. Around 1.56%.

Other info:
1- Weird enough we started having some of this errors as well:
```
Fetch failed: The user is not authorized to access the project. Please make sure you are using the API key that corresponds to your Firebase project.
Forbidden
```
Do you have any idea why this might be happening? I checked and double checked that the KEY that we have in our google-services.json is the same as in the api credentials...

2- Our top 3 errors regarding the fetching of remote config are:
```
The client had an error while calling the backend! connect timed out
```
```
The client had an error while calling the backend! Unable to resolve host "firebaseremoteconfig.googleapis.com": No address associated with hostname android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
```
```
Fetch failed: The user is not authorized to access the project. Please make sure you are using the API key that corresponds to your Firebase project. Forbidden
```

3- The way we are fetching our remote config is by calling in the main activity:
```
val refreshTime =
            when (buildType) {
                "release" -> 3600L
                else -> 60L
            }
        firebaseRemoteConfig.apply {
            setDefaultsAsync(R.xml.remote_config_defaults).addOnCompleteListener { task ->
                if (!task.isSuccessful) {
                    logTaskFailure(task, DEFAULTS_SOURCE)
                }
            }
            setConfigSettingsAsync(
                    FirebaseRemoteConfigSettings.Builder()
                        .setFetchTimeoutInSeconds(10L)
                        .setMinimumFetchIntervalInSeconds(refreshTime)
                        .build())
                .addOnCompleteListener { task ->
                if (!task.isSuccessful) {
                    logTaskFailure(task, CONFIG_SETTINGS_SOURCE)
                }
            }
            fetchAndActivate().addOnCompleteListener { task ->
                if (!task.isSuccessful) {
                    logBooleanTaskFailure(task, FETCH_AND_ACTIVATE_SOURCE)
                }
            }
        }
```

**Comment by ashwinraghav** [comment] 2020-08-19 21:00
@franvis That's helpful!
> I tried what it was suggested above by updating our google-services.json, 

What did you have to update in the google-services ? That should not require any changes with any of the mitigations

> On the other hand I saw in google cloud api that the CreateInstallation is throwing some errors according to the metrics. Around 1.56%.

Does 1.56% roughly correspond with the number of errors you are seeing on the clients?

> The user is not authorized to access the project. Please make sure you are using the API key that corresponds to your Firebase project.
> Forbidden
> ```

My hunch is that this has to do with the API itself being enabled. See [SO](https://stackoverflow.com/questions/54603283/firebase-remote-config-fetch-failed-with-user-not-authorized) post.
 
> ```
> The client had an error while calling the backend! Unable to resolve host "firebaseremoteconfig.googleapis.com": No address associated with hostname android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
> ```
> 
This seems related to the device not having internet connectivity. See https://github.com/firebase/firebase-android-sdk/issues/1069

**Comment by franvis** [comment] 2020-08-20 05:57
> What did you have to update in the google-services ? That should not require any changes with any of the mitigations

I did two things as part of that suggestion. 
1- As I already mentioned, I restricted the API Key that we were using to certain API's (Remote config, installations, google maps). After seeing that not helping at all I removed the restrictions and left it as we had it before.
2- I noticed we had 2 SHA-256 in the firebase console settings of our project associated to our production app and one of them was wrong. So I removed it. After that I downloaded the new generated `google-services.json` and updated the one in our project.

> Does 1.56% roughly correspond with the number of errors you are seeing on the clients?

No, it doesn't. I checked our logs the last day and we had around 11k errors logged and in the metrics of google cloud we had 40 only.


> My hunch is that this has to do with the API itself being enabled. See [SO](https://stackoverflow.com/questions/54603283/firebase-remote-config-fetch-failed-with-user-not-authorized) post.

I checked this quite a lot of times during all these issues. I'm positive the API is enabled as I also see metrics for it (And not that many errors btw).

> This seems related to the device not having internet connectivity. See #1069

I will try to ignore that particular exception for those errors then, but I have to say that still looks quite odd to have thousands of people with bad internet connection...

**Comment by Paduado** [comment] 2020-08-25 23:15
> I will try to ignore that particular exception for those errors then, but I have to say that still looks quite odd to have thousands of people with bad internet connection...

I'm also having that same error with a lot of users, everything makes it seem like it is indeed a network issue, but I also find it very weird

**Comment by franvis** [comment] 2020-09-01 08:56
@ashwinraghav Hello, any news on this? Even ignoring that particular exception for supposedly not having internet connectivity we still have quite a lot of other errors when fetching config.

**Comment by franvis** [comment] 2020-09-10 14:24
Hello @ashwinraghav @ankitaj224 @rlazo , I noticed that when I downloaded the new `google-services.json` file it comes without an "oauth_client" that we use to have. And if I check in the Google Cloud console, that OAuth client it is indeed not there. After that I tried to re add it and Google Cloud complains saying that it already exists, although I cannot see it as I mentioned. Do you have any indication as to if this can be the cause of our problem? And if it is, how can I fix it?

**Comment by franvis** [comment] 2020-10-06 07:31
For everyone having this issue as well. We found the "problem" in our particular case. 
We were calling fetchAndActivate from the onCreate lifecycle method of our Application class. As far as I always saw, there's no mention of this being an issue in Firebase documentation (maybe I missed it?) but after we removed that, all the problems we were having (crashlytics was not working, remote config failing incredibly a lot, analytics giving strange results) got fixed. Hope it can help someone else. Will leave this open unless @ashwinraghav or @ankitaj224 or @rlazo think we can close it.

**Comment by andirayo** [comment] 2020-10-10 09:15
@egilmorez : FYI

**Comment by ankitaj224** [comment] 2020-10-21 17:35
Thanks for the update @franvis & clearing explaining how you fixed this issue. 

Android team responded that they are working on the fix which will be available in latest builds but it wont get backported to Android 7 & 8.  

I will go ahead & close this issue as there hasn't been any new reports. Please feel free to reopen if someone continues to run into this issue.

Thanks.

**Closed by ankitaj224** 2020-10-21 17:35 UTC
Labels: api: remoteconfig, firebase-installations, needs-attention
