### ISSUE TITLE
Google Auth Linking overwrites other auth providers.

### ISSUE THREAD

**Issue by shubhendu1** [firebase/firebase-android-sdk#25] opened 2018-09-18 13:49 UTC
* Android Studio version: 3.1.4
  * Firebase Component: Authentication
  * Component version: 16.0.3

I am trying to link multiple auth providers for a user, everything is working fine but when user tries to connect google account to other auth providers account, google account seems to overwrite every other account.

#### Steps to reproduce:

Created account using email and password.
Linked with facebook and twitter account.
And after linking to Google account, it overwrites all the other accounts.

#### Relevant Code:

```
AuthCredential credential = GoogleAuthProvider.getCredential(account.getIdToken(), null);
FirebaseUser user = mAuth.getCurrentUser();
user.linkWithCredential(credential);

```

**Comment by bojeil-google** [comment] 2018-09-18 16:45
That should not be the case. Google would overwrite existing providers if you sign in with it. Check this [post](https://stackoverflow.com/questions/40766312/firebase-overwrites-signin-with-google-account/40768870) for more on this behavior. However, if you link the credential, the existing providers should remain.

**Comment by samtstern** [comment] 2018-10-10 16:33
Closing as @bojeil-google has identified this as intended behavior.  Thanks for clarifying!

**Closed by samtstern** 2018-10-10 16:33 UTC
