### ISSUE TITLE
No response while creating short dynamic link if Google Play Services are present but disabled

### ISSUE THREAD

**Issue by maksym-moroz** [firebase/firebase-android-sdk#2712] opened 2021-06-03 10:44 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2
  * Firebase Component: Dynamic Links
  * Component version: com.google.firebase:firebase-dynamic-links:19.1.1

#### Steps to reproduce:

After I try to shorten dynamic link there is no response from Firebase API regardless of callback

The code provided in section "Relevant code" will never emit if Google Play Services are present on the device but were manually stopped and disabled through settings. 
Note that this code works fine if Google Play Services are present and enabled.
It works fine if there are no Google Play Services on the device through .addOnFailureListener { }
However if Google Play Services happen to be disabled Firebase API fails.

Note that other callback such as addOnCompleteListener or addOnCancelled do not work as well.
I can provide any additional info if needed.
This is easy to reproduce and should be easy to fix. Thanks
#### Relevant Code:

Single.create { emitter ->
                Firebase.dynamicLinks.shortLinkAsync(ShortDynamicLink.Suffix.SHORT) {
                    longLink = dynamicLink
                }
                    .addOnSuccessListener { emitter.onSuccess(it.shortLink.toString()) }
                    .addOnFailureListener { emitter.onSuccess(dynamicLink.toString()) }
            }
           
```
// TODO(you): code here to reproduce the problem
```

**Comment by gsakakihara** [comment] 2021-06-07 18:09
When you make the shorten dynamic link call with Google Play services disabled, do you see a notification appear that asks to enable Google Play services? If you click on that notification and then either enable or not and leave that screen, do you then get a success/failure callback?

**Comment by maksym-moroz** [comment] 2021-06-07 21:19
@gsakakihara No notification.

**Comment by gsakakihara** [comment] 2021-06-08 14:41
It should be showing a notification when it's unable to connect to Google Play services because it is disabled. What device are you seeing this on? Do you see anything in the logs when you make the API call?

**Comment by maksym-moroz** [comment] 2021-06-12 20:41
I looked into it and this is what I get. The issue is reproducing on Android TV emulator with google play services manually disabled.

```
2021-06-06 23:34:11.735 26169-26169/com.***.application W/FA: Service connection failed: ConnectionResult{statusCode=SERVICE_DISABLED, resolution=null, message=null}
2021-06-06 23:34:11.739 26169-26514/com.***.application W/GoogleApiManager: The service for com.google.firebase.dynamiclinks.internal.zzd is not available: ConnectionResult{statusCode=SERVICE_DISABLED, resolution=null, message=null}
2021-06-06 23:34:11.758 26169-26236/com.***.application D/EGL_emulation: eglMakeCurrent: 0xdd91ab40: ver 3 0 (tinfo 0xdd90fe40)
2021-06-06 23:34:11.760 26169-26514/com.***.application W/GoogleApiAvailability: GMS core API Availability. ConnectionResult=3, tag=null
    java.lang.IllegalArgumentException
        at com.google.android.gms.common.GoogleApiAvailability.zaa(com.google.android.gms:play-services-base@@17.5.0:51)
        at com.google.android.gms.common.GoogleApiAvailability.zaa(com.google.android.gms:play-services-base@@17.5.0:117)
        at com.google.android.gms.common.api.internal.GoogleApiManager.zaa(com.google.android.gms:play-services-base@@17.5.0:252)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.5.0:109)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(com.google.android.gms:play-services-base@@17.5.0:75)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zai(com.google.android.gms:play-services-base@@17.5.0:263)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.5.0:133)
        at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@17.5.0:164)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-06-06 23:34:11.892 26169-26210/com.***.application V/FA: Connecting to remote service
2021-06-06 23:34:11.894 26169-26169/com.***.application W/FA: Service connection failed: ConnectionResult{statusCode=SERVICE_DISABLED, resolution=null, message=null}
2021-06-06 23:34:11.897 26169-26210/com.***.application V/FA: Connecting to remote service
2021-06-06 23:34:11.906 26169-26169/com.***.application W/FA: Service connection failed: ConnectionResult{statusCode=SERVICE_DISABLED, resolution=null, message=null}
2021-06-06 23:34:11.907 26169-26210/com.***.application V/FA: Processing queued up service tasks: 4
2021-06-06 23:34:11.907 26169-26210/com.***.application E/FA: Failed to send current screen to service
2021-06-06 23:34:11.907 26169-26210/com.***.application E/FA: Discarding data. Failed to send event to service
2021-06-06 23:34:11.907 26169-26210/com.***.application E/FA: Discarding data. Failed to send event to service
2021-06-06 23:34:11.907 26169-26210/com.***.application E/FA: Failed to send current screen to service
2021-06-06 23:34:11.907 26169-26210/com.***.application V/FA: Processing queued up service tasks: 0
2021-06-06 23:34:11.908 26169-26210/com.***.application V/FA: Processing queued up service tasks: 0

```
The issue is replicating always. I have moved logic out of rx chain after thinking issue may lie in _Single.create_ scheduler but to no success. The issue persists

**Comment by gsakakihara** [comment] 2021-06-14 19:12
That stack trace actually seems to be correct, it's recognizing that GMS Core is disabled. The notification that is supposed to be displayed is not being shown, though, which looks like it may be due to a difference in how notifications are handled on Android TV. I've filed an bug for this on the GMS Core common library that handles this (internal reference number 191055291).

**Comment by maksym-moroz** [comment] 2021-07-19 08:46
Hi, any updates? Is there a link I can track the progress on this? Thank you

**Comment by maksym-moroz** [comment] 2021-07-20 12:57
@gsakakihara fyi

**Comment by gsakakihara** [comment] 2021-07-26 21:46
The team working on this has investigated the bug and it looks like the plan is to return an error immediately if this happens on Android TV. I don't have a time frame on when this will be fixed, though.

**Comment by argzdev** [comment] 2023-01-18 14:27
There's been quite a few updates since this was initially reported. That said, I'll close this issue for now. Feel free to ask this to be reopened if this is still reproducible on the latest version of Firebase Dynamic Links `21.1.0`

**Closed by argzdev** 2023-01-18 14:27 UTC
Labels: api: dynamiclinks, internal-bug-filed
