### ISSUE TITLE
Sporadic crashes after calling FirebaseInstallations.delete()

### ISSUE THREAD

**Issue by davidmigloz** [firebase/firebase-android-sdk#3103] opened 2021-11-03 10:49 UTC
###  Describe your environment

  * Android Studio version: 
```
Android Studio Arctic Fox | 2020.3.1 Patch 1
Build #AI-203.7717.56.2031.7621141, built on August 7, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
```
  * Firebase Component: Firebase Installations 
  * Component version: BoM 28.4.2

### Describe the problem

Every day we get at least one crash when the app tries to reset the Firebase installation (when the user logs out of the app).

#### Steps to reproduce:

Our code looks like this:
```kotlin
private suspend fun resetFirebase() {
    FirebaseMessaging.getInstance().deleteToken().await()
    FirebaseInstallations.getInstance().delete().await()
} 
```

The stack trace of the crash we get is the following:

```
Fatal Exception: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.deleteFirebaseInstallation(FirebaseInstallationServiceClient.java:356)
       at com.google.firebase.installations.FirebaseInstallations.deleteFirebaseInstallationId(FirebaseInstallations.java:601)
       at com.google.firebase.installations.FirebaseInstallations.$r8$lambda$ukIZcZ_XlkiT9OCDxQIhblgD6_Y(FirebaseInstallations.java)
       at com.google.firebase.heartbeatinfo.DefaultHeartBeatInfo$$InternalSyntheticLambda$0$2e3b229a5d659018965e6d1c65d3d8a9938514d7e32639c0222b9ff8668a0b97$0.call$bridge(DefaultHeartBeatInfo.java:28)
       at com.google.android.gms.tasks.zzx.run(zzx.java:18)
       at com.google.android.gms.cloudmessaging.zzk.run$bridge(zzk.java:18)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

Is it normal to get Service Unavailable so frequently? 
Should I add a retry mechanism? If so, after how much time should I retry?
Thanks.

**Comment by argzdev** [comment] 2021-11-04 09:15
Hi @davidmigloz, thanks for reporting. I'll try to investigate and see what I can find.

**Comment by argzdev** [comment] 2021-11-04 17:13
Hi @davidmigloz, after investigating with our engineers. It seems that there is already a [retry mechanism](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java#L324) set in place for FirebaseInstallations. With that said, there is no need to add a retry mechanism, and it would be best to add a try catch for this line of code in case the issue is encountered. As for the service unavailable issue, this is most likely due to a server side issue. 

If this bothers more developers in the future, then we investigate this further. But since the occurrence on a daily basis is rare and difficult to reproduce, we will be closing the ticket for now. Thank you for your understanding.

**Closed by argzdev** 2021-11-04 17:13 UTC
Labels: api: installations

**Comment by davidmigloz** [comment] 2021-11-04 18:21
Thanks for the investigation @argzdev. 
Understood, I'll catch the exception for now.

**Comment by Zookey** [comment] 2021-11-30 12:28
I am getting the same exception: Caused by com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.

For me it seems that it happens when the SDK tries to generate auth token.

Why would this happen? Firebase server is down or user does not have Internet connection or something else?

`Caused by com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(FirebaseInstallationServiceClient.java:452)
       at com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(FirebaseInstallations.java:566)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:390)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2$FirebaseInstallations(FirebaseInstallations.java:377)
       at com.google.firebase.installations.-$$Lambda$FirebaseInstallations$VZq1h0TBcWNH8Y5yY86ujrFFyLo.run(:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)`
