### ISSUE TITLE
Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_STANDARD

### ISSUE THREAD

**Issue by rahul00845** [firebase/firebase-android-sdk#2957] opened 2021-09-06 07:26 UTC
Android Studio version: _____Android Studio arctic fox 2020.3.1
Firebase Component: _____ firebase-messaging
Component version: _____'com.google.firebase:firebase-bom:27.1.0'

We got this crash for few users repetitively, not reproducible, this is reported in crashlytics. It is happening for Android * 8 on devices Xiaomi, Vivo.

android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex (TimeZoneNamesImpl.java:724)
android.icu.impl.TimeZoneNamesImpl$ZNames.getName (TimeZoneNamesImpl.java:790)
android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName (TimeZoneNamesImpl.java:183)
android.icu.text.TimeZoneNames.getDisplayName (TimeZoneNames.java:261)
java.text.SimpleDateFormat.subFormat (SimpleDateFormat.java:1296)
java.text.SimpleDateFormat.format (SimpleDateFormat.java:1004)
java.text.SimpleDateFormat.format (SimpleDateFormat.java:974)
java.text.DateFormat.format (DateFormat.java:341)
com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.isSameDateUtc (HeartBeatInfoStorage.java:133)
com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.shouldSendSdkHeartBeat (HeartBeatInfoStorage.java:143)
com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.shouldSendGlobalHeartBeat (HeartBeatInfoStorage.java:159)
com.google.firebase.heartbeatinfo.DefaultHeartBeatInfo.getHeartBeatCode (DefaultHeartBeatInfo.java:72)
com.google.firebase.firestore.remote.FirebaseClientGrpcMetadataProvider.updateMetadata (FirebaseClientGrpcMetadataProvider.java:62)
com.google.firebase.firestore.remote.FirestoreChannel.requestHeaders (FirestoreChannel.java:300)
com.google.firebase.firestore.remote.FirestoreChannel.lambda$runBidiStreamingRpc$0 (FirestoreChannel.java:149)
com.google.firebase.firestore.remote.FirestoreChannel$$Lambda$1.onComplete (FirestoreChannel.java:6)
com.google.android.gms.tasks.zzi.run (zzi.java:7)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:457)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run (AsyncQueue.java:229)
java.lang.Thread.run (Thread.java:764)

**Comment by aguatno** [comment] 2021-09-06 18:35
Hi @rahul00845 thanks for reporting. It looks like this is a duplicate of #2740. Closing this to avoid duplicate efforts. Please upvote there instead or leave a comment. Thanks.

**Closed by aguatno** 2021-09-06 18:35 UTC
Labels: api: messaging
