### ISSUE TITLE
Add android 14 support to modeldownloader 

### ISSUE THREAD

**Issue by OleksandrGrument** [firebase/firebase-android-sdk#5593] opened 2023-12-08 11:56 UTC
### [REQUIRED] Step 2: Describe your environment

  * Firebase Component: com.google.firebase:firebase-ml-modeldownloader-ktx:24.2.1
  * Component version: 24.2.1

### [REQUIRED] Step 3: Describe the problem
The library not support new changes in android 14 
https://developer.android.com/about/versions/14/behavior-changes-14

According to the documentation and changelog - runtime-registered broadcasts receivers must specify export behavior according to new rules
![image](https://github.com/firebase/firebase-android-sdk/assets/20426405/1ff712e1-e1d9-4aa6-9b40-bd58b1e4ef32)

#### Steps to reproduce:
Update target sdk of project to  targetSdkVersion 34
And after migration im having regular this issue when i'm trying to download custom model 

Firebase exception, java.lang.SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

**Comment by argzdev** [comment] 2023-12-08 13:52
Hey @OleksandrGrument, thanks for reporting. Could you share with us the full stacktrace. Thanks!

**Comment by argzdev** [comment] 2023-12-08 14:28
Hi @OleksandrGrument, I was wondering which line of code or file in our `firebase-ml-modeldownloader` SDK is triggering this exception. Was there any references to the SDK from the stacktrace?

**Comment by OleksandrGrument** [comment] 2023-12-08 15:04
@argzdev I'm getting exception in addOnFailureListener 
![image](https://github.com/firebase/firebase-android-sdk/assets/20426405/db3cb981-d2fa-4cb9-a0bf-863b945e581c)

**Comment by argzdev** [comment] 2023-12-11 14:49
Got it, thanks @OleksandrGrument. I was able to reproduce the same behavior. I'll notify our engineers and see what we can do here.

**Comment by OleksandrGrument** [comment] 2023-12-11 14:51
@argzdev Awesome. Thank you

**Comment by argzdev** [comment] 2023-12-20 11:40
Hi @OleksandrGrument, since the fix has been merged. I'll go ahead and close this. As for when it'll be available, we generally aim to release every few weeks, but due to the holiday seasons, we'll likely expect this to be available sometime next year.

**Closed by argzdev** 2023-12-20 11:40 UTC
Labels: type: bug, api: mlkit
