### ISSUE TITLE
google-services:4.4.0 is incompatible with appdistribution:4.0.0

### ISSUE THREAD

**Issue by sergei-lapin** [firebase/firebase-android-sdk#5349] opened 2023-09-21 08:00 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Giraffe 2022.3.1 Patch 1
  * Firebase Component: Firebase App Distribution
  * Component version: 4.0.0

### [REQUIRED] Step 3: Describe the problem

After upgrade to `com.google.gms.google-services:4.4.0` Firebase App Distribution's task `appDistributionUpload***` started to fail with `Missing app id. Please check that it was passed in and try again`. Rolling `google-services` back to `4.3.15` resolved the issue.

#### Steps to reproduce:

1. Specify credentials for upload via `GOOGLE_APPLICATION_CREDENTIALS` environment variable
2. AGP 8.1.1
3. Gradle 8.3
4. `com.google.gms.google-services:4.4.0`
5. `com.google.firebase.appdistribution:4.0.0`
6. Run `./gradlew :app:appDistributionUpload***`

**Comment by argzdev** [comment] 2023-09-21 10:07
Hi @sergei-lapin, thanks for reaching out. I was able to reproduce the same behavior. Interestingly there's an odd behavior where this works, because of the `Using cached Firebase CLI credentials`.

Scenario 1:
1. Use version `com.google.gms.google-services:4.3.15`
2. Use `export GOOGLE_APPLICATION_CREDENTIALS=....` in terminal
3. Run `gradle app:assembleDebug app:appDistributionUploadDebug` (works)
4. Update to version `com.google.gms.google-services:4.4.0`
5. Run `gradle app:assembleDebug app:appDistributionUploadDebug` (works, because of the cached credential)

Scenario 2:
1. Use version `com.google.gms.google-services:4.4.0`
2. Clean and rebuild the project
2. Use `export GOOGLE_APPLICATION_CREDENTIALS=....` in terminal
3. Run `gradle app:assembleDebug app:appDistributionUploadDebug` (error missing app id is encountered)

That said, I'll notify our engineers and we'll keep you posted once we receive feedback.

**Comment by mtrakal** [comment] 2023-10-02 08:48
It's a regression of: https://github.com/firebase/firebase-android-sdk/issues/3403

**Comment by mwolfe38** [comment] 2023-10-03 18:37
Looking at the build directories with 4.3.15 vs 4.4.0 I notice the following differences:
4.4.0:
contains a gmpAppId.txt file at the top level. 
contains app/build/generated/res/process[variant]GoogleServices/values/values.xml 

example:
`app/build/generated/res/processStandardReleaseGoogleServices/values/values.xml`


4.3.15
no gmpAppId.txt file at the top level
contains app/build/generated/res/google-services/[variant-subfolders]/values/values.xml
example: `app/build/generated/res/google-services/standard/release/values/values.xml`

Both of the values.xml files are the same

**Comment by vzahradnik** [comment] 2023-10-17 13:15
I can confirm the findings of @mwolfe38 . I wish I could find this thread sooner and save time on debugging :)

**Comment by argzdev** [comment] 2023-10-18 16:32
Hi folks, just an update, our engineers are rolling out a fix in the next release. We expect this release targeted for next week. We'll keep you posted!

**Comment by argzdev** [comment] 2023-10-27 13:35
Hi folks, the fix is now available in the [latest update](https://firebase.google.com/support/release-notes/android#appdistro_gradle_plugin_v4-0-1) for App Distribution. Please use version `4.0.1`. That said, I'll go ahead and close this now. Thanks!

**Closed by argzdev** 2023-10-27 13:35 UTC
Labels: type: bug, api: appdistribution
