### ISSUE TITLE
Firebase Analytics engagement time is weird when using aac navigation with fragment.

### ISSUE THREAD

**Issue by fromdestiny** [firebase/firebase-android-sdk#3949] opened 2022-07-28 05:01 UTC
### [READ] Step 1: Are you in the right place?
Yes.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Chipmunk 2021.2.1
  * Firebase Component: firebase-analytics
  * Component version: firebasebom 30.1.0

### [REQUIRED] Step 3: Describe the problem
Engagement time is too much long. 

#### Steps to reproduce:

1. I'm using android aac Navigation. 
androidx.navigation:navigation-ui-ktx:2.4.1
androidx.navigation:navigation-fragment-ktx:2.4.1

2. And turned off google_analytics_automatic_screen_report

`
<meta-data
            android:name="google_analytics_automatic_screen_reporting_enabled"
            android:value="false" /> `

3. And I'm using SingleActivity with Fragments.  When screen change, I call findNavController().navigate({otherFragment}) or findNavController().popBackStack() or onBackPressed().

Every fragment after onResume send screenName log event.
  ```
 firebaseAnalytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW, Bundle().apply {
        putString(FirebaseAnalytics.Param.SCREEN_CLASS, "splash")
        putString(FirebaseAnalytics.Param.SCREEN_NAME, "splash")
    })
```

4. screen event is logged.(It's ok!!)  but The problem is Android engagement time. 
![스크린샷 2022-07-28 오후 12 08 55](https://user-images.githubusercontent.com/6613160/181411943-8d7a02a8-dffb-4dc2-ad89-cfbaea3c8a76.png)
![스크린샷 2022-07-28 오후 1 41 09](https://user-images.githubusercontent.com/6613160/181422077-e70a1cd2-0917-4923-849e-639aa661734e.png)

 My splash fragment is for loading app initial data. So it couldn't be show more than 10s. 
I think user's behavior is not different between iOS and aos. And IOS's engagement time is what I excepted. 

What is wrong in my android code?..

**Comment by argzdev** [comment] 2022-08-03 15:10
Hi @fromdestiny, thanks for reporting. Sorry for the delayed response here. I tried simulating this by creating a clean project with one activity and 2 fragments with buttons to redirect from first to second fragment, or vice versa. However, checking the logs for the `engagement_time` being recorded by the SDK seems to produce the correct duration.

I believe the issue is more related on the server side computation. That being said, your analytics data now resides in the Google Analytics property in Firebase and not in the Firebase project itself. I would recommend checking it with [Google Analytics Support](https://support.google.com/analytics/answer/9026876?hl=en) as they can offer more assistance with regards to this kind of issue.

Closing for now, feel free to reopen if you think this is an SDK issue. Thanks!

**Closed by argzdev** 2022-08-03 15:10 UTC
Labels: api: analytics

**Comment by fromdestiny** [comment] 2022-08-04 03:23
Thank you for reply. I would like to ask about "How to checking the logs for the engagement_time" .

In firebase debug view  when I check the screen_view event
![Screen Shot 2022-08-04 at 12 22 14 PM](https://user-images.githubusercontent.com/6613160/182756133-6cd8b693-4f35-42af-a23a-6f639ac6de0d.png)


engagement_time_msec :  38062
firebase_previous_screen :  B
firebase_screen : A
.... etc... 

What is the engagement_time_msec means? 
Is it means  how long user stay in B screen(previous_screen) ??

**Comment by argzdev** [comment] 2022-08-04 09:26
> How to checking the logs for the engagement_time

We simply check this via the logcat. You would notice during logging an event, there is a log entry for `screen_view` event that it contains a parameter for `engagement_time_msec`.

```
2022-08-04 17:00:14.213 752-1085/com.argz.issue3949 V/FA: Logging screen view with name, class: second, second
2022-08-04 17:00:14.372 752-1086/com.argz.issue3949 V/FA: Connecting to remote service
2022-08-04 17:00:14.461 752-1086/com.argz.issue3949 V/FA: Recording user engagement, ms: 18503
2022-08-04 17:00:14.473 752-1086/com.argz.issue3949 V/FA: Connection attempt already in progress
2022-08-04 17:00:14.473 752-1086/com.argz.issue3949 D/FA: Connected to remote service
2022-08-04 17:00:14.482 752-1086/com.argz.issue3949 V/FA: Processing queued up service tasks: 2
2022-08-04 17:00:14.548 16591-1087/? V/FA-SVC: Logging event: origin=app,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=app, engagement_time_msec(_et)=18503, ga_previous_class(_pc)=first, ga_previous_id(_pi)=-1829375040917825866, ga_previous_screen(_pn)=first, ga_screen_class(_sc)=second, ga_screen_id(_si)=-1829375040917825865, ga_screen(_sn)=second, manual_tracking(_mst)=1}]
```

> What is the engagement_time_msec means?
Is it means how long user stay in B screen(previous_screen) ??

Yes, you're correct. That is the simplest explanation of what `engagement_time_msec` is. As you can see from our documentations [here](https://support.google.com/analytics/answer/11109416?hl=en):
> The User engagement metric shows the time that your app screen was in the foreground or your web page was in focus. When your site or app is running but no page or screen is displayed, Analytics doesn't collect the metric. The metric can help you understand when users actively use your website or app.

You may check this [comment](https://github.com/firebase/firebase-android-sdk/issues/3933#issuecomment-1192836562) for further explanation. 

Regarding the discrepancy in your data, I think reaching out to [Google Analytics Support](https://support.google.com/analytics/answer/9026876?hl=en) will help you with your issue. They have specialists which can offer more assistance.

You can also try the support options below:
- [Google Analytics 360](https://support.google.com/marketingplatform/answer/9026876) (360 partner agencies and direct clients only)
- For other questions, please reach out to the [Google Analytics Help Community](https://support.google.com/analytics/community).
 
Should you have other Firebase-specific questions, you could always reach out to us through our [support channel](https://firebase.google.com/support/).
