### ISSUE TITLE
ANR executing service com.google.firebase.auth.api.fallback.service.FirebaseAuthFallbackService

### ISSUE THREAD

**Issue by mkocus** [firebase/firebase-android-sdk#3300] opened 2022-01-11 11:06 UTC
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2020.3.1 Patch 4
  * Firebase Component: BoM 29.03 (crashlytics, config-ktx, dynamic-links-ktx, analytics-ktx, database-ktx, auth-ktx)
  * Component version: as specified in BoM

#### Steps to reproduce:

We have starting seeing random ANRr on our users, which are reported to happen inside `FirebaseAuthFallbackService`. They seem to happen during the application first start.

We have previously updated the Firebase version to use BoM format. It seems that the firebase crashlytics logs massive amount of same error about missing open logs before giving ANR.

We cannot give reliable reproduction scenario.

```
... lots of lines repeated below ...
2022-01-11 11:47:10.581 3968-4436/<our_package> E/FirebaseCrashlytics: Could not open log file: /data/user/0/<our_package>/files/.com.google.firebase.crashlytics.files.v1/open-sessions/60EEC7AE028D00010F808FBD31139444/userlog
2022-01-11 11:47:10.634 3968-4436/<our_package> E/FirebaseCrashlytics: Could not open log file: /data/user/0/<our_package>/files/.com.google.firebase.crashlytics.files.v1/open-sessions/60EEC7AE028D00010F808FBD31139444/userlog
2022-01-11 11:47:10.687 3968-4436/<our_package> E/FirebaseCrashlytics: Could not open log file: /data/user/0/<our_package>/files/.com.google.firebase.crashlytics.files.v1/open-sessions/60EEC7AE028D00010F808FBD31139444/userlog
    java.io.FileNotFoundException: /data/user/0/<our_package>/files/.com.google.firebase.crashlytics.files.v1/open-sessions/60EEC7AE028D00010F808FBD31139444/userlog.tmp: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:485)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288)
        at com.google.firebase.crashlytics.internal.log.QueueFile.open(QueueFile.java:221)
        at com.google.firebase.crashlytics.internal.log.QueueFile.initialize(QueueFile.java:202)
        at com.google.firebase.crashlytics.internal.log.QueueFile.<init>(QueueFile.java:117)
        at com.google.firebase.crashlytics.internal.log.QueueFileLogStore.openLogFile(QueueFileLogStore.java:128)
        at com.google.firebase.crashlytics.internal.log.QueueFileLogStore.writeToLog(QueueFileLogStore.java:52)
        at com.google.firebase.crashlytics.internal.log.LogFileManager.writeToLog(LogFileManager.java:64)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(CrashlyticsController.java:387)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(CrashlyticsController.java:383)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105)
        at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
        at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
        at libcore.io.IoBridge.open(IoBridge.java:471)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288) 
        at com.google.firebase.crashlytics.internal.log.QueueFile.open(QueueFile.java:221) 
        at com.google.firebase.crashlytics.internal.log.QueueFile.initialize(QueueFile.java:202) 
        at com.google.firebase.crashlytics.internal.log.QueueFile.<init>(QueueFile.java:117) 
        at com.google.firebase.crashlytics.internal.log.QueueFileLogStore.openLogFile(QueueFileLogStore.java:128) 
        at com.google.firebase.crashlytics.internal.log.QueueFileLogStore.writeToLog(QueueFileLogStore.java:52) 
        at com.google.firebase.crashlytics.internal.log.LogFileManager.writeToLog(LogFileManager.java:64) 
        at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(CrashlyticsController.java:387) 
        at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(CrashlyticsController.java:383) 
        at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105) 
        at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:3) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64) 
        at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27) 
        at java.lang.Thread.run(Thread.java:764) 

2022-01-11 11:47:10.941 3320-3334/? E/ActivityManager: ANR in <our_package>
    PID: 3968
    Reason: executing service <our_package>/com.google.firebase.auth.api.fallback.service.FirebaseAuthFallbackService
    Load: 7.83 / 1.96 / 0.66
    CPU usage from 0ms to 13333ms later (2022-01-11 11:46:57.579 to 2022-01-11 11:47:10.912):
      100% 3968/<our_package>: 93% user + 6.6% kernel / faults: 29579 minor 34 major
      49% 3320/system_server: 31% user + 18% kernel / faults: 5001 minor 4 major
...
```

#### Relevant Code:

No relevant code, information given above.

**Comment by argzdev** [comment] 2022-01-11 11:20
Hi @mkocus, thanks for reporting. This looks like a duplicate of #2387. With that said, please continue your report there instead, and give the issue a thumbs up so our engineers can prioritize it based on severity. Thanks!

**Closed** 2022-01-11 11:21 UTC
Labels: api: auth

**Comment by mkocus** [comment] 2022-01-11 15:25
Ok, will do that. Thanks for the quick response.
