### ISSUE TITLE
Request: Api to get FirebaseMessaging instance or token for non default FirebaseApp

### ISSUE THREAD

**Issue by thejk** [firebase/firebase-android-sdk#3205] opened 2021-12-06 13:46 UTC
## What feature would you like to see?

An API to access FirebaseMessaging instances for a specific FirebaseApp and not only the default project. Similar to FirebaseDatabase.getInstance(FirebaseApp app) I imagine. This would allow FirebaseMessaging.getInstance(app).getToken() to work with multiple projects. 
From #2778 we understand that expanding getToken() to support senderID is not planned.

## How would you use it?

To replace the deprecated FirebaseInstanceId.getInstance().getToken(senderID, FirebaseMessaging.INSTANCE_ID_SCOPE);
We use FCM with multiple firebase projects in the same app and as noted FirebaseMessaging.getInstance().getToken() only gives access to the default project.

**Comment by argzdev** [comment] 2021-12-06 14:06
Hi @thejk, thank you for your input. I'll mark this as a feature request so our engineers can have a look and discuss this further once they have time. Thanks!

**Comment by gsakakihara** [comment] 2021-12-06 15:51
Duplicate of https://github.com/firebase/firebase-android-sdk/issues/2285.

**Closed by gsakakihara** 2021-12-06 15:51 UTC
Labels: type: feature request, api: messaging
