### ISSUE TITLE
Firebase Auth crashes with OutOfMemoryError in Android 12

### ISSUE THREAD

**Issue by mutual-arildo** [firebase/firebase-android-sdk#3617] opened 2022-04-04 19:06 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Bumblebee 2021.1.1 Patch 2
  * Firebase Component: auth
  * Component version: firebase-auth:21.0.3
  * Device: Android 12 - Samsung S10

### [REQUIRED] Step 3: Describe the problem

Firebase Auth crashes with OutOfMemoryError in Android 12

#### Steps to reproduce:

This is the console output for one of our Android 12 users getting the crash.

java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 25165824 free bytes and 104MB until OOM, target footprint 452092968, growth limit 536870912
    at java.util.Arrays.copyOf(Arrays.java:3257)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
    at java.lang.StringBuilder.append(StringBuilder.java:203)
    at org.json.JSONStringer.string(JSONStringer.java:327)
    at org.json.JSONStringer.value(JSONStringer.java:261)
    at org.json.JSONArray.writeTo(JSONArray.java:616)
    at org.json.JSONStringer.value(JSONStringer.java:242)
    at org.json.JSONObject.writeTo(JSONObject.java:740)
    at org.json.JSONObject.toString(JSONObject.java:708)
    at com.google.firebase.auth.internal.zzbg.zzd(com.google.firebase:firebase-auth@@21.0.3:27)
    at com.google.firebase.auth.FirebaseAuth.zzH(com.google.firebase:firebase-auth@@21.0.3:13)
    at com.google.firebase.auth.zzo.zza(com.google.firebase:firebase-auth@@21.0.3:1)
    at com.google.android.gms.internal.firebase-auth-api.zzrv.zzb(com.google.firebase:firebase-auth@@21.0.3:3)
    at com.google.android.gms.internal.firebase-auth-api.zzuh.zzj(com.google.firebase:firebase-auth@@21.0.3:1)
    at com.google.android.gms.internal.firebase-auth-api.zzue.zzn(com.google.firebase:firebase-auth@@21.0.3:2)
    at com.google.android.gms.internal.firebase-auth-api.zztg.zzn(com.google.firebase:firebase-auth@@21.0.3:1)
    at com.google.android.gms.internal.firebase-auth-api.zzqe.zzb(com.google.firebase:firebase-auth@@21.0.3:2)
    at com.google.android.gms.internal.firebase-auth-api.zzup.zza(com.google.firebase:firebase-auth@@21.0.3:24)
    at com.google.android.gms.internal.firebase-auth-api.zztv.zzf(com.google.firebase:firebase-auth@@21.0.3:4)
    at com.google.android.gms.internal.firebase-auth-api.zzrl.zzp(com.google.firebase:firebase-auth@@21.0.3:4)
    at com.google.android.gms.internal.firebase-auth-api.zzth.zzj(com.google.firebase:firebase-auth@@21.0.3:5)
    at com.google.android.gms.internal.firebase-auth-api.zzrv.zzc(com.google.firebase:firebase-auth@@21.0.3:1)
    at com.google.android.gms.internal.firebase-auth-api.zzui.run(com.google.firebase:firebase-auth@@21.0.3:1)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

#### Relevant Code:
It calls this code when resuming the app and crashes.

```
fun checkSignedIn(isPhoneAuth: Boolean) {
        if (!isPhoneAuth) {
            val fireBaseUser = FirebaseAuth.getInstance().currentUser

            fireBaseUser?.let { user ->

                user.getIdToken(true)
                        .addOnCompleteListener { task ->
                            if (task.isSuccessful) {
                                task.result?.token?.let { token ->
                                    if (loggingIn) {
                                        login(token, LoginMethod.FACEBOOK)
                                    } else {
                                        signup(token, LoginMethod.FACEBOOK)
                                    }
                                } ?: kotlin.run {
                                    resetLogin()
                                }
                            } else {
                                resetLogin()
                                val exception = task.exception
                                val errorMessage = exception?.message ?: ""

                                onError(errorMessage)
                            }
                        }
            } ?: kotlin.run {
                if (!isLoading) {
                    showLogin()
                }
            }
        } else {

            val fireBaseUser = FirebaseAuth.getInstance().currentUser

            fireBaseUser?.let { user ->

                user.getIdToken(true)
                        .addOnCompleteListener { task ->
                            if (task.isSuccessful) {
                                task.result?.token?.let { token ->
                                    saveAccessToken(token)
                                    phoneAuthAccessToken = token

                                    if (loggingIn) {
                                        login(phoneAuthAccessToken, LoginMethod.PHONE)
                                    } else {
                                        signup(phoneAuthAccessToken, LoginMethod.PHONE)
                                    }
                                } ?: kotlin.run {
                                    resetLogin()
                                }
                            } else {
                                resetLogin()
                                val exception = task.exception
                                val errorMessage = exception?.message ?: ""

                                onError(errorMessage)
                            }
                        }
            } ?: kotlin.run {
                //resetLogin()
                if (!isLoading) {
                    showLogin()
                }
            }
        }
    }
```

**Comment by fangyuxi** [comment] 2022-04-07 04:54
We have faced the same crash and the same crash stack, please fix it asap, thank you.

**Comment by hnljp** [comment] 2022-04-08 09:39
When investigating it, please have a look at the crashlog from (as they are most likely related)
https://github.com/firebase/firebase-android-sdk/issues/3626

**Comment by lisajian** [comment] 2022-04-08 18:46
Hi, thanks for filing this issue! We are unable to promise any timeline for this, but if others also have this issue, adding a +1 on this issue can help us prioritize adding this to the roadmap.

(Googler-only internal tracking bug: [b/228618336](https://b.corp.google.com/issues/228618336))

**Comment by amensia** [comment] 2022-04-12 08:09
Same for me, not only on Android 12
But it occur a lot since I updated to BOM 29.3.0
Can't find a way to replicate

There is also a null pointer on firebase auth 

`Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:248)
       at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
       at java.util.ArrayList.add(ArrayList.java:467)
       at com.google.firebase.auth.internal.zzx.zzc(com.google.firebase:firebase-auth@@21.0.3:8)
       at com.google.firebase.auth.FirebaseAuth.zzH(com.google.firebase:firebase-auth@@21.0.3:8)
       at com.google.firebase.auth.zzo.zza(zzo.java:1)
       at com.google.firebase.auth.zzt.zza$bridge(com.google.firebase:firebase-auth@@21.0.3:5)
       at com.google.android.gms.internal.firebase-auth-api.zzrv.zzb(com.google.firebase:firebase-auth@@21.0.3:3)
       at com.google.android.gms.internal.firebase-auth-api.zzuh.zzj(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzue.zzn(com.google.firebase:firebase-auth@@21.0.3:2)
       at com.google.android.gms.internal.firebase-auth-api.zztg.zzn(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzqe.zzb(com.google.firebase:firebase-auth@@21.0.3:2)
       at com.google.android.gms.internal.firebase-auth-api.zzup.zza(com.google.firebase:firebase-auth@@21.0.3:24)
       at com.google.android.gms.internal.firebase-auth-api.zztv.zzf(com.google.firebase:firebase-auth@@21.0.3:4)
       at com.google.android.gms.internal.firebase-auth-api.zzrl.zzp(com.google.firebase:firebase-auth@@21.0.3:4)
       at com.google.android.gms.internal.firebase-auth-api.zzth.zzj(com.google.firebase:firebase-auth@@21.0.3:5)
       at com.google.android.gms.internal.firebase-auth-api.zzrv.zzc(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzui.run(com.google.firebase:firebase-auth@@21.0.3:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)`
       
Only solution for now is to downgrade to previous BOM version -_-

**Comment by hnljp** [comment] 2022-04-12 10:26
For me it seems like it is only happening when returning to the app from the background.
But I am not sure if the activity has been destroyed, before opening it.

**Comment by hnljp** [comment] 2022-04-12 10:30
> Only solution for now is to downgrade to previous BOM version -_-
I am also going to revert to the previous BoM, before releasing our apps  to the public.

**Comment by mutual-arildo** [comment] 2022-04-12 12:46
> > Only solution for now is to downgrade to previous BOM version -_-
> 
> I am also going to revert to the previous BoM, before releasing our apps to the public.

My solution was to revert to Auth 20.0.4.

**Comment by hnljp** [comment] 2022-04-13 11:45
I have tested with a few versions and I can confirm that at least the related issue https://github.com/firebase/firebase-android-sdk/issues/3626 is not only happening on Android 12.

And it seems that I need to revert to BoM 29.1.0 , to get rid of this issue.
So this issue was most likely introduced, when fixing the memory leak #2387 
Released with:
https://firebase.google.com/support/release-notes/android#auth_v21-0-2

**Comment by SteveBurkert** [comment] 2022-04-19 14:14
Same here. 
`[...] Failed to allocate a 25459360 byte allocation with 2097152 free bytes and 23MB until OOM`

For us it's only **1** user crashing over 2000 times. 
It happens every 1-5min.

On Applications create we're attaching an `AuthStateListener`, waiting for it to complete and 
fetching the current user from `FirebaseAuth` in order to do some verification.

**Device**
Brand:LENOVO
Model:P70
Orientation: Portrait
RAM free: 694.25 MB
Disk free: 2.59 GB
Operating System
Version:Android 5.1

**Comment by commonnuisance** [comment] 2022-04-21 09:35
bom version: 29.3.1

exact same issue on 2 devices:

Device
Brand:Xiaomi
Model:Mi 11
Orientation: Landscape
RAM free: 2.95 GB
Disk free: 183.98 GB
Operating system
Version:Android 12
Orientation: Landscape
Rooted:No

Device
Brand:samsung
Model:Galaxy A6
Orientation: Landscape
RAM free: 819.53 MB
Disk free: 4.96 GB
Operating system
Version:Android 10
Orientation: Landscape
Rooted:No

Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 75497480 byte allocation with 22344008 free bytes and 21MB until OOM, target footprint 268435456, growth limit 268435456
java.util.Arrays.copyOf (Arrays.java:3257)
java.lang.AbstractStringBuilder.ensureCapacityInternal (AbstractStringBuilder.java:124)
java.lang.AbstractStringBuilder.append (AbstractStringBuilder.java:649)
java.lang.StringBuilder.append (StringBuilder.java:203)
org.json.JSONStringer.string (JSONStringer.java:354)
.
.
.

**Comment by DevAtHeart** [comment] 2022-04-26 06:55
BOM Version 29.3.0

We also have this issue on Pixel 6 and Fairphone 4 with Android 12.

`Failed to allocate a 37748744 byte allocation with 16694672 free bytes and 15MB until OOM, target footprint 268435456, growth limit 268435456`

**Comment by bswhite1** [comment] 2022-05-03 17:43
We are seeing these as well. 
BOM Version 29.3.0 Android 11 and 12

Also not sure if this is related, but showed up at the same time:

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.parseUserInfoList(FlutterFirebaseAuthPlugin.java:15)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.parseFirebaseUser(FlutterFirebaseAuthPlugin.java:129)
       at io.flutter.plugins.firebase.auth.IdTokenChannelStreamHandler.lambda$onListen$0(IdTokenChannelStreamHandler.java:21)
       at io.flutter.plugins.firebase.auth.IdTokenChannelStreamHandler.$r8$lambda$YFUVy4vuqZSNJHZYCVP6LRIaeoc(IdTokenChannelStreamHandler.java)
       at io.flutter.plugins.firebase.auth.IdTokenChannelStreamHandler$$InternalSyntheticLambda$3$e66cf25435250bec3a306a85fa9de6077b3eb90c107a0816a27fd84112fe3053$0.onIdTokenChanged(IdTokenChannelStreamHandler.java:6)
       at com.google.firebase.auth.zzm.run(zzm.java:52)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7803)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by OrhanTozan** [comment] 2022-05-09 08:22
Is this fixed in BoM 30.0.0?

**Comment by rojepp** [comment] 2022-05-14 08:57
Is this what's fixed in BoM 30.0.1?
https://firebase.google.com/support/release-notes/android#auth_v21-0-4

**Comment by offline-first** [comment] 2022-05-22 12:13
Same on `firebase-bom:30.0.1`
I'm not sure if the error #3617 and #3626 is the same.

Fatal Exception: java.lang.NullPointerException
Attempt to get length of null array

```java
java.util.ArrayList.ensureExplicitCapacity (ArrayList.java:248)
java.util.ArrayList.ensureCapacityInternal (ArrayList.java:241)
java.util.ArrayList.add (ArrayList.java:467)
com.google.firebase.auth.internal.zzx.zzc (com.google.firebase:firebase-auth@@21.0.4:10)
com.google.firebase.auth.FirebaseAuth.zzH (com.google.firebase:firebase-auth@@21.0.4:8)
com.google.firebase.auth.zzo.zza (com.google.firebase:firebase-auth@@21.0.4:1)
com.google.android.gms.internal.firebase-auth-api.zzrv.zzb (com.google.firebase:firebase-auth@@21.0.4:3)
com.google.android.gms.internal.firebase-auth-api.zzuh.zzj (com.google.firebase:firebase-auth@@21.0.4:1)
com.google.android.gms.internal.firebase-auth-api.zzue.zzn (com.google.firebase:firebase-auth@@21.0.4:2)
com.google.android.gms.internal.firebase-auth-api.zztg.zzn (com.google.firebase:firebase-auth@@21.0.4:1)
com.google.android.gms.internal.firebase-auth-api.zzqe.zzb (com.google.firebase:firebase-auth@@21.0.4:2)
com.google.android.gms.internal.firebase-auth-api.zzup.zza (com.google.firebase:firebase-auth@@21.0.4:24)
com.google.android.gms.internal.firebase-auth-api.zztv.zzf (com.google.firebase:firebase-auth@@21.0.4:4)
com.google.android.gms.internal.firebase-auth-api.zzrl.zzp (com.google.firebase:firebase-auth@@21.0.4:4)
com.google.android.gms.internal.firebase-auth-api.zzth.zzj (com.google.firebase:firebase-auth@@21.0.4:5)
com.google.android.gms.internal.firebase-auth-api.zzrv.zzc (com.google.firebase:firebase-auth@@21.0.4:1)
com.google.android.gms.internal.firebase-auth-api.zzui.run (com.google.firebase:firebase-auth@@21.0.4:1)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)
```

Android: 10,11,12
Devices: Samsung (Galaxy A32, Galaxy A32 5G, Galaxy A71, Galaxy A80, Galaxy A9 (2018), Galaxy S20+, Galaxy S20 FE, Galaxy S20 FE 5G, Galaxy S21 5G, Galaxy A52s 5G, Galaxy S10 Lite), OPPO CPH1907,  Motorola moto g(60), motorola edge, motorola one 5G UW, Xiaomi Mi A1, ... and more

**Comment by GoatHunter** [comment] 2022-05-31 11:20
Same here, we're using Firebase for Unity SDK 8.9.0, been observed on Android 11.x and 12.x devices:
```

java.lang.OutOfMemoryError: Failed to allocate a 75497480 byte allocation with 25165824 free bytes and 25MB until OOM, target footprint 266519624, growth limit 268435456
        at java.util.Arrays.copyOf(Arrays.java:3257)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
        at java.lang.StringBuilder.append(StringBuilder.java:203)
        at org.json.JSONStringer.string(JSONStringer.java:327)
        at org.json.JSONStringer.value(JSONStringer.java:261)
        at org.json.JSONArray.writeTo(JSONArray.java:616)
        at org.json.JSONStringer.value(JSONStringer.java:242)
        at org.json.JSONObject.writeTo(JSONObject.java:734)
        at org.json.JSONObject.toString(JSONObject.java:702)
        at com.google.firebase.auth.internal.zzbg.zzd(com.google.firebase:firebase-auth@@21.0.3:27)
        at com.google.firebase.auth.FirebaseAuth.zzH(com.google.firebase:firebase-auth@@21.0.3:13)
        at com.google.firebase.auth.zzo.zza(com.google.firebase:firebase-auth@@21.0.3:1)
        at com.google.android.gms.internal.firebase-auth-api.zzrv.zzb(com.google.firebase:firebase-auth@@21.0.3:3)
        at com.google.android.gms.internal.firebase-auth-api.zzuh.zzj(com.google.firebase:firebase-auth@@21.0.3:1)
        at com.google.android.gms.internal.firebase-auth-api.zzue.zzn(com.google.firebase:firebase-auth@@21.0.3:2)
        at com.google.android.gms.internal.firebase-auth-api.zztg.zzn(com.google.firebase:firebase-auth@@21.0.3:1)
        at com.google.android.gms.internal.firebase-auth-api.zzqe.zzb(com.google.firebase:firebase-auth@@21.0.3:2)
        at com.google.android.gms.internal.firebase-auth-api.zzup.zza(com.google.firebase:firebase-auth@@21.0.3:24)
        at com.google.android.gms.internal.firebase-auth-api.zztv.zzf(com.google.firebase:firebase-auth@@21.0.3:4)
        at com.google.android.gms.internal.firebase-auth-api.zzrl.zzp(com.google.firebase:firebase-auth@@21.0.3:4)
        at com.google.android.gms.internal.firebase-auth-api.zzth.zzj(com.google.firebase:firebase-auth@@21.0.3:5)
        at com.google.android.gms.internal.firebase-auth-api.zzrv.zzc(com.google.firebase:firebase-auth@@21.0.3:1)
        at com.google.android.gms.internal.firebase-auth-api.zzui.run(com.google.firebase:firebase-auth@@21.0.3:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by GrayTsar** [comment] 2022-05-31 19:00
This crash causes a lot of problems.
Xiaomi 11T (Android 11),  Galaxy S9+ (Android 11), Redmi Note 7 (Android 10), POCO F2 Pro (Android 12)
`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 25165824 free bytes and 98MB until OOM, target footprint 458637016, growth limit 536870912
       at java.util.Arrays.copyOf(Arrays.java:3257)
       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
       at java.lang.StringBuilder.append(StringBuilder.java:203)
       at org.json.JSONStringer.string(JSONStringer.java:354)
       at org.json.JSONStringer.value(JSONStringer.java:261)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONObject.writeTo(JSONObject.java:740)
       at org.json.JSONObject.toString(JSONObject.java:708)
       at com.google.firebase.auth.internal.zzbg.zzd(com.google.firebase:firebase-auth@@21.0.4:27)
       at com.google.firebase.auth.FirebaseAuth.zzH(com.google.firebase:firebase-auth@@21.0.4:13)
       at com.google.firebase.auth.zzo.zza(com.google.firebase:firebase-auth@@21.0.4:1)
       at com.google.android.gms.internal.firebase-auth-api.zzrv.zzb(com.google.firebase:firebase-auth@@21.0.4:3)
       at com.google.android.gms.internal.firebase-auth-api.zzuh.zzj(com.google.firebase:firebase-auth@@21.0.4:1)
       at com.google.android.gms.internal.firebase-auth-api.zzue.zzn(com.google.firebase:firebase-auth@@21.0.4:2)
       at com.google.android.gms.internal.firebase-auth-api.zztg.zzn(com.google.firebase:firebase-auth@@21.0.4:1)
       at com.google.android.gms.internal.firebase-auth-api.zzqe.zzb(com.google.firebase:firebase-auth@@21.0.4:2)
       at com.google.android.gms.internal.firebase-auth-api.zzup.zza(com.google.firebase:firebase-auth@@21.0.4:24)
       at com.google.android.gms.internal.firebase-auth-api.zztv.zzf(com.google.firebase:firebase-auth@@21.0.4:4)
       at com.google.android.gms.internal.firebase-auth-api.zzrl.zzp(com.google.firebase:firebase-auth@@21.0.4:4)
       at com.google.android.gms.internal.firebase-auth-api.zzth.zzj(com.google.firebase:firebase-auth@@21.0.4:5)
       at com.google.android.gms.internal.firebase-auth-api.zzrv.zzc(com.google.firebase:firebase-auth@@21.0.4:1)
       at com.google.android.gms.internal.firebase-auth-api.zzui.run(com.google.firebase:firebase-auth@@21.0.4:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
`
Another one. 

`java.lang.OutOfMemoryError: 	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.lang.StringBuilder.toString(StringBuilder.java:413)
	at org.json.JSONStringer.toString(JSONStringer.java:443)
	at org.json.JSONObject.toString(JSONObject.java:702)
	at com.google.firebase.auth.internal.zzbg.zzd(com.google.firebase:firebase-auth@@21.0.4:27)
	at com.google.firebase.auth.FirebaseAuth.zzH(com.google.firebase:firebase-auth@@21.0.4:13)
	at com.google.firebase.auth.zzo.zza(com.google.firebase:firebase-auth@@21.0.4:1)
	at com.google.android.gms.internal.firebase-auth-api.zzrv.zzb(com.google.firebase:firebase-auth@@21.0.4:3)
	at com.google.android.gms.internal.firebase-auth-api.zzuh.zzj(com.google.firebase:firebase-auth@@21.0.4:1)
	at com.google.android.gms.internal.firebase-auth-api.zzue.zzn(com.google.firebase:firebase-auth@@21.0.4:2)
	at com.google.android.gms.internal.firebase-auth-api.zztg.zzn(com.google.firebase:firebase-auth@@21.0.4:1)
	at com.google.android.gms.internal.firebase-auth-api.zzqe.zzb(com.google.firebase:firebase-auth@@21.0.4:2)
	at com.google.android.gms.internal.firebase-auth-api.zzup.zza(com.google.firebase:firebase-auth@@21.0.4:24)
	at com.google.android.gms.internal.firebase-auth-api.zztv.zzf(com.google.firebase:firebase-auth@@21.0.4:4)
	at com.google.android.gms.internal.firebase-auth-api.zzrl.zzp(com.google.firebase:firebase-auth@@21.0.4:4)
	at com.google.android.gms.internal.firebase-auth-api.zzth.zzj(com.google.firebase:firebase-auth@@21.0.4:5)
	at com.google.android.gms.internal.firebase-auth-api.zzrv.zzc(com.google.firebase:firebase-auth@@21.0.4:1)
	at com.google.android.gms.internal.firebase-auth-api.zzui.run(com.google.firebase:firebase-auth@@21.0.4:1)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)`

**Comment by rosalyntan** [comment] 2022-05-31 23:31
Hi folks, thanks for reporting this issue! As an update, we're currently working on verifying a fix for this issue.

**Comment by masmil1988** [comment] 2022-06-01 13:07
My temporary solution has been forcing the firebase_auth version to 21.0.1, which seems to be not affected by this bug.

**Comment by Cellaryllis** [comment] 2022-06-07 06:34
> 

Hello, thanks for verifying the fix! Is there any ETA on when we can expect the update/fix to go live? Our impacted users would love to be able to use the app again.

**Comment by Cellaryllis** [comment] 2022-06-13 19:13
@rosalyntan Pinging you in case you didn't see the above message! :)

**Comment by rosalyntan** [comment] 2022-06-14 23:02
Hi @Cellaryllis -- a fix for both the NPE and OOM will be going out in the next release. However, this issue has proven extremely hard to reproduce, so we've been unable to fully verify if the OOM is resolved, unfortunately.

I'll update this thread again once the new version is released.

**Comment by achuinard** [comment] 2022-06-23 00:41
@rosalyntan Any release soon?

**Comment by OleksiiSB** [comment] 2022-06-24 16:39
Looks like it was released: https://firebase.google.com/support/release-notes/android#auth_v21-0-6

**Comment by efstathiosntonas** [comment] 2022-06-24 16:58
@mikehardy just fyi 🥰

**Comment by mikehardy** [comment] 2022-06-24 18:51
@efstathiosntonas yeah saw this in the release notes as I was reading them just now - for react-native-firebase you may adopt this immediately by overriding the BoM to be 30.2.0 like so https://rnfirebase.io/#android and we'll have a release "real soon now" that just incorporates it by default. I want to add Android 13 notification permissions first though as that will be a huge deal for people

**Comment by efstathiosntonas** [comment] 2022-06-24 18:57
Thanks @mikehardy! This bug is killing me, countless of reported crashes.

**Comment by zagalaga** [comment] 2022-06-25 09:04
Does anybody have a solution for Flutter? What is the last working version?

**Comment by OrhanTozan** [comment] 2022-06-25 12:04
Since this version https://firebase.google.com/support/release-notes/android#auth_v21-0-6 should fix this issue, I think we can close this issue, and re-open it if it still happens in the future.

**Comment by mikehardy** [comment] 2022-06-25 14:55
@zagalaga it looks to me like you may override the android BoM version in flutter_fire:

https://github.com/firebase/flutterfire/blob/3769bccadedc2c12228ec51dfb48561a23055370/packages/firebase_core/firebase_core/android/build.gradle#L38

Sort of like so https://firebase.flutter.dev/docs/manual-installation/#android-1

Thus if you wanted to *try* (no guarantees, but you could try) setting that to 30.2.0, you will then be using the release with the fixed version

**Comment by softkot** [comment] 2022-06-26 19:12
looks like id does not fix it.

`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.parseUserInfoList(FlutterFirebaseAuthPlugin.java:349)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.parseFirebaseUser(FlutterFirebaseAuthPlugin.java:334)
       at io.flutter.plugins.firebase.auth.IdTokenChannelStreamHandler.lambda$onListen$0(IdTokenChannelStreamHandler.java:42)
       at io.flutter.plugins.firebase.auth.IdTokenChannelStreamHandler.$r8$lambda$YFUVy4vuqZSNJHZYCVP6LRIaeoc(IdTokenChannelStreamHandler.java)
       at io.flutter.plugins.firebase.auth.IdTokenChannelStreamHandler$$InternalSyntheticLambda$3$35dd39551203b9b4300d339811ffc70b6ab66a759c578d95a3a64d11ae42bb7a$0.onIdTokenChanged(IdTokenChannelStreamHandler.java:6)
       at com.google.firebase.auth.zzl.run(com.google.firebase:firebase-auth@@21.0.6:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8256)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)`

**Comment by mikehardy** [comment] 2022-06-26 19:47
Those stack traces are inside the flutter plugin, not firebase-android-sdk. 

```
at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.parseUserInfoList(FlutterFirebaseAuthPlugin.java:349)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.parseFirebaseUser(FlutterFirebaseAuthPlugin.java:334)
       at io.flutter.plugins.firebase.auth.IdTokenChannelStreamHandler.lambda$onListen$0(IdTokenChannelStreamHandler.java:42)
       at io.flutter.plugins.firebase.auth.IdTokenChannelStreamHandler.$r8$lambda$YFUVy4vuqZSNJHZYCVP6LRIaeoc(IdTokenChannelStreamHandler.java)
       at io.flutter.plugins.firebase.auth.IdTokenChannelStreamHandler$$InternalSyntheticLambda$3$35dd39551203b9b4300d339811ffc70b6ab66a759c578d95a3a64d11ae42bb7a$0.onIdTokenChanged(IdTokenChannelStreamHandler.java:6)
       at com.google.firebase.auth.zzl.run(com.google.firebase:firebase-auth@@21.0.6:4)
       
```

You should log this in the FlutterFire repo -

1- FlutterFire auth parses a user list with SDK-provided collection: https://github.com/firebase/flutterfire/blob/3769bccadedc2c12228ec51dfb48561a23055370/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java#L334
2- Using an iterator on the object sent by the SDK
https://github.com/firebase/flutterfire/blob/3769bccadedc2c12228ec51dfb48561a23055370/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java#L346-L349
3- but the iterator is not under the plugins' control and may change asynchronously while iterating, causing your stack trace above with ConcurrentModificationException

The repair is I think to make a copy of the userInfoList before getting the iterator. There are a few ways to do that, here's an easy one. You can try altering that line of code directly in place @softkot and see if it works for you, then maybe just propose the PR for FlutterFire

```java
// make a shallow copy of the collection *then* get an iterator, to avoid ConcurrentModificationException
Iterator<? extends UserInfo> iterator = new ArrayList<? extends UserInfo>(userInfoList).iterator();
```

**Comment by softkot** [comment] 2022-06-26 19:58
Thanks a lot @mikehardy ! I will follow you suggestion and propose the PR if it helps.

**Comment by bswhite1** [comment] 2022-07-05 20:56
@mikehardy / @softkot Did either of you create a flutterfire issue for this yet? If so what as the number?

**Comment by mikehardy** [comment] 2022-07-06 03:48
Oh yes! I pointed this out to the FlutterFire crew and behold - a merged PR already! https://github.com/firebase/flutterfire/pull/8967
Please understand that fixes the ConcurrentModificationException which is (was!) a real FlutterFire issue but is distinct from the issue logged here. Hope this helps

**Closed** 2022-07-07 13:45 UTC
Labels: type: bug, api: auth, internal-bug-filed

**Comment by zagalaga** [comment] 2022-07-14 16:12
Working with latest flutter libraries and still getting the crash
 
firebase_core: ^1.19.2
firebase_auth: ^3.4.2

Am I doing something wrong?

**Comment by bhumkong** [comment] 2022-07-15 02:52
@zagalaga Flutter auth plugin uses an outdated Android Auth plugin version. I created an issue [here](https://github.com/firebase/flutterfire/issues/9107).
