### ISSUE TITLE
Upgrading from com.google.gms.google-services 4.3.5 to 4.3.10 breaks FirebaseApp.initializeApp

### ISSUE THREAD

**Issue by hborders** [firebase/firebase-android-sdk#3687] opened 2022-04-28 17:32 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

Android Studio Bumblebee | 2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 16, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 24
Registry: external.system.auto.import.disabled=true, ide.instant.shutdown=false
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.21-release-334-AS7442.40)

  * Firebase Component: `com.google.gms.google-services` (Database, Firestore, Storage, Functions, etc)
  * Component version: `4.3.10`

### [REQUIRED] Step 3: Describe the problem

I upgraded `com.google.gms.google-services` from `4.3.5` to `4.3.10`, and now my `release` build crashes on startup with the following:
```
2022-04-28 12:07:11.456 13536-13536/? W/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
2022-04-28 12:07:11.468 13536-13536/? W/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.

java.lang.RuntimeException: Unable to create application tv.twitch.android.app.consumer.TwitchApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process tv.twitch.android.qa. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6767)
        at android.app.ActivityThread.access$1500(ActivityThread.java:256)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

This looks very similar to https://github.com/firebase/firebase-android-sdk/issues/2894

#### Steps to reproduce:

Upgraded `com.android.library` and `com.android.application` from `7.1.0` to `7.1.3` and `com.google.gms.google-services` from `4.3.5` to `43.10`. Then run a `bundleRelease` task.

#### Relevant Code:

N/A

**Comment by argzdev** [comment] 2022-04-29 09:22
Hi @hborders, thanks for reporting. I tried to create a clean project with your code setup, however I'm unable to reproduce the same issue. 

Relevant code:

project build.gradle
```
buildscript {
    repositories {
        google()  // Google's Maven repository
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

plugins {
    id 'com.android.application' version '7.1.3' apply false
    id 'com.android.library' version '7.1.3' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

module build.gradle
```
plugins {
    id 'com.android.application'
}

android {
    compileSdk 32

    defaultConfig {
        applicationId "com.argz.issue3687"
        minSdk 21
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    implementation platform('com.google.firebase:firebase-bom:29.3.1')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-storage'
    implementation 'com.google.firebase:firebase-functions'
}
```

application class
```
public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        FirebaseOptions options = new FirebaseOptions.Builder()
            .setApplicationId("1:xxxxxxxx:android:xxxxxxxxxxx")
            .build();
        FirebaseApp.initializeApp(getBaseContext(), options);
    }
}
```

And then I ran `gradle app:bundleRelease`, am I missing anything?

Could you provide more details or a minimal repro of the issue, so I can investigate this further? Thanks!

**Comment by hborders** [comment] 2022-04-29 16:10
We don't call `FirebaseOptions.Builder().setApplicationId("...").build();`.

Is that required now?

**Comment by argzdev** [comment] 2022-04-29 16:32
This isn't necessary. You could also just call `FirebaseApp.initializeApp(getBaseContext());`, if you have `google-services.json` included in your package. 

Could you provide a code snippet of how you call `FirebaseApp` or a minimal repro of your issue?

**Comment by hborders** [comment] 2022-04-29 20:28
Thanks! I rolled back to `4.3.8` and everything worked fine. Do you have any advice for logging I could add to our build? I expect that our `google-services.json` file isn't getting included when building with `4.3.10`. I think creating a minified version of our build is going to be difficult.

**Comment by argzdev** [comment] 2022-05-02 11:52
Perhaps you could try [this](https://stackoverflow.com/questions/35558637/where-are-gradle-logs) link for logging tips.

Unfortunately, it is difficult to say what the issue is and I cannot investigate this further without any extra information or minimal repro of the issue. That being said, i'll leave this open for now until new details are provided. Thanks!

**Comment by hborders** [comment] 2022-05-02 20:59
I ran another build with `4.3.10`, but I generated an APK instead, and things seemed to work. I'm going to try another run with an AAB file.

**Comment by argzdev** [comment] 2022-05-03 08:37
With these details, it looks like the main issue not with Firebase but rather with the `google-services.json`. Could you file an issue on this [repo](https://github.com/google/play-services-plugins/issues) instead? They'll be able to assist you better. That being said, I'll be closing this issue now. Thanks!

**Closed by argzdev** 2022-05-03 08:37 UTC
Labels: api: core, needs-attention
