### ISSUE TITLE
Manually log screen_view events call gets ignored because duplicate parameters

### ISSUE THREAD

**Issue by abdialidrus** [firebase/firebase-android-sdk#3788] opened 2022-06-06 12:34 UTC
## [REQUIRED] Step 2: Describe your environment

- Android Studio version: Android Studio Chipmunk | 2021.2.1
- Firebase Component: Firebase Analytics
- Component version: 18.0.2

## [REQUIRED] Step 3: Describe the problem

We want to log `screen_view` event to track our app's perfomance. We decide to manually log `screen_view` event because most of our screens/pages are using Fragment. Everything work as expected except when a page opened from a Dynamic Link. When the app first opened, the `screen_view` event logged successfully. But after that if user open a dynamic link again (even though the dynamic link is totally different form before) it gets ignored.

![image](https://user-images.githubusercontent.com/20806662/172154621-965fb3b6-5e22-4c3a-a518-39d3a5b17992.png)

### #1 Dynamic link (https://mobile.komuniti.co.id/share/g6tuw9ukkZzK5FkUA) -> `screen_view` event log

origin=app,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=app, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=9177988992201632150, manual_tracking(_mst)=1, **_entry_point_name=product_share_dynamic_link_**, entry_point_type=dynamic_link, komuniti_screen_name=product_details_screen}]

### #2 Dynamic link (https://mobile.komuniti.co.id/share/NhFc6XqcpdJ78iGZ9) -> `screen_view` event log

origin=app,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=app, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=7241396491289599412, manual_tracking(_mst)=1, **_entry_point_name=group_invite_dynamic_link_**, entry_point_type=dynamic_link, komuniti_screen_name=product_details_screen}]

from 2 logs above, clearly both of the parameters are not identical (the difference is in the bolded part) but the second event still gets ignored.

**Comment by abdialidrus** [comment] 2022-06-07 03:12
Update

If i change the Name of the event from `screen_view` to something different, the problem is no longer exist and the event will always get fired no matter the parameters indeed a duplicate or not

**Comment by argzdev** [comment] 2022-06-07 11:35
Thanks for reporting, @abdialidrus. I'm not sure what the issue is here. I tried to create a clean project with your configuration, but I'm unable to reproduce the same behavior.

Relevant Code for FragmentOne & FragmentTwo
```
    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        mFirebaseAnalytics = FirebaseAnalytics.getInstance(getActivity());
        logEvent();
    }

    public void logEvent() {
        Bundle bundle = new Bundle();
        bundle.putString(FirebaseAnalytics.Param.SCREEN_CLASS, "main_activity_class");
        bundle.putString(FirebaseAnalytics.Param.SCREEN_NAME, "main_activity_name");
        mFirebaseAnalytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW, bundle);
    }
```

Steps:
1. Open app, FragmentOne will show up and log one `screen_view` event.
2. Open dynamic link from browser, it will then redirect to the app. FragmentTwo will show up and log another `screen_view` event.

Could the issue might be how you're logging your events? I'm not sure if changing the name of the event should have any effect on the issue, but if it is, then it could be problematic. Could you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) of this issue so I can investigate this further? Thanks.

**Comment by abdialidrus** [comment] 2022-06-08 03:20
Hi @argzdev thank you for the respond. Let me provide the real case here,

- So, I have 2 type of dynamic link. First type is **_Product Share_** and second type is **_Group Buy_**. Both of this link will redirect the user to a fragment, called **_ProductDetailFragment_**.
- in onViewCreated method of _**ProductDetailFragment**_, I call `logEvent` method to send event log to FirebaseAnalytics
```
    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        mFirebaseAnalytics = FirebaseAnalytics.getInstance(getActivity());
        logEvent();
    }

    public void logEvent() {
        Bundle bundle = new Bundle();
        bundle.putString("my_screen_name", "com.example.app:id/ProductDetailFragment"
        bundle.putString("entry_point_type", "dynamic_link");
        bundle.putString("entry_point_name", "product_share_link");
        mFirebaseAnalytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW, bundle);
    }
```
- in this case, for the first time (app first open) user come from a dynamic link, so param `entry_point_type` have `dynamic_link` as the value. And for example for the first time user happen to open a _**Product Share**_ type of link, so param `entry_point_name` have `product_share_link`. Event will be sent successfully.
- Next the same user minimize the app, then click a different dynamic link with the type _**Group Buy**_. The user will be redirected to _**ProductDetailFragment**_ again and then the fragment try to send log with the value of `entry_point_name` will be `group_share_link`. This time the event gets ignored.

**Comment by argzdev** [comment] 2022-06-09 14:17
Hi @abdialidrus, thanks for the detailed explanation. I tried to simulate the your issue and I'm still unable to reproduce it.

What I did was change handling of dynamic link in `FragmentOne`, in your case the `ProductDetailFragment`. I used 2 deeplinks as an example `youtube` and `twitter` which will log 2 different events.

Relevant code:
```
FirebaseDynamicLinks.getInstance()
  .getDynamicLink(getActivity().getIntent())
  .addOnSuccessListener(getActivity(), pendingDynamicLinkData -> {
      Uri deepLink = null;
      if (pendingDynamicLinkData != null) {
          deepLink = pendingDynamicLinkData.getLink();

          if(deepLink.toString().equals("https://www.youtube.com")){
              logEvent("product_share_link");
          } else if (deepLink.toString().equals("https://www.twitter.com")){
              logEvent("group_share_link");
          }

      } else{
          Toast.makeText(getActivity(), "this is null", Toast.LENGTH_SHORT).show();
      }
  });

public void logEvent(String entry_point_type) {
        Bundle bundle = new Bundle();
        bundle.putString("my_screen_name", "com.example.app:id/ProductDetailFragment");
        bundle.putString("entry_point_type", entry_point_type);
        bundle.putString("entry_point_name", "product_share_link");
        mFirebaseAnalytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW, bundle);
        Log.d(TAG, "logEvent: " + entry_point_type);
        Toast.makeText(getActivity(), "event: " + entry_point_type + " has been logged", Toast.LENGTH_SHORT).show();
    }
```

However, upon checking Firebase Console, I'm able to retrieve these properly. Am I missing anything?

Perhaps the way you're logging the event is causing the error `Ignoring call to log screen view event with duplicate parameters.`?

Since I'm unable to reproduce this issue, could you provide a minimal repro so I can investigate this further? Thanks.

**Comment by abdialidrus** [comment] 2022-06-17 08:39
Sorry for the late response,

@argzdev My app use single Activity architecture with Jetpack Navigation Component. beside that, the logging method is the same with your sample.

I think the cause of the error `Ignoring call to log screen view event with duplicate parameters` is `ga_screen_class(_sc)` and `ga_screen_id(_si)` values being the same in both event logs (regardless the custom parameters)

1. First try `screen_view` event log
```
origin=app,
name=screen_view(_vs),
params=Bundle[{
  ga_event_origin(_o)=app, 
  ga_screen_class(_sc)=MainActivity, 
  ga_screen_id(_si)=8689716850284124003, 
  manual_tracking(_mst)=1, 
  event_timestamp=2022-06-17T07:41:55.029Z, 
  entry_point_name=product_share_dynamic_link, 
  entry_point_type=dynamic_link, 
  komuniti_screen_name=product_details_screen
}]
```

2. While app remain running in background, second try open app from different dynamic link. `screen_view` event gets ignored, but there is another event sent (`dynamic_link_app_open`)
```
origin=fdl,
name=dynamic_link_app_open,
params=Bundle[{
  medium=dynamic_link, 
  dynamic_link_accept_time=1655451797884, 
  source=firebase, 
  campaign=, 
  ga_event_origin(_o)=fdl, 
  ga_screen_class(_sc)=MainActivity, 
  ga_screen_id(_si)=8689716850284124003, 
  dynamic_link_link_name=,
  dynamic_link_link_id=https://mobile.komuniti.co.id/share/eN1GRwQfzUhw9poeA
}]
```
as you can see, `ga_screen_class(_sc)` and `ga_screen_id(_si)` have same value in both tries., which is make the error make sense. 
I understand if this error occur when the user click the same exact link. But the case is, with different link it also happen.

**Comment by argzdev** [comment] 2022-06-17 13:59
Thanks for these details, @abdialidrus. I think your assumption is correct, it might be due to `ga_screen_id(_si)` having the same value which is why it isn't being logged. However, when I try to open different or even the same link, I always get a different value for `ga_screen_id(_si)` for `screen_view`, or either of the `entry_point_type`'s.

I'm thinking you might be able to pinpoint your issue with why you're having the same `ga_screen_id(_si)`. Let me know if this helps, thanks!

**Comment by abdialidrus** [comment] 2022-06-22 04:04
Yes, your guess is correct. I have set `android:launchMode` as `singleTask` for MainActivity. And when change the `android:launchMode` to `default`, I get different value for `ga_screen_id`. This actually solve my problem. Thank you so much.

But, what value does this `ga_screen_id` actually represent? does it have anything to do with the instance of the activity?

**Comment by argzdev** [comment] 2022-06-22 09:19
I'm glad that fixed the problem, @abdialidrus. Looking at the [documentations](https://firebase.google.com/docs/analytics/screenviews#automatically_track_screens):
> Events that occur on these screens are automatically tagged with the parameter firebase_screen_class (for example, menuViewController or MenuActivity) and a generated firebase_screen_id.

I'm assuming that the `screen_id` is generated for each activity that is created. And in this case, since the `android:launchMode` was set to `singleTask`, the activity is only generated once, as a result having only one value for `screen_id`.

That being said, I'll close this issue now since this is resolved. Feel free to reply back here if you have any follow up questions, or open a new issue if there are new concerns. Thanks!

**Closed by argzdev** 2022-06-22 09:19 UTC
Labels: api: analytics, needs-attention

**Comment by abdialidrus** [comment] 2022-06-23 04:54
@argzdev Thank you so much for the help on this issue.

but there is something still bothering me. as you said, since the `android:launchMode` was set to `singleTask`, the activity is only generated once, as a result having only one value for `screen_id`. But I have tested a case like this,

1. I have two fragments, `HomeFragment` and `ProductDetailFragment`.
2. These two fragments hosted by 1 Activity.
3. I tried navigating from `HomeFragment` to `ProductDetailFragment`.
4. On each `OnViewCreated` method of the fragment, I log activity object. The result is activity object stay the same in both of the Fragments.
5. On `OnViewCreated` method of `ProductDetailFragment` I sent log of `screen_view` event. The result is I opened `ProductDetailFragment` multiple times (with different or same products randomly) and everytime event `screen_view` is successfully logged (no duplicate error and different value of `ga_screen_id` in each log). Even though the activity remains the same.

**Comment by argzdev** [comment] 2022-06-23 10:08
I've also tested it on my side and it looks like `ga_screen_id` always has a different value for each `screen_view` event whether manually or automatically logged. On the other hand, `ga_screen_id` value is always the same when `user_engagement` is logged. Which means that `ga_screen_id` can differ depending on the type of event being logged.

So my assumption for the `ga_screen_id` being generated once relating to its activity is incorrect, apologies for that. For question type concerns, it would be in your best interest to reach out to our [Firebase support](https://firebase.google.com/support/troubleshooter/contact) instead, since an Firebase Analytics specialist will be able to assist you better.
