### ISSUE TITLE
@brunobowden Wanted to circle back on this. After reading over your original report, and looking at your solution using flavors, that seems solid to me. I suspect you're right about the caching. I'm going to look into that and see if I can find the root cause, but in the meantime, I wanted to make sure - is there anything here blocking you?

### ISSUE THREAD

**Issue by mposch-Z** [firebase/firebase-android-sdk#4009] opened 2022-08-18 18:40 UTC
@brunobowden Wanted to circle back on this. After reading over your original report, and looking at your solution using flavors, that seems solid to me. I suspect you're right about the caching. I'm going to look into that and see if I can find the root cause, but in the meantime, I wanted to make sure - is there anything here blocking you?

_Originally posted by @mrwillis21 in https://github.com/firebase/firebase-android-sdk/issues/2191#issuecomment-745527500_

Any update to root cause?  Invalidating Android studio cache/app cache/google play services cache is not resolving my issue, so build flavors are the only way around this?

**Comment by mrober** [comment] 2022-09-02 20:03
Hi @mposch-Z, we looked into this and think we found the source of the problem is that the google services plugin isn't reprocessing the google-services.json file after it's been updated. You can work around it for now by running `./gradlew app:clean` between builds when you change the google-services.json file. Please let us know if this work, and then we will fix the source the problem in a future version.

**Comment by mposch-Z** [comment] 2022-09-09 15:41
During development I tried doing a clean build via the UI in Android studio with no success.  I'm not sure if the "clean project" option is the same as the command you're recommending  The solution I applied was to create build flavors..
Seems like something should be done so a person only building a debug version doesn't experience this issue.

**Comment by mrichards** [comment] 2022-09-09 18:05
@mposch-Z Running `Build` -> `Clean Project` should execute the `./gradlew clean` task (as is my understanding), so that should have worked. It sounds like build flavors has solved your problem, so feel free to close this ticket if you prefer. I agree that you shouldn't need to use build flavors to solve this issue, and we believe we have a fix that should be released soon.

If you want to continue to try to debug/resolve this without build flavors, you can try the following:
1. Run `./gradlew clean` from the command line explicitly, just to be sure.
1. Check if you have multiple `google-services.json` files in your project? If so, make sure they don't have any conflicting app ids, as the Google Services plugin may be processing a different one than you intend.
1. If neither of those work, run your app build with the `--debug` option and provide the build log, filtered to the Crashlytics Plugin output. For example:
```
> ./gradlew app:assembleRelease --debug | grep "\[com.google.firebase.crashlytics\]"

```

Alternatively, you can wait for the next release of the Google Services plugin and see if that solves it.

**Comment by brunobowden** [comment] 2022-09-16 07:20
@mposch-Z - the workaround I mentioned in the report worked fine for me. Sorry for the delayed response on my part but thanks for checking in on me.

**Closed** 2022-09-30 01:01 UTC
Labels: api: crashlytics, needs-info, no-recent-activity
