### ISSUE TITLE
Messages Still Received on Deleted Firebase Messaging Token

### ISSUE THREAD

**Issue by TarekkMA** [firebase/firebase-android-sdk#5824] opened 2024-04-03 08:30 UTC
### Environment Details

- **Android Studio Version**: Android Studio Iguana | 2023.2.1 Patch 1
- **Firebase Component**: Messaging
- **Component Version**: 32.7.4

### Problem Description

Original Issue reported here: https://github.com/firebase/flutterfire/issues/12567

#### Issue Summary:
Messages are still received on a topic even after the Firebase Messaging token, which had subscribed to the topic, is invalidated and a new token is generated.

#### Steps to Reproduce:

1. Subscribe to a topic named `test_topic`.
2. Send a message to `test_topic` and confirm it's received.
3. Invalidate the current Firebase Messaging token:
    - Invoke `deleteToken()`
    - Then, request a new token with `getToken()`
4. Verify that the new token is different from the previous one.
5. Attempt to send another message to `test_topic`. Notice that the message is still received, despite the fact that the token which had subscribed to it has been deleted.
6. Wait approximately 15 minutes and repeat sending a message to `test_topic`. The issue persists, indicating that messages are still delivered to a token that should no longer be subscribed to the topic.

**Comment by argzdev** [comment] 2024-04-05 10:07
Hi @TarekkMA, thanks for reaching out. This is working as intended. The invalidated tokens aren't immediately deleted. Our internal jobs run on a daily basis and thus the deletion and invalidation of FCM tokens should be done in a day or so. Let me know if this answers your question. Thanks!

**Comment by TarekkMA** [comment] 2024-04-05 11:12
Hi @argzdev, thank you for the information.

**Comment by sumittiware** [comment] 2024-04-05 11:20
Hi @argzdev so, if we get the new token using `getToken()` after calling `deleteToken()`, the new token will be automatically subscribed to the older topics?

**Comment by argzdev** [comment] 2024-04-05 14:16
@sumittiware I've tested this now and this behavior is what's happening. However, I'm not sure if this is an intended behavior. I believe resubscribing to the topic should be done, instead of it automatically subscribing to the older topic as mentioned in best practice from our [documentations](https://firebase.google.com/docs/cloud-messaging/manage-tokens#unsub-stale-tokens-from-topics).

Thanks for explaining this further, @princebansal. Although, I'm wondering is there any reason why we don't use unsubscribe to the topics? I think in your use case, you should be able to resolve this issue by unsubscribing the user whenever they log out.

Let me know if this helps. Thanks!

**Comment by princebansal** [comment] 2024-04-05 14:32
@argzdev Thanks for the quick response. 
Unsubscribing wont be possible because we have no stored information of the topics that the new token is subscribed to. 
We store token to subscribed topic data in our database and use that data to subscribe or unsubscribe a topic from a token. 
But since this new token is freshly generated, ideally our system has no stored topics against it. Hence we wont know which topics we should unsubscribe from. 

In ideal scenario, the freshly generated token should come with no topics subscribed, and we should be given the control to manage topics for that token.

**Comment by argzdev** [comment] 2024-04-05 14:55
Sorry, I didn't clarify it further. You're correct calling `unsubscribeFromTopic` to the newly generated token would not really do anything. But what I mean is to call this for the old token before you generate a new token, would it not be possible to call the `unsubscribeFromTopic`?

> In ideal scenario, the freshly generated token should come with no topics subscribed, and we should be given the control to manage topics for that token.

But yeah, I'm also under the impression that that's what's expected from the newly generated token. In the meantime, I've notified our engineers of this issue with internally tracking bug b/333061151. I'll keep you folks posted once I receive an update.

**Comment by princebansal** [comment] 2024-04-08 09:28
@argzdev Any updates on this?

**Comment by princebansal** [comment] 2024-04-10 14:37
Hi @argzdev Waiting for revert on this

**Comment by princebansal** [comment] 2024-04-11 18:58
Sure @argzdev . Thanks for the update

**Comment by TarekkMA** [comment] 2024-04-18 08:11
Waiting for updates from @argzdev

**Comment by lehcar09** [comment] 2024-05-21 09:22
Hi @TarekkMA, thank you for your patience. We have received a response from our engineer and according to investigation this is working as intended. For context, each FCM registration token contains the [FID](https://firebase.google.com/docs/projects/manage-installations) to target devices for message delivery. When you delete the token (`deleteToken`), the FID is still the same. 

```
i.e.
//Current token: dlrmE***:APA91bEH***
Firebase.messaging.deleteToken()

Firebase.messaging.token
//New Token: dlrmE***:APA91bFy***
```
This leads to the same subscription being associated. That said, we recommend [deleting the FID](https://firebase.google.com/docs/projects/manage-installations#delete-fid) when you delete the token. Thus, the Topics fanout to the old/deleted FID will not be delivered.

```
i.e.
//Current token: dlrmE***:APA91bEH***

Firebase.messaging.deleteToken()

FirebaseInstallations.getInstance().delete()

Firebase.messaging.token
//New Token: e4Mrm***:APA91bGy***
```

I'll go ahead and close this issue now. Let me know if there's any misunderstanding and/ or we need to reopen this issue for further investigation.

**Closed by lehcar09** 2024-05-21 09:22 UTC
Labels: api: messaging, needs-attention

**Comment by princebansal** [comment] 2024-05-21 13:26
@lehcar09 Thanks for probing into the issue and providing a detailed explanation of the behaviour. 

The recommended steps should definitely go in the relevant docs because I believe that the deleteToken() method doesn't convey the fact that the FID will stay same.

**Comment by Zachary625** [comment] 2024-06-19 02:35
> Hi @TarekkMA, thank you for your patience. We have received a response from our engineer and according to investigation this is working as intended. For context, each FCM registration token contains the [FID](https://firebase.google.com/docs/projects/manage-installations) to target devices for message delivery. When you delete the token (`deleteToken`), the FID is still the same.
> 
> ```
> i.e.
> //Current token: dlrmE***:APA91bEH***
> Firebase.messaging.deleteToken()
> 
> Firebase.messaging.token
> //New Token: dlrmE***:APA91bFy***
> ```
> 
> This leads to the same subscription being associated. That said, we recommend [deleting the FID](https://firebase.google.com/docs/projects/manage-installations#delete-fid) when you delete the token. Thus, the Topics fanout to the old/deleted FID will not be delivered.
> 
> ```
> i.e.
> //Current token: dlrmE***:APA91bEH***
> 
> Firebase.messaging.deleteToken()
> 
> FirebaseInstallations.getInstance().delete()
> 
> Firebase.messaging.token
> //New Token: e4Mrm***:APA91bGy***
> ```
> 
> I'll go ahead and close this issue now. Let me know if there's any misunderstanding and/ or we need to reopen this issue for further investigation.

This also helped us as well, it would be nice to put this in official doc: https://firebase.google.com/docs/cloud-messaging/manage-tokens, this and the delay of actual token deletion are both quite important for production, thank you very much!
