### ISSUE TITLE
Caused by android.database.sqlite.SQLiteDatabaseLockedException database is locked (code 5): , while compiling: PRAGMA journal_mode

### ISSUE THREAD

**Issue by oNguyenDucManh** [firebase/firebase-android-sdk#3029] opened 2021-10-05 08:00 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.2
  * Firebase Component: Firestore
  * Component version: com.google.firebase:firebase-firestore-ktx

### [REQUIRED] Step 3: Describe the problem

The results that we got from Firebase Crashlytics show that some users faced the problem with Firestore. I can'r reproduce

#### Relevant Code:

```
Fatal Exception: java.lang.RuntimeException
Internal error in Cloud Firestore (21.7.1).
com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3 (AsyncQueue.java:19)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run (AsyncQueue.java:2)
android.os.Handler.handleCallback (Handler.java:790)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:198)
android.app.ActivityThread.main (ActivityThread.java:7055)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:523)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:836)

Caused by java.lang.RuntimeException
java.lang.RuntimeException: Failed to gain exclusive lock to the Cloud Firestore client's offline persistence. This generally means you are using Cloud Firestore from multiple processes in your app. Keep in mind that multi-process Android apps execute the code in your Application class in all processes, so you may need to avoid initializing Cloud Firestore in your Application class. If you are intentionally using Cloud Firestore from multiple processes, you can only enable offline persistence (that is, call setPersistenceEnabled(true)) in one of them.
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1 (AsyncQueue.java:14)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run (AsyncQueue.java:4)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:457)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run (AsyncQueue.java:15)
java.lang.Thread.run (Thread.java:764)

Caused by java.lang.RuntimeException
Failed to gain exclusive lock to the Cloud Firestore client's offline persistence. This generally means you are using Cloud Firestore from multiple processes in your app. Keep in mind that multi-process Android apps execute the code in your Application class in all processes, so you may need to avoid initializing Cloud Firestore in your Application class. If you are intentionally using Cloud Firestore from multiple processes, you can only enable offline persistence (that is, call setPersistenceEnabled(true)) in one of them.
com.google.firebase.firestore.local.SQLitePersistence.start (SQLitePersistence.java:44)
com.google.firebase.firestore.core.ComponentProvider.initialize (ComponentProvider.java:6)
com.google.firebase.firestore.core.FirestoreClient.initialize (FirestoreClient.java:65)
com.google.firebase.firestore.core.FirestoreClient.lambda$new$0 (FirestoreClient.java:10)
com.google.firebase.firestore.core.FirestoreClient$$Lambda$1.run (FirestoreClient.java:8)
com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2 (AsyncQueue.java)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call (AsyncQueue.java:2)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1 (AsyncQueue.java)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run (AsyncQueue.java:4)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:457)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run (AsyncQueue.java:15)
java.lang.Thread.run (Thread.java:764)

Caused by android.database.sqlite.SQLiteDatabaseLockedException
database is locked (code 5): , while compiling: PRAGMA journal_mode
android.database.sqlite.SQLiteConnection.nativePrepareStatement (SQLiteConnection.java)
android.database.sqlite.SQLiteConnection.acquirePreparedStatement (SQLiteConnection.java:903)
android.database.sqlite.SQLiteConnection.executeForString (SQLiteConnection.java:648)
android.database.sqlite.SQLiteConnection.setJournalMode (SQLiteConnection.java:334)
android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration (SQLiteConnection.java:306)
android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:216)
android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:194)
android.database.sqlite.SQLiteConnectionPool.openConnectionLocked (SQLiteConnectionPool.java:493)
android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:200)
android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:192)
android.database.sqlite.SQLiteDatabase.openInner (SQLiteDatabase.java:869)
android.database.sqlite.SQLiteDatabase.open (SQLiteDatabase.java:854)
android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:729)
android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:719)
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:295)
android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:238)
com.google.firebase.firestore.local.SQLitePersistence.start (SQLitePersistence.java:16)
com.google.firebase.firestore.core.ComponentProvider.initialize (ComponentProvider.java:6)
com.google.firebase.firestore.core.FirestoreClient.initialize (FirestoreClient.java:65)
com.google.firebase.firestore.core.FirestoreClient.lambda$new$0 (FirestoreClient.java:10)
com.google.firebase.firestore.core.FirestoreClient$$Lambda$1.run (FirestoreClient.java:8)
com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2 (AsyncQueue.java)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call (AsyncQueue.java:2)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1 (AsyncQueue.java)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run (AsyncQueue.java:4)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:457)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run (AsyncQueue.java:15)
java.lang.Thread.run (Thread.java:764)


```

**Comment by ehsannas** [comment] 2021-10-06 02:32
A similar issue was reported in Oct 2019 (#953). It seemed that the crashes were related a very specific device (Xiaomi BlackShark 1 with Android 9). Unfortunately we don't have access these devices, and we haven't been able to reproduce this otherwise.

**Comment by oNguyenDucManh** [comment] 2021-10-06 04:47
> A similar issue was reported in Oct 2019 (#953). It seemed that the crashes were related a very specific device (Xiaomi BlackShark 1 with Android 9). Unfortunately we don't have access these devices, and we haven't been able to reproduce this otherwise.

This error I’m but on many other device, ví dụ OPPO, FUJITSU, SHARP, Sony, samsung, KYOCERA

![0](https://user-images.githubusercontent.com/6302085/136142178-2d4b9e2c-ce61-433d-99dc-1aab2e28dcf1.PNG)

**Comment by ehsannas** [comment] 2021-10-12 21:15
It could be possible that there is in fact two different instances of an app running on these devices (maybe they have a specific Android flavour that allows this?). Have you had any luck reproducing the issue on any device? If so, which device?

**Comment by ehsannas** [comment] 2022-03-29 20:46
Since we have no way to reproduce this issue, I am going to close this.
Please don't hesitate to reopen if you find a way to reproduce the issue. Thanks

**Closed by ehsannas** 2022-03-29 20:46 UTC
Labels: api: firestore
