### ISSUE TITLE
Uncaught exception in Firebase Database runloop (20.0.5)

### ISSUE THREAD

**Issue by freebird00700** [firebase/firebase-android-sdk#3798] opened 2022-06-08 22:18 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

I don't know. i had to uninstall the app and then reinstall to remove the crash.

#### Relevant Code:

```
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.5). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7559)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

Caused by android.database.sqlite.SQLiteException: cannot rollback - no transaction is active (code 1 SQLITE_ERROR)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:441)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:403)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:585)
       at com.google.firebase.database.android.SqlPersistenceStorageEngine.endTransaction(SqlPersistenceStorageEngine.java:810)
       at 
com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(DefaultPersistenceManager.java:246)
       at com.google.firebase.database.core.SyncTree.applyUserOverwrite(SyncTree.java:191)
       at com.google.firebase.database.core.Repo.setValue(Repo.java:473)
       at com.google.firebase.database.DatabaseReference$1.run(DatabaseReference.java:290)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)


```

**Comment by freebird00700** [comment] 2022-06-09 11:44
Before uninstalling it was happening every single time. But after
reinstalling the app, crash didn't happen again.

**Comment by argzdev** [comment] 2022-06-09 12:46
Thanks for the details, @freebird00700. 

Upon investigating, the error `cannot rollback - no transaction is active (code 1 SQLITE_ERROR)` can happen when your device memory is full. This issue looks very similar to your previous issue #3785 that is caused by full memory. What you can do here is try running this on a clean emulator or device.

However, since this issue happens infrequently, and you can no longer replicate this. Without any steps to reproduce this issue, it'll be difficult to investigate this further. As a result, I'll close this case since you're no longer experiencing this issue. 

Feel free to ask this to be reopened if you encounter this issue again or if other developers also start reporting the same behavior. Our engineers can prioritize investigating this further based on severity. Thanks!

**Closed by argzdev** 2022-06-09 12:46 UTC
Labels: api: database, needs-attention
