### ISSUE TITLE
Bug: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)

### ISSUE THREAD

**Issue by pistolcaffe** [firebase/firebase-android-sdk#6384] opened 2024-10-15 02:01 UTC
### [READ] Step 1: Are you in the right place?

Yes, I am reporting an issue related to the Firebase Android SDK, specifically Firestore, which appears to align with the scope of this repository.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 17.0.10+0-17.0.10b1087.21-11609105 aarch64
  * Firebase Component: Firestore (Database, Firestore, Storage, Functions, etc)
  * Component version: FirebaseBom (33.0.0)

### [REQUIRED] Step 3: Describe the problem

We are receiving error reports from multiple users via Crashlytics with the following error logs:

> android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
>        at libcore.io.Linux.android_getaddrinfo(Linux.java)
>        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
>        at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
>        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
>        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
>        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
>        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
>        at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
>        at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
>        at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
>        at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
>        at java.lang.Thread.run(Thread.java:1012)

This issue was reportedly fixed in https://github.com/firebase/firebase-android-sdk/issues/2152, but it still seems to be occurring.

#### Steps to reproduce:

This is a crash report from users, but according to the logs, they probably just install the app, and for some reason the OS claims the app misses Internet connection.

**Comment by MarkDuckworth** [comment] 2024-10-15 15:54
Looks like a duplicate of https://github.com/firebase/firebase-android-sdk/issues/2233. I'll ping the owner of that issue to see if there is an update.

**Closed** 2024-10-15 16:09 UTC
Labels: api: core, api: firestore
