### ISSUE TITLE
java.lang.IllegalStateException  dagger.internal.DoubleCheck.get

### ISSUE THREAD

**Issue by Belka1000867** [firebase/firebase-android-sdk#1621] opened 2020-06-05 07:13 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.2
  * Firebase Component: InAppMessaging
  * Component version: from BoM v 25.4.0

An error is specific only for Android 4.4

#### Steps to reproduce:

An error is shown in Firebase Crashlytics. 

#### Relevant Code:

```
java.lang.ExceptionInInitializerError: 
  at okhttp3.internal.platform.Android10Platform.<clinit> (Android10Platform.java:67)
  at okhttp3.internal.platform.Platform$Companion.findPlatform (Platform.java:206)
  at okhttp3.internal.platform.Platform$Companion.access$findPlatform (Platform.java:169)
  at okhttp3.internal.platform.Platform.<clinit> (Platform.java:170)
  at okhttp3.OkHttpClient.<init> (OkHttpClient.java:232)
  at okhttp3.OkHttpClient$Builder.build (OkHttpClient.java:1052)
  at com.google.firebase.inappmessaging.display.internal.injection.modules.PicassoModule.providesFiamController (PicassoModule.java:46)
  at com.google.firebase.inappmessaging.display.internal.injection.modules.PicassoModule_ProvidesFiamControllerFactory.providesFiamController (PicassoModule_ProvidesFiamControllerFactory.java:43)
  at com.google.firebase.inappmessaging.display.internal.injection.modules.PicassoModule_ProvidesFiamControllerFactory.get (PicassoModule_ProvidesFiamControllerFactory.java:32)
  at com.google.firebase.inappmessaging.display.internal.injection.modules.PicassoModule_ProvidesFiamControllerFactory.get (PicassoModule_ProvidesFiamControllerFactory.java:11)
  at dagger.internal.DoubleCheck.get (DoubleCheck.java:47)
  at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get (FiamImageLoader_Factory.java:21)
  at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get (FiamImageLoader_Factory.java:8)
  at dagger.internal.DoubleCheck.get (DoubleCheck.java:47)
  at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get (FirebaseInAppMessagingDisplay_Factory.java:57)
  at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get (FirebaseInAppMessagingDisplay_Factory.java:16)
  at dagger.internal.DoubleCheck.get (DoubleCheck.java:47)
  at com.google.firebase.inappmessaging.display.internal.injection.components.DaggerAppComponent.providesFirebaseInAppMessagingUI (DaggerAppComponent.java:80)
  at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.buildFirebaseInAppMessagingUI (FirebaseInAppMessagingDisplayRegistrar.java:74)
  at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.access$lambda$0 (FirebaseInAppMessagingDisplayRegistrar.java)
  at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar$$Lambda$1.create (FirebaseInAppMessagingDisplayRegistrar.java)
  at com.google.firebase.components.ComponentRuntime.lambda$new$0 (ComponentRuntime.java:69)
  at com.google.firebase.components.ComponentRuntime$$Lambda$1.get (ComponentRuntime.java)
  at com.google.firebase.components.Lazy.get (Lazy.java:53)
  at com.google.firebase.components.ComponentRuntime.initializeEagerComponents (ComponentRuntime.java:158)
  at com.google.firebase.FirebaseApp.initializeAllApis (FirebaseApp.java:563)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:304)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:268)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:253)
  at com.google.firebase.provider.FirebaseInitProvider.onCreate (FirebaseInitProvider.java:51)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1591)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1562)
  at com.google.firebase.provider.FirebaseInitProvider.attachInfo (FirebaseInitProvider.java:45)
  at android.app.ActivityThread.installProvider (ActivityThread.java:5084)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:4673)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4613)
  at android.app.ActivityThread.access$1800 (ActivityThread.java:141)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1298)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5336)
  at java.lang.reflect.Method.invokeNative (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:871)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:687)
  at dalvik.system.NativeStart.main (NativeStart.java)

Caused by: java.lang.IllegalStateException: 
  at okhttp3.internal.platform.AndroidPlatform.<clinit> (AndroidPlatform.java:206)
  at okhttp3.internal.platform.Android10Platform.<clinit> (Android10Platform.java:67)
  at okhttp3.internal.platform.Platform$Companion.findPlatform (Platform.java:206)
  at okhttp3.internal.platform.Platform$Companion.access$findPlatform (Platform.java:169)
  at okhttp3.internal.platform.Platform.<clinit> (Platform.java:170)
  at okhttp3.OkHttpClient.<init> (OkHttpClient.java:232)
  at okhttp3.OkHttpClient$Builder.build (OkHttpClient.java:1052)
  at com.google.firebase.inappmessaging.display.internal.injection.modules.PicassoModule.providesFiamController (PicassoModule.java:46)
  at com.google.firebase.inappmessaging.display.internal.injection.modules.PicassoModule_ProvidesFiamControllerFactory.providesFiamController (PicassoModule_ProvidesFiamControllerFactory.java:43)
  at com.google.firebase.inappmessaging.display.internal.injection.modules.PicassoModule_ProvidesFiamControllerFactory.get (PicassoModule_ProvidesFiamControllerFactory.java:32)
  at com.google.firebase.inappmessaging.display.internal.injection.modules.PicassoModule_ProvidesFiamControllerFactory.get (PicassoModule_ProvidesFiamControllerFactory.java:11)
  at dagger.internal.DoubleCheck.get (DoubleCheck.java:47)
  at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get (FiamImageLoader_Factory.java:21)
  at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get (FiamImageLoader_Factory.java:8)
  at dagger.internal.DoubleCheck.get (DoubleCheck.java:47)
  at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get (FirebaseInAppMessagingDisplay_Factory.java:57)
  at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get (FirebaseInAppMessagingDisplay_Factory.java:16)
  at dagger.internal.DoubleCheck.get (DoubleCheck.java:47)
  at com.google.firebase.inappmessaging.display.internal.injection.components.DaggerAppComponent.providesFirebaseInAppMessagingUI (DaggerAppComponent.java:80)
  at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.buildFirebaseInAppMessagingUI (FirebaseInAppMessagingDisplayRegistrar.java:74)
  at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.access$lambda$0 (FirebaseInAppMessagingDisplayRegistrar.java)
  at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar$$Lambda$1.create (FirebaseInAppMessagingDisplayRegistrar.java)
  at com.google.firebase.components.ComponentRuntime.lambda$new$0 (ComponentRuntime.java:69)
  at com.google.firebase.components.ComponentRuntime$$Lambda$1.get (ComponentRuntime.java)
  at com.google.firebase.components.Lazy.get (Lazy.java:53)
  at com.google.firebase.components.ComponentRuntime.initializeEagerComponents (ComponentRuntime.java:158)
  at com.google.firebase.FirebaseApp.initializeAllApis (FirebaseApp.java:563)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:304)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:268)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:253)
  at com.google.firebase.provider.FirebaseInitProvider.onCreate (FirebaseInitProvider.java:51)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1591)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1562)
  at com.google.firebase.provider.FirebaseInitProvider.attachInfo (FirebaseInitProvider.java:45)
  at android.app.ActivityThread.installProvider (ActivityThread.java:5084)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:4673)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4613)
  at android.app.ActivityThread.access$1800 (ActivityThread.java:141)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1298)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5336)
  at java.lang.reflect.Method.invokeNative (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:871)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:687)
  at dalvik.system.NativeStart.main (NativeStart.java)

```

**Comment by rlazo** [comment] 2020-06-05 14:41
Hi @Belka1000867 which version of picasso are you using? this bug looks related to https://github.com/square/okhttp/issues/4746

**Comment by ashwinraghav** [comment] 2020-06-05 16:18
Duplicate of https://github.com/firebase/firebase-android-sdk/issues/1397

**Closed by ashwinraghav** 2020-06-05 16:18 UTC
Labels: api: inappmessaging, needs-info
