### ISSUE TITLE
com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host)

### ISSUE THREAD

**Issue by rahul00845** [firebase/firebase-android-sdk#384] opened 2019-04-29 11:09 UTC
### [REQUIRED] Step 3: Describe the problem
Firebase network exception is showing in craslytics, not able to reproduce this error. 

Exception: java.util.concurrent.ExecutionException: com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred.
       at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
       at com.google.android.gms.tasks.Tasks.await(Unknown Source:23)
       at com.xxxx.android.authentication.Firebase.getAuthDetail(SignInActivity.kt:40)
       at com.xxx.android.webview.WebViewActivity.getToken(WebViewActivity.kt:1150)
       at com.xxx.android.webview.WebAppInterface.getToken(WebAppInterface.kt:320)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:160)
       at android.os.HandlerThread.run(HandlerThread.java:65)

Caused by com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred.
       at com.google.firebase.auth.api.internal.zzds.zzb(Unknown Source:15)
       at com.google.firebase.auth.api.internal.zzew.zza(Unknown Source:11)
       at com.google.firebase.auth.api.internal.zzeo.zzc(Unknown Source:33)
       at com.google.firebase.auth.api.internal.zzep.onFailure(Unknown Source:49)
       at com.google.firebase.auth.api.internal.zzdy.dispatchTransaction(Unknown Source:18)
       at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source:12)
       at android.os.Binder.execTransact(Binder.java:752)

**Comment by mistreckless** [comment] 2019-05-14 19:35
Same error. I really have no idea how to fix this. The error occurs most often on Xiaomi devices. 
Approximate steps to reproduce: 
1) Integrate google sign in and firebase auth (https://firebase.google.com/docs/auth/android/google-signin?authuser=0)
2) Every time app launch get google credentials -> sign in to firebase -> get firebase id token (https://firebase.google.com/docs/auth/admin/verify-id-tokens)
3) Everything works fine, but in a few weeks this error occurs
Clear cache, clear data and reinstall app doesn't helps.

**Comment by candrwow** [comment] 2019-07-17 14:59
when device login successfully,then don't do anything or power off,after 1 hour(or long time,I think local idToken is out of date),this error will happen.
my code is:
```
firebaseAuth.getCurrentUser().getIdToken(false)
                        .addOnCompleteListener(task -> {...})
```
but when I change `getIdToken(false)` to `getIdToken(true)`,this error will not happen.
my firebase auth version is 16~18.1.0,they all have this error.

**Comment by hpols** [comment] 2019-08-03 08:45
I've just got this error true. I haven't changed this part of the code for quite a while (somewhere around a month) and it was working before. I revisit it today to go through the full app flow and get this error. I've already checked if google play is running etc. as I first thought perhaps the server is down …

**Comment by olonge** [comment] 2019-08-12 16:57
Same here.
I'm getting this error on a Huawei MediaPad.
However, I am eventually able to log in after repeated attempts. 

PS. I can't rule out a dodgy WiFi connection, though

**Comment by artsemionov** [comment] 2019-11-01 12:30
Also having this.

**Comment by FibreOptics** [comment] 2019-12-13 05:37
My react app has this after sign in and sign out once OR closing the sign in popup. It seems to be a cool down?!!! Still looking for answers.
This is where the error was throw from in nexttick.js
```
goog.async.throwException = function(exception) {
  // Each throw needs to be in its own context.
  goog.global.setTimeout(function() { throw exception; }, 0);
};
```

**Comment by ashwinraghav** [comment] 2020-06-09 18:40
Thanks for your patience on this.
- Are you able to share the versions of Firebase Auth you are using?
- What devices do these occur on?
- Have you upgraded to newer versions of Auth, since the time of this report and seen the errors go away?

**Comment by ashwinraghav** [comment] 2020-06-26 22:00
Closing since the issue seems largely inactive

**Closed by ashwinraghav** 2020-06-26 22:00 UTC
Labels: api: auth

**Comment by Ranindu15** [comment] 2020-07-26 11:18
same issue here. Any solution for this>
