### ISSUE TITLE
Crashlytics without Analytics adds more than 500Kb to dex

### ISSUE THREAD

**Issue by Tolriq** [firebase/firebase-android-sdk#4235] opened 2022-10-24 10:57 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Flamingo C5
  * Firebase Component: Crashlytics
  * Component version: BOM 31.0.1 / crashlytics gradle 2.9.2

### [REQUIRED] Step 3: Describe the problem

I'm trying to add Crashlytics in a new app without Analytics this adds 566Kb of dex size with a large part that looks like autogenerated values for session events.

This is quite an insane size just to gather crash logs (Mostly thanks to Google who removed the device models where the crash occurs from Play Console without warning).

Is there a way to reduce that size to something more acceptable?

![image](https://user-images.githubusercontent.com/932609/197509941-60505386-a04b-438e-be75-cc1c6f08f776.png)

**Comment by argzdev** [comment] 2022-10-24 12:19
Hi @Tolriq, thanks for reporting. May I ask what tool are you using to check the dex size? I want to try and investigate this as well.

**Comment by Tolriq** [comment] 2022-10-24 12:30
In this case I used the APK analyzer from Android Studio as it's the easiest to apply proguard mapping.

I forget to mention but this is on a R8 full mode build. In debug builds it's probably more.

**Comment by mrichards** [comment] 2022-10-24 14:58
@Tolriq Can you double-check that you are minifying your build? In my test app, I apply R8 in the default configuration (using `minifyEnabled true` and nothing special in the `proguard-rules` file), and the total size increase of my APK when using only Crashlytics, compared to an app with no Firebase SDKs, is about 152k.

The sizes for classes in my `com.google.firebase.crashlytics.internal.model` package are much smaller than the ones in your screenshot:

![image](https://user-images.githubusercontent.com/1540856/197556298-0ee778de-75b3-487c-a944-cd80c5f14b1d.png)

Each Firebase AAR ships with an embedded `proguard-rules` containing minimally-required `keep` rules for that SDK, so you should not need to add your own Firebase-specific R8/proguard rules. If you have something like `-keep class com.google.firebase.crashlytics.**`, you're APK size will be larger than necessary.

**Comment by Tolriq** [comment] 2022-10-24 15:10
I'm very certain that it's minimized in full mode and highly optimized for that, this is a metric I follow very very closely.

And that's why I opened the issue here, I'm pretty sure there's a bug somewhere as it does not sound normal, for the record this is a large application full compose.

I'm using AGP  8.0.0-alpha05 / R8 4.0.34 (So could be a regression in R8 4.x too but I doubt)

![image](https://user-images.githubusercontent.com/932609/197560046-b7ae579c-18ba-4ea9-a9bc-432e1a757330.png)

The AutoValue class is  named `AutoValue_CrashlyticsReport_Session_Event_Application_Execution` and seems to get tons of unrelated stuff there. 
The app is single activity no fragment. Maybe there's some things that tries to be smart about Compose to trace compose and keeps all? 

But yes your screenshot it what I would expect at most for such a library;

**Comment by mrichards** [comment] 2022-10-24 19:31
In my APK analyzer, `AutoValue_CrashlyticsReport_Session_Event_Application_Execution$1` has zero defined methods and is only 64 bytes. (I believe it is so small because the minifier inlines almost everything from that class.)

If you download the [Crashlytics AAR directly](https://maven.google.com/web/index.html?q=crashlytics#com.google.firebase:firebase-crashlytics:18.3.1), you can drag & drop the `.aar` into Android Studio and inspect its bytecode in the `classes.jar` file directly. The fields & methods for  `com.google.firebase.crashlytics.internal.model.AutoValue_CrashlyticsReport_Session_Event_Application_Execution` do not match up at all with what you're seeing in the APK analyzer. So either you applied the wrong `mappings.txt` to your APK or there's something very strange happening with your build that is not caused by Crashlytics / Firebase.

What happens when you use the most recent stable AGP & R8 versions instead of the alphas?

**Comment by Tolriq** [comment] 2022-10-25 06:23
This is the correct mapping

This is the result from AGP 7.3.1 with default R8 (3.3.83) (Again R8 in full mode android.enableR8.fullMode=true)

![image](https://user-images.githubusercontent.com/932609/197691028-6d998afa-7927-495a-afa6-5cd658410514.png)

But this can be a AS retrace issue. 

I've just tested to remove the crashlytics plugin and get the same result, since without the plugin there can't be code generated I guess I'll have to see with R8 team how to properly map things to see where all the dex size is from then.

Can you confirm that the gradle plugin part of crashlytics is just to add the necessary steps to upload the mappings/symbols? (It currently does not work with AGP 8 alphas but it's probably normal)

**Comment by mrichards** [comment] 2022-10-25 17:25
You are correct, the Crashlytics Gradle plugin doesn't alter any of the classes or bytecode. The only impact it has on the APK is injecting one string resource into the app as an XML resource file.

I think one of the these three things must be happening: 1) another plugin is messing with your build; 2) you found an R8 bug, or 3) your app, or a dependency, has unexpected / improper minification rules. 

If you make a fresh sample app with only Crashlytics (or use the [Crashlytics quickstart](https://github.com/firebase/quickstart-android/tree/master/crash)), I expect that you will see the smaller SDK footprint in your APK. If the issue persists with a minimally-reproduceable example, you can post it and I'll dig into it further.

Assuming it does not, I suggest testing builds with and without applying other Gradle plugins that you use, and also taking a look at the merged proguard rules file, which can be found somewhere like `app/build/outputs/mapping/release/configuration.txt`, to look for anything suspicious.

**Comment by Tolriq** [comment] 2022-10-26 06:48
After talking to R8 team, it's not really a bug but a limitation of the tooling due to horizontal merging (maybe only in full mode).
So the size displayed and the content of the classes are not real as they can include many other things / code.

I'll need to figure out other ways to properly follow what touches the dex sizes in the future. Sorry for the false alarm.

Unrelated but asking quickly before investigating later but is the gradle plugin supposed to work with AGP 8.0 alphas? I get ''Caused by: org.gradle.api.internal.provider.MissingValueException: Cannot query the value of this property because it has no value available."

**Closed** 2022-10-26 14:54 UTC
Labels: api: crashlytics, needs-attention
