### ISSUE TITLE
Bug: NPE on FirebaseInstallations.registerFidWithServer

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [firebase/firebase-android-sdk#1918] opened 2020-08-26 06:08 UTC
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:  4.0.1

  * Firebase Component: core+Crashlytics
  * Component version: 
    implementation 'com.google.firebase:firebase-core:17.5.0'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

### [REQUIRED] Step 3: Describe the problem
A crash report via Crashlytics, showing that it's from Firebase:
https://console.firebase.google.com/u/0/project/app-manager-cdf2c/crashlytics/app/android:com.lb.app_manager/issues/f6245cc1182d5c8ff2d9df615df13785?time=last-seven-days&sessionId=5F45F8C503550001170D19C74AC60785_DNE_0_v2

https://issuetracker.google.com/issues/166291459

The exception is:

Fatal Exception: java.lang.NullPointerException
       at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:452)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:331)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doGetId$1(FirebaseInstallations.java:296)
       at com.google.firebase.installations.FirebaseInstallations$$Lambda$3.run(FirebaseInstallations.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

[flq39A3eOs.zip](https://github.com/firebase/firebase-android-sdk/files/5127910/flq39A3eOs.zip)

#### Steps to reproduce:
It crashes for some users with this exception. 
I don't know how to reproduce. It's still quite rare.

#### Relevant Code:
No idea on which phase it occurs.
The exception doesn't include any mention of a function/class of my app.

**Comment by rlazo** [comment] 2020-08-26 15:59
Duplicate of #1915

**Comment by AndroidDeveloperLB** [comment] 2020-08-26 16:19
@rlazo Are you sure it's a duplicate?
There I can see this:

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

And here I can't for some reason.

**Comment by rlazo** [comment] 2020-08-26 16:48
@AndroidDeveloperLB both are NPE and both come from the same line `(FirebaseInstallations.java:452)`, so I **think** they are duplicates. Just to be extra sure I'll reopen this issue to keep track of it.

**Comment by AndroidDeveloperLB** [comment] 2020-08-26 18:15
@rlazo They could be duplicates. I don't know.
Why didn't I get more information though?
It's said there it's on "Xiaomi MiBox S (Android 9)". 
In my case it's on "Classic MY8301" (4.3, probably), and "Galaxy Grand Neo Plus" (4.4.4 ).

**Comment by ankitaj224** [comment] 2020-08-26 19:02
@AndroidDeveloperLB  I am from the Firebase Installations team and as @rlazo mentioned, this issue is definitely a duplicate of #1915 

Your app transitively depends on `com.google.firebase:firebase-installations:16.3.2`  from `com.google.firebase:firebase-core:17.5.0` responsible for the crash.

Latest version of firebase-installations(FIS) i.e `com.google.firebase:firebase-installations:16.3.3` contains the fix.

I am not sure when firebase-core will update their dependency on FIS. But to resolve this issue you can define a direct dependency on `com.google.firebase:firebase-installations:16.3.3`.

Please let me know if you have any questions.

**Closed** 2020-08-26 19:07 UTC
Labels: api: core, firebase-installations

**Comment by AndroidDeveloperLB** [comment] 2020-08-26 19:49
@ankitaj224 Didn't know the core depends on more modules of android-x. I thought it's the base of the base...

Anyway, thanks.
