### ISSUE TITLE
ERROR_MISSING_CLIENT_IDENTIFIER

### ISSUE THREAD

**Issue by AnYuer** [firebase/firebase-android-sdk#2240] opened 2020-12-08 14:20 UTC
您好，接入电话验证码发送的时候  报了这个错误提示：ERROR_MISSING_CLIENT_IDENTIFIER
This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.

请问该怎么解决，万分感激

**Comment by rlazo** [comment] 2020-12-09 02:27
Hi @AnYuer thanks for the report. To help you better, we need more information. Can you fill in details that our issue template recommends?

```
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

// TODO(you): code here to reproduce the problem
```

**Comment by AnYuer** [comment] 2020-12-09 03:32
Android Studio版本:4.1.1
firebase 电话验证码 发送验证码功能
 问题：ERROR_MISSING_CLIENT_IDENTIFIER
This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.

**Comment by AnYuer** [comment] 2020-12-09 03:39
望回复，十万火急，谢谢您

**Comment by rlazo** [comment] 2021-01-10 02:00
Hi @AnYuer sorry for the late reply. We need more information to help you debug the issue. Please follow the template so we have enough info. Thanks

**Comment by ShakeelAhmed210** [comment] 2021-01-19 07:49
### [READ] Step 1: Are you in the right place?  Yes, we are in right place

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:


### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____4.1.1
  * Firebase Component: _____ (Firebase phone auth)
  * Component version: _____'com.google.firebase:firebase-auth:20.0.2'

### [REQUIRED] Step 3: Describe the problem

The problem happens when we follow the integration guide for firebase phone auth.  it was working previously, but i think some recent changes in firebase sdk has broken the functionality, when we enter phone number and press continue, it tried to send code but failed, and gives below erorr

**This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.**



when we add the signup 


#### Steps to reproduce:
just follow the tutorial for firebase phone auth.

What happened? How can we make the problem occur?  
follow firebase phone auth in firebase 
[Tutorial](https://firebase.google.com/docs/auth/android/phone-auth?authuser=0
)
This could be a description, log/console output, etc.

**This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.**

**Comment by malcolmdeck** [comment] 2021-01-19 18:09
Thank you for the report. Can you please verify that you have enable the Android Device Verification API in the Google Cloud Console? In addition, can you please link a minimal viable reproduction of this issue? I can't get this error to occur

**Comment by ShakeelAhmed210** [comment] 2021-01-20 05:45
yes, i have enabled device verification api from google cloud console. 

it was working previously and was taking user to webpage for reCAPTCHA verification, but then it stopped working, we have not changed anything in our implementation, nothing was changed in any settings,  

can you confirm that you have taken only the steps those are mentioned in firebase documentation, or have you done anything extra in configurations?


i checked firebase phone auth sample code from git, but the issue is same.

**Comment by intelle-tech** [comment] 2021-01-27 07:49
what information required from my side, instead of closing it, please assign to @AnYuer

**Comment by malcolmdeck** [comment] 2021-01-29 00:20
Are you getting any Logcat information in addition to the ERROR_MISSING_CLIENT_IDENTIFIER? Or are you perhaps turning on a testing flow? I can't get this behavior to reproduce for myself, so I can't debug this. 

As for extra configurations, no you shouldn't need to do anything special, the docs give you all of the steps :)

**Comment by intelle-tech** [comment] 2021-01-29 05:07
we have deleted previous project and created new one, and the issue was resolved. i believe there is bug which occurs sometimes with some developers, not with all. The issue is resolved, you can close this thread

**Comment by rlazo** [comment] 2021-01-29 14:01
Thanks for the update @intelle-tech !

**Closed by rlazo** 2021-01-29 14:01 UTC
Labels: api: auth, needs-attention
