### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError Firebase Auth

### ISSUE THREAD

**Issue by mallikarjunba** [firebase/firebase-android-sdk#3699] opened 2022-05-05 09:27 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Bumblebee | 2021.1.1 Patch 3
  * Firebase Component: Firebase Auth (Database, Firestore, Storage, Functions, etc)
  * Component version: 21.0.2

#### Steps to reproduce:
Firebase Auth crashes with OutOfMemoryError in Android 8 or Android 10

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Logs:
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 75497480 byte allocation with 8388608 free bytes and 48MB until OOM, target footprint 225537616, growth limit 268435456
       at java.util.Arrays.copyOf(Arrays.java:3257)
       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
       at java.lang.StringBuilder.append(StringBuilder.java:203)
       at org.json.JSONStringer.string(JSONStringer.java:354)
       at org.json.JSONStringer.value(JSONStringer.java:261)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONObject.writeTo(JSONObject.java:733)
       at org.json.JSONObject.toString(JSONObject.java:701)
       at com.google.firebase.auth.internal.zzbg.zzd(zzbg.java:27)
       at com.google.firebase.auth.FirebaseAuth.zzG(FirebaseAuth.java:13)
       at com.google.firebase.auth.zzo.zza(zzo.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzru.zzb(zzru.java:3)
       at com.google.android.gms.internal.firebase-auth-api.zzug.zzj(zzug.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzud.zzn(zzud.java:2)
       at com.google.android.gms.internal.firebase-auth-api.zztf.zzn(zztf.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzqd.zzb(zzqd.java:2)
       at com.google.android.gms.internal.firebase-auth-api.zzuo.zza(zzuo.java:24)
       at com.google.android.gms.internal.firebase-auth-api.zztu.zzf(zztu.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zzrk.zzp(zzrk.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zztg.zzj(zztg.java:5)
       at com.google.android.gms.internal.firebase-auth-api.zzru.zzc(zzru.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzuh.run(zzuh.java:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

-----------------------------------------------------------------------------------------------------
Logs2:
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 75497480 byte allocation with 8388608 free bytes and 51MB until OOM, max allowed footprint 156104920, growth limit 201326592
       at java.util.Arrays.copyOf(Arrays.java:3260)
       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:660)
       at java.lang.StringBuilder.append(StringBuilder.java:203)
       at org.json.JSONStringer.string(JSONStringer.java:344)
       at org.json.JSONStringer.value(JSONStringer.java:252)
       at org.json.JSONArray.writeTo(JSONArray.java:613)
       at org.json.JSONStringer.value(JSONStringer.java:233)
       at org.json.JSONObject.writeTo(JSONObject.java:723)
       at org.json.JSONObject.toString(JSONObject.java:692)
       at com.google.firebase.auth.internal.zzbg.zzd(zzbg.java:27)
       at com.google.firebase.auth.FirebaseAuth.zzG(FirebaseAuth.java:13)
       at com.google.firebase.auth.zzo.zza(zzo.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzru.zzb(zzru.java:3)
       at com.google.android.gms.internal.firebase-auth-api.zzug.zzj(zzug.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzud.zzn(zzud.java:2)
       at com.google.android.gms.internal.firebase-auth-api.zztf.zzn(zztf.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzqd.zzb(zzqd.java:2)
       at com.google.android.gms.internal.firebase-auth-api.zzuo.zza(zzuo.java:24)
       at com.google.android.gms.internal.firebase-auth-api.zztu.zzf(zztu.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zzrk.zzp(zzrk.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zztg.zzj(zztg.java:5)

**Comment by argzdev** [comment] 2022-05-05 09:34
Thanks for reporting, @mallikarjunba. This looks like a duplicate of #3617. That being said, please continue your report on that issue instead for better tracking, also give it a thumbs up so our engineers can prioritize the fix based on severity. Thanks!

**Closed by argzdev** 2022-05-05 09:34 UTC
Labels: api: auth
