### ISSUE TITLE
Breakpad Symbol Generation Failed (exit=1)

### ISSUE THREAD

**Issue by mmillington** [firebase/firebase-android-sdk#4280] opened 2022-11-03 20:15 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
  * Firebase Component: Firebase Crashlytics NDK
  * Component version: 
  firebase-crashlytics-gradle: 2.9.1
  firebase-crashlytics-ndk: 18.2.11

#### Steps to reproduce:

run app:generateCrashlyticsSymbolFile[AnyBuildType]

It seems to be a similar situation to this Issue: https://github.com/firebase/firebase-android-sdk/issues/3338
Although our exit code is 1, compared to theirs which was 126.

We are using the Unreal Engine, and have been doing so with Crashlytics integrated into our app for multiple years now without ever encountering such an issue.  We managed to track it down to a particular commit, which was quite a large change in the codebase, and without any particular clues from the failure itself it's hard for us to know where to start to diagnose the problem.

It will be nearly impossible for us to create a MCVE since that would probably include the Unreal Engine, and since we don't really know why it is failing we don't know what would be required in the MCVE to reproduce the issue.  

This is the output I receive:
[output.txt](https://github.com/firebase/firebase-android-sdk/files/9930011/output.txt)
[stderr.txt](https://github.com/firebase/firebase-android-sdk/files/9930018/stderr.txt)

I've tried following the suggestions in the thread above to get more information, but having a bit of trouble.

If I run the dump_syms.exe manually on the specific .so file that is causing the failure (libue4.so) with the -v option I get the following output only:

'Failed to mmap ELF file 'app\build\intermediates\merged_native_libs\release\out\lib\armeabi-v7a\libUE4.so': No error
Failed to write symbol file.'

However I'm not sure I'm supplying the correct parameters to dump_syms.  I'm trying to follow the instructions here:
https://www.chromium.org/developers/decoding-crash-dumps/
where it mentions running:

dump_syms /lib/libfoo.so /usr/debug/lib > /tmp/libfoo.so.sym

But even with the .so files that the symbol generation succeeds on (libplaycore.so for example) I get the error:

libplaycore.so: file contains no debugging information (no ".stab" or ".debug_info" sections)

So I think I'm doing something wrong.

As with the poster in the linked thread, I'd expect more information about the failure itself in order to diagnose the issue properly.  As it stands I'm not 100% where the problem lies.

**Comment by humanolaranja** [comment] 2022-12-08 16:28
Facing the same

**Comment by smg-daniell** [comment] 2023-01-09 22:39
I have exactly the same issue on windows, but I don't get this error on Mac

**Comment by mrober** [comment] 2023-02-03 17:30
The dump_syms executable distributed with the Crashlytics gradle plugin is modified, can you try running that command manually again but use the dump_syms located in `build/crashlytics/{debug|release}/dump_syms/`? If that still does not work, would you be willing to share your symbols file with us? If so, please reach out to [Firebase support](https://firebase.google.com/support/), provide them with the symbols file, and mention my name mrober. Thanks!

**Comment by limjonguk** [comment] 2023-02-06 07:35
I'm experiencing the same issue after updating Crashlytics.
The test environment is as follows.

[Build environment]
- OS : Windows 10
- Android SDK Build-Tool : v30.0.3
- Android SDK Platform-Tools: v33.0.3
- NDK : v21.4.7075529
- JDK : 8 or 11
- Build Environment : Unreal Engine 4.27

[updated version]
- Updated firebase-crashlytics-gradle library from v2.3.0 to v2.9.2
- Updated firebase-crashlytics-ndk library from v17.2.1 to v18.2.3

There were several processes, but the build was successful by changing the symbol file generator to cSYM. (The symbol file generator has been changed to 'breakped' since crashlytics-gradle v2.8.0)
But still seems to be having issues. Null symbol file generated for.. message is displayed and the symbol file is not normally created.
I've contacted Firebase support and are working on this issue with Marlon (Case 10215122). If there are any additional confirmations, we will share them.

**Comment by jpainam** [comment] 2023-04-17 22:10
Experiencing the same issue

**Comment by mrober** [comment] 2023-05-18 14:06
I am trying to reproduce this issue on Windows. Would somebody be willing to send an example of their symbols file that experiences this issue to [Firebase Support] and mentioned my ldap mrober? Then I can look deeper.

**Comment by limjonguk** [comment] 2023-05-18 14:36
@mrober Hello, we are still talking with Marlon about (firebase support : Case 10215122).
We will reproduce the issue in a few days and share the symbol file. thank you.

**Comment by mrober** [comment] 2023-06-01 15:19
Thanks everybody for the info, and thanks for providing us with example symbol files. We have confirmed there is an issue. The build tool fails with large symbol files over 2GB on Windows. Likely this is caused by some compatibility layer, we are tracking this internally.

We confirmed the build tool still works with large files on Linux and macOS. So a workaround for now is to upload symbols from a Linux machine or Mac, some folks do this by having a dedicated CI system.

The [Firebase CLI](https://firebase.google.com/docs/cli) command to upload symbols is:

```
firebase crashlytics:symbols:upload --app=1:123:android:123 path/to/symbols
```

**Comment by mutagene** [comment] 2023-06-07 13:36
I'm running into this issue building on macOS (M1 Pro) an app which is using Qt.

**Comment by mutagene** [comment] 2023-06-07 15:01
If I run  `dump_syms.bin` and capture stderr, I get `Failed to write symbol file.` for 24 of the 155 libraries. With verbosity enabled, I get the following for `build/intermediates/merged_native_libs/release/out/lib/arm64-v8a//libFailingLibrary.so: unable to generate file identifier`.

**Comment by mrober** [comment] 2023-06-16 13:56
@mutagene Could you please provide me with an example of one of those 24 files? I am actively working on this issue right now. If you're not ok posting it publicly, you can reach out to [Firebase Support](https://firebase.google.com/support/) and it will get routed to me. Thanks!

**Comment by mrober** [comment] 2023-06-16 19:41
Hi folks, I have a fix for the issue with large files on Windows. Unfortunately, it didn't make it into this release. I built an artifact you can use for now, please try it and let me know if you have any problems.

Download and extract [m2repository.zip](https://github.com/firebase/firebase-android-sdk/files/11774265/m2repository.zip), and then add it to your build by doing something like:

```
pluginManagement {
  repositories {
    maven { url "/path/to/artifact" }
    ...
  }
}
```

(for kts use `maven { url = uri("file:///path/to/artifact") }` syntax instead)

And then use the plugin by

`id 'com.google.firebase.crashlytics' version '2.9.7-alpha' apply false`

**Comment by unpaleness** [comment] 2023-06-29 10:31
Hi!
I've tried to use 2.9.7-alpha as mentioned above but unfortunately the problem still persists. The difference is in the error code:
`> java.io.IOException: Breakpad symbol generation failed (exit=-1073741511), see STDERR`

**Comment by unpaleness** [comment] 2023-06-30 11:53
I've also checked a weird approach and it works:
- install **firebase cli**
- try to upload symbols (fails)
- replace **.crashlytics/dump_syms.exe** with custom one (I've used the one built from sources: https://github.com/mozilla/dump_syms/tree/main)
- try to upload again (works)

**Comment by danbachler** [comment] 2023-07-31 23:10
I am running into a very similar problem except my exit code is 134.  

The build environment is a Linux VM, managed by CircleCI, but the same build step also failed on a Linux machine (Mint 21.1 Cinnamon, Kernel 5.15.0-78-generic), and a Mac machine (Ventura 13.4.1).

The issue is with a golang lib (.so), all other libs both internal and external process fine.

We are running version 2.9.7 on all mentioned devices.

**Comment by rostyslavbur** [comment] 2023-08-04 14:03
@mrober Hi, after update to 2.9.7(or 2.9.8) facing similar issue "java.io.IOException: Breakpad symbol generation failed (exit=-1073741511), see STDERR". When trying to launch dump_syms.exe, even .exe standalone(without specifying any arguments) it fails with an exception "the procedure entry point _ZSt28_throw_bad_array_new_lengthv could not be located in the dynamic link library", checked 2.9.6 version and below, everything is ok, as far as I understand "libstdc++-6.dll" must include that symbol, but it doesn't.

**Comment by mrober** [comment] 2023-08-04 14:27
Thanks for reporting this everyone. I found there are three issues:

1. Symbols failing to upload for large files on Windows
2. Symbols failing to upload for some golang libs on all platforms
3. The `dump_syms` binary itself failing to run on some machines due to an old `libstdc++-6.dll` on Windows since 2.9.7

So 1. is fixed in 2.9.7, but some machines might not be able to utilize it due to 3. I will post a new version of `dump_syms` today. And that will be included in the next release in a couple weeks. And 2. is still in progress, I am not sure if it will make it into the next release or the next-next release.

**Comment by mrober** [comment] 2023-08-04 20:03
@rostyslavbur [Here](https://github.com/firebase/firebase-android-sdk/files/12264236/dump_syms.zip) is a `dump_syms` binary that I built to avoid the issue with `libstdc++-6.dll`. I am still not sure how we will resolve this for the next release, so just consider this a work in progress. Please let me know if you have any issues with this version or any questions.

**Comment by mrober** [comment] 2023-08-28 15:41
The `dump_syms` binary for Windows is fixed in version 2.9.9 of the Crashlytics Gradle plugin. You may need to clean your build environment to ensure the plugin is using the latest version of the binary.

We are working on a fix for the issue with symbols for some golang libs failing to upload.

**Comment by sergeiignatov** [comment] 2023-10-23 02:42
@mrober could you please advice, how can I exclude one prebuilt *.so library from symbol file upload? It will be useful to exclude that golang lib temporarily until fix is released.

**Comment by mrober** [comment] 2023-10-23 14:28
@sergeiignatov in the mean time you could disable uploading from your gradle build file by setting `nativeSymbolUploadEnabled = false`, and then use the [Firebase CLI](https://firebase.google.com/docs/cli#crashlytics-commands) to upload symbols. You can specify each file if you want, or copy all but the golang into a dir and upload that. Sorry for the delay in this issue, we are working on other high priority issues right now, but I do plan to work on this soon.

**Comment by davidgalarza** [comment] 2024-04-16 16:07
Any update I'm facing the same issue to upload android symbols with my MAC M3 PRO:
```
i  Generating symbols for build/app/outputs/symbols
⚠  [CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Skipping dumpsyms extraction, file exists: /Users/davidgalarzachacon/Documents/Sounter/App/sounter/.crashlytics/dump_syms.bin
[CRASHLYTICS LOG DEBUG] Breakpad symbol generator initialized: /Users/davidgalarzachacon/Documents/Sounter/App/sounter/.crashlytics/dump_syms.bin
[CRASHLYTICS LOG DEBUG] Generating native symbol files for /Users/davidgalarzachacon/Documents/Sounter/App/sounter/build/app/outputs/symbols; writing output to: /tmp/crashlytics-b4c1841c-3eb2-4af0-8fed-06f333fb9f6d/nativeSymbols/1-16353195526-android-3d90083307c68cc2/breakpad
[CRASHLYTICS LOG DEBUG] 4 native libraries found at build/app/outputs/symbols
[CRASHLYTICS LOG DEBUG] Crashlytics generating Breakpad Symbol file for: /Users/davidgalarzachacon/Documents/Sounter/App/sounter/build/app/outputs/symbols/app.android-x64.symbols
[CRASHLYTICS LOG DEBUG] Extracting Breakpad symbols to temp file: /tmp/crashlytics-b4c1841c-3eb2-4af0-8fed-06f333fb9f6d/nativeSymbols/1-16353195526-android-3d90083307c68cc2/breakpad/app.android-x64.symbols2536240426155651774.tmp
[CRASHLYTICS LOG DEBUG] GNU Build Id for /Users/davidgalarzachacon/Documents/Sounter/App/sounter/build/app/outputs/symbols/app.android-x64.symbols: ec84697026f909d65ad68741a25562d5
[CRASHLYTICS LOG DEBUG] Renaming Breakpad symbol file to: /tmp/crashlytics-b4c1841c-3eb2-4af0-8fed-06f333fb9f6d/nativeSymbols/1-16353195526-android-3d90083307c68cc2/breakpad/app.android-x64-x86_64-ec84697026f909d65ad68741a25562d5.sym
[CRASHLYTICS LOG DEBUG] Generated symbol file: /tmp/crashlytics-b4c1841c-3eb2-4af0-8fed-06f333fb9f6d/nativeSymbols/1-16353195526-android-3d90083307c68cc2/breakpad/app.android-x64-x86_64-ec84697026f909d65ad68741a25562d5.sym (6,094,369 bytes)
[CRASHLYTICS LOG DEBUG] Crashlytics generating Breakpad Symbol file for: /Users/davidgalarzachacon/Documents/Sounter/App/sounter/build/app/outputs/symbols/app.ios-arm64.symbols
[CRASHLYTICS LOG DEBUG] Extracting Breakpad symbols to temp file: /tmp/crashlytics-b4c1841c-3eb2-4af0-8fed-06f333fb9f6d/nativeSymbols/1-16353195526-android-3d90083307c68cc2/breakpad/app.ios-arm64.symbols8103815293564869336.tmp
java.io.IOException: Breakpad symbol generation failed (exit=1), see STDERR
	at com.google.firebase.crashlytics.buildtools.ndk.internal.breakpad.BreakpadSymbolGenerator.generateSymbols(BreakpadSymbolGenerator.java:133)
	at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:273)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:185)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:118)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:65)
	at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:111)


Error: java command failed with args: -jar,/Users/davidgalarzachacon/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,/tmp/crashlytics-b4c1841c-3eb2-4af0-8fed-06f333fb9f6d/nativeSymbols/1-16353195526-android-3d90083307c68cc2/breakpad,-verbose,-generateNativeSymbols,-unstrippedLibrary,build/app/outputs/symbols,-clientName,firebase-cli;crashlytics-buildtools

```

**Comment by mrober** [comment] 2024-04-25 19:10
We have a prerelease of the next major version of the Crashlytics Gradle plugin, you can find it in https://github.com/firebase/firebase-android-sdk/issues/5733. This has several improvements, including better support native apps. The prerelease comes with the latest upstream changes to Breakpad, which will resolve this problem. If the prerelease does not resolve this problem, please let me know on that issue.

**Closed by mrober** 2024-04-25 19:10 UTC
Labels: api: crashlytics, triaged-accepted
