### ISSUE TITLE
Crashlytics making the app crash on "release" version but not in "debug"

### ISSUE THREAD

**Issue by BobbyESP** [firebase/firebase-android-sdk#6146] opened 2024-08-01 15:23 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Ladybug | 2024.1.3 Canary 2
  * Firebase Component: Crashlytics and Analytics 
  * Component version: `Firebase BoM - 33.1.2` -> `(implicit) Firebase Crashlytics - 19.0.3`

### [REQUIRED] Step 3: Describe the problem
I'm trying to build my application with two variants (`FOSS `and `GMS - Google Mobile Services`), being Crashlytics used in the PlayStore version (GMS) for sending bug reports and crashes to me. I updated the libraries since I was using some outdated and after this, I realized that the GMS version worked well in debug mode, but once I build it for release and install it on my device, the app instantly crashes.

#### Steps to reproduce:
1. Add Crashlytics to the project as the Firebase onboarding says
2. Open the app WITH `RELEASE ` mode
3. Crash happens with the next stack trace:

```
Process: com.bobbyesp.metadator, PID: 14123 - java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bobbyesp.metadator/com.bobbyesp.metadator.MainActivity}: java.lang.NullPointerException: FirebaseCrashlytics component is not present.
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3991)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:224)
                                                                                                    	at android.os.Looper.loop(Looper.java:318)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8790)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
                                                                                                    Caused by: java.lang.NullPointerException: FirebaseCrashlytics component is not present.
                                                                                                    	at com.bobbyesp.metadator.MainActivity.onCreate(SourceFile:300)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8891)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8856)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1471)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
```

#### Relevant Code:
- `libs.versions.toml`
```toml
[versions]
googleServices = "4.4.2"
firebaseBom = "33.1.2"

[libraries]
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

[plugins]
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" }
google-gms = { id = "com.google.gms.google-services", version.ref = "googleServices" }
```

- `build.gradle.kts (Project-level)`
```kotlin
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.kotlin) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.hilt) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.kotlin.parcelize) apply false
    alias(libs.plugins.kotlin.ksp) apply false
    alias(libs.plugins.compose.compiler) apply false
    alias(libs.plugins.androidTest) apply false

    alias(libs.plugins.google.gms) apply false
    alias(libs.plugins.firebase.crashlytics) apply false
}

val isGoogleMobileServicesBuild by extra {
    gradle.startParameter.taskNames.none { task -> task.contains("foss", ignoreCase = true) }
}
```

- `app/build.gradle.kts (module-level)`
```kotlin
import com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsExtension

val isGoogleMobileServicesBuild: Boolean by rootProject.extra

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.android.kotlin)
    alias(libs.plugins.kotlin.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.compose.compiler)
}

if (isGoogleMobileServicesBuild) {
    apply(plugin = libs.plugins.google.gms.get().pluginId)
    apply(plugin = libs.plugins.firebase.crashlytics.get().pluginId)
}

...

    flavorDimensionList.add("version")

    productFlavors {
        create("playstore") {
            dimension = "version"
            configure<CrashlyticsExtension> {
                mappingFileUploadEnabled = true //Todo: SET TO TRUE WHEN FIXED
                nativeSymbolUploadEnabled = true
            }
        }

        create("foss") {
            dimension = "version"
        }
    }

...

dependencies {
//-------------------FIREBASE-------------------//
    "playstoreImplementation"(platform(libs.firebase.bom))
    "playstoreImplementation"(libs.firebase.analytics)
    "playstoreImplementation"(libs.firebase.crashlytics)
}
```

You can find more information about the app in the repository: [Metadator](https://github.com/BobbyESP/Metadator)

**Comment by lehcar09** [comment] 2024-08-02 16:38
Hi @BobbyESP, thank you for reaching out and providing an MCVE to help our investigation. I tried reproducing the issue, however, I'm experiencing a different error, and on build.

```
Extension of type 'CrashlyticsExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension]
```

In addition to that, the issue occurs only on the `foss` variant of your app as I was able to run the "playstore" variant successfully.

Do I need to configure something else? Did you encounter this build issue?

Based on my understanding this error occurs due to implementation. You’re adding the extra property `isGoogleMobileServicesBuild` when any of the tasks in the current Gradle execution contains the substring "foss". And, only when the property `isGoogleMobileServicesBuild`, you're adding the Crashlytics plugin in the module level build gradle (app/build.gradle.kts). 

The Gradle builds all possible combinations of product flavors and build types by default. Even if you specify a particular variant to build, the compiler still processes all other variants to determine dependencies, resource merging, and other build tasks. Thus, it still detects the missing Crashlytics gradle dependency.

If I may suggest, you can check the conditional logic based on the current variant to include or exclude specific configurations.

i.e.
```
afterEvaluate {
 if (project.hasProperty('android.variantFilter') && project.property('android.variantFilter') == 'foss') { 
     // Additional configurations for foss variant 
  } 
}
```

**Comment by BobbyESP** [comment] 2024-08-02 16:49
Sorry about this. You can try moving the plugins apply from the condition to the `playstore` product flavour creation, like this:

```kotlin
    flavorDimensionList.add("version")

    productFlavors {
        create("playstore") {
            dimension = "version"
			apply(plugin = libs.plugins.google.gms.get().pluginId)
    		apply(plugin = libs.plugins.firebase.crashlytics.get().pluginId)
            configure<CrashlyticsExtension> {
                mappingFileUploadEnabled = false //Todo: SET TO TRUE WHEN FIXED
                nativeSymbolUploadEnabled = false
            }
        }

        create("foss") {
            dimension = "version"
        }
    }
``` 

and deleting this:

```kotlin
if (isGoogleMobileServicesBuild) {
    apply(plugin = libs.plugins.google.gms.get().pluginId)
    apply(plugin = libs.plugins.firebase.crashlytics.get().pluginId)
}
```

This was just a workaround, but seemed not to work since my CI failed exactly due to this, but I forgot to change the code example here, sorry for the inconveniences, I apologize. I'm pretty sure that the error occurs because when creating at build-time the flavour, Gradle still doesn't know that those plugins have to be applied.

Anyways I'll proceed to check what you told me just to ensure things.

**Comment by BobbyESP** [comment] 2024-08-02 16:59
And that's quite strange since the `foss` version works correctly for me (BUT THIS DOES NOT IMPLEMENT THE FIREBASE DEPENDENCIES), but not the 'playstore' one (`debug` version works, but not the `release` one).

In the MainActivity of the app I'm adding this:

```kotlin
class MainActivity : ComponentActivity() {
	...
    @OptIn(ExperimentalMaterial3WindowSizeClassApi::class)
    override fun onCreate(savedInstanceState: Bundle?) {
		...
        super.onCreate(savedInstanceState)
		...
    	Firebase.crashlytics.setCrashlyticsCollectionEnabled(true)
		...
    }
...
}
```

**Comment by BobbyESP** [comment] 2024-08-02 18:03
@lehcar09 Sorry for the ping, but I found where the issue comes from. I thought it was irrelevant, but seems like `    	Firebase.crashlytics.setCrashlyticsCollectionEnabled(true)` makes the app crash. If I delete that, the app works just fine, so I don't know exactly whats the real problem.

I send you a video with a little research of the problem:

https://github.com/user-attachments/assets/6a603f43-f9d5-46a5-9262-e80d8c3e72f3

**Comment by lehcar09** [comment] 2024-08-05 17:47
Thank you for sharing those details @BobbyESP. I was able to reproduce the issue with the code snippets you shared. 

After some debugging, the issue might be due to R8. There is a reported issue before (#5033) that when `isMinifyEnabled = true` it was causing an issue and this was resolved by adding `android.enableR8.fullMode=false` on your project gradle.properties or upgrading to AGP version 8.0.2. 

Based on this [documentation](https://developer.android.com/build/shrink-code#full-mode),

> R8 includes a set of additional optimizations (referred to as "full mode") which makes it behave differently from ProGuard. These optimizations are enabled by default since [Android Gradle plugin version 8.0.0](https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes)…Because the additional optimizations make R8 behave differently from ProGuard, they may require you to include additional ProGuard rules to avoid runtime issues if you're using rules designed for ProGuard.

I did add the `android.enableR8.fullMode=false` and I was able to run your shared MCVE without any errors. Aside from that, I tried using the current release version (8.5.1) of Android Gradle plugin based on this [documentation](https://developer.android.com/reference/tools/gradle-api) and I was able to run the app without any error.

Can you share the previous AGP version you're using? Did you encounter this issue in your previous build?

I’ll notify our engineers about this and see what we can do here. 

In the meantime, I recommend using the current AGP release version 8.5.1. While alpha versions of the Android Gradle plugin can offer early access to new features, they should be used with caution for some reasons.

**Comment by BobbyESP** [comment] 2024-08-05 22:15
Hi, @lehcar09! Thanks for how the problem was explained and the clarity on the resolution one more time. The issue has been solved by downgrading the AGP to the `8.5.1` version (I was using the `8.7.0-alpha02`). So indeed this seems to be a problem with AGP as you told me. If you need any more information I'll be glad to help. Thanks for the communication flow and everything!

[I did updated the libraries in kind a brute way](https://github.com/BobbyESP/Metadator/commit/5c1b0a43edcffd5ffe68ebd435cc9af9def369c3) and so this happened 😆 I wouldn't know that the problem was in the AGP, but it was suspicious the fact that the bug only happened when using the minified version of the app AND just the Play Store version.

Thanks another time!

**Comment by lehcar09** [comment] 2024-08-14 15:09
Hi @BobbyESP, I spoke with our engineers, and coordinated with the Android team. According to the Android team, this issue is due to change in R8 where it only includes default `<init>()` for empty member rules in compat mode.

> The issue should be "fixed" by the next alpha (5). We swap back to the old behavior, the new behavior will be launched under a flag sometime in the future (and eventually become default in full mode). This means that in addition to keeping the class you explicitly need to keep your constructor if the only reference to it is a class constant.

We have confirmed that this issue is resolved in the alpha05 version. That said, I’ll be closing this issue now. Let me know if we need to re-open the issue. Thanks!

**Closed by lehcar09** 2024-08-14 15:09 UTC
Labels: api: crashlytics

**Comment by BobbyESP** [comment] 2024-08-14 15:18
Thank you so much for the help!
