### ISSUE TITLE
NullPointerException at AbtIntegrationHelper.setExperimentActive

### ISSUE THREAD

**Issue by OlehHaidaienko** [firebase/firebase-android-sdk#4716] opened 2023-02-24 17:07 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Electric Eel | 2022.1.1 Patch 1
  * Firebase Component: In-App Messaging
  * Component version: 20.3.0

#### Steps to reproduce:
I can't reproduce. Please take a look at the log and screenshot from Firebase Crashlytics
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.concurrent.Executor.execute(java.lang.Runnable)' on a null object reference
       at com.google.firebase.inappmessaging.internal.AbtIntegrationHelper.setExperimentActive(AbtIntegrationHelper.java:94)
       at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager.triggeredInAppMessage(InAppMessageStreamManager.java:363)
       at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager.lambda$getTriggeredInAppMessageMaybe$27(InAppMessageStreamManager.java:346)
       at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager.$r8$lambda$w4tUspl0-bTh48AvRyCAZ0a1mSM(InAppMessageStreamManager.java)
       at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager$$InternalSyntheticLambda$1$4b09f0da19d4914563fbc47a8eb385ca850290e0e2e34b6d79e30263981ca83c$3.apply(InAppMessageStreamManager.java:6)
       at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess(MaybeFlatten.java:88)
       at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)
       at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:312)
       at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:174)
       at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:56)
```
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/7819367/221242214-f972133f-a3cd-4356-a869-2c5c89490683.png">

**Comment by igoralvess** [comment] 2023-02-24 20:01
I'm having the same issue :(

**Comment by hallefyfretebras** [comment] 2023-02-24 20:03
The same issue here, almost 60k users crashing 💣

**Comment by hallefy** [comment] 2023-02-24 20:04
The same issue here, almost 60k users crashing 💣

**Comment by argzdev** [comment] 2023-02-27 09:34
Hi all, did you happen to use an earlier version prior to encountering this problem? Would it be possible for you to provide us with the previous version that was working? 

However, if there were no changes made to the version before the problem occurred, it's possible that the issue is related to the backend. In that case, please reach out to our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact). They can assist you better since you'll be able to share project details and campaign configurations.

**Comment by OlehHaidaienko** [comment] 2023-03-17 14:59
@argzdev HI, after monitoring this issue for a while I can confirm that it appears only in versions where Firebase BoM was updated. 
We're gonna update BoM to `31.2.3` and will check if the crash still exists

**Comment by argzdev** [comment] 2023-03-17 15:12
Hey @OlehHaidaienko, sorry for the radio silence here. We're still investigating this. Thanks for the extra details.

Here are some of my findings:
- Changes made between versions `20.1.2` to `20.2.0` is during the commit dates between Mar. 10, 2022 - Oct. 12, 2022.
- [History](https://github.com/firebase/firebase-android-sdk/commits/master/firebase-inappmessaging) of commits for `firebase-inappmessaging` shows around 10-11 commits during this timeline (Mar - Oct 2022).
- All commits in the given timeline doesn't seem to have any changes made to the `AbtIntegrationHelper` and `InAppMessageStreamManager`

**Comment by OlehHaidaienko** [comment] 2023-03-27 10:10
Hi @argzdev 
We started rolling out a new app version with updated Firebase BoM `31.2.3` but the issue still exists
Currently, 16k crash events affecting ~2.7k users. 
I could provide some extra logs if you need

**Comment by argzdev** [comment] 2023-03-27 11:10
Hi guys, we're still investigating this. Any chance you could share with us the setup of your campaign. Please do remove any PII (personal identifiable information) if needed. This might give us an idea what's causing the issue. 

Yes, those extra logs will be helpful, @OlehHaidaienko. Thanks!

**Comment by OlehHaidaienko** [comment] 2023-03-27 16:35
@argzdev What information do you need regarding campaign setup?
Btw I checked all active campaigns that we have and wasn’t able to reproduce the crash but I noticed something weird.
In `InAppMessageStreamManager.triggeredInAppMessage` method I see that `abtIntegrationHelper.executor` is `null`.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/7819367/228005188-c9acf28d-1e06-4311-90c4-6411b36e9742.png">
Seems if this condition will be true you should get NPE `content.getPayloadCase().equals(ThickContent.PayloadCase.EXPERIMENTAL_PAYLOAD)`
Maybe this information will help

**Comment by OlehHaidaienko** [comment] 2023-04-18 11:31
@argzdev Hi, please try the following steps to reproduce the issue:

1. Create an experiment for in-app messages with multiple variants(images in our case)
2. Activate the experiment
3. Open the app
4. Observe crash

Note: App won't crash if you added your device as a test device in the experiment because of the check `!content.getIsTestCampaign()`
```
if (!content.getIsTestCampaign()) {
    abtIntegrationHelper.setExperimentActive(
        content.getExperimentalPayload().getExperimentPayload()
    )
}
```
I hope it will help to investigate the issue

**Comment by argzdev** [comment] 2023-04-18 13:50
Sorry for the radio silence here. Really appreciate the updates, @OlehHaidaienko. I was able to reproduce the same behavior from your steps to reproduce the issue. I'll bring this up to our engineers and see what we can do here.

**Comment by FelipeLimaDeSouza** [comment] 2023-04-18 19:52
I have the same problem

**Comment by argzdev** [comment] 2023-04-19 10:18
Hi all, a fix is on the way #4913. Thank you for your patience.

**Comment by FelipeLimaDeSouza** [comment] 2023-04-19 19:32
> Fix merged. Will be available in next release.

When the new version will be released?

**Comment by argzdev** [comment] 2023-05-02 11:07
Hi all, this fix is now release on [Firebase BoM version 32.0.0](https://firebase.google.com/support/release-notes/android#bom_v32-0-0) or In-App Messaging version 20.3.2. You may check out the [release notes](https://firebase.google.com/support/release-notes/android#inappmessaging_v20-3-2) for more information. I'll close this issue now. Thanks!

**Closed by argzdev** 2023-05-02 11:07 UTC
Labels: type: bug, api: inappmessaging
