### ISSUE TITLE
The injectCrashlyticsBuildIds*** Gradle task depends on the merge***NativeLibs task implicitly

### ISSUE THREAD

**Issue by h6ah4i** [firebase/firebase-android-sdk#5083] opened 2023-06-19 03:26 UTC
### [READ] Step 1: Are you in the right place?

YES

### [REQUIRED] Step 2: Describe your environment

 * Gradle version: 8.0
 * Android Gradle Plugin version: 8.0.2
 * Crashlytics Gradle Plugin version: 2.9.6

#### Steps to reproduce:

Gradle build fails when building an Android project which uses Crashlytics with NDK integration.

```
./gradlew app:assembleRelease

...

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:injectCrashlyticsBuildIdsRelease' (type 'InjectBuildIdsTask').
  - Gradle detected a problem with the following location: '***/app/build/intermediates/merged_native_libs/release/out/lib'.
    
    Reason: Task ':app:injectCrashlyticsBuildIdsRelease' uses this output of task ':app:mergeReleaseNativeLibs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':app:mergeReleaseNativeLibs' as an input of ':app:injectCrashlyticsBuildIdsRelease'.
      2. Declare an explicit dependency on ':app:mergeReleaseNativeLibs' from ':app:injectCrashlyticsBuildIdsRelease' using Task#dependsOn.
      3. Declare an explicit dependency on ':app:mergeReleaseNativeLibs' from ':app:injectCrashlyticsBuildIdsRelease' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.

...
```

#### Workaround

I'm using the following code to work around this issue. Put these lines of code into the `build.gradle` of the app module.

```gradle

tasks.all { task ->
    if (task.name.startsWith('injectCrashlyticsBuildIds')) {
        task.dependsOn 'merge' + (task.name =~ /^injectCrashlyticsBuildIds(.+)$/)[0][1] + 'NativeLibs'
    }
}
```

**Comment by argzdev** [comment] 2023-06-22 09:07
Thanks for reaching out, @h6ah4i. I'm unable to reproduce the same behavior with the given details. I tried creating a clean project and added Crashlytics NDK. I changed AGP and Gradle version accordingly. However, running `./gradlew app:assembleRelease` seems to work just fine for me. Not sure what I'm doing wrong. That said, could you provide me a code snippet or [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) for us to investigate this further? Thanks!

**Comment by egorikftp** [comment] 2023-06-22 09:58
In our project, we use the following code, maybe it will help

```kotlin
buildTypes {
     release {
            ....
            configure<CrashlyticsExtension> {
                mappingFileUploadEnabled = true
                nativeSymbolUploadEnabled = true
                unstrippedNativeLibsDir = "build/intermediates/merged_native_libs/release/out/lib"
            }
          ....
        }

}
```


```kotlin
//Uploading NDK Crashlytics logs to Firebase
tasks.whenTaskAdded {
    if (name == "assembleRelease") {
        finalizedBy("uploadCrashlyticsSymbolFileRelease")
    }
}
```

**Comment by Psijic** [comment] 2023-06-23 15:50
@argzdev said I should participate.
At 10:19, Jun 23, 2023, Android Studio detected the following issue(s) with Gradle plugin com.google.firebase.crashlytics

Always-Run Tasks
This task might be setting its up-to-date check to always return false.

Plugin: com.google.firebase.crashlytics
Task: injectCrashlyticsMappingFileIdRelease
Task type: com.google.firebase.crashlytics.buildtools.gradle.tasks.InjectMappingFileIdTask
Issues for the same task were detected in 1 module(s), total execution time was <0.1s (0.1%), by module:
  Execution mode: FULL, time: <0.1s (0.1%), determines build duration: true, on critical path: true, issues: Always-Run Tasks

====Build information:====
Execution date: 23.06.2023, 10:19
Total build duration: 71.4s
Configuration time: 6.7s (9.4%)
Critical path tasks time: 64.3s (90.0%)
Critical path tasks size: 9
AGP versions: 8.0.2
====Platform information:====
AI-222.4459.24.2221.10121639, JRE 17.0.6+0-17.0.6b802.4-9586694x64 JetBrains s.r.o., OS Linux(amd64) v5.14.21-150500.53-default, screens 2560.0x1440.0

AS: Flamingo | 2022.2.1 Patch 2
Kotlin plugin: 222-1.8.20-release-AS3739.54
Android Gradle Plugin: 8.0.2
Gradle: 8.1
Gradle JDK: JetBrains Runtime version 17.0.6
NDK: from local.properties: (not specified), latest from SDK: (not found)
CMake: from local.properties: (not specified), latest from SDK: 3.22.1-g37088a8, from PATH: 3.20.4

**Comment by guillaume-tgl** [comment] 2023-06-29 13:58
I get a similar though different error message since I've updated to Gradle 8:
```
Task ':generateCrashlyticsSymbolFile**' uses this output of task ':merge**NativeLibs' without declaring an explicit or implicit dependency.
```

Should I open another ticket or will the fix correct this one too?

**Comment by mrober** [comment] 2023-06-29 16:41
@guillaume-tgl The fix I mentioned above is specific to the inject task. Could you please open another ticket and put in more details like your gradle build files? The issues are very likely related, but I want to track them separately because the fixes will go out in different releases. Thanks

**Comment by guillaume-tgl** [comment] 2023-06-30 08:56
> @guillaume-tgl The fix I mentioned above is specific to the inject task. Could you please open another ticket and put in more details like your gradle build files? The issues are very likely related, but I want to track them separately because the fixes will go out in different releases. Thanks

Sure

**Comment by egorikftp** [comment] 2023-07-18 12:05
Looks like 2.9.7 released

**Comment by argzdev** [comment] 2023-07-20 09:57
Hi all, I was also able to verify that it's now working with version 2.9.7. I'll close this for now. If anyone is still encountering this issue with the latest version, let us know so we can reopen and investigate this issue further. Thanks!

**Closed by argzdev** 2023-07-20 09:57 UTC
Labels: api: crashlytics, needs-attention

**Comment by h6ah4i** [comment] 2023-07-20 11:02
I confirmed that the latest version 2.9.7 has been resolved this issue for my setup. Thank you :tada:

**Comment by egorikftp** [comment] 2023-07-25 13:02
Still reproduce in 2.9.7
