### ISSUE TITLE
FirebaseAnalytics.setUserProperty() issue.

### ISSUE THREAD

**Issue by HairySnow** [firebase/firebase-android-sdk#4495] opened 2022-12-23 12:16 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1
  * Firebase Component: FirebaseAnalytics
  * Component version: com.google.firebase:firebase-core:21.0.0

### [REQUIRED] Step 3: Describe the problem
Problem: When I used setUserProperty() to remove the user property（DPID） on September 21st, it did work, but after November 1st, the problem occurred again, and the previously removed user property appeared again, and only existed in Traffic acquisition.
Here are screenshots:
User acquisition:
![企业微信截图_16717771313352](https://user-images.githubusercontent.com/24764220/209333625-4bbeffe0-ce8a-4d1a-b132-a6323a067b7f.png)

Traffic acquisition:
![2](https://user-images.githubusercontent.com/24764220/209333647-8bf6f9d8-9074-40ce-a232-41b7ca9268dc.png)

Data starts to grow after November 1st :
![企业微信截图_1671768320408(1)](https://user-images.githubusercontent.com/24764220/209334033-3daf821b-4169-476c-a212-b2dfa5886e9b.png)

#### Steps to reproduce:

1. Log in to Google Analytics Dashboard 
2. Click Reports
3. Click Acquisition -- overview
4. Add 'DPID' comparison

#### Relevant Code:
My code:
@JvmStatic
    fun initUserProperty() {
        if (LoginUtils.isLogin()) {
            setUserProperty("Issuer_Name", LoginUtils.getUserEntity()?.agentColor?.channel)
//            setUserProperty("DP_Number", MembershipUtils.getMembership()?.dpid)
        }
        setUserProperty("DP_Number", " ") //set blank value to remove this property
    }

**Comment by argzdev** [comment] 2022-12-23 12:52
HI @HairySnow, thanks for reporting. Could you answer a few questions for me:
1. Did you update or make any changes to your app before the November 1st issue occurred?
2. Is it possible that not all your users have upgraded to the latest app which contains the `setUserProperty` that removes the user property? So some of your old users might've started using your app again which may trigger the features available in the old version of your app?

If you answer no for both of these questions, and since the SDK has worked removing `setUserProperty` before, but is now triggered by something. Then I believe the SDK is working as intended, and most likely the issue lies in the backend. That said, it would be better for you to reach out to our [Firebase support](https://firebase.google.com/support). They'll be able to assist you .

**Comment by HairySnow** [comment] 2022-12-23 13:33
> HI @HairySnow, thanks for reporting. Could you answer a few questions for me:
> 
> 1. Did you update or make any changes to your app before the November 1st issue occurred?
> 2. Is it possible that not all your users have upgraded to the latest app which contains the `setUserProperty` that removes the user property? So some of your old users might've started using your app again which may trigger the features available in the old version of your app?
> 
> If you answer no for both of these questions, and since the SDK has worked removing `setUserProperty` before, but is now triggered by something. Then I believe the SDK is working as intended, and most likely the issue lies in the backend. That said, it would be better for you to reach out to our [Firebase support](https://firebase.google.com/support). They'll be able to assist you .

Thanks for your reply!
1.No. The code of my app has not been changed since the new version(1.0.7) was released on September 21st, it works fine before November 1st.
2.No. As mentioned above, we have removed the user property 'DPID' in version 1.0.7, but a small amount of data was uploaded to Google Analytics from version 1.0.7 starting from November 1st, prior to this, version 1.0.7 did not upload this user property 'DPID'.
![image](https://user-images.githubusercontent.com/24764220/209343336-1ade5d41-d928-48de-bba9-511c936b2d8f.png)

Thanks again!

**Comment by argzdev** [comment] 2022-12-23 14:21
Thanks for confirming, @HairySnow. Since we validated that this isn't an issue on the SDK, there's nothing else we can do on the SDK side. That said, could you reach out to our [Firebase support](https://firebase.google.com/support), since they have visibility with regards to backend issues. I'll close this for now. Feel free to ask this to be reopened if you think this is a mistake or if there's anything we can change on the SDK side. Thanks!

**Closed by argzdev** 2022-12-23 14:21 UTC
Labels: api: analytics, needs-attention
