### ISSUE TITLE
AndroidAppUri.getDeepLinkUri() should not be annotated with @RecentlyNonNull

### ISSUE THREAD

**Issue by benkay** [firebase/firebase-android-sdk#3412] opened 2022-02-07 14:14 UTC
* Android Studio version: Bumblebee
  * Firebase Component: AppIndexing
  * Component version: 20.0.0

AndroidAppUri.getDeepLinkUri() is annotated with both @Nullable and @RecentlyNonNull. It returns null
in some situations which as far as I can tell are completely valid - the "scheme" and "host_path" parts of
the URI are optional

<img width="626" alt="image" src="https://user-images.githubusercontent.com/832393/152803307-6b8a45fa-9cca-461b-af93-c65b79f0aa11.png">

This causes runtime crashes when the `-Xjsr305=strict` Kotlin option is enabled, for some reason with the following code
```
val deepLinkUri = appUri.deepLinkUri
```
- Shows `deepLinkUri` as nullable in the IDE
- Adds non-null assertions, so crashes at runtime if deepLinkUri returns null

Workaround for the moment is to explicitly add the type annotation to the variable
```
val deepLinkUri: Uri? = appUri.deepLinkUri
```

**Comment by argzdev** [comment] 2022-02-08 09:39
Hi @benkay, thanks for your report. Any chance you could provide us a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) of this issue? It'll greatly speed up our investigation, thanks!

**Comment by benkay** [comment] 2022-02-15 14:44
The following code crashes, despite the URI being a valid AndroidAppUri according to the docs.

```kotlin
val appUri = AndroidAppUri.newAndroidAppUri(Uri.parse("android-app://com.example.app/"))
val deepLinkUri = appUri.deepLinkUri
println(deepLinkUri)
```

**Comment by argzdev** [comment] 2022-02-15 15:23
Thanks for the extra details, @benkay. Per checking, we can’t guarantee that App Indexing will still work as expected since it has removed from the Firebase product set. Currently, we do not recommend using App Indexing for most Firebase apps and no longer support this feature.

What you can do is use the recommended feature - [Android App Links](https://developer.android.com/training/app-links) for your app. If you have issues regarding the feature you can file a report in the official android website by finding the 'Report platform bug' button under the Support section. This is located at the left side of the footer of the website. With that said, I'll be closing this issue now.

**Closed by argzdev** 2022-02-15 15:23 UTC
Labels: api: appindexing, needs-attention
