### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.inappmessaging.model.MessageType com.google.firebase.inappmessaging.model.InAppMessage.getMessageType()' on a null object reference

### ISSUE THREAD

**Issue by Ashishlearn123** [firebase/firebase-android-sdk#4638] opened 2023-02-09 06:03 UTC
We have observed huge crashes on production related to firebaseInAppMessaging, though we have not encountered the issue during development.

Before are the details :

firebaseBomVersion = "30.5.0"

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.inappmessaging.model.MessageType com.google.firebase.inappmessaging.model.InAppMessage.getMessageType()' on a null object reference
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.extractActions(FirebaseInAppMessagingDisplay.java:437)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.inflateBinding(FirebaseInAppMessagingDisplay.java:308)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$000(FirebaseInAppMessagingDisplay.java:79)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$1.run(FirebaseInAppMessagingDisplay.java:286)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by argzdev** [comment] 2023-02-09 13:06
Thanks for reporting, @Ashishlearn123. This seems to be a duplicate of #4214. That said, while we investigate this further. Kindly leave a thumbs up on that author's post. So that we can track the issue and prioritize a deeper investigation depending on severity. 

I'll close this issue since this is a duplicate. Thanks!

**Closed by argzdev** 2023-02-09 13:06 UTC
Labels: api: inappmessaging
