### ISSUE TITLE
Native C++ App with latest Firebase Android and C++ SDK crashes startup and also resuming

### ISSUE THREAD

**Issue by max-critcrew** [firebase/firebase-android-sdk#3408] opened 2022-02-05 09:46 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:   Android Studio Bumblebee | 2021.1.1
  * Firebase Component: Dynamic Links
  * Component version: C++ SDK 8.9.0 for the native part of the app, otherwise these Android SDKs:

    implementation 'com.google.firebase:firebase-invites:17.0.0'
    implementation 'com.google.firebase:firebase-iid:21.1.0'
    implementation 'com.google.firebase:firebase-messaging:23.0.0'
    implementation 'com.google.firebase:firebase-analytics:20.0.2'

### [REQUIRED] Step 3: Describe the problem

We're using Firebase for dynamic links. We updated to the latest C++ and Java SDKs in order to support Android target 30, upgrade gradle etc. Now when launching the app and creating the firebase app in C++ Code, it is crashing, due to a null intent. We fixed this by setting a new intent to the activity before creating the C++ firebase app - but now it crashed on resuming the app.

Here's the stacktrace:

```
2022-02-05 10:24:47.815 18964-18964/com.forestringgames.apps.towerduel E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.forestringgames.apps.towerduel, PID: 18964
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getDataString()' on a null object reference
        at com.google.firebase.dynamiclinks.internal.zze.getDynamicLink(Unknown Source:10)
        at com.google.firebase.dynamiclinks.internal.cpp.DynamicLinksNativeWrapper$1.run(DynamicLinksNativeWrapper.java:75)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

We now found a "fix" for the issue by overriding getIntent in our activity like this:

```
    @Override
    public Intent getIntent()
    {
        //================================================================================
        // Fix crashes
        //================================================================================
        if (super.getIntent() == null)
        {
            this.setIntent(new Intent());
        }

        return super.getIntent();
    }
```

This is quite ugly, but the app runs perfectly fine with it.

#### Steps to reproduce:

Install the latest firebase C++ SDK + Java SDK, then tab in/out of the app and it crashes 100% of the time.

#### Relevant Code:

C++ Part:

This code worked perfectly fine before updating to the latest Firebase SDK, now it crashes 100% of the time:
```
        _firebaseApp = firebase::App::Create(firebase::AppOptions(), cocos2d::JniHelper::getEnv(), cocos2d::JniHelper::getActivity());
        firebase::dynamic_links::Initialize(*_firebaseApp, this);
```

Java Part:

`        FirebaseApp.initializeApp(this.getApplicationContext());
`

**Comment by max-critcrew** [comment] 2022-02-08 10:50
@argzdev Sorry, we're having quite tight deadlines with clients right now and won't manage to set something up. What we basically did is have a C++ Cocos2d-x project with the latest C++ firebase SDK and the latest Java SDK. Then it crashes every time.

**Comment by argzdev** [comment] 2022-02-10 15:10
Hi @max-critcrew, upon initial investigation it looks like your issue is mainly on the C++ component. I'm not sure where the issue exactly lies since it's difficult to investigate without an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) of your issue. With that said, could you file a new ticket at our [firebase-cpp-sdk](https://github.com/firebase/firebase-cpp-sdk/issues), they will be able to assist and help you better with your issue.

I'll be closing this issue for now. Thanks!

**Closed by argzdev** 2022-02-10 15:10 UTC
Labels: api: dynamiclinks, needs-attention
