### ISSUE TITLE
Tasks circular dependency in `firebase-crashlytics-gradle` 3.0.0 when databinding enabled

### ISSUE THREAD

**Issue by sergei-lapin** [firebase/firebase-android-sdk#5940] opened 2024-05-08 10:05 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Jellyfish 2023.3.1
  * Firebase Component: firebase-crashlytics-gradle 
  * Component version: 3.0.0

### [REQUIRED] Step 3: Describe the problem

Trying to update `firebase-crashlytics-gradle` from 2.9.9 to 3.0.0 in a project with databinding enabled (analyzing Gradle output it seems to be related) and receiving this while trying to assemble an APK:

```
Circular dependency between the following tasks:
:app:dataBindingGenBaseClassesDebug
+--- :app:mergeDebugResources
|    \--- :app:injectCrashlyticsMappingFileIdDebug
|         \--- :app:dataBindingGenBaseClassesDebug (*)
\--- :app:parseDebugLocalResources
     \--- :app:packageDebugResources
          \--- :app:injectCrashlyticsMappingFileIdDebug (*)
(*) - details omitted (listed previously)
```

#### Steps to reproduce:

Update project with databinding from 2.9.9 to 3.0.0

**Comment by lehcar09** [comment] 2024-05-08 12:46
Hi @sergei-lapin, thank you for reaching out. This is duplicate of issue #5925. 

Per https://github.com/firebase/firebase-android-sdk/issues/5925#issuecomment-2098586623, the fix (v3.0.1) will be released in the next couple days. For now, you can try the latest changes from the pre-release build https://github.com/firebase/firebase-android-sdk/issues/5733.

**Closed by lehcar09** 2024-05-08 12:46 UTC
Labels: api: crashlytics
