### ISSUE TITLE
What is tha android firestore sdk get() and set() method timeout and how we can increase this timeout during calling get set method for slow internet connection.

### ISSUE THREAD

**Issue by rajnesh-culturealley** [firebase/firebase-android-sdk#1586] opened 2020-05-22 07:12 UTC
## What feature would you like to see?
Android Firestore read write timeout.
Describe the feature you would like to add, ideally proposing a specific API.

## How would you use it?
We are using to addSnapshotListener but it is not called sometimes when internet connection is slow (may request not completed due to timeout)
Tell us how you'd use this feature in your app.
There is any option to increase read write timeout.

**Comment by ashwinraghav** [comment] 2020-05-26 17:04
Duplicate of #565

**Closed by ashwinraghav** 2020-05-26 17:04 UTC
Labels: api: firestore, needs-triage
