### ISSUE TITLE
It's not possible instantiate Crashlytics with custom API_KEY

### ISSUE THREAD

**Issue by mtrakal** [firebase/firebase-android-sdk#1801] opened 2020-07-21 18:47 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Not relevant, 4.0.1
  * Firebase Component: Crashlytics
  * Component version: 17.1.0

### [REQUIRED] Step 3: Describe the problem
We need to log eveythig expect crashes / performance to **Project ONE (owned by contracting authority)** and Crashlytics / performance to **Project TWO (owned by contractor)**.
Until we migrate to FirebaseCrashlytics and used Fabric 2.10.1, it works as expected. Analytics and everythig initialized by google-services.json was logged to Project ONE, but Crashlytics (maybe using still `com.crashlytics.ApiKey` from AndroidManifest) was logged to Project TWO.

#### Steps to reproduce:
- use old Fabric Crashlytics v 2.10.1 and log to Project TWO, but in google-services.json have another project Project ONE api key from which you use RemoteConfig, Authentications, etc...
- migrate to FirebaseCrashlytics and it start logging crashlytics to Project ONE instead of Project TWO.

What happened? How can we make the problem occur?

#### Relevant Code:
```
-            Fabric.with(this, Crashlytics())
+            FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true)
```

**Comment by mtrakal** [comment] 2020-07-21 18:51
I expect possibility like this, when there is possible use `FirebaseOptions.Builder().` but there is no way, how to force FirebaseCrashlytics use second instance of Firebase...

```
            FirebaseApp.initializeApp(this)

            val secondFirebase = FirebaseOptions.Builder().setApiKey("some_api_key").build()
            FirebaseApp.initializeApp(this, secondFirebase, "secondFirebase")
            FirebaseCrashlytics.getInstance("NEED_TO_SPECIFY_FIREBASEAPP").setCrashlyticsCollectionEnabled(true)
```

**Comment by ashwinraghav** [comment] 2020-07-21 21:56
Thanks for the report. This is a duplicate of https://github.com/firebase/firebase-android-sdk/issues/66. Closing this in favor of that issue. Please upvote there instead.

**Closed by ashwinraghav** 2020-07-21 21:56 UTC
Labels: api: crashlytics
