### ISSUE TITLE
CI frequently fails due to errors fetching maven dependencies (perhaps a general networking issue though?).

### ISSUE THREAD

**Issue by mikelehen** [firebase/firebase-android-sdk#78] opened 2018-10-18 00:01 UTC
See for example https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/76/smoke-tests-debug/1052700842647359491/:

```
W1017 23:22:18.094] Could not resolve all files for configuration ':buildSrc:runtimeClasspath'.
W1017 23:22:18.094] > Could not download sdk-common.jar (com.android.tools:sdk-common:26.0.1)
W1017 23:22:18.094]    > Could not get resource 'https://maven.google.com/com/android/tools/sdk-common/26.0.1/sdk-common-26.0.1.jar'.
W1017 23:22:18.095]       > Connection reset
```

Based on other flakes, I wonder if there's general network unreliability in the CI environment.

**Comment by samtstern** [comment] 2018-10-18 15:54
This may not be related, but in my own experience I have seen some gradle versions time out when talking to `maven.google.com` a lot, but upgrading to the latest gradle/gradlew version fixed it for me.

**Comment by gsoltis** [comment] 2018-11-27 22:42
Another one: https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/68/smoke-tests-release/1067542178768621568/

**Comment by mikelehen** [comment] 2019-02-01 00:49
Seems these still happen...?  https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/226/smoke-tests-release/1091131208982597632/

```
W0201 00:36:20.602] Execution failed for task ':firebase-database-collection:downloadLicenses'.
W0201 00:36:20.602] > java.net.SocketTimeoutException: Read timed out
```

**Comment by vkryachko** [comment] 2019-02-01 14:45
@ashwinraghav Looks like the flakiness is caused by license download, can we somehow cache them or store the most wide-spread ones in the repo?

**Comment by vkryachko** [comment] 2019-05-22 17:25
Since this was only a problem in the old smoke tests - which are no longer around - closing this issue.
Feel free to re-open if this happens again.

**Closed by vkryachko** 2019-05-22 17:25 UTC
Labels: ci-flakiness
