### ISSUE TITLE
Crash after calling task.getResult().getToken() - IllegalArgumentException: method POST must have a request body.

### ISSUE THREAD

**Issue by grebulon** [firebase/firebase-android-sdk#1540] opened 2020-05-11 08:48 UTC
### [READ] Step 1: Are you in the right place?
yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.1
  * Firebase Component: firebase-messaging
  * Component version: 20.1.7

### [REQUIRED] Step 3: Describe the problem

Sometimes, after calling `task.getResult().getToken()` my app crashes with the following stack.
This happens occasionally, usually once a week. After that the app keeps crashing on startup and the only thing that stops it from crashing is to **delete the cache** from Android's app settings.
I suspect it has to do with caching of the token because after cleaning the cache will make the problem goes away (until the next cache refresh)

```
java.lang.IllegalArgumentException: method POST must have a request body.
com.android.okhttp.Request$Builder.method(Request.java:267)
com.android.okhttp.internal.huc.JavaApiConverter.createOkResponseForCacheGet(JavaApiConverter.java:216)
com.android.okhttp.internal.huc.CacheAdapter.get(CacheAdapter.java:53)
com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:316)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:483)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:135)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:266)
com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeRequestBodyToOutputStream(com.google.firebase:firebase-installations@@16.3.0:208)
com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeGenerateAuthTokenRequestBodyToOutputStream(com.google.firebase:firebase-installations@@16.3.0:248)
com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(com.google.firebase:firebase-installations@@16.3.0:369)
com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(com.google.firebase:firebase-installations@@16.3.0:471)
com.google.firebase.installations.FirebaseInstallations.doNetworkCall(com.google.firebase:firebase-installations@@16.3.0:342)
com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationInternal$0(com.google.firebase:firebase-installations@@16.3.0:330)
com.google.firebase.installations.FirebaseInstallations$$Lambda$5.run(Unknown Source:4)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:919)
```
Note that I'm using **okhttp 3.12.10** - the latest version that supports Android 4.4 (API 19). In okhttp 4.0, the code that throws this error is gone.
Looking in the okhttp source code, it seems that the problem is just as the error message says: FirebaseInstallationServiceClient is posting with `body == null`. I'd look in `FirebaseInstallationServiceClient.writeGenerateAuthTokenRequestBodyToOutputStream` but the source code is not in this git repository.

In my various emails with Firebase support they hinted that some of the initialization options are missing (API key, Project ID, etc.) but I'm using the automatic initialization with the gradle plugin and google-services.json exactly as described in the docs. Furthermore, I validated that the info from google-services.json is merged into the apk's resources and that firebase is initialized properly (by calling FirebaseApp.initializeApp() which lead to a log stating: "FirebaseApp name [DEFAULT] already exists!"

#### Steps to reproduce:

First you need to compile with okhttp 3.12.10 (any 3.12.x will do)
```
dependencies {
  implementation("com.squareup.okhttp3:okhttp:3.12.10")
}
```
Then call `task.getResult().getToken()` as in the code below.
Run it for some time, probably several times every day for a week, and it will probably happen. I think this has to do with caching of the token because after this crashes, it will keep on crashing until you clear the cache.

#### Relevant Code:
```
FirebaseInstanceId.getInstance().getInstanceId().addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
    @Override
    public void onComplete(@NonNull Task<InstanceIdResult> task) {
        if (!task.isSuccessful()) {
            return;
        }
        String token = task.getResult().getToken();
    }
});
```

**Comment by andirayo** [comment] 2020-05-11 16:55
@grebulon : 
Thank you for reporting this!

It seems like the Firebase Installations's weekly `#GenerateAuthToken` call is triggering this issue.
We will look into this!

**Question**: What percentage of end-users is affected or are all affected?

FYI:
* As a temporary fix for this you can downgrade `firebase-messaging` to `v20.1.0` **or before**.
* `FirebaseInstallationServiceClient.writeGenerateAuthTokenRequestBodyToOutputStream` is part of this repository: https://github.com/firebase/firebase-android-sdk/blob/9eb88b11811ceed30de571435044201ca60ef262/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java#L246
* Upon quick search I could find this Github issue of the OkHttp library that seems to still affect developers in 2019: https://github.com/square/retrofit/issues/854. But nevertheless there seems to be a weird behavior that we will look into.

**Comment by ankitaj224** [comment] 2020-05-11 23:54
@grebulon Thanks for all the details on reproducing this issue.

Have you enabled [HttpResponseCaching](https://developer.android.com/reference/android/net/http/HttpResponseCache) in your app?

**Comment by grebulon** [comment] 2020-05-12 08:05
@andirayo, this effects many users. I've had around to 500 of reports on this from my automated crash reporting code in the past 3 weeks. That's only from people who chose to report. I think that in the end it will affect ALL users.
I saw the reports on the retrofit issue, but it doesn't seem related to this issue.
I will downgrade to 20.1.0 and see if that helps.

@ankitaj224 HttpResponseCache is not enabled.

Thank you for looking into this.

**Comment by ankitaj224** [comment] 2020-05-13 02:06
@grebulon Are you able to reproduce this issue consistently ? And if there is a demo app, can you please share the link which I can use to test.

**Comment by grebulon** [comment] 2020-05-13 13:05
@ankitaj224 Not consistently. But I have enough users to push an update and wait for the next cache invalidation (which usually happens on weekends) and see if this helps.
Do you think that it's enough to just disable the httpURLConnection cache?

**Comment by ankitaj224** [comment] 2020-05-14 22:04
@grebulon 
Most likely. I am still reading about the Okhttp underlying caching in Android.  Disabling the httpURLConnection cache along with explicit Cache-control should help. I am trying to reproduce the issue and try this fix.

Do you use initialize Okhttp client with a cache in your app?

**Comment by grebulon** [comment] 2020-05-15 08:55
I don't do anything explicit with the connection cache, so it must be using the default state.
I downgraded as andirayo suggested to v20.0 in my beta group and haven't seen any crashes from there.
But there's something that may be troubling - I have a debug report call in my code that I trigger when FirebaseMessagingService#onNewToken() is called and I haven't seen this happen even once for any of my users. I also trigger a report when a token changes after calling task.getResult().getToken() - which happens but very rarely.
What's the lifetime of these tokens? How often do they change?

**Comment by andirayo** [comment] 2020-05-17 19:05
FCM registration tokens are constant for the lifetime of installations of your application, unless FCM has a reason to update the tokens.
Thus, not getting reports about tokens changing is nothing to worry about.

**Question**: Did this behavior change for you?

**Comment by grebulon** [comment] 2020-05-18 06:00
That's OK as I'm not seeing tokens being replaced, and I'm not getting any more of the crashes after downgrading.
Drop me a note after releasing the caching change, and I'll test it on my beta group.

**Comment by ankitaj224** [comment] 2020-06-17 01:02
@grebulon firebase-messaging: 20.2.1 will be released by this week (June 19 2020) that should contain caching fix. Please try releasing the app with the latest version and let me know if it fixes the issue. 

Thank you for testing out the fix.

**Comment by grebulon** [comment] 2020-06-25 09:58
Just to let you know that I can't do the test right now, but I'm on it and will test as soon as my release timeline has a free slot.

**Comment by ankitaj224** [comment] 2020-06-25 19:25
Thanks @grebulon . Looking forward to hearing how the tests go.

**Comment by grebulon** [comment] 2020-07-02 09:26
Hello Ankita (and googlebot)
I've deployed a beta of our app to a group of ~600 people and already got ~40 token change event notices so it seems to be working fine. But I'd give it another week or two to make sure that everything is fine.

**Comment by ankitaj224** [comment] 2020-07-06 17:36
@grebulon  Thanks for the information. Keep us posted on your beta release results.

**Comment by grebulon** [comment] 2020-07-12 08:27
I think it's safe to say that this bug is fixed. I'm still running the new version in a beta group of a few hundreds and if there's another problem I will report. Thank you for handling this so professionally.

**Comment by ankitaj224** [comment] 2020-07-13 21:22
Thanks for the confirmation @grebulon . I will go ahead and close this issue for now. Please feel free to reopen if you continue to see the issue.

**Closed by ankitaj224** 2020-07-13 21:22 UTC
Labels: firebase-installations, needs-attention
