### ISSUE TITLE
No Crashlytics data in Firebase when moving from Fabric

### ISSUE THREAD

**Issue by szaske** [firebase/firebase-android-sdk#2828] opened 2021-07-13 18:33 UTC
### [REQUIRED] Step 2: Describe your environment
Android Studio 4.2.2
Firebase bom 28.2.1

### [REQUIRED] Step 3: Describe the problem
Like many others here I am unable to get Crashlytics data to appear in my project after moving from Fabric. I've followed ever bit of advise I can find here in your issues sections and in SO. Nothing seems to work. The thing that concerns me is that I see in logcat the following line:

"2021-07-13 11:08:31.264 22650-22650/com.my.package D/FirebaseCrashlytics: Loaded cached settings: {"settings_version":3,"cache_duration":86400,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":false,"prompt_enabled":false,"push_enabled":false,"firebase_crashlytics_enabled":false,"collect_anrs":false},"app":{"status":"activated","update_required":false,"report_upload_variant":2,"native_report_upload_variant":2},"fabric":{"org_id":"ORG_ID_HERE","bundle_id":"com.my.package"},"expires_at":1626279221179}

How can I clear these "cached settings"? They're pointing to my Fabric and I've cleared all local mentions of Fabric. I'm not sure if this is causing my problem, but it's definitely suspicious.

#### Steps to reproduce:
Follow instructions to get Firebase & Crashlytics installed in my Android app. Create a test crash in my app and make it happen. Visit my Crashlytics dashboard for my project and see that it's still waiting for data.  BTW, I can get Firebase Performance data to appear in the dashboard, just not Crashlytics.

**Comment by aguatno** [comment] 2021-07-21 13:45
Hi @szaske Looking at the logs you shared, it seems that the SDK was not able to find any crashes to be reported. I would love to dig deeper into this with you. The first thing I would like to confirm is how this was tested. Did you do the following?

- Enable debug mode in the app
- Build/run the app and then cause a [test crash](https://firebase.google.com/docs/crashlytics/test-implementation?platform=android)
- Restart the app (the SDK will try to send the reports when restarting the app after a crash)
- Collect the logs

If you are seeing the same behavior, the next step would be to try isolating this issue by reproducing this with a minimal sample. For this, you could use our [sample](https://github.com/firebase/quickstart-android/tree/master/crash) with your goog-services.json file and package name.

**Comment by dimsuz** [comment] 2021-07-22 10:46
We also have this issue: crashes do not appear in Firebase Console.

I have tried your suggestion and the crash sent by the sample app is sent, shown and processed.
But other crashes we have do not.

It seems that Crashlytics itself crashes wile processing the stacktrace. Here's a log of a crash which seems to be sent, but it never gets shown in the console:

```
         mobile.interna  I  Background concurrent copying GC freed 101457(4MB) AllocSpace objects, 19(380KB) LOS objects, 48% free, 6MB/12MB, paused 1.941ms total 111.299ms
untime.SQLiteEventStore  D  Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
untime.JobInfoScheduler  D  Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMD
                            lyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=-731891974 in 1000ms(Backend next call timestamp 0). Attempt 1
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: ru.kode.dominvest.mobile.internal, PID: 13754
                         E  io.reactivex.exceptions.CompositeException: 2 exceptions occurred.
                         E      at io.reactivex.internal.observers.LambdaObserver.b(LambdaObserver.java:5)
                         E      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.j(ObservableObserveOn.java:11)
                         E      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:18)
                         E      at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:1)
                         E      at android.os.Handler.handleCallback(Handler.java:873)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loop(Looper.java:193)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6669)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                         E    ComposedException 1 :
                         E      java.lang.RuntimeException: crashlytics test
                         E          at ru.kode.dominvest.mobile.portfolio.ui.main.PortfolioMainPresenter$buildMachine$26$1.I(PortfolioMainPresenter.kt:3)
                         E          at ru.dimsuz.unicorn.reactivex.MachineConfigKt$buildActions$1$1.I(MachineConfig.kt:2)
                         E          at ru.dimsuz.unicorn.reactivex.MachineBuilderKt$reduceActions$$inlined$let$lambda$1.call(MachineBuilder.kt:3)
                         E          at io.reactivex.internal.operators.single.SingleFromCallable.d(SingleFromCallable.java:5)
                         E          at io.reactivex.Single.a(Single.java:2)
                         E          at io.reactivex.internal.operators.single.SingleDoAfterSuccess.d(SingleDoAfterSuccess.java:1)
                         E          at io.reactivex.Single.a(Single.java:2)
                         E          at io.reactivex.internal.operators.completable.CompletableFromSingle.e(CompletableFromSingle.java:1)
                         E          at io.reactivex.Completable.a(Completable.java:2)
                         E          at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:1)
                         E          at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:1)
                         E          at android.os.Handler.handleCallback(Handler.java:873)
                         E          at android.os.Handler.dispatchMessage(Handler.java:99)
                         E          at android.os.Looper.loop(Looper.java:193)
                         E          at android.app.ActivityThread.main(ActivityThread.java:6669)
                         E          at java.lang.reflect.Method.invoke(Native Method)
                         E          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                         E          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                         E      Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
                         E          at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:5)
                         E          at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.c(SessionReportingCoordinator.java:4)
                         E          at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:15)
                         E          at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.b(CrashlyticsBackgroundWorker.java:1)
                         E          at com.google.android.gms.tasks.zzf.run(Unknown Source:3)
                         E          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E          at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.a(ExecutorUtils.java:1)
                         E          at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:2)
                         E          at java.lang.Thread.run(Thread.java:764)
                         E    ComposedException 2 :
                         E      java.lang.IllegalStateException: exception while reducing view state
                         E          at w0.b.e(Unknown Source:7)
                         E          at io.reactivex.internal.observers.LambdaObserver.b(LambdaObserver.java:3)
                         E          at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.j(ObservableObserveOn.java:11)
                         E          at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:18)
                         E          at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:1)
                         E          at android.os.Handler.handleCallback(Handler.java:873)
                         E          at android.os.Handler.dispatchMessage(Handler.java:99)
                         E          at android.os.Looper.loop(Looper.java:193)
                         E          at android.app.ActivityThread.main(ActivityThread.java:6669)
                         E          at java.lang.reflect.Method.invoke(Native Method)
                         E          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                         E          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                         E      Caused by: java.lang.RuntimeException: crashlytics test
                         E          at ru.kode.dominvest.mobile.portfolio.ui.main.PortfolioMainPresenter$buildMachine$26$1.I(PortfolioMainPresenter.kt:3)
                         E          at ru.dimsuz.unicorn.reactivex.MachineConfigKt$buildActions$1$1.I(MachineConfig.kt:2)
                         E          at ru.dimsuz.unicorn.reactivex.MachineBuilderKt$reduceActions$$inlined$let$lambda$1.call(MachineBuilder.kt:3)
                         E          at io.reactivex.internal.operators.single.SingleFromCallable.d(SingleFromCallable.java:5)
                         E          at io.reactivex.Single.a(Single.java:2)
                         E          at io.reactivex.internal.operators.single.SingleDoAfterSuccess.d(SingleDoAfterSuccess.java:1)
                         E          at io.reactivex.Single.a(Single.java:2)
                         E          at io.reactivex.internal.operators.completable.CompletableFromSingle.e(CompletableFromSingle.java:1)
                         E          at io.reactivex.Completable.a(Completable.java:2)
                         E          at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:1)
                         E          at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:1)
                         E          at android.os.Handler.handleCallback(Handler.java:873)
                         E          at android.os.Handler.dispatchMessage(Handler.java:99)
                         E          at android.os.Looper.loop(Looper.java:193)
                         E          at android.app.ActivityThread.main(ActivityThread.java:6669)
                         E          at java.lang.reflect.Method.invoke(Native Method)
                         E          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                         E          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                         E      Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
                         E          at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:5)
                         E          at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.c(SessionReportingCoordinator.java:4)
                         E          at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:15)
                         E          at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.b(CrashlyticsBackgroundWorker.java:1)
                         E          at com.google.android.gms.tasks.zzf.run(Unknown Source:3)
                         E          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E          at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.a(ExecutorUtils.java:1)
                         E          at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:2)
                         E          at java.lang.Thread.run(Thread.java:764)
                Process  I  Sending signal. PID: 13754 SIG: 9

                            Process ru.kode.dominvest.mobile.internal created for service ru.kode.dominvest.mobile.internal/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerServ
                            ice
                            PID: 13862   UID:    GIDs: 

         mobile.interna  E  Not starting debugger since process cannot load the jdwp agent.
            FirebaseApp  I  Device unlocked: initializing all Firebase APIs for app [DEFAULT]
    FirebaseCrashlytics  I  Initializing Firebase Crashlytics 18.1.0 for ru.kode.dominvest.mobile.internal
untime.JobInfoScheduler  D  Upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIO
                            UZZZGVpU25VVE92Mk0=) is already scheduled. Returning...
         mobile.interna  W  Unsupported class loader
                         W  Skipping duplicate class check due to unsupported classloader
         DynamiteModule  I  Considering local module com.google.android.gms.measurement.dynamite:51 and remote module com.google.android.gms.measurement.dynamite:51
                         I  Selected remote version of com.google.android.gms.measurement.dynamite, version >= 51
                         V  Dynamite loader version >= 2, using loadModule2NoCrashUtils
         mobile.interna  W  Unknown chunk type '200'.
   FirebaseInitProvider  I  FirebaseApp initialization successful
         mobile.interna  W  Unsupported class loader
 ```

Notice how this trace has Crashlytics' `TrimmedThrowableData.java` as the origin at the bottom

**Comment by dimsuz** [comment] 2021-07-29 09:43
Information is presented above, see my last comment with the stacktrace of the crash.

**Comment by szaske** [comment] 2021-07-29 15:46
It appears my overzealous router firewall (pfBlockerNG) was blocking Crashlytics. So you can close this ticket. I would however be interested in getting the list of Crashlytic DNS entries so I can whitelist them. If it's not too much trouble.

**Comment by aguatno** [comment] 2021-07-30 15:42
Thanks for the update @szaske. I'll be closing this now.

@dimsuz if everything looks good on your end, then something odd is happening with Firebase Console why Crashlytics is not showing logs. I would suggest reaching out to Firebase support so they can help you troubleshoot. Otherwise Feel free to open a new issue.

**Closed by aguatno** 2021-07-30 15:42 UTC
Labels: api: crashlytics, needs-attention

**Comment by dimsuz** [comment] 2021-07-30 20:02
@aguatno thanks. I can see in the Console crashes I report using `recordException`, but none other. Each of those I cannot see generates the stacktrace I've posted above.

Just to be clear, can you confirm that this part of the abvoe trace is OK to have:

```
at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:5)
at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.c(SessionReportingCoordinator.java:4)
at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:15)
```
because it led me to believe that something odd is in firebase crashlytics _library_. 
It looks like it fails during report sending.
