### ISSUE TITLE
[Crashlytics] uploadCrashlyticsSymbolFileRelease failed with response code 500

### ISSUE THREAD

**Issue by ninh-huynh** [firebase/firebase-android-sdk#5073] opened 2023-06-09 15:13 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Firebase Component: Firebase Crashlytics, Google Services
  * Component version: 2.9.4, 4.3.15

### [REQUIRED] Step 3: Describe the problem

Recently, we receive this error on CI environment. Sometimes, retrying the job will fix it but right now, it happens more frequently. This failure impacts our developer a lot in the build process.

#### Steps to reproduce:

Build apk/bundle normally and then call uploadCrashlyticsSymbol:

`
./gradlew uploadCrashlyticsSymbolFileRelease
`

![image](https://github.com/firebase/firebase-android-sdk/assets/28674990/e425ee6a-8599-47de-bd90-d8dcb4879af3)

**Comment by Mr-S-Mirzoev** [comment] 2023-06-12 14:52
Upvote, this recently started happening in our application too.

**Comment by HPNavjot** [comment] 2023-06-13 09:47
Upvote, we faced this issue intermittently on Jun 9, 2023 (first occurrence at 4:30 AM GMT+5:30). But now we are facing this issue with every build.

**Comment by argzdev** [comment] 2023-06-13 10:04
Hi all, not sure if this is related to #4682. There was a recent fix on a bug in capturing build IDs on clean builds when `unstrippedNativeLibsPath` is overridden. Could you try testing with `com.google.firebase:firebase-crashlytics-gradle` version `2.9.5` and see if that makes any difference? Thanks.

**Comment by RobinVanina** [comment] 2023-06-13 21:13
We are facing the same issue as well. Occurred the first time 3 days ago

**Comment by argzdev** [comment] 2023-06-14 11:37
I was able to reproduce the same behavior, let me notify our engineers and see what we can do here.

**Comment by argzdev** [comment] 2023-06-14 16:53
Hi all, it was noted by our engineers that this was a backend issue and not an issue on the SDK or build tool. They are aware of this bug and was able to confirm that it's been fixed just a while ago. That said, I'll close this issue now. Feel free to let me know if the issue is still present and I'll reopen the thread. Thanks!

**Closed by argzdev** 2023-06-14 16:53 UTC
Labels: type: bug, api: crashlytics

**Comment by eric-sofisoftwarellc** [comment] 2023-06-22 23:14
Still happening, ptal

`Caused by: java.io.IOException: Unknown error while sending file, check network [/builds/c9q6Rc8f/0/mobile/android/[abc]/app/build/crashlytics/release/nativeSymbols/crashlytics-trampoline-arm64-995e64a260d8ec583d833cb5c4372182a0e06934.gz; response: 500 HTTP/1.1 500 Internal Server Error]
	at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.sendFile(RestfulWebApi.java:109)
...
`
