### ISSUE TITLE
NullPointerException on FirebaseInstallations.registerFidWithServer

### ISSUE THREAD

**Issue by francescocervone** [firebase/firebase-android-sdk#1787] opened 2020-07-20 10:57 UTC
### Environment

  * Android Studio version: `3.6.3`
  * Firebase Component: `firebase-analytics`, `firebase-messaging`, `firebase-config`, `firebase-crashlytics` -> `firebase-installations`
  * Component version: `firebase-analytics:17.4.3`, `firebase-messaging:20.2.1`, `firebase-config:19.1.4`, `firebase-crashlytics:17.1.0` -> `firebase-installations:16.3.2`

### Description
Crashlytics reported some crashes on some OnePlus 6 devices with Android 10 on 19/07/2020.

#### Stacktrace
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:452)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:331)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doGetId$1(FirebaseInstallations.java:296)
       at com.google.firebase.installations.FirebaseInstallations$$Lambda$3.run(FirebaseInstallations.java:2000)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by searchy2** [comment] 2020-07-24 21:28
Is this caused by clearing SharedPreferences?
```
    val sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context)
    sharedPreferences.edit().clear().commit()
```
After clearing SharedPreferences, this crash might happen.

**Comment by nedols** [comment] 2020-07-27 13:35
Same issue.

Below dependencies used in my project. 

```
def firebase_messagging = "20.2.3"
implementation "com.google.firebase:firebase-messaging:$firebase_messagging"

def firebase_config = "19.2.0"
implementation ("com.google.firebase:firebase-config:$firebase_config", {
        exclude group: 'com.google.protobuf'
}) // fixme: see issue still present at https://github.com/firebase/firebase-android-sdk/issues/1143

def firebase_auth = "19.3.2"
implementation "com.google.firebase:firebase-auth-ktx:$firebase_auth"

def realtime_database = "19.3.1"
implementation "com.google.firebase:firebase-database:$realtime_database"

def firebase_functions = "19.0.2"
implementation "com.google.firebase:firebase-functions-ktx:$firebase_functions"

def firestore_ktx = "21.1.1"
implementation "com.google.firebase:firebase-firestore-ktx:$firestore_ktx"

def firebase_analytics = "17.4.4"
implementation "com.google.firebase:firebase-analytics-ktx:$firebase_analytics"

def firebase_crashlytics = "17.1.1"
implementation "com.google.firebase:firebase-crashlytics:$firebase_crashlytics"

def firebase_appindexing = "19.1.0"
implementation "com.google.firebase:firebase-appindexing:$firebase_appindexing"

```

and stacktrace:

```
FATAL EXCEPTION: firebase-installations-executor-1
    Process: <my package id>, PID: 1690
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:452)
        at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:331)
        at com.google.firebase.installations.FirebaseInstallations.lambda$doGetId$1(FirebaseInstallations.java:296)
        at com.google.firebase.installations.FirebaseInstallations$$Lambda$3.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by wugeo0824** [comment] 2020-07-28 12:28
Anything we can do to temporarily stop this crash from happening?

**Comment by ankitaj224** [comment] 2020-07-28 21:20
@searchy2 That's highly likely. Do you or others who are reporting crash clear the shared prefs?

@wugeo0824 We are rolling out a fix this week which should be released either by Friday or Monday next week. Updating to the latest version of FCM releasing this week should fix the issue.

**Comment by StainlessStlRat** [comment] 2020-07-29 20:40
> Is this caused by clearing SharedPreferences?
> 
> ```
>     val sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context)
>     sharedPreferences.edit().clear().commit()
> ```
> 
> After clearing SharedPreferences, this crash might happen.

This crash did start popping up for me after I renamed a shared preference value.

**Comment by rvijayraghavan** [comment] 2020-07-30 13:55
@ankitaj224 We are noticing this issue on a new app install. Looking forward to the library update with the fix.

**Comment by lucas34** [comment] 2020-08-03 03:51
Is this issue fixed ? It's mentioned in the latest release note but the ticket is still open 
https://firebase.google.com/support/release-notes/android#installations_v16-3-2

**Comment by calvarez-ov** [comment] 2020-08-03 07:50
We have version 16.3.2, and we have this crash. So it's weird that it's mentioned as a fix in 16.3.2. Note that 16.3.2 is also the version mentioned in the description of this ticket.

**Comment by lucas34** [comment] 2020-08-03 08:14
Looks like a typo in the release note. 16.3.2 was rollout awhile ago. I'm trying to update to 16.3.3 to see if it fix.

**Comment by ankitaj224** [comment] 2020-08-03 15:55
@lucas34 You are right, that's a typo. Thanks for catching it, we will fix the release notes in a short while. firebase-installations:16.3.3 or firebase-messaging:20.2.4 contain the probable fix.

**Comment by ankitaj224** [comment] 2020-08-11 17:30
Please let us know if anyone has tried out the fix.

**Comment by menting311** [comment] 2020-08-12 19:59
@ankitaj224  - I am confused..the current version of crashlytics is firebase-crashlytics:17.1.1. How do we use firebase-installations if we are using the crashlytics SDK?

**Comment by ankitaj224** [comment] 2020-08-12 21:00
@menting311 Thanks for reaching out & sorry for the confusion. You have two options:

1. Add a direct dependency on firebase-installations:16.3.3 in your app.
2. Or await for Crashlytics new release which is planned for this week ( ~ Aug 13th).

**Comment by lucas34** [comment] 2020-08-13 02:52
We updated to 16.3.3 and it solved the issue. Thanks !

**Comment by ankitaj224** [comment] 2020-08-13 17:20
@lucas34 Thank you so much for confirming.

I will go ahead and close this issue. Please feel free to reach out if you continue to see this issue.

**Closed by ankitaj224** 2020-08-13 17:20 UTC
Labels: firebase-installations, needs-info

**Comment by menting311** [comment] 2020-08-18 18:23
@ankitaj224  - So is this fix in crashlytics 17.2.1? I was looking at the release notes on this and I am not seeing anything referring to this?

https://firebase.google.com/support/release-notes/android#crashlytics_v17-2-1

**Comment by ankitaj224** [comment] 2020-08-19 00:35
@menting311 Yes, crashlytics 17.2.1 transitively get this fix as it depends on firebase-installations:16.3.3. https://firebase.google.com/support/release-notes/android#installations_v16-3-3

**Comment by MahdiYusefi** [comment] 2020-08-19 12:43
it's been two days that this crash happens in crashlytics:17.1.1 only for android 4 meanwhile versions that contains 17.1.1 its been live from about one week ago.

**Comment by ankitaj224** [comment] 2020-08-19 17:22
@MahdiYusefi Its possible probably some disk write issue. I would recommend updating to crashlytics 17.2.1 and that should fix the issue. 

Thanks.
