### ISSUE TITLE
IllegalStateException in crashlytics.prepareBaseDir

### ISSUE THREAD

**Issue by cobraapps** [firebase/firebase-android-sdk#3440] opened 2022-02-12 16:58 UTC
Had this crash reported through to Google Play console:

java.lang.RuntimeException: 
  at android.app.ActivityThread.installProvider (ActivityThread.java:7462)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:7002)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6890)
  at android.app.ActivityThread.access$1300 (ActivityThread.java:269)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2010)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7860)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1068)
Caused by: java.lang.IllegalStateException: 
  at com.google.firebase.crashlytics.internal.persistence.FileStore.prepareBaseDir (FileStore.java:188)
  at com.google.firebase.crashlytics.internal.persistence.FileStore.<init> (FileStore.java:66)
  at com.google.firebase.crashlytics.FirebaseCrashlytics.init (FirebaseCrashlytics.java:75)
  at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics (CrashlyticsRegistrar.java:57)
  at com.google.firebase.crashlytics.CrashlyticsRegistrar$$InternalSyntheticLambda$2$db162bb9be36f9206ef3c77773d22791204d3cb6279c7815312c3bc51d3b6568$0.create (CrashlyticsRegistrar.java)
  at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0 (ComponentRuntime.java:132)
  at com.google.firebase.components.ComponentRuntime$$InternalSyntheticLambda$1$562ccfbab29457946f69b904d7c620216b88cbd0fd784cee32e00ed2dcd3a60c$0.get (ComponentRuntime.java)
  at com.google.firebase.components.Lazy.get (Lazy.java:53)
  at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents (ComponentRuntime.java:291)
  at com.google.firebase.components.ComponentRuntime.initializeEagerComponents (ComponentRuntime.java:281)
  at com.google.firebase.FirebaseApp.initializeAllApis (FirebaseApp.java:584)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:303)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:267)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:252)
  at com.google.firebase.provider.FirebaseInitProvider.onCreate (FirebaseInitProvider.java:51)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2113)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2087)
  at com.google.firebase.provider.FirebaseInitProvider.attachInfo (FirebaseInitProvider.java:45)
  at android.app.ActivityThread.installProvider (ActivityThread.java:7457)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:7002)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6890)
  at android.app.ActivityThread.access$1300 (ActivityThread.java:269)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2010)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7860)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1068)

Device:
Android version 10

App build against:
com.google.firebase:firebase-crashlytics:18.2.7

**Comment by argzdev** [comment] 2022-02-14 09:40
Hi @cobraapps, thanks for your report. This looks like a duplicate of #3269. Our engineers are currently looking into it. You may continue your report there. With that said, I'll be closing this case now.

**Closed by argzdev** 2022-02-14 09:40 UTC
Labels: api: crashlytics, needs-triage
