### ISSUE TITLE
"Card model secondary action must be null or have a button" in-app campaign message crash with only primary button.

### ISSUE THREAD

**Issue by sandsaber** [firebase/firebase-android-sdk#6543] opened 2024-11-29 13:28 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Ladybug | 2024.2.1 Patch 2
  * Firebase Component: Auth, Config, Analytics, Messaging, Crashlytics, Perf, InApp Messaging Display 
  * Component version: Firebase BOM 33.4.0

### [REQUIRED] Step 3: Describe the problem
Getting plenty of crashes with Firebase in-app messaging when specify campaign which has only one primary button. 
![image](https://github.com/user-attachments/assets/bb8e76d9-b39b-4d62-a73b-a235c7ad5b73)

```
Fatal Exception: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: Card model secondary action must be null or have a button
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
       at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
       at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
       at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
       at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:224)
       at android.os.Looper.loop(Looper.java:318)
       at android.app.ActivityThread.main(ActivityThread.java:8727)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

Caused by java.lang.IllegalArgumentException: Card model secondary action must be null or have a button
       at com.google.firebase.inappmessaging.model.CardMessage$Builder.build(CardMessage.java:249)
       at com.google.firebase.inappmessaging.model.ProtoMarshallerClient.decode(ProtoMarshallerClient.java:231)
       at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager.triggeredInAppMessage(InAppMessageStreamManager.java:370)
       at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager.lambda$getTriggeredInAppMessageMaybe$27(InAppMessageStreamManager.java)
       at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess(MaybeFlatten.java:88)
       at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)
       at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:312)
       at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:174)
```

#### Steps to reproduce:
Issues happens randomly, but do happen. 
I was able to reproduce it only once per 10-30 test running via "Test on Device"
Testing campaign (nothing special, it can be random "lorem"):
![image](https://github.com/user-attachments/assets/f526f32c-d8a4-415e-ba6b-57413a4953a1)
 

1. Create a campaign, fill the data, and have only one primary button.
2. Press "test on device" and add the ID of the device which you want to test and send the test to this device. 
3. Reopen application on device to receive the campaign. (After the campaign show, press the primary button and fully close application). Repeat. 
4. Randomly, crash may appear when an application opened. (Approx in 10-20 test run, require patience to reproduce)

#### Relevant Code:

Seem like the same issues:
https://github.com/firebase/firebase-android-sdk/issues/4625
https://github.com/firebase/firebase-android-sdk/issues/4048

Full log
[com.onoffapp.app_issue_ca44ad0ed195e57cfebb658c9c40e0d8_crash_session_6748C9FD01D20001457C39C575C2C5DD_DNE_1_v2_stacktrace.txt](https://github.com/user-attachments/files/17959678/com.onoffapp.app_issue_ca44ad0ed195e57cfebb658c9c40e0d8_crash_session_6748C9FD01D20001457C39C575C2C5DD_DNE_1_v2_stacktrace.txt)

**Comment by lehcar09** [comment] 2024-11-29 20:16
Hi @sandsaber, thank you for reaching out and reporting the issue. I tried reproducing the issue with the steps you shared, however, I wasn't able to encounter any crash. By any chance, can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) and see if you can reproduce the issue?

Aside from that, does the issue occur on certain devices and/or android versions? Thanks!

**Comment by sandsaber** [comment] 2024-12-02 09:21
@lehcar09 Hi, reproducing the issue takes time and patience, it took me quite a while to do it. 
Btw, maybe it will be helpful, I reproduced the issue only on release build, via internal test (Plat Store). I took installation ID and started sending the campaign via "Test On device"  functionality. ( I was unable to test it on debug build via installation ID, never received the campaign)

If I find any details or clear steps, I will share. The issue exists, but it is challenging to reproduce it, only around 10% of our users got it, according to Crashlytics. 

According to Crashlytics, no specific device or android version. Even not specific version of in-app messages or firebase.
![image](https://github.com/user-attachments/assets/0920fb10-91de-4133-8402-5f6b6f307931)

![image](https://github.com/user-attachments/assets/cef88636-90be-4713-b527-303c6ad79a4c)

Only one step in all crashed devices, user opened application (application were closed or went to background). I reproduced via same way, I sent a campaign via "Test on Device" and then opened the application ( took me around 20 time to do that)

**Comment by sandsaber** [comment] 2024-12-02 12:02
Dear @lehcar09 I was able to reproduce the issue with 100%. 
Does not matter what kind of application, I reproduce it both in our app and in a quick in-app sample which you share.

Steps to reproduce:
1. Start creating a campaign, fill the data. (do not finish creation)
![image](https://github.com/user-attachments/assets/ef7dad85-97a0-434d-bd5f-e24308d49df4)
2. Then press on "Test on device", use specific installation ID to test, that it card message will be shown correctly. 
3. After successful display in app, please fully dismiss app from try.
4. Go back to in-app message (firebase site).
5. Press add secondary button, uncheck "Use dismiss as action" for secondary button. Put same url as primary - in my case I used - onoff-b2c://onoff.app/add-credits
Press on Secondary title and on color.
![image](https://github.com/user-attachments/assets/f48cf0ff-777a-4e8c-98ae-bfb95ae345eb)
6. Press "X" to delete secendorary button.
7. Press "test on device" and send it to your device.
8. Open application and observer crash. Please notice, if you next create a campaign, then users will receive crashes always, when in-app will try to show this campaign. 

Here the video:

https://github.com/user-attachments/assets/0c499bca-2e9a-42c1-9059-dab665b80b6c

**Comment by lehcar09** [comment] 2024-12-02 16:00
Thank you for all the details @sandsaber. Upon checking, the issue is not on the SDK side. I found a bug report about this issue. Based on the investigation, the Firebase console doesn’t clear both `secondary_action` and `secondary_action_button` keys in the payload when the secondary button is removed.

Moving forward, it would be best to reach out to the Firebase Support team to check for updates on the issue. You can share the b/270966200 for reference on the bug report.

That said, I’ll be closing this issue now. Let me know if there’s misunderstanding so we can reopen the issue. Thanks!

**Closed by lehcar09** 2024-12-02 16:00 UTC
Labels: api: inappmessaging
