### ISSUE TITLE
no native crash reports since crashlytics-ndk:17.3.0, library "libcrashlytics-common.so" not found

### ISSUE THREAD

**Issue by lwky** [firebase/firebase-android-sdk#2646] opened 2021-05-05 22:50 UTC
Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe your environment

com.android.tools.build:gradle:4.1.2
com.google.gms:google-services:4.3.5
com.google.firebase:firebase-crashlytics-gradle:2.5.2
com.google.firebase:firebase-bom:27.0.0
com.google.firebase:firebase-crashlytics-ndk
compileSdkVersion 29
ndkVersion 21.4.7075529
minSdkVersion 21
targetSdkVersion 29
abiFilters 'armeabi-v7a'
stl "c++_static"

device api23 (google nexus 7)

### [REQUIRED] Step 3: Describe the problem

when a native crash occurs, this runtime exception is thrown
`java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libcrashlytics-common.so" not found`

this library is present in the apk, together with:
```
libcrashlytics-common.so
libcrashlytics-handler.so
libcrashlytics-trampoline.so
libcrashlytics.so
libnativeMyApp.so
```

it can be loaded manually without a problem using System.loadLibrary("crashlytics-common")

crashlytics-ndk:17.2.2 did not have this problem

FirebaseCrashlytics.getInstance().recordException() in java works fine and shows up in the console

#### Steps to reproduce:

generate a native crash:
```
int *x = reinterpret_cast<int *>(0);
*x = 42;
```

```
19930 20056 E MyApp :  <FORCING NATIVE CRASH>
21010 21010 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10166 <<<<<<
21010 21010 D AndroidRuntime: CheckJNI is OFFized.
  601  2202 I ActivityManager: Start proc 21098:android.process.acore/u0a0 for broadcast com.android.providers.contacts/.PackageIntentReceiver
21010 21010 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
21010 21010 I Radio-JNI: register_android_hardware_Radio DONE
20777 20786 W art     : Suspending all threads took: 15.533ms
21098 21098 W System  : ClassLoader referenced unknown path: /system/app/UserDictionaryProvider/lib/arm
  601  1864 I ActivityManager: Start proc 21142:com.android.launcher/u0a35 for broadcast com.android.launcher/com.android.launcher2.PackageChangedReceiver
21010 21010 D AndroidRuntime: Calling main entry com/google/firebase/crashlytics/ndk/CrashpadMain
21010 21010 D AndroidRuntime: Shutting down VM
21010 21010 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
21010 21010 E AndroidRuntime: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libcrashlytics-common.so" not found
21010 21010 E AndroidRuntime: 	at com.google.firebase.crashlytics.ndk.CrashpadMain.main(CrashpadMain.java:22)
21010 21010 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
21010 21010 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
21010 21010 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libcrashlytics-common.so" not found
21010 21010 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
21010 21010 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
21010 21010 E AndroidRuntime: 	at com.google.firebase.crashlytics.ndk.CrashpadMain.main(CrashpadMain.java:20)
21010 21010 E AndroidRuntime: 	... 2 more
21010 21010 E AndroidRuntime: Error reporting crash
21010 21010 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
21010 21010 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
21010 21010 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)
21010 21010 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
21010 21010 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:55)
21010 21010 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2607)
21010 21010 E AndroidRuntime: 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2606)
21010 21010 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
21010 21010 E AndroidRuntime: 	at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:84)
21010 21010 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
21010 21010 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
21010 21010 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
21010 21010 I Process : Sending signal. PID: 21010 SIG: 9
19930 20056 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 20056 (Thread-6205)
  190   190 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
  190   190 F DEBUG   : Build fingerprint: 'google/razor/flo:6.0.1/MOB30X/3036618:user/release-keys'
  190   190 F DEBUG   : Revision: '0'
  190   190 F DEBUG   : ABI: 'arm'
  190   190 F DEBUG   : pid: 19930, tid: 20056, name: Thread-6205  >>> com.myapp.debug <<<
  190   190 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
  190   190 W debuggerd: type=1400 audit(0.0:1236): avc: denied { search } for name="com.google.android.gms" dev="mmcblk0p30" ino=82054 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
  190   190 W debuggerd: type=1400 audit(0.0:1237): avc: denied { search } for name="com.google.android.gms" dev="mmcblk0p30" ino=82054 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
  190   190 F DEBUG   :     r0 9e639e44  r1 00000000  r2 0000002a  r3 0000005c
  190   190 F DEBUG   :     r4 0000030c  r5 9e63a824  r6 b6d9fec0  r7 9e63b698
  190   190 F DEBUG   :     r8 9e63b258  r9 00000001  sl 00000000  fp 9e63a2e0
  190   190 F DEBUG   :     ip a0438120  sp 9e639db0  lr b6d7e25b  pc 9f15c148  cpsr 800f0010
20332 20363 W ResourceType: ResTable_typeSpec entry count inconsistent: given 67, previously 69
20332 20363 W ResourceType: ResTable_typeSpec entry count inconsistent: given 5678, previously 5679
  190   190 F DEBUG   :
  190   190 F DEBUG   : backtrace:
  190   190 F DEBUG   :     #00 pc 00077148  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so
  190   190 F DEBUG   :     #01 pc 00076c68  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN6JNIApi3logEiPc+28)
  190   190 F DEBUG   :     #02 pc 00076c40  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_Z9jniapiLogiPc+28)
  190   190 F DEBUG   :     #03 pc 0009dac0  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN6logger3logEiPKciPcb+716)
  190   190 F DEBUG   :     #04 pc 00532ff4  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so
  190   190 F DEBUG   :     #05 pc 00532efc  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so
  190   190 F DEBUG   :     #06 pc 00532eb8  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so
  190   190 F DEBUG   :     #07 pc 00532e94  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so
  190   190 F DEBUG   :     #08 pc 00531c18  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so
  190   190 F DEBUG   :     #09 pc 0009d454  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so
  190   190 F DEBUG   :     #10 pc 00098580  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZNKSt6__ndk18functionIFvvEEclEv+20)
  190   190 F DEBUG   :     #11 pc 000c9448  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN6cinder7signals6detail19CollectorInvocationINS1_16CollectorDefaultIvEEFvvEE6invokeERS4_RKNSt6__ndk18functionIS5_EE+28)
  190   190 F DEBUG   :     #12 pc 000c9310  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN6cinder7signals6detail11SignalProtoIFvvENS1_16CollectorDefaultIvEEE4emitERS5_+192)
  190   190 F DEBUG   :     #13 pc 000c91f4  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN6cinder7signals6detail11SignalProtoIFvvENS1_16CollectorDefaultIvEEE4emitEv+40)
  190   190 F DEBUG   :     #14 pc 00893c10  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN9CinderSigIJEE4emitEv+28)
  190   190 F DEBUG   :     #15 pc 0009d454  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so
  190   190 F DEBUG   :     #16 pc 00098580  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZNKSt6__ndk18functionIFvvEEclEv+20)
  190   190 F DEBUG   :     #17 pc 000c9448  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN6cinder7signals6detail19CollectorInvocationINS1_16CollectorDefaultIvEEFvvEE6invokeERS4_RKNSt6__ndk18functionIS5_EE+28)
  190   190 F DEBUG   :     #18 pc 000c9310  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN6cinder7signals6detail11SignalProtoIFvvENS1_16CollectorDefaultIvEEE4emitERS5_+192)
  190   190 F DEBUG   :     #19 pc 000c91f4  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN6cinder7signals6detail11SignalProtoIFvvENS1_16CollectorDefaultIvEEE4emitEv+40)
  190   190 F DEBUG   :     #20 pc 00893c10  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN9CinderSigIJEE4emitEv+28)
  190   190 F DEBUG   :     #21 pc 008eebf1  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN19InputDelegateBounds13handleInputUpEi4Vec2+512)
  190   190 F DEBUG   :     #22 pc 008d485d  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so
  190   190 F DEBUG   :     #23 pc 000989e0  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN15AndroidRenderer18flushInputMessagesEv+996)
  190   190 F DEBUG   :     #24 pc 00096be4  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN15AndroidRenderer4stepEv+2092)
  190   190 F DEBUG   :     #25 pc 00098bb0  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN15AndroidRenderer10renderLoopEv+312)
  190   190 F DEBUG   :     #26 pc 00094fd4  /data/app/com.myapp.debug-1/lib/arm/libnativeMyApp.so (_ZN15AndroidRenderer19threadStartCallbackEPv+28)
  190   190 F DEBUG   :     #27 pc 0003f45f  /system/lib/libc.so (_ZL15__pthread_startPv+30)
  190   190 F DEBUG   :     #28 pc 00019b43  /system/lib/libc.so (__start_thread+6)
20383 20401 D FirebaseInstanceId: background sync failed: INVALID_SENDER, retry in 30s
21142 21142 W System  : ClassLoader referenced unknown path: /system/priv-app/Launcher2/lib/arm
 20931 20940 W art     : Suspending all threads took: 13.458ms
  205   205 I Zygote  : Process 19930 exited due to signal (11)
  601  2202 I ActivityManager: Process com.myapp.debug (pid 19930) has died
  601  2202 W ActivityManager: Force removing ActivityRecord{9ca5576 u0 com.myapp.debug/nl.myapp.MyAppMain t3866}: app died, no saved state
```

**Comment by kmandrika** [comment] 2021-05-06 00:03
@lwky is your app using dynamic features? If not, are you able to provide a small repro for this (this would be the fastest way for us to figure out what's up)?

**Comment by eek001c** [comment] 2021-05-13 19:32
Hi,
I experience same issue starting from firebase-crashlytics-ndk:17.3.0. Also tried version 17.4.1.
With 17.2.2 crashes uploaded to firebase, but with missing symbols.
I have similar environment:
Target API version 21
Compile API version 28
Ndk: 21.1.6352462
Starting on Android 6.0 Atoto A6 Pro

What additional information do you need?

**Comment by kmandrika** [comment] 2021-05-13 19:38
Hi @eek001c,

Are you using dynamic features/app bundles? Can you provide a bit more info on how your app is structured?

**Comment by eek001c** [comment] 2021-05-14 08:57
I have QT based app started on android device. Build and deploy using Qt creator.
My project is quite big. I will try to create some test project from Qt examples to check if issue reproduced.

**Comment by eek001c** [comment] 2021-05-17 11:31
I've prepared test app. Issue is reproduced with Qt Android app from Qt examples.
How I may pass app to you, about 13mb?

**Comment by eek001c** [comment] 2021-05-28 13:25
Waiting response how can share code

**Comment by kmandrika** [comment] 2021-06-01 13:15
Hi @eek001c,

Sorry for the radio silence here - we've found what the issue is & it should be fixed in the next release of the SDK. I will let you know when it's slated to go out (shortly).

**Closed** 2021-06-15 01:01 UTC
Labels: api: crashlytics, needs-info, no-recent-activity
