### ISSUE TITLE
FirebaseUser.uid sometimes returns the email instead of uid

### ISSUE THREAD

**Issue by jvojacek** [firebase/firebase-android-sdk#3641] opened 2022-04-13 12:55 UTC
https://github.com/firebase/firebase-android-sdk/issues/298
Step 1: Are you in the right place?
I think I am.

Step 2: Describe your environment

  * Android Studio version: Bumblebee | 2021.1.1 Patch 1
  * Firebase Component:  FirestoreKTX, AnalyticsKTX, CrashlyticsKTX, AuthKTX
  * Component version: firebase-bom:29.3.0

Step 3: Describe the problem
I have same issue as already described in https://github.com/firebase/firebase-android-sdk/issues/298.

Sometimes when I call currentUser.uid it returns email instead of uid. I tried to reloading currentUser using ```Firebase.auth.currentUser?.reload()``` but i still get email instead of uid. The only way I have found to retrieve the uid is to log the user out and log back in. 

#### Relevant Code:
I do not think this code help but i am getting uid like
```
Firebase.auth.currentUser?.uid
```

**Comment by allenmrazek** [comment] 2022-04-13 17:36
Sounds related to the issue I'm seeing too #2434. Disappointing that reloading the user didn't work, that is one of the fixes I am attempting. The other one I'll know more about in a few days is fetching the uid from the jwt instead and just treating currentUser.uid as unreliable

**Comment by argzdev** [comment] 2022-04-18 09:22
Hi @jvojacek, thanks for reporting. Are you able to reproduce this issue consistently? Any chance you can provide a minimal repro of this issue including steps on how to encounter the issue? Thanks in advance!

**Comment by jvojacek** [comment] 2022-04-19 08:50
Hello @argzdev, sorry but I am unable to provide you with more detailed information about repro. I also noticed that if I start getting the email or numbers (as mentioned in the issue https://github.com/firebase/firebase-android-sdk/issues/2434) instead of the uid, I also get the wrong profile picture URL (account via Google provider - I get my original Google profile picture instead of the photo changed via Auth).

**Comment by argzdev** [comment] 2022-04-19 09:07
Thanks for the extra details @jvojacek. Does this issue happen quite often? 

Let's leave this issue open for now in case some of our engineers might have an idea what the issue may be.

**Comment by jvojacek** [comment] 2022-04-19 10:19
@argzdev I would say it is been happening quite a bit lately (last week). I would say 3/4 times a day. I had to change the way I was getting the uid. Now I get the uid from our backend via idToken, because currentUser.uid is not reliable.

**Comment by argzdev** [comment] 2022-04-29 18:12
@jvojacek thanks for this info.  It looks to me that this inconsistency is happening as an issue on the backend side of things. That being said, could you reach out to our [Firebase Support](https://firebase.google.com/support) instead? Since they have visibility on your project details, they'll be able to assist you a lot better. I'll close this issue for now. If more developers experience this issue, then it might be an SDK issue.

**Closed by argzdev** 2022-04-29 18:12 UTC
Labels: api: auth
