### ISSUE TITLE
Cannot mark as impressed more than one message almost same time

### ISSUE THREAD

**Issue by igorjacauna** [firebase/firebase-android-sdk#3774] opened 2022-06-01 21:21 UTC
* Android Studio version: Arctic Fox 2020.3.1 Patch 4
  * Firebase Component: InAppMessage
  * Component version: 19.1.5

#### Steps to reproduce:

Have a custom Display component for InAppMessage, i.e.:

```java
FirebaseInAppMessaging.getInstance().setMessageDisplayComponent(new MyFirebaseMessaging());
```

#### Relevant Code:

My custom display component has a `HashMap` to handle multiple messages displaying on screen. Like 2 cards embedded on layout.

```java
private final HashMap<String, HashMap> InAppMessages = new HashMap<>();
```

Every time we receive a message we do something like:

```java
@Override
public void displayMessage(@NonNull InAppMessage inAppMessage, @NonNull FirebaseInAppMessagingDisplayCallbacks callbacks) {
    try {
        String campaignId = inAppMessage.getCampaignMetadata().getCampaignId();
    
        // Here we build a object that represents the received message
        HashMap<String, Object> inAppMessageObject = new HashMap<String, Object>();
        inAppMessageObject.put("message", inAppMessage);
        inAppMessageObject.put("callbacks", callbacks);
        
        // Then we put on HashMap this object to be called later
        this.InAppMessages.put(campaignId, inAppMessageObject);
    } catch (Exception e) {
        Log.e("FIAM: Error", e.toString());
    }
}
```

#### The problem

Some times, more than one event is triggered each one with a message assigned:

```java
FirebaseInAppMessaging.getInstance().triggerEvent("main_screen_opened");
FirebaseInAppMessaging.getInstance().triggerEvent("another_main_screen_opened");
``` 

But when we try to mark as impressed only one message are marked. We use something like this to handle multiple messages and mark each as impressed:

```java
public void markAsImpressionDetected(String campaignId) {
    try {
        // We recover from HashMap the message callbacks
        FirebaseInAppMessagingDisplayCallbacks callbacks = (FirebaseInAppMessagingDisplayCallbacks) this.InAppMessages.get(campaignId).get("callbacks");

        // And call 
        callbacks.impressionDetected();
    } catch(Exception e) {
        Log.e("FIAM: Error", e.toString());
    }
}
```

With milliseconds between each call. But always only one of 2 or more messages are marked as impressed. And no error was throw

**Comment by argzdev** [comment] 2022-06-03 13:21
Hi @igorjacauna, thanks for reporting. I'm not sure where the issue is, could you provide a minimal repro of your issue so I can investigate this further? Thanks in advance!

**Comment by igorjacauna** [comment] 2022-06-03 17:14
Hi @argzdev ! Thanks for the reply! 

So, let me try explain how we use it.

Currently, we are using in a ReactNative app, so on our custom Display class, when the `displayMessage` are called, we send a event to ReactNative to render the component assign to message.

We were trying to use to display 2 differents messages linked to 2 cards components embeded on layout at same time, so we trigged two events each one linked with a differente message.

So, `displayMessage` are called twice and and send info about the messages to ReactNative that renders the 2 componentes relateds. Also, we put to a HashMap, using the message ID as index, the messages callbacks and keep it in memory

When ReactNative render the components, we send back the `impressionDetected` passing the message ID used to populate the HashMap.

With the message ID we recovery the message callbacks from HashMap and call `impressionDetected`

But when we call twice or more times `makrImpressionDetected` for differents messages in a short time only one message are marked as read

**Comment by eldhosembabu** [comment] 2022-08-01 22:22
Hi @igorjacauna ,

Could you please confirm how you are checking make sure all impression detected calls are getting fired and marked as read? Is it based on some callbacks?

Also could you please try calling the impressiondetected calls with a delay (may be 5 seconds between each call?)

**Comment by igorjacauna** [comment] 2022-08-03 15:53
Hi @eldhosembabu,

To check if impression detected is called and marked as read we follow the ADB logcat by using `adb logcat | grep "FIAM"`, it shows logs from Firebase when a message already impressed or not and in our custom `FirebaseInAppMessagingDisplay` class implementation we put some logs to known if `impressionDetected` been called correctly and compare with logs from FIAM.

We create a delay with 5 seconds and the problem persists. We follow this steps:

1. Open the app
2. Call for two messages: Message A bind to event `event_a` and Message B bind to `event_b`. We call the messages with firing the events:
  ```java
  FirebaseInAppMessaging.getInstance().triggerEvent("event_a");
  FirebaseInAppMessaging.getInstance().triggerEvent("event_b");
  ```
3. On `adb logcat | grep "FIAM"` shows:
  ```
  FIAM.Headless: Already impressed campaign Message A ? : false
  FIAM.Headless: Already impressed campaign Message B ? : false
  ```
4. We display the two messages on two differents components on screen
5. When the messages are displayed, we call `impressionDetected` for Message A
6. Our logs shows `impressionDetected` called without errors
7. Delay 5 seconds for call `impressionDetected` for Message B
8. Our logs shows `impressionDetected` called without errors
9. We close the app
10. We open the app again
11. We fire again the two events, `event_a` and `event_b`
12. On `adb logcat | grep "FIAM"` shows:
  ```
  FIAM.Headless: Already impressed campaign Message A ? : true
  FIAM.Headless: Already impressed campaign Message B ? : false
  ```
13. Once the Message B is marked as not impressed it shows up again, but before when we call `impressionDetected` for it, no error occurred
14. We display the Message B
15. Call `impressionDetected` for Message B
16. Our logs shows `impressionDetected` called without errors
17. Close the app
18. Reopen the app
19. Fire `event_a` and `event_b`
20. On `adb logcat | grep "FIAM"` shows:
  ```
  FIAM.Headless: Already impressed campaign Message A ? : true
  FIAM.Headless: Already impressed campaign Message B ? : true
  ```

Hope this help.

**Comment by eldhosembabu** [comment] 2022-08-09 17:03
Could you please provide a sample app where I can try reproducing the issue?

**Comment by igorjacauna** [comment] 2022-08-10 14:02
Hi @eldhosembabu, I created this repo: https://github.com/igorjacauna/android-firebase-sdk-issue

**Comment by eldhosembabu** [comment] 2022-08-24 17:45
Hi @igorjacauna ,

Could you please try to reproduce this issue in our [Quick Start App](https://github.com/firebase/quickstart-android/tree/master/inappmessaging)? I was not able to get the above repo code working since I'm not familiar with the react code.

**Comment by eldhosembabu** [comment] 2022-08-24 17:47
The possible reason for this issue is this [wasImpressed](https://github.com/firebase/firebase-android-sdk/blame/master/firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImpl.java#L45) flag which is static. But i need to reproduce the issue on quick start to provide a fix.

**Comment by argzdev** [comment] 2022-10-21 15:42
Hi all, seems to me that the fix for this has been merged. That said, I'll close this issue now. Feel free to reopen if the issue is still present.

**Closed by argzdev** 2022-10-21 15:42 UTC
Labels: type: bug, api: inappmessaging, needs-attention
