### ISSUE TITLE
App Distribution plugin doesn't support Gradle configuration cache

### ISSUE THREAD

**Issue by ribafish** [firebase/firebase-android-sdk#2978] opened 2021-09-15 11:02 UTC
### Environment

  * Android Studio version: Arctic Fox 2020.3.1 Patch 2
  * Firebase Component: App distribution
  * Component version: 2.2.0
  * Gradle version: 7.2, AGP 7.0.2

### Describe the problem

When trying to run the `appDistributionUploadRelease` with gradle configuration cache turned on it produces an error when storing the cache because the task isn't set up to support it.

#### Steps to reproduce:

Run `appDistributionUploadRelease` (or any other build variant) with gradle configuration cache enabled. Error pasted below:

```
1 problem was found storing the configuration cache.

- Task `:target:mobile:app:appDistributionUploadCurrentStageRelease` of type `com.google.firebase.appdistribution.gradle.UploadDistributionTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.

  See https://docs.gradle.org/7.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

FAILURE: Build failed with an exception.

* What went wrong:

Configuration cache state could not be cached: field 'appDistributionProperties' from type 'com.google.firebase.appdistribution.gradle.UploadDistributionTask': error writing value of type 'org.gradle.api.internal.provider.DefaultProperty'
> Configuration cache state could not be cached: field 'variant' from type 'com.google.firebase.appdistribution.gradle.AppDistributionProperties': error writing value of type 'com.android.build.gradle.internal.api.ApplicationVariantImpl'
   > Configuration cache state could not be cached: field 'unitTestVariant' from type 'com.android.build.gradle.internal.api.ApplicationVariantImpl': error writing value of type 'com.android.build.gradle.internal.api.UnitTestVariantImpl'
      > Configuration cache state could not be cached: field 'variantData' from type 'com.android.build.gradle.internal.api.UnitTestVariantImpl': error writing value of type 'com.android.build.gradle.internal.variant.TestVariantData'
         > Configuration cache state could not be cached: field 'testedVariantData' from type 'com.android.build.gradle.internal.variant.TestVariantData': error writing value of type 'com.android.build.gradle.internal.variant.ApplicationVariantData'
            > Configuration cache state could not be cached: field 'artifacts' from type 'com.android.build.gradle.internal.variant.ApplicationVariantData': error writing value of type 'com.android.build.api.artifact.impl.ArtifactsImpl'
               > Configuration cache state could not be cached: field 'storageProvider' from type 'com.android.build.api.artifact.impl.ArtifactsImpl': error writing value of type 'com.android.build.api.artifact.impl.StorageProviderImpl'
                  > Configuration cache state could not be cached: field 'directory' from type 'com.android.build.api.artifact.impl.StorageProviderImpl': error writing value of type 'com.android.build.api.artifact.impl.TypedStorageProvider'
                     > Configuration cache state could not be cached: field 'singleStorage' from type 'com.android.build.api.artifact.impl.TypedStorageProvider': error writing value of type 'java.util.LinkedHashMap'
                        > java.util.ConcurrentModificationException (no error message)
```

**Comment by aguatno** [comment] 2021-09-17 17:27
Hi @ribafish Does it fail only when using gradle? Do you get any errors when uploading the apk using the console? It will also better if you could provide a minimal, reproducible example of your project along with the steps needed to replicate the issue.

**Comment by ribafish** [comment] 2021-09-20 10:37
Yes, it fails when using with gradle and only fails if it's ran with Gradle's [configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) enabled. I've put together a small project here: [example](https://github.com/ribafish/firebaseDistributionCrashExample), but you can get the same result if you run the `appDistributionUploadRelease` with `--configuration-cache` flag in any project.

**Comment by eygraber** [comment] 2021-09-23 03:17
Running into the same issue. Everything in my build works with Gradle's configuration cache, except for this plugin.

**Comment by aguatno** [comment] 2021-09-23 19:56
I was able to see replicate the exception. Thanks @ribafish the mcve is very helpful. We'll continue the investigation.

**Comment by tagboola** [comment] 2022-01-21 19:26
Hey folks! We just released version `3.0.0` of our gradle plugin that contains a fix for the configuration cache issue. For more details check out the release notes.

https://firebase.google.com/support/release-notes/android#appdistro_gradle_plugin_v3-0-0

**Comment by ribafish** [comment] 2022-01-26 14:20
I tried to update to `3.0.0`, but found an issue with it that breaks our build: https://github.com/firebase/firebase-android-sdk/issues/3369

**Comment by argzdev** [comment] 2022-02-02 11:18
Since this has been fixed in version 3.0.0, I'll be closing this issue now.

**Closed by argzdev** 2022-02-02 11:18 UTC
Labels: needs-attention, api: appdistro

**Comment by Nexuscompute** [comment] 2022-02-02 11:22
plug-in exists at eclipse.org

**Comment by eygraber** [comment] 2022-03-02 06:28
This is still failing in 3.0.0:

```
1 problem was found storing the configuration cache.
    - Task `:app:appDistributionUploadDev` of type `com.google.firebase.appdistribution.gradle.UploadDistributionTask`: invocation of 'Task.project' at execution time is unsupported.
    See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
  > Invocation of 'Task.project' by task ':app:appDistributionUploadDev' at execution time is unsupported.
```

**Comment by tagboola** [comment] 2022-03-02 15:37
@eygraber can you share the `firebaseAppDistribution` block in your `build.gradle` file, making sure to remove any sensitive information?
