### ISSUE TITLE
Crashlytics gradle plugin doesn't work with gradle 6.6 configuration cache feature

### ISSUE THREAD

**Issue by radimjanda754** [firebase/firebase-android-sdk#1894] opened 2020-08-19 07:39 UTC
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Crashlytics (gradle plugin)
  * Component version: 2.2.0

### [REQUIRED] Step 3: Describe the problem

Crashlytics gradle plugin doesn't work well with new 6.6 gradle's feature of caching configuration.
When I enable the configuration cache feature in the gradle.properties
`org.gradle.unsafe.configuration-cache=true`
I get gradle errors caused by the plugin at task `injectCrashlyticsMappingFileId`
`Caused by: groovy.lang.MissingPropertyException: No such property: resourceFile for class: java.lang.Object
	at com.google.firebase.crashlytics.buildtools.gradle.tasks.InjectMappingFileIdTask$_closure1.doCall(InjectMappingFileIdTask.groovy:39)`

when I delete crashlytics gradle plugin, then everything starts to work

**Comment by rlazo** [comment] 2020-08-19 16:31
Hi @radimjanda754 thanks for your report. Yes, the crashlytics gradle plugin doesn't support configuration cache yet, but we are actively working on adding support for it.

**Comment by ashwinraghav** [comment] 2020-08-19 16:54
Duplicate of https://github.com/firebase/firebase-android-sdk/issues/1750

**Closed by ashwinraghav** 2020-08-19 16:54 UTC
Labels: api: crashlytics, type: feature request
