### ISSUE TITLE
[Crashlytics] A problem was found with the configuration of task ':app:generateCrashlyticsSymbolFileRelease'

### ISSUE THREAD

**Issue by egorikftp** [firebase/firebase-android-sdk#5090] opened 2023-06-21 10:41 UTC
### [READ] Step 1: Are you in the right place?

YES

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Flamingo
  * Gradle version: 8.1.1
  * Android Gradle Plugin version: 8.0.2
  * Crashlytics Gradle Plugin version: 2.9.6
  * firebase-bom: 32.1.1

#### Steps to reproduce:

Gradle build fails when building an Android project which uses Crashlytics with NDK integration.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:generateCrashlyticsSymbolFileRelease' (type 'GenerateSymbolFileTask').
  - Gradle detected a problem with the following location: '/home/vsts/work/1/s/app/build/intermediates/merged_native_libs/release/out/lib'.
    
    Reason: Task ':app:generateCrashlyticsSymbolFileRelease' uses this output of task ':app:mergeReleaseNativeLibs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':app:mergeReleaseNativeLibs' as an input of ':app:generateCrashlyticsSymbolFileRelease'.
      2. Declare an explicit dependency on ':app:mergeReleaseNativeLibs' from ':app:generateCrashlyticsSymbolFileRelease' using Task#dependsOn.
      3. Declare an explicit dependency on ':app:mergeReleaseNativeLibs' from ':app
:generateCrashlyticsSymbolFileRelease' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.1.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

```

**Comment by argzdev** [comment] 2023-06-21 11:07
Hi @egorikftp, thanks for reaching out. It looks like a duplicate of #5083. For better tracking, kindly continue your report on that thread. Please do leave a thumbs up reaction emoji on the author's post so we can track the severity. I'll go ahead and close this one. Thanks!

**Closed by argzdev** 2023-06-21 11:07 UTC
Labels: api: crashlytics
