### ISSUE TITLE
Uncaught exception in Firebase Database runloop (19.4.0)

### ISSUE THREAD

**Issue by deepakrathi** [firebase/firebase-android-sdk#2015] opened 2020-09-29 12:53 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Realtime Database
  * Component version: 19.4.0

#### Steps to reproduce:
Step1 = login
step2 = logout
step3 = login again and after a second or two, it crashes

#### Relevant Code:
I am clearing the data with the following function on logout

```
 public static void clearApplicationData() {
        File cache = getContext().getCacheDir();
        File appDir = new File(cache.getParent());
        if (appDir.exists()) {
            String[] children = appDir.list();
            for (String s : children) {
                if (!s.equals("lib")) {
                    deleteDir(new File(appDir, s));
                    NotificationManager notificationManager = (NotificationManager) getContext().getSystemService(NOTIFICATION_SERVICE);
                    assert notificationManager != null;
                    notificationManager.cancelAll();
                    PrefManager.setToken(null);
                    PrefManager.clearPrefs();
                    Intent intent = new Intent(getContext(), SplashActivity.class);
                    getContext().startActivity(intent);
                    Intent locationServiceIntent = new Intent(getContext(), LocationTrackerService.class);
                    getContext().stopService(locationServiceIntent);
                }
            }
        }
    }
```

**Comment by rlazo** [comment] 2020-10-01 08:52
Hi @deepakrathi can you include the full error message?  

Also, the exception is the same as #2017 are you getting the same stacktrace?

**Comment by rlazo** [comment] 2020-10-13 15:32
Thanks for the pointer @deepak786 I'm marking this one as duplicated of that one to centralize the info.

**Comment by rlazo** [comment] 2020-10-13 15:32
Duplicate of #1940

**Comment by rodrigozoio** [comment] 2020-10-16 01:46
> @rlazo there is a similar issue which has more error details and no one is assigned to that yet. So could you please check that #1940?
> 
> The version 19.3.1. works fine but 19.4.0 and 19.5.0 have the issues. So we can't use the updated versions.

Thank you so much!!!! I was having problems during logout with random crash similar to this topic and couldn't figure it out... Then saw your comment and downgraded my sdk. The problem is gone!!!

**Closed** 2020-10-23 01:45 UTC
Labels: api: database, needs-info, no-recent-activity
