### ISSUE TITLE
The client had an error while calling the backend!

### ISSUE THREAD

**Issue by CollinsDroid** [firebase/firebase-android-sdk#1515] opened 2020-04-29 10:22 UTC
###  Describe your environment

 Android device: Techno F1
Android OS version: 8.1.0
Google Play Services version: 4.3.3
Firebase/Play Services SDK version: 19.0.3

### [REQUIRED] Step 3: Describe the problem

```
 com.google.firebase.remoteconfig.FirebaseRemoteConfigClientException: The client had an error while calling the backend!
        at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(com.google.firebase:firebase-config@@19.1.3:195)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(com.google.firebase:firebase-config@@19.1.3:295)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(com.google.firebase:firebase-config@@19.1.3:267)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1(com.google.firebase:firebase-config@@19.1.3:205)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$Lambda$2.then(Unknown Source:4)
        at com.google.android.gms.tasks.zzf.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:299)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.setFetchRequestBody(com.google.firebase:firebase-config@@19.1.3:328)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(com.google.firebase:firebase-config@@19.1.3:183)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(com.google.firebase:firebase-config@@19.1.3:295) 
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(com.google.firebase:firebase-config@@19.1.3:267) 
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1(com.google.firebase:firebase-config@@19.1.3:205) 
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$Lambda$2.then(Unknown Source:4) 
        at com.google.android.gms.tasks.zzf.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2020-04-29 11:11:43.680 6222-6274/com.mevron.driver E/Fabric: Error performing auto configuration.
    io.fabric.sdk.android.services.network.HttpRequest$HttpRequestException: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xa327df40: I/O error during system call, Connection timed out
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2550)
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2530)
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2516)
        at io.fabric.sdk.android.services.settings.AbstractAppSpiCall.applyMultipartDataTo(AbstractAppSpiCall.java:108)
        at io.fabric.sdk.android.services.settings.AbstractAppSpiCall.invoke(AbstractAppSpiCall.java:76)
        at io.fabric.sdk.android.services.settings.UpdateAppSpiCall.invoke(UpdateAppSpiCall.java:29)
        at io.fabric.sdk.android.Onboarding.performUpdateApp(Onboarding.java:206)
        at io.fabric.sdk.android.Onboarding.performUpdateApp(Onboarding.java:196)
        at io.fabric.sdk.android.Onboarding.performAutoConfigure(Onboarding.java:177)
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:113)
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:46)
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63)
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28)
        at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xa327df40: I/O error during system call, Connection timed out
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:299)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
        at io.fabric.sdk.android.services.network.HttpRequest.openOutput(HttpRequest.java:2454)
        at io.fabric.sdk.android.services.network.HttpRequest.startPart(HttpRequest.java:2467)
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2546)
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2530) 
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2516) 
        at io.fabric.sdk.android.services.settings.AbstractAppSpiCall.applyMultipartDataTo(AbstractAppSpiCall.java:108) 
        at io.fabric.sdk.android.services.settings.AbstractAppSpiCall.invoke(AbstractAppSpiCall.java:76) 
        at io.fabric.sdk.android.services.settings.UpdateAppSpiCall.invoke(UpdateAppSpiCall.java:29) 
        at io.fabric.sdk.android.Onboarding.performUpdateApp(Onboarding.java:206) 
        at io.fabric.sdk.android.Onboarding.performUpdateApp(Onboarding.java:196) 
        at io.fabric.sdk.android.Onboarding.performAutoConfigure(Onboarding.java:177) 
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:113) 
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:46) 
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63) 
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28) 
        at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by andirayo** [comment] 2020-04-29 23:29
Fly-by comment:
Do you also use `firebase-messaging` in your application and, if yes, which version of `firebase-messaging`?
Can you please share a project identifier with us, either project ID or project number?

**Comment by CollinsDroid** [comment] 2020-04-29 23:52
Thanks for your reply,
I use firebase messaging version 20.1.5
Project I'd mevron-1330b

**Comment by andirayo** [comment] 2020-04-30 00:09
@CollinsDroid : Thank you. I checked the logs of the Firebase Installations service (`firebase-installations`). I don't see many requests, but the ones I see for `mevron-1330b` are successful.

I had a hunch that there was a problem for your app with a new Firebase infrastructure service. But that is not the case.
Leaving it to the Firebase Config team to debug this issue.

**Comment by CollinsDroid** [comment] 2020-04-30 00:10
Thanks with much thanks

**Comment by overflow42** [comment] 2020-05-06 11:04
Hello, I got the same issue. I'm using com.google.firebase:firebase-config:17.0.0, com.google.firebase:firebase-analytics:17.0.0, com.google.gms:google-services:4.2.0.
When I try to fetch I get this error but I can't find it on logcat, I need to log it with task.getExpection().

**Comment by Bild78** [comment] 2020-05-06 12:09
I know 1 thing I saw info on my girls phone addresses to KB93341@gmail.com
c as re tug o explain that to me.

**Comment by Bild78** [comment] 2020-05-06 12:24
I saw a lot of y'alls notes and paperwork it looks like your checking me
out more than fix any problems car to call me I don't understand I saw text
messages I sent the day before 770 866 9123

**Comment by vikey89** [comment] 2020-05-28 08:13
Hello, we have the same issue. We using:
- com.google.firebase:firebase-messaging:20.0.0
- com.google.firebase:firebase-config:19.0.2

the problem occurs randomly only in the production app.

**Comment by danasilver** [comment] 2020-05-28 16:03
Since the error message "The client had an error while calling the backend!" is the standard error message used in the Remote Config SDK for a client error (ex. a connection timeout, SSL issue, etc) it's hard to pinpoint the exact issue without a full stack trace.

In @CollinsDroid's case, I see `Connection closed by peer` as the cause of the Remote Config error as well as `I/O error during system call, Connection timed out` from Fabric. If the issue isn't consistently reproducible, it's likely caused by a flaky internet connection. Possibly the case for other instances of this happening randomly across various devices, SDK versions, and Android versions.

I'm going to close this issue since it doesn't seem like something we can address in the SDK.

**Closed by danasilver** 2020-05-28 16:03 UTC
Labels: api: remoteconfig, needs-triage
